const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const ast=ts.createSourceFile('hook.ts',fs.readFileSync('app/destiny-compass/_hooks/useCompassReport.ts','utf8'),ts.ScriptTarget.Latest,true);
function callback(name,ctx){let found;function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)===name)found=n.initializer.arguments[0];ts.forEachChild(n,visit)}visit(ast);assert.ok(found);vm.runInContext(ts.transpileModule('var run='+found.getText(ast),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx);return ctx.run}
function fixture(){let owner=true;const posts=[],states=[],acks=[];const scope={locale:'ko',isCurrent:()=>true};const ctx=vm.createContext({Date,String,Error,URL,JSON,Array,Promise,captureOwner:()=>()=>owner,captureLocaleScope:()=>scope,reportIdRef:{current:'owned'},payloadRef:{current:{requestId:'original',idempotencyKey:'original',transactionId:'receipt'}},continuationRef:{current:''},window:{location:{href:'https://mock.test/journey/'},history:{replaceState(){}},setTimeout:fn=>{fn();return 1}},document:{hidden:false},navigator:{onLine:true},WAVE_B_TIMEOUT_MS:95000,WAVE_A_TIMEOUT_MS:95000,setState:state=>states.push(state),field:null,question:'',resumeWiring:{onDelivery:value=>acks.push(value)},copy:{reportFailedMessage:'failed',connectionLostMessage:'network'},mergeSections:(a,b)=>({...a,...Object.fromEntries((b||[]).map(r=>[r.key,r]))}),postJson:async(path,body)=>{posts.push({path,body});return{status:200,data:{ok:true,stage:'complete',reportId:'owned',sections:[{key:'opening',body:'saved'}]}}}});return{ctx,posts,states,acks,scope,ownerChange:()=>{owner=false},base:{reportId:'owned',sections:{},systemConfidence:[],phase:'waveB'}}}
test('saved ID resumes without expired token or a payment gate',async()=>{const f=fixture();await callback('runWaveB',f.ctx)(f.base,f.scope);assert.equal(f.posts[0].body.reportId,'owned');assert.equal(f.posts[0].body.continuationToken,undefined);assert.deepEqual(f.acks,[true])});
test('202 partial responses continue until final storage confirmation',async()=>{const f=fixture();let calls=0;f.ctx.postJson=async()=>({status:++calls<3?202:200,data:{ok:true,stage:calls<3?'partial':'complete',reportId:'owned',sections:[],retryable:true}});await callback('runWaveB',f.ctx)(f.base,f.scope);assert.equal(calls,3);assert.equal(f.states.at(-1).phase,'done');assert.deepEqual(f.acks,[true])});
test('late completion after account change is discarded',async()=>{const f=fixture();f.ctx.postJson=async()=>{f.ownerChange();return{status:200,data:{ok:true,stage:'complete'}}};await callback('runWaveB',f.ctx)(f.base,f.scope);assert.equal(f.acks.length,0);assert.ok(f.states.every(s=>s.phase!=='done'))});
test('offline and hidden screens make no provider request',async()=>{for(const hidden of[true,false]){const f=fixture();f.ctx.document.hidden=hidden;f.ctx.navigator.onLine=hidden;await callback('runWaveB',f.ctx)(f.base,f.scope);assert.equal(f.posts.length,0)}});
test('missing initial seed reuses the original purchase body',async()=>{const f=fixture();let calls=0;f.ctx.postJson=async(path,body)=>{f.posts.push({path,body});return ++calls===1?{status:404,data:{ok:false}}:{status:200,data:{ok:true,stage:'complete',reportId:'owned',sections:[]}}};await callback('runWaveB',f.ctx)(f.base,f.scope);assert.equal(f.posts[1].path,'/api/destiny-compass-ai/report');assert.equal(f.posts[1].body.requestId,'original');assert.equal(f.posts[1].body.transactionId,'receipt')});

test('unlock after storage failure resumes original evidence without opening checkout',async()=>{const f=fixture();let gates=0,resumes=0;Object.assign(f.ctx,{input:{},field:{seed:'same'},isPaying:false,inFlight:{current:false},readCache:()=>({reportId:'owned',phase:'waveB',sections:{}}),sessionKeyFor:()=> 'key',toAiLocale:v=>v,detectLocale:()=> 'ko',localStorage:{getItem:()=>JSON.stringify({requestId:'original',transactionId:'receipt'})},ensurePaidAccess:async()=>{gates++;return{ok:true}},runWaveB:async()=>{resumes++}});await callback('unlock',f.ctx)();assert.equal(gates,0);assert.equal(resumes,1);assert.equal(f.ctx.payloadRef.current.transactionId,'receipt')});
