const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync('js/saju-engine.js','utf8'),tree=ts.createSourceFile('ui.js',source,99,true,1);
const code=['_cdQuestionOwner','_cdRememberQuestionResult','_cdMountQuestionRecovery','_cdRetryTransientPost','_cdIsTransientConsultResult'].map(name=>tree.statements.find(n=>n.name?.text===name).getText(tree)).join('\n');
function fixture(){const events={},store=new Map(),calls=[],shown=[];let owner='user-1',pending=[];
 const window={addEventListener:(name,fn)=>(events[name]??=new Set()).add(fn),removeEventListener:(name,fn)=>events[name]?.delete(fn)};
 const document={...window,visibilityState:'visible'};
 const ctx=vm.createContext({window,document,Promise,Error,sessionStorage:{getItem:key=>store.get(key),setItem:(key,value)=>store.set(key,value),removeItem:key=>store.delete(key)},getStoredAuthUser:()=>({id:owner}),getFortuneAuthToken:()=>'',setTimeout:fn=>{queueMicrotask(fn);},fetch:async(url,opts)=>{calls.push({url,opts});const item=pending.shift();if(item instanceof Error)throw item;return {status:item.status,ok:item.status<300,json:async()=>item.payload};}});vm.runInContext(code,ctx);
 return {ctx,store,calls,shown,events,setOwner:value=>{owner=value;for(const fn of events['cd:auth-changed']||[])fn();},queue:value=>{pending=value;},options:{attached:()=>true,busy:()=>false,loading(){},show:data=>shown.push(data),clear:()=>shown.length=0,error:message=>shown.push({error:message})}};
}
const partial={status:202,payload:{ok:true,status:'partial',saved:false,featureKey:'astrology_ai_prompt_generator',resultId:'paid-narrative:original',resumeBody:{resumeResultId:'paid-narrative:original'},retryable:true}};
const complete={status:200,payload:{...partial.payload,status:'completed',saved:true,resultText:'마지막 문장까지 저장되었습니다.'}};
async function settle(){for(let i=0;i<30;i++)await new Promise(resolve=>setImmediate(resolve));}
test('partial and transient storage failure continue the same call until completed',async()=>{const f=fixture(),replies=[partial,{status:503,payload:{retryable:true}},complete];let calls=0;const result=await f.ctx._cdRetryTransientPost(()=>{calls++;return replies.shift();});assert.equal(calls,3);assert.equal(result.payload.saved,true);assert.equal(f.store.get('cd.question.result:user-1:astrology'),'paid-narrative:original');});
test('exhausted partial is not UI success',async()=>{const f=fixture();const result=await f.ctx._cdRetryTransientPost(()=>({...partial,payload:{...partial.payload,retryable:false}}));assert.equal(result.ok,false);assert.equal(result.status,503);});
test('account change discards an in-flight completed reply',async()=>{const f=fixture();let resolve;const result=f.ctx._cdRetryTransientPost(()=>new Promise(done=>{resolve=done;}));await Promise.resolve();await Promise.resolve();f.setOwner('user-2');resolve(complete);await assert.rejects(result,/계정/);assert.equal(f.store.size,0);});
test('mount discovers pending result and resumes using only the saved ID',async()=>{const f=fixture();f.queue([partial,complete]);f.ctx._cdMountQuestionRecovery('astrology',f.options);await settle();assert.equal(f.calls.length,2);assert.match(f.calls[0].url,/ai-result$/);assert.deepEqual(JSON.parse(f.calls[1].opts.body),partial.payload.resumeBody);assert.equal(f.shown.at(-1).saved,true);});
test('reload reads the saved completed result without POST',async()=>{const f=fixture();f.store.set('cd.question.result:user-1:astrology','paid-narrative:original');f.queue([complete]);f.ctx._cdMountQuestionRecovery('astrology',f.options);await settle();assert.equal(f.calls.length,1);assert.match(f.calls[0].url,/resultId=paid-narrative%3Aoriginal/);assert.equal(f.shown.at(-1).resultText,complete.payload.resultText);});
test('online recovers interrupted pending delivery without opening a payment gate',async()=>{const f=fixture();f.queue([new Error('offline'),new Error('offline'),new Error('offline')]);f.ctx._cdMountQuestionRecovery('astrology',f.options);await settle();f.queue([partial,complete]);for(const fn of f.events.online||[])fn();await settle();assert.equal(f.shown.at(-1).saved,true);f.setOwner('user-2');assert.equal(f.shown.length,0);});
