const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const raw=fs.readFileSync('worker/routes/fortune-chat.js','utf8'),tree=ts.createSourceFile('chat.js',raw,99,true,1);
const code=['ownedSessionFilter','handleFortuneChatRoutes'].map(name=>tree.statements.find(n=>n.name?.text===name).getText(tree).replace(/^export /,'')).join('\n');
function fixture(fault){let who={userId:'owner',guestIdHash:'same-browser'},doc={sessionId:'session',userId:'owner',anonymousSessionId:'same-browser',messages:[]},written=false;const filters=[];
 const query=value=>({lean:async()=>structuredClone(value)}),match=filter=>Object.entries(filter).every(([k,v])=>doc[k]===v||(v===null&&doc[k]==null));
 const ctx=vm.createContext({Request,Response,JSON,objectIdOrString:value=>value,identity:async()=>who,connectDb:async()=>{},getRoutePath:r=>new URL(r.url).pathname.replace('/api/fortune-chat',''),readJson:r=>r.json(),json:(data,opts)=>new Response(JSON.stringify(data),opts),notFound:()=>new Response('{}',{status:404}),methodNotAllowed:()=>new Response('{}',{status:405}),FortuneChatSession:{findOne:filter=>{filters.push(filter);if(written&&fault==='read')return query(null);return query(match(filter)?doc:null);},findOneAndUpdate:(filter,update)=>{if(fault==='throw')throw Error('storage');if(fault==='null')return query(null);if(fault!=='noop')Object.assign(doc,update.$set);written=true;return query(doc);}}});vm.runInContext(code,ctx);return {filters,setWho:v=>who=v,post:messages=>ctx.handleFortuneChatRoutes(new Request('https://mock.test/api/fortune-chat/sessions/session',{method:'POST',body:JSON.stringify({messages})}),{}),get:()=>ctx.handleFortuneChatRoutes(new Request('https://mock.test/api/fortune-chat/sessions/session'),{})};}
const messages=Array.from({length:80},(_,i)=>({id:'line-'+i,speaker:'assistant',text:i===79?'마지막 유료 상담 문장':'상담 '+i}));
test('all eighty supplied messages survive storage and reopening',async()=>{const f=fixture();assert.equal((await f.post(messages)).status,200);const result=await(await f.get()).json();assert.equal(result.session.messages.length,80);assert.equal(result.session.messages.at(-1).text,'마지막 유료 상담 문장');});
for(const fault of ['throw','null','noop','read'])test('storage '+fault+' cannot report a delivered transcript',async()=>{const f=fixture(fault),response=await f.post(messages);assert.equal(response.status,503);assert.equal((await response.json()).retryable,true);});
test('logging out on the same browser does not expose the account transcript',async()=>{const f=fixture();await f.post(messages);f.setWho({userId:'',guestIdHash:'same-browser'});assert.equal((await f.get()).status,404);assert.equal(f.filters.at(-1).userId,null);});
test('a different signed-in account cannot read or replace the transcript',async()=>{const f=fixture();f.setWho({userId:'other',guestIdHash:'same-browser'});assert.equal((await f.get()).status,404);assert.equal((await f.post(messages)).status,404);});
