const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('geomancy-oracle-v4.html','utf8'),main=[...source.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1],reader=fs.readFileSync('js/core/paid-narrative-reader.js','utf8');
const pause=()=>new Promise(r=>setTimeout(r,20)),reply=(status,payload)=>({status,json:async()=>payload});
function setup(fetcher,records={}){const dom=new JSDOM(source,{url:'https://mock.test/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,gates=[];let resume;
 w.localStorage.setItem('fortune_auth_user',JSON.stringify({id:'owner-a'}));for(const[k,v]of Object.entries(records))w.localStorage.setItem(k,v);
 w.fetch=fetcher;w.AbortController=AbortController;w.cdStandaloneAiLocale={current:()=> 'ko'};w.requestAnimationFrame=()=>0;w.HTMLElement.prototype.scrollIntoView=function(){};
 const gradient={addColorStop(){}},ctx=new Proxy({},{get:(_t,key)=>key.startsWith('create')?()=>gradient:()=>{}});w.HTMLCanvasElement.prototype.getContext=()=>ctx;
 const timer=w.setTimeout.bind(w);w.setTimeout=(fn,ms)=>timer(fn,ms>=22000?ms:1);
 w.__cdCheckoutEntry={registerPaidResumeHandler:(_kind,handler)=>resume=handler};w._cdCoinGatePerUse=async(cost,_text,onPaid,_cancel,options)=>{gates.push({cost,options});onPaid('paid-id',{requestId:options.requestId});return {ok:true};};
 w.eval(reader);require('node:vm').runInContext(main,dom.getInternalVMContext());return {dom,w,gates,resume:(...args)=>resume(...args)};}
const full={ok:true,saved:true,status:'completed',resultId:'paid-narrative:geomancy-test',requestId:'original',locale:'ko',question:'어떤 선택이 좋을까요?',theme:'sultan',cards:{judge:{english:'Via',korean:'길'}},answer:'저장한 종합 본문',advice:'마지막 신탁 본문'};
test('payment precedes one original cast, storage retry keeps it, and saved result reopens without payment',async()=>{const posts=[];let done=false;
 const e=setup(async(url,options)=>{assert.match(url,/^\/api\/oracle\/(geomancy|result)/);if(options.method==='GET')return done?reply(200,full):reply(404,{});const body=JSON.parse(options.body);posts.push(body);full.requestId=posts[0].requestId;if(posts.length===1)return reply(503,{ok:false,retryable:true,reason:'RESULT_STORAGE_UNAVAILABLE'});if(posts.length===2)return reply(202,{...full,saved:false,status:'partial',totalParts:7,completedParts:['answer'],resumeBody:{resumeResultId:full.resultId}});done=true;return reply(200,full);});
 await pause();e.w.document.getElementById('q-input').value=full.question;await e.w.submitQ();for(let i=0;i<100&&!done;i++)await pause();assert.equal(done,true);assert.equal(e.gates.length,1);assert.equal(e.gates[0].cost,50);assert.equal(e.gates[0].options.resume.args.counts.length,16);assert.equal(e.gates[0].options.requestId,posts[0].requestId);assert.deepEqual(posts[0],posts[1]);assert.deepEqual(posts[2],{resumeResultId:full.resultId});assert.match(e.w.document.getElementById('rs-ai-txt').textContent,/마지막 신탁 본문/);
 e.w.document.querySelector('#rs-ai-txt nav button').click();const key='cd:geomancy:v2:owner-a',saved=e.w.localStorage.getItem(key);assert.equal(JSON.parse(saved).body,null);e.dom.window.close();
 const re=setup(async(_url,options)=>{assert.equal(options.method,'GET');return reply(200,full);},{[key]:saved});await pause();await re.w.recoverGeomancy();assert.equal(re.gates.length,0);assert.match(re.w.document.getElementById('rs-ai-txt').textContent,/읽던 부분으로 이동/);re.dom.window.close();});
test('paid redirect retains original cast and a changed account rejects a late response',async()=>{let release;const e=setup(async(_url,options)=>{if(options.method==='GET')return reply(404,{});return new Promise(resolve=>release=()=>resolve(reply(200,full)));});await pause();const pending=e.resume({args:{requestId:'paid-original',question:full.question,theme:'sultan',counts:Array(16).fill(11)}},{requestId:'paid-original',merchantUid:'paid-id',payload:{}});for(let i=0;i<100&&!release;i++)await pause();assert.ok(release);e.w.localStorage.setItem('fortune_auth_user',JSON.stringify({id:'owner-b'}));e.w.dispatchEvent(new e.w.Event('cd:auth-changed'));release();assert.equal(await pending,false);assert.equal(e.w.localStorage.getItem('cd:geomancy:v2:owner-b'),null);assert.doesNotMatch(e.w.document.getElementById('rs-ai-txt').textContent,/마지막 신탁/);assert.equal(e.gates.length,0);e.dom.window.close();});
