const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const source=ts.transpileModule(fs.readFileSync('app/fortune-chat/paid-turn-recovery.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function fixture(replies){const values=new Map(),calls=[];let active=true;const context={exports:{},DOMException,sessionStorage:{getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)}};vm.runInNewContext(source,context);const body={requestId:'paid-original',birthDate:'1990-01-01',concern:'원래 질문'};return {api:context.exports,values,calls,body,stop:()=>{active=false;},run:(extra={})=>context.exports.requestGuardianTurn({url:'https://mock.test/generate',sessionId:'owned-session',paid:true,body,headers:{},signal:new AbortController().signal,active:()=>active,wait:async()=>{},fetcher:async(_url,opts)=>{calls.push(JSON.parse(opts.body));const item=replies.shift();if(typeof item==='function')return item();if(item instanceof Error)throw item;return {status:item.status,json:async()=>item.payload};},...extra})};}
const pending={status:202,payload:{ok:false,retryable:true,paymentRetainedForRetry:true}},completed={status:200,payload:{ok:true,saved:true,generationSource:'paid',requestId:'paid-original',result:{coreReading:'저장한 본문'}}};
test('lost response and pending save reuse the exact original request',async()=>{const f=fixture([new Error('lost'),pending,completed]);assert.equal((await f.run()).ok,true);assert.equal(f.calls.length,3);for(const call of f.calls)assert.deepEqual(call,f.body);assert.equal(f.api.readPendingTurn('owned-session'),null);assert.equal(f.api.readPendingTurn('owned-session',true).completed,true);});
test('refresh retains original birth, question and request key',async()=>{const f=fixture([pending,pending,pending,pending,completed]);await f.run();assert.ok(f.api.readPendingTurn('owned-session'));await f.run({body:{...f.body,birthDate:'2000-02-02',concern:'새 질문'}});assert.deepEqual(f.calls.at(-1),f.body);assert.equal(f.api.readPendingTurn('other-session',true),null);});
test('revocation removes local retry hint',async()=>{const f=fixture([{status:403,payload:{ok:false}}]);assert.equal((await f.run()).status,403);assert.equal(f.api.readPendingTurn('owned-session',true),null);});
test('account switch discards late result and does not mark it complete',async()=>{const f=fixture([()=>{f.stop();return {status:200,json:async()=>completed.payload};}]);const response=await f.run();assert.equal(response.stale,true);assert.equal(f.api.readPendingTurn('owned-session',true).completed,false);});
test('provider exhaustion remains incomplete without another purchase',async()=>{const f=fixture([{status:202,payload:{ok:false,retryable:false,paymentRetainedForRetry:true}}]);assert.equal((await f.run()).ok,false);assert.equal(f.calls.length,1);assert.ok(f.api.readPendingTurn('owned-session'));});
