const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const root = path.resolve(__dirname, '..', '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

// 달빛 예화(月花) 모티프 시스템 PR-1 (2026-09-03) — 히어로 문양·달 + 섹션 구분선.
// 정본은 scripts/design/gen-yehwa-motifs.mjs → styles/yehwa-motifs.css(생성물) 이고
// index.html 은 그 시트를 렌더블로킹으로 싣는다(구분선이 레이아웃 높이를 가져 늦은 로드는 CLS).

test('the shell loads yehwa-motifs.css before the hero renders', () => {
  const html = read('index.html');
  const link = html.search(/<link rel="stylesheet" href="\/styles\/yehwa-motifs\.css\?v=build-[0-9a-f]+">/);
  const hero = html.indexOf('class="normal-logo moon-hero');
  assert.ok(link > 0, 'blocking <link> for /styles/yehwa-motifs.css is missing');
  assert.ok(hero > 0, 'hero marker missing');
  assert.ok(link < hero, 'yehwa-motifs.css must be linked before the hero markup');
});

test('section dividers sit between the home sections', () => {
  const html = read('index.html');
  const count = (html.match(/<div class="cd-yehwa-divider" aria-hidden="true"><\/div>/g) || []).length;
  assert.ok(count >= 5 && count <= 7, `expected 5~7 dividers, got ${count}`);
});

test('hero motifs live in the ambient layer, never inside the first-paint copy', () => {
  const html = read('index.html');
  const ambientStart = html.indexOf('<div class="moon-hero__ambient"');
  const copyStart = html.indexOf('<div class="moon-hero__copy">', ambientStart);
  assert.ok(ambientStart > 0 && copyStart > ambientStart);
  const ambient = html.slice(ambientStart, copyStart);
  for (const cls of ['moon-hero__yehwa--bl', 'moon-hero__yehwa--tr', 'moon-hero__yehwa-moon']) {
    assert.ok(ambient.includes(cls), `${cls} missing from .moon-hero__ambient`);
  }
  // 🔴 verify:hero-firstpaint-lock — 카피·trust 블록 안에 장식을 넣지 않는다.
  const copyEnd = html.indexOf('<div class="moon-hero__visual ', copyStart);
  assert.ok(copyEnd > copyStart);
  assert.ok(!html.slice(copyStart, copyEnd).includes('moon-hero__yehwa'), 'motif markup leaked into .moon-hero__copy');
});

test('yehwa-motifs.css is generated, paired for Safari, quiet, and repainted for neo', () => {
  const css = read('styles/yehwa-motifs.css');
  // sync:public 의 TINY_THRESHOLD(512B) 보다 커야 미러가 생긴다.
  assert.ok(css.length > 2048, `stylesheet suspiciously small: ${css.length}`);
  assert.match(css, /^\/\* generated by scripts\/design\/gen-yehwa-motifs\.mjs/);
  const webkit = (css.match(/-webkit-mask-image:/g) || []).length;
  const std = (css.match(/(?<![-\w])mask-image:/g) || []).length;
  assert.ok(webkit > 0 && webkit === std, `mask-image pairs mismatch: -webkit ${webkit} vs std ${std}`);
  // 네오 재도색 — 같은 마스크, 칠만 샴페인골드.
  assert.match(css, /html\.neo-mode body \.moon-hero__yehwa[^{]*\{[^}]*background:/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-divider::before[^{]*\{[^}]*background:/);
  // 라인아트는 텍스트 뒤의 배경 장식 — 실측(2026-09-03) 연이 히어로 일러스트 위에서 .5 가 선 대비 1.3:1(은은),
  // 그 위로 올리면 일러스트를 덮는다. 상한 .5 를 넘기면 장식이 아니라 그림이 된다.
  const blocks = css.match(/\.moon-hero__yehwa(?:--\w+)?\s*[{,][^}]*\}/g) || [];
  assert.ok(blocks.length >= 3);
  for (const block of blocks) {
    const m = block.match(/opacity:\s*(\.\d+|\d(?:\.\d+)?)/);
    if (m) assert.ok(Number(m[1]) <= 0.5, `hero motif opacity too high: ${block.slice(0, 60)} → ${m[1]}`);
  }
  assert.match(css, /\.moon-hero__yehwa\s*\{[^}]*z-index:\s*0/);
});

// ── PR-2 (2026-09-03) — 카드 인장·스파클 ───────────────────────────────────────
// 인장은 두 카드 모두 "모서리 밖으로 걸쳐 두고 카드의 overflow 로 자른다"는 한 가지 방식으로 놓았고,
// 그래서 호스트 카드의 담기(position/isolation/overflow)가 빠지면 조용히 사라지거나 카드 밖으로 샌다.

test('seals are child spans on the two host cards, sparkles sit inside the art box', () => {
  const html = read('index.html');
  assert.equal((html.match(/<span class="cd-yehwa-seal"/g) || []).length, 6, 'expected 6 seals (운명의 문 1 + 대표 상담 5)');
  assert.equal((html.match(/class="cd-yehwa-seal" aria-hidden="true"/g) || []).length, 6, 'every seal must be aria-hidden');
  // 🔴 ::before/::after 로 바꾸지 말 것 — .cd-sig-card 는 animation-fill-mode:backwards 인 cdSigRise 를 돌아
  // 의사요소가 시작 프레임 값에 붙들린다. 자식 span 이라야 카드와 함께 움직인다(hover/active 실측 동일 좌표).
  const sig = html.match(/<a class="cd-sig-card(?: cd-sig-card--[a-z]+)?"[^>]*>[^<]*<span class="cd-yehwa-seal"/g) || [];
  assert.equal(sig.length, 5, `대표 상담 카드 5장 전부에 인장이 있어야 한다 (현재 ${sig.length})`);
  // 🔴 빠른 서비스 카드에는 인장을 두지 않는다(2026-09-03 사용자 결정) — 182x106px 카드에서
  // 72px 인장은 높이의 68% 이고, 그 크기에서는 꽃잎이 직선 방사살로 잘려 "시계 밴드"로 읽혔다.
  const quick = html.match(/<a class="cd-quick-card"[^>]*>[^<]*<span class="cd-yehwa-seal"/g) || [];
  assert.equal(quick.length, 0, `빠른 서비스 카드에는 인장이 없어야 한다 (현재 ${quick.length})`);
  const doorStart = html.indexOf('<a class="fortune-gateway__door fortune-gateway__door--chat"');
  assert.ok(doorStart > 0, '운명의 문 카드 마커가 없다');
  const doorHead = html.slice(doorStart, html.indexOf('fortune-gateway__door-art', doorStart));
  assert.ok(doorHead.includes('<span class="cd-yehwa-seal"'), '운명의 문 카드 인장이 아트 상자 앞에 없다');

  // 스파클은 아트 상자 안에만 둔다 — 카드 기준 px 로 놓으면 문구가 바뀔 때 글자를 덮는다.
  const artStart = html.indexOf('<span class="fortune-gateway__door-art" aria-hidden="true">');
  assert.ok(artStart > 0, '.fortune-gateway__door-art 마커가 없다');
  const artEnd = html.indexOf('</span>\n              <span class="fortune-gateway__door-kicker">', artStart);
  assert.ok(artEnd > artStart, '아트 상자의 끝을 찾지 못했다');
  const art = html.slice(artStart, artEnd);
  for (const cls of ['cd-yehwa-sparkle--a', 'cd-yehwa-sparkle--b', 'cd-yehwa-sparkle--c']) {
    assert.ok(art.includes(cls), `${cls} 가 아트 상자 밖에 있다`);
  }
  assert.equal((html.match(/cd-yehwa-sparkle--/g) || []).length, 3, '스파클은 아트 상자 안 3개뿐이어야 한다');
});

test('seal and sparkle placements are generated for every host and repainted for neo', () => {
  const css = read('styles/yehwa-motifs.css');
  for (const sel of ['.fortune-gateway__door--chat .cd-yehwa-seal', '.cd-sig-card .cd-yehwa-seal']) {
    assert.ok(css.includes(`${sel} {`), `${sel} 배치 규칙이 없다`);
  }
  assert.ok(!css.includes('.cd-quick-card .cd-yehwa-seal'), '빠른 서비스 카드용 인장 규칙은 두지 않는다');
  assert.match(css, /\.cd-yehwa-seal \{[^}]*z-index:\s*-1/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-seal[^{]*\{[^}]*background:/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-sparkle[^{]*\{[^}]*background:/);
  // 인장·스파클은 히어로 문양(<= .5)보다 진하지만 선문양의 상한은 있다 — 넘기면 장식이 아니라 그림이 된다.
  const blocks = css.match(/\.cd-yehwa-(?:seal|sparkle)[^{]*\{[^}]*\}/g) || [];
  assert.ok(blocks.length >= 4);
  for (const block of blocks) {
    const m = block.match(/opacity:\s*(\.\d+|\d(?:\.\d+)?)/);
    if (m) assert.ok(Number(m[1]) <= 0.6, `card motif opacity too high: ${block.slice(0, 48)} → ${m[1]}`);
  }
});

// ── PR-3 (2026-09-03) — 섹션 코너 가지 · 고민 활성 카드 인장 · 모란 ────────────────
// 가지·모란도 인장과 같은 방식이다: 호스트의 자식 <span>, z-index -1, 호스트가 이미 가진 스태킹 컨텍스트에 기댄다.
// 자리는 전부 폭 스윕(1350→390, 12단계)으로 글자 잉크와 겹침 0 을 확인한 좌표이므로 옮길 때는 같은 스윕을 다시 돈다.

test('sprigs, concern seals and peonies are child spans on their hosts', () => {
  const html = read('index.html');
  assert.equal((html.match(/class="cd-yehwa-sprig /g) || []).length, 4, '가지는 왜 우리 2 + AI 카드 2 = 4개');
  assert.equal((html.match(/<span class="cd-yehwa-sprig cd-yehwa-sprig--(?:tl|tr)" aria-hidden="true"><\/span>/g) || []).length, 4, '가지는 전부 aria-hidden 인 --tl/--tr 이어야 한다');
  assert.match(html, /<section data-cd-funnel-section="why_us" class="cd-why-us"[^>]*>\s*<span class="cd-yehwa-sprig cd-yehwa-sprig--tl"/, '왜 우리 섹션 첫 자식이 가지가 아니다');
  assert.match(html, /<section class="cd-ai-feats"[^>]*>\s*<span class="cd-yehwa-sprig cd-yehwa-sprig--tl"/, 'AI 카드 첫 자식이 가지가 아니다');
  // 🔴 파인더 가격 행은 단방향 가지(branch-spray)만 받는다 — 좌우 대칭인 구분선 마스크(branch-h)를 여기 두면
  // 방식/가격 행 사이 거터에 미러 쌍이 떠서 "나눌 것 없는 자리의 구분선"으로 읽힌다(2026-09-03 시각 판정).
  // 문양은 필터 묶음(.fortune-gateway__filters)이 아니라 가격 행 안에 있어야 자리가 행 baseline 에 붙는다.
  assert.doesNotMatch(html, /<div class="fortune-gateway__filters"[^>]*>\s*<span class="cd-yehwa/, '문양은 필터 묶음이 아니라 가격 행 안에 둔다');
  assert.equal((html.match(/class="cd-yehwa-spray"/g) || []).length, 1, '가지 스프레이는 파인더 가격 행 1개뿐이어야 한다');
  assert.match(html, /<div class="fortune-gateway__filter-row" role="group" aria-label="가격대로 좁히기"[^>]*>\s*<span class="cd-yehwa-spray" aria-hidden="true"><\/span>/, '가격 행 첫 자식이 가지 스프레이가 아니다');

  // 고민 카드 6장 전부에 인장 span 이 있고 CSS 가 aria-expanded=true 인 카드에서만 켠다.
  const concern = html.match(/<button type="button" class="cd-concern__card"[^>]*>\s*<span class="cd-yehwa-seal cd-yehwa-seal--concern" aria-hidden="true"><\/span>/g) || [];
  assert.equal(concern.length, 6, `고민 카드 6장 전부에 인장이 있어야 한다 (현재 ${concern.length})`);
  assert.equal((html.match(/cd-yehwa-seal--concern"/g) || []).length, 6, '고민 인장은 카드 안 6개뿐이어야 한다');

  assert.ok(html.includes('<div class="cd-feedback__copy"><span class="cd-yehwa-peony" aria-hidden="true"></span>'), '피드백 카드 가운데 열의 모란이 없다');
  assert.ok(html.includes('<div class="cd-footer-shell" data-marker="cd-footer-refine-v20260724"><span class="cd-yehwa-peony" aria-hidden="true"></span>'), '푸터 링크 허브의 모란이 없다');
  assert.equal((html.match(/class="cd-yehwa-peony"/g) || []).length, 2, '모란은 피드백 카드 + 푸터 2개뿐이어야 한다');
});

test('PR-3 placements are generated, ordered by width, and repainted for neo', () => {
  const css = read('styles/yehwa-motifs.css');
  for (const sel of [
    '.cd-why-us > .cd-yehwa-sprig',
    '.cd-ai-feats > .cd-yehwa-sprig',
    '.cd-concern__card[aria-expanded="true"] .cd-yehwa-seal--concern',
    '.cd-feedback__copy > .cd-yehwa-peony',
    '.cd-footer-shell > .cd-yehwa-peony',
  ]) {
    assert.ok(css.includes(`${sel} {`), `${sel} 배치 규칙이 없다`);
  }
  assert.ok(css.includes('.fortune-gateway__filter-row > .cd-yehwa-spray {'), '파인더 가격 행 스프레이 배치 규칙이 없다');
  assert.ok(!css.includes('.fortune-gateway__filters > .cd-yehwa'), '문양은 필터 묶음이 아니라 가격 행에 붙인다');
  // 🔴 파인더에 좌우 대칭 구분선 마스크를 쓰지 않는다 — 단방향 branch-spray 만.
  const spray = (css.match(/\.fortune-gateway__filter-row > \.cd-yehwa-spray \{[^}]*\}/) || [])[0] || "";
  assert.match(spray, /mask-image:\s*var\(--cd-yehwa-mask-branch-spray\)/, '스프레이는 branch-spray 마스크여야 한다');
  assert.ok(!spray.includes('branch-h'), '파인더에 좌우 대칭 구분선 마스크를 쓰지 않는다');
  // 🔴 행이 스태킹 컨텍스트를 만들어야 z-index:-1 이 패널의 불투명 배경 뒤로 빠지지 않는다.
  assert.match(css, /\.fortune-gateway__filter-row \{[^}]*position:\s*relative[^}]*z-index:\s*0/, '가격 행에 스태킹 컨텍스트가 없다');
  assert.match(css, /\.cd-yehwa-sprig \{[^}]*z-index:\s*-1/);
  assert.match(css, /\.cd-yehwa-peony \{[^}]*z-index:\s*-1/);
  // 비활성 고민 카드에는 인장이 보이면 안 된다 — 기본 display:none, 활성 카드에서만 block.
  assert.match(css, /\.cd-concern__card \.cd-yehwa-seal--concern \{[^}]*display:\s*none/);
  assert.match(css, /\.cd-concern__card\[aria-expanded="true"\] \.cd-yehwa-seal--concern \{[^}]*display:\s*block/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-sprig[^{]*\{[^}]*background:/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-peony[^{]*\{[^}]*background:/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-spray[^{]*\{[^}]*background:/);
  assert.match(css, /html\.neo-mode body \.cd-concern__card \.cd-yehwa-seal--concern[^{]*\{[^}]*background:/);
  // 🔴 AI 카드 가지의 1200px 축소 규칙은 900px 모바일 규칙보다 앞에 있어야 한다 — 두 --tr 규칙의 특이도가 같아
  // 순서로 이기고, 뒤집히면 모바일에서 170x131 이 남아 제목과 겹친다(2026-09-03 실제로 한 번 뒤집혔다).
  const w1200 = css.indexOf('@media (max-width: 1200px)');
  const w900 = css.indexOf('@media (max-width: 900px)');
  assert.ok(w1200 > 0 && w900 > w1200, `1200px 블록(${w1200})이 900px 블록(${w900})보다 앞에 있어야 한다`);
  const block900 = css.slice(w900, css.indexOf('@media', w900 + 1));
  assert.ok(block900.includes('.cd-ai-feats > .cd-yehwa-sprig--tr {'), '900px 블록에 AI 우상단 가지 축소 규칙이 없다');
  assert.match(block900, /\.cd-ai-feats > \.cd-yehwa-sprig--tl \{[^}]*display:\s*none/, '900px 아래에서 AI 좌상단 가지를 꺼야 한다');
  assert.match(block900, /\.cd-yehwa-peony,[^{]*\{[^}]*display:\s*none/, '900px 아래에서 모란을 꺼야 한다');
  assert.match(block900, /\.fortune-gateway__filter-row > \.cd-yehwa-spray,[^{]*\{[^}]*display:\s*none/, '900px 아래에서 파인더 스프레이를 꺼야 한다');
  // 선문양 상한은 인장과 같다(.6) — 넘기면 장식이 아니라 그림이 된다.
  const blocks = css.match(/\.cd-yehwa-(?:sprig|peony|spray)[^{]*\{[^}]*\}/g) || [];
  assert.ok(blocks.length >= 7);
  for (const block of blocks) {
    const m = block.match(/opacity:\s*(\.\d+|\d(?:\.\d+)?)/);
    if (m) assert.ok(Number(m[1]) <= 0.6, `line motif opacity too high: ${block.slice(0, 48)} → ${m[1]}`);
  }
});

test('the generator reproduces the committed stylesheet byte for byte', () => {
  execFileSync(process.execPath, [path.join(root, 'scripts/design/gen-yehwa-motifs.mjs'), '--check'], {
    cwd: root,
    stdio: 'pipe',
  });
});
