const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const root = path.resolve(__dirname, '..', '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

// 달빛 예화(月花) 모티프 시스템 PR-1 (2026-09-03) — 히어로 문양·달 + 섹션 구분선.
// 정본은 scripts/design/gen-yehwa-motifs.mjs → styles/yehwa-motifs.css(생성물) 이고
// index.html 은 그 시트를 렌더블로킹으로 싣는다(구분선이 레이아웃 높이를 가져 늦은 로드는 CLS).

test('the shell loads yehwa-motifs.css before the hero renders', () => {
  const html = read('index.html');
  const link = html.search(/<link rel="stylesheet" href="\/styles\/yehwa-motifs\.css\?v=build-[0-9a-f]+">/);
  const hero = html.indexOf('class="normal-logo moon-hero');
  assert.ok(link > 0, 'blocking <link> for /styles/yehwa-motifs.css is missing');
  assert.ok(hero > 0, 'hero marker missing');
  assert.ok(link < hero, 'yehwa-motifs.css must be linked before the hero markup');
});

test('section dividers sit between the home sections', () => {
  const html = read('index.html');
  const count = (html.match(/<div class="cd-yehwa-divider" aria-hidden="true"><\/div>/g) || []).length;
  assert.ok(count >= 5 && count <= 7, `expected 5~7 dividers, got ${count}`);
});

test('hero motifs live in the ambient layer, never inside the first-paint copy', () => {
  const html = read('index.html');
  const ambientStart = html.indexOf('<div class="moon-hero__ambient"');
  const copyStart = html.indexOf('<div class="moon-hero__copy">', ambientStart);
  assert.ok(ambientStart > 0 && copyStart > ambientStart);
  const ambient = html.slice(ambientStart, copyStart);
  for (const cls of ['moon-hero__yehwa--bl', 'moon-hero__yehwa--tr', 'moon-hero__yehwa-moon']) {
    assert.ok(ambient.includes(cls), `${cls} missing from .moon-hero__ambient`);
  }
  // 🔴 verify:hero-firstpaint-lock — 카피·trust 블록 안에 장식을 넣지 않는다.
  const copyEnd = html.indexOf('<div class="moon-hero__visual ', copyStart);
  assert.ok(copyEnd > copyStart);
  assert.ok(!html.slice(copyStart, copyEnd).includes('moon-hero__yehwa'), 'motif markup leaked into .moon-hero__copy');
});

test('yehwa-motifs.css is generated, paired for Safari, quiet, and repainted for neo', () => {
  const css = read('styles/yehwa-motifs.css');
  // sync:public 의 TINY_THRESHOLD(512B) 보다 커야 미러가 생긴다.
  assert.ok(css.length > 2048, `stylesheet suspiciously small: ${css.length}`);
  assert.match(css, /^\/\* generated by scripts\/design\/gen-yehwa-motifs\.mjs/);
  const webkit = (css.match(/-webkit-mask-image:/g) || []).length;
  const std = (css.match(/(?<![-\w])mask-image:/g) || []).length;
  assert.ok(webkit > 0 && webkit === std, `mask-image pairs mismatch: -webkit ${webkit} vs std ${std}`);
  // 네오 재도색 — 같은 마스크, 칠만 샴페인골드.
  assert.match(css, /html\.neo-mode body \.moon-hero__yehwa[^{]*\{[^}]*background:/);
  assert.match(css, /html\.neo-mode body \.cd-yehwa-divider::before[^{]*\{[^}]*background:/);
  // 라인아트는 텍스트 뒤의 배경 장식 — 실측(2026-09-03) 연이 히어로 일러스트 위에서 .5 가 선 대비 1.3:1(은은),
  // 그 위로 올리면 일러스트를 덮는다. 상한 .5 를 넘기면 장식이 아니라 그림이 된다.
  const blocks = css.match(/\.moon-hero__yehwa(?:--\w+)?\s*[{,][^}]*\}/g) || [];
  assert.ok(blocks.length >= 3);
  for (const block of blocks) {
    const m = block.match(/opacity:\s*(\.\d+|\d(?:\.\d+)?)/);
    if (m) assert.ok(Number(m[1]) <= 0.5, `hero motif opacity too high: ${block.slice(0, 60)} → ${m[1]}`);
  }
  assert.match(css, /\.moon-hero__yehwa\s*\{[^}]*z-index:\s*0/);
});

test('the generator reproduces the committed stylesheet byte for byte', () => {
  execFileSync(process.execPath, [path.join(root, 'scripts/design/gen-yehwa-motifs.mjs'), '--check'], {
    cwd: root,
    stdio: 'pipe',
  });
});
