const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const ast=ts.createSourceFile('client.tsx',fs.readFileSync('app/nakshatra/ai/NakshatraAiClient.tsx','utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let fn;function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='pollResult')fn=n.initializer.arguments[0];ts.forEachChild(n,visit)}visit(ast);
function fixture(){let current=true,completed=false;const posts=[],partials=[],finished=[],errors=[];const ctx=vm.createContext({Date,JSON,encodeURIComponent,captureOwner:()=>()=>current,pendingId:{current:''},pendingStart:{current:null},busyRef:{current:false},setPhase:()=>{},TRANSIENT_MAX_RETRIES:6,GENERATION_DEADLINE_MS:600000,POLL_MAX_ATTEMPTS:45,POLL_INTERVAL_MS:0,sleep:async()=>{},document:{hidden:false},navigator:{onLine:true},ACCESS_TOKEN_HEADER:'access',API:{result:'/result',generate:'/generate',start:'/start'},toText:v=>String(v||''),copy:{aiErrorConflict:'conflict',aiErrorTimeout:'timeout'},applyProgress:v=>partials.push(v),finish:v=>finished.push(v),fail:v=>errors.push(v),isRetriableResultPollFailure:status=>status>=500,authFetch:async(url,init)=>{if(init.method==='POST'){posts.push(JSON.parse(init.body));completed=true}return{ok:true,status:completed?200:202,json:async()=>({ok:true,sessionId:'saved',status:completed?'completed':'generating',decks:{consultation:[]}})}}});vm.runInContext(ts.transpileModule('const run = '+fn.getText(ast),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx);return{ctx,posts,partials,finished,errors,run:()=>vm.runInContext('run("saved", "")',ctx),changeOwner:()=>{current=false}}}
test('saved partial GET continues POST with the same ID',async()=>{const f=fixture();await f.run();assert.deepEqual(f.posts,[{sessionId:'saved'}]);assert.equal(f.finished.length,1);assert.equal(f.partials[0].status,'generating')});
test('hidden or offline screen starts no provider wave',async()=>{for(const hidden of [true,false]){const f=fixture();f.ctx.document.hidden=hidden;f.ctx.navigator.onLine=hidden;await f.run();assert.equal(f.posts.length,0);assert.equal(f.ctx.pendingId.current,'saved')}});
test('account switch rejects a late response',async()=>{const f=fixture();f.ctx.authFetch=async()=>{f.changeOwner();return{status:202,json:async()=>({sessionId:'saved'})}};await f.run();assert.equal(f.partials.length,0);assert.equal(f.posts.length,0)});
test('storage failures retain the server ID and never acknowledge completion',async()=>{const f=fixture();f.ctx.authFetch=async()=>({status:503,json:async()=>({ok:false,retryable:true})});await f.run();assert.equal(f.ctx.pendingId.current,'saved');assert.equal(f.finished.length,0);assert.deepEqual(f.errors,['timeout'])});
test('missing initial save retries the original request without a payment gate',async()=>{const f=fixture();f.ctx.pendingStart.current={body:{paymentId:'original-receipt'},key:'original-key'};f.ctx.authFetch=async()=>({status:404,json:async()=>({})});f.ctx.postJson=async(path,body,key)=>{assert.equal(path,'/start');assert.equal(key,'original-key');assert.equal(body.paymentId,'original-receipt');return{response:{status:200,ok:true},data:{status:'completed',decks:{consultation:[]}}}};await f.run();assert.equal(f.finished.length,1)});

test('transient failures preserve the progress budget and retain a finite retry ceiling',async()=>{const f=fixture();f.ctx.POLL_MAX_ATTEMPTS=1;let calls=0;f.ctx.authFetch=async()=>{calls++;return calls<6?{status:503,json:async()=>({retryable:true})}:{ok:true,status:200,json:async()=>({status:'completed',decks:{consultation:[]}})}};await f.run();assert.equal(calls,6);assert.equal(f.finished.length,1);assert.equal(f.errors.length,0)});
