const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom'),vm=require('vm');
const source=fs.readFileSync('yoga-guru.html','utf8'),main=[...source.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('let selectedDuration')),reader=fs.readFileSync('js/core/paid-narrative-reader.js','utf8');
const pause=()=>new Promise(r=>setTimeout(r,20)),reply=(status,payload)=>({status,json:async()=>payload});
function setup(fetcher,records={}){const dom=new JSDOM(source,{url:'https://mock.test/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,gates=[];let resume;
 w.localStorage.setItem('fortune_auth_user',JSON.stringify({id:'owner-a'}));for(const[k,v]of Object.entries(records))w.localStorage.setItem(k,v);
 w.fetch=fetcher;w.AbortController=AbortController;w.cdStandaloneAiLocale={current:()=> 'ko'};w.requestAnimationFrame=()=>0;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};
 const timer=w.setTimeout.bind(w);w.setTimeout=(fn,ms)=>timer(fn,ms>=22000?ms:1);
 w.__cdCheckoutEntry={registerPaidResumeHandler:(_kind,handler)=>resume=handler};w._cdCoinGatePerUse=async(cost,_text,onPaid,_cancel,options)=>{gates.push({cost,options});onPaid('paid-id',{requestId:options.requestId});return {ok:true};};
 w.eval(reader);vm.runInContext(main,dom.getInternalVMContext());return {dom,w,gates,resume:(...args)=>resume(...args)};}
function full(duration){return {ok:true,saved:true,status:'completed',resultId:'paid-narrative:yoga-test',requestId:'original',locale:'ko',duration,source:'gemini',course_metadata:{title:'저장한 수련 코스',duration_min:duration,intensity:'Beginner',focus_area:'편안한 움직임'},sequence:['Warmup','Asana','Pranayama','Relaxation'].map((type,i)=>({step_number:i+1,type,english_name:'Practice '+i,sanskrit_name:'Practice '+i,duration_seconds:duration*15,instructions:[i+'단계의 첫 안내',i+'단계의 마지막 안내'],breathing_guide:'편안한 호흡을 유지해 주세요.',benefits_physical:'자신의 상태를 관찰하세요.',benefits_spiritual:'상징으로 주의를 모아 보세요.',caution:'불편하면 쉬어 주세요.'})),closing_mantra:'마지막 수련 안내'};}
for(const duration of[30,60])test(duration+' minute purchase retries storage with original request, then reopens saved course',async()=>{const posts=[],data=full(duration);let done=false;
 const e=setup(async(url,options)=>{assert.match(url,/\/api\/yoga-guru/);assert.doesNotMatch(url,/refund|billing/);if(options.method==='GET')return done?reply(200,data):reply(404,{});const body=JSON.parse(options.body);posts.push(body);data.requestId=posts[0].requestId;if(posts.length===1)return reply(503,{ok:false,retryable:true,reason:'RESULT_STORAGE_UNAVAILABLE'});if(posts.length===2)return reply(202,{...data,saved:false,status:'generating',course_metadata:undefined,sequence:undefined,totalParts:1,completedParts:[],resumeBody:{resumeResultId:data.resultId}});done=true;return reply(200,data);});
 await pause();e.w.document.getElementById('moodInput').value='오늘은 차분하게 쉬고 싶어요.';const button=e.w.document.querySelector('[data-duration="'+duration+'"]');e.w.selectDuration(button,duration);assert.equal(await e.w.invokeGuru(),true);assert.equal(e.gates.length,1);assert.equal(e.gates[0].cost,duration===30?30:50);assert.equal(e.gates[0].options.requestId,posts[0].requestId);assert.equal(e.gates[0].options.resume.args.duration,duration);assert.deepEqual(posts[0],posts[1]);assert.deepEqual(posts[2],{resumeResultId:data.resultId});assert.match(e.w.document.getElementById('courseOutput').textContent,/마지막 수련 안내/);e.w.document.querySelectorAll('.step-header')[3].click();const key='cd:yoga:v2:owner-a',saved=e.w.localStorage.getItem(key);assert.equal(JSON.parse(saved).body,null);e.dom.window.close();
 const re=setup(async(_url,options)=>{assert.equal(options.method,'GET');return reply(200,data);},{[key]:saved});await pause();await re.w.recoverYoga();assert.equal(re.gates.length,0);assert.ok(re.w.document.querySelectorAll('.step-card')[3].classList.contains('expanded'));assert.ok(re.w.document.getElementById('musicPanel'));re.dom.window.close();});
test('account change rejects a late paid course without writing or refunding',async()=>{let release;const e=setup(async(url,options)=>{assert.doesNotMatch(url,/refund|billing/);if(options.method==='GET')return reply(404,{});return new Promise(resolve=>release=()=>resolve(reply(200,full(30))));});await pause();const pending=e.resume({args:{requestId:'paid-original',mood:'편안하게 쉬고 싶어요.',duration:30}},{requestId:'paid-original',merchantUid:'paid-id',payload:{}});for(let i=0;i<100&&!release;i++)await pause();assert.ok(release);e.w.localStorage.setItem('fortune_auth_user',JSON.stringify({id:'owner-b'}));e.w.dispatchEvent(new e.w.Event('cd:auth-changed'));release();assert.equal(await pending,false);assert.equal(e.w.localStorage.getItem('cd:yoga:v2:owner-b'),null);assert.doesNotMatch(e.w.document.getElementById('courseOutput').textContent,/마지막 수련/);assert.equal(e.gates.length,0);e.dom.window.close();});
