// Existing runtime locale keys; shared copy for React and legacy adapters.
const keys = ['title','disclosure','pending','intro','back','more','view','search','price','ad','empty','preview','dismiss','all','purpose','budget','species','cat','dog','generic','image','returnResult'];
const rows = {
 ko: ['영냥이의 생활 추천','이 게시물은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다.','생활 추천을 준비하고 있어요. 검수를 마친 상품부터 소개할게요.','운세를 읽은 뒤, 일상에 이어갈 작은 선택을 둘러보세요. 구매 가능 여부와 배송 조건은 쿠팡에서 확인해 주세요.','뒤로가기','관련 추천 더 보기','쿠팡에서 보기 ↗','관련 상품 검색 결과 보기 ↗','쿠팡에서 현재 가격 확인','제휴 광고','선택한 조건에 맞는 상품을 준비하고 있어요.','미리보기 · 실제 상품과 구매 링크가 아닙니다','추천 접기','전체','관심사','예산 상한 (원)','반려동물 선택','고양이','강아지','일반 수집 용품','상품 이미지 준비 중','운세 결과로 돌아가기'],
 en: ['Yeongnyangi’s everyday picks','This post is part of the Coupang Partners program, through which we receive a commission.','Everyday picks are being prepared. Products will appear after review.','Explore small choices for everyday life after your reading. Check availability and delivery terms on Coupang.','Back','More related picks','View on Coupang ↗','View related search results ↗','Check current price on Coupang','Affiliate ad','No reviewed products match these choices yet.','Preview · Not a real product or purchase link','Hide picks','All','Interests','Budget limit (KRW)','Choose a pet','Cat','Dog','General collecting supplies','Product image pending','Return to your reading'],
 ja: ['ヨンニャンの日常のおすすめ','この記事はCoupang Partnersの活動の一環であり、当方は一定の手数料を受け取ります。','日常のおすすめを準備中です。確認済みの商品からご紹介します。','鑑定のあと、日常につながる小さな選択を。購入可否と配送条件はCoupangでご確認ください。','戻る','関連するおすすめを見る','Coupangで見る ↗','関連商品の検索結果を見る ↗','現在の価格はCoupangで確認','アフィリエイト広告','条件に合う確認済み商品はまだありません。','プレビュー・実際の商品や購入リンクではありません','おすすめを閉じる','すべて','関心','予算上限（ウォン）','ペットを選択','猫','犬','一般的な収集用品','商品画像を準備中','鑑定結果に戻る'],
 'zh-CN': ['灵喵的生活推荐','本内容属于Coupang Partners推广活动，我们将从中获得一定佣金。','生活推荐正在准备中，审核后的商品会在这里展示。','读完运势，看看适合日常生活的小选择。能否购买及配送条件请在Coupang确认。','返回','查看更多相关推荐','前往Coupang查看 ↗','查看相关商品搜索结果 ↗','在Coupang确认当前价格','联盟广告','暂时没有符合条件的已审核商品。','预览·非真实商品或购买链接','收起推荐','全部','兴趣','预算上限（韩元）','选择宠物','猫','狗','通用收藏用品','商品图片准备中','返回运势结果'],
 'zh-TW': ['靈喵的生活推薦','本內容屬於Coupang Partners推廣活動，我們將從中獲得一定佣金。','生活推薦正在準備中，審核後的商品會在這裡展示。','讀完運勢，看看適合日常生活的小選擇。能否購買及配送條件請在Coupang確認。','返回','查看更多相關推薦','前往Coupang查看 ↗','查看相關商品搜尋結果 ↗','在Coupang確認目前價格','聯盟廣告','暫時沒有符合條件的已審核商品。','預覽・非真實商品或購買連結','收起推薦','全部','興趣','預算上限（韓元）','選擇寵物','貓','狗','通用收藏用品','商品圖片準備中','返回運勢結果'],
 vi: ['Gợi ý thường ngày của Yeongnyangi','Bài viết này thuộc chương trình Coupang Partners và chúng tôi nhận được một khoản hoa hồng từ hoạt động này.','Các gợi ý đang được chuẩn bị. Sản phẩm sẽ xuất hiện sau khi được kiểm tra.','Khám phá lựa chọn cho cuộc sống thường ngày. Kiểm tra khả năng mua và điều kiện giao hàng trên Coupang.','Quay lại','Xem thêm gợi ý','Xem trên Coupang ↗','Xem kết quả tìm kiếm liên quan ↗','Kiểm tra giá hiện tại trên Coupang','Quảng cáo liên kết','Chưa có sản phẩm đã kiểm tra phù hợp.','Xem trước · Không phải sản phẩm hay liên kết mua thật','Ẩn gợi ý','Tất cả','Sở thích','Giới hạn ngân sách (KRW)','Chọn thú cưng','Mèo','Chó','Đồ dùng sưu tầm chung','Đang chuẩn bị ảnh sản phẩm','Quay lại kết quả'],
 hi: ['योंगन्यांगी के रोज़मर्रा के सुझाव','यह पोस्ट Coupang Partners कार्यक्रम का हिस्सा है, जिसके अंतर्गत हमें कमीशन मिलता है।','सुझाव तैयार किए जा रहे हैं। जाँचे गए उत्पाद ही दिखाए जाएँगे।','अपने पठन के बाद रोज़मर्रा के छोटे विकल्प देखें। उपलब्धता और डिलीवरी की शर्तें Coupang पर जाँचें।','वापस','और संबंधित सुझाव','Coupang पर देखें ↗','संबंधित खोज परिणाम देखें ↗','वर्तमान कीमत Coupang पर देखें','एफिलिएट विज्ञापन','इन विकल्पों से मेल खाने वाले जाँचे गए उत्पाद अभी नहीं हैं।','पूर्वावलोकन · वास्तविक उत्पाद या खरीद लिंक नहीं','सुझाव छिपाएँ','सभी','रुचियाँ','बजट सीमा (KRW)','पालतू जानवर चुनें','बिल्ली','कुत्ता','सामान्य संग्रह सामग्री','उत्पाद चित्र तैयार हो रहा है','पठन परिणाम पर लौटें'],
 es: ['Selecciones cotidianas de Yeongnyangi','Esta publicación forma parte de Coupang Partners, programa por el que recibimos una comisión.','Estamos preparando las recomendaciones. Solo aparecerán productos revisados.','Explora pequeñas opciones para el día a día. Consulta disponibilidad y entrega en Coupang.','Volver','Más recomendaciones','Ver en Coupang ↗','Ver resultados de búsqueda relacionados ↗','Consultar precio actual en Coupang','Publicidad de afiliación','Aún no hay productos revisados que coincidan.','Vista previa · No es un producto ni enlace de compra real','Ocultar recomendaciones','Todo','Intereses','Presupuesto máximo (KRW)','Elegir mascota','Gato','Perro','Accesorios de colección generales','Imagen pendiente','Volver a la lectura'],
 fr: ['Les choix du quotidien de Yeongnyangi','Cette publication fait partie du programme Coupang Partners, dans le cadre duquel nous percevons une commission.','Les recommandations sont en préparation. Seuls les produits vérifiés seront présentés.','Découvrez de petits choix pour le quotidien. Vérifiez la disponibilité et la livraison sur Coupang.','Retour','Autres recommandations','Voir sur Coupang ↗','Voir les résultats de recherche associés ↗','Vérifier le prix actuel sur Coupang','Publicité affiliée','Aucun produit vérifié ne correspond pour le moment.','Aperçu · Ni produit réel ni lien d’achat','Masquer les recommandations','Tout','Centres d’intérêt','Budget maximal (KRW)','Choisir un animal','Chat','Chien','Accessoires de collection généraux','Image en préparation','Revenir à la lecture'],
 de: ['Yeongnyangis Alltagstipps','Dieser Beitrag ist Teil des Coupang-Partners-Programms, über das wir eine Provision erhalten.','Die Empfehlungen werden vorbereitet. Es werden nur geprüfte Produkte angezeigt.','Entdecke kleine Ideen für den Alltag. Verfügbarkeit und Lieferbedingungen bitte bei Coupang prüfen.','Zurück','Weitere Empfehlungen','Bei Coupang ansehen ↗','Ähnliche Suchergebnisse ansehen ↗','Aktuellen Preis bei Coupang prüfen','Affiliate-Werbung','Noch keine geprüften Produkte für diese Auswahl.','Vorschau · Kein echtes Produkt oder Kauflink','Empfehlungen ausblenden','Alle','Interessen','Budgetgrenze (KRW)','Haustier auswählen','Katze','Hund','Allgemeines Sammelzubehör','Produktbild in Vorbereitung','Zur Deutung zurück'],
 nl: ['Yeongnyangi’s dagelijkse keuzes','Dit bericht maakt deel uit van Coupang Partners, waarvoor wij een commissie ontvangen.','De aanbevelingen worden voorbereid. Alleen gecontroleerde producten worden getoond.','Ontdek kleine keuzes voor het dagelijks leven. Controleer beschikbaarheid en levering bij Coupang.','Terug','Meer aanbevelingen','Bekijk op Coupang ↗','Bekijk verwante zoekresultaten ↗','Bekijk de actuele prijs op Coupang','Affiliate-advertentie','Er zijn nog geen gecontroleerde producten voor deze selectie.','Voorbeeld · Geen echt product of aankooplink','Aanbevelingen verbergen','Alles','Interesses','Budgetlimiet (KRW)','Kies een huisdier','Kat','Hond','Algemene verzamelbenodigdheden','Productafbeelding in voorbereiding','Terug naar de lezing'],
 ms: ['Pilihan harian Yeongnyangi','Siaran ini merupakan sebahagian daripada program Coupang Partners yang membolehkan kami menerima komisen.','Cadangan sedang disediakan. Hanya produk yang disemak akan dipaparkan.','Terokai pilihan kecil untuk kehidupan harian. Semak ketersediaan dan syarat penghantaran di Coupang.','Kembali','Lagi cadangan berkaitan','Lihat di Coupang ↗','Lihat hasil carian berkaitan ↗','Semak harga semasa di Coupang','Iklan afiliasi','Belum ada produk disemak yang sepadan.','Pratonton · Bukan produk atau pautan pembelian sebenar','Sembunyikan cadangan','Semua','Minat','Had bajet (KRW)','Pilih haiwan peliharaan','Kucing','Anjing','Bekalan koleksi umum','Imej produk sedang disediakan','Kembali ke bacaan'],
};
const categories = {
 ko: ['도서·기록','일상 식품·생활','반려동물','최애·수집'],
 en: ['Books & journals','Everyday living','Pets','Music & collecting'],
 ja: ['本・記録','食品・暮らし','ペット','音楽・コレクション'],
 'zh-CN': ['图书与记录','日常食品与生活','宠物','音乐与收藏'],
 'zh-TW': ['圖書與記錄','日常食品與生活','寵物','音樂與收藏'],
 vi: ['Sách và ghi chép','Đời sống thường ngày','Thú cưng','Âm nhạc và sưu tầm'],
 hi: ['किताबें और लेखन','दैनिक जीवन','पालतू जानवर','संगीत और संग्रह'],
 es: ['Libros y diarios','Vida cotidiana','Mascotas','Música y colecciones'],
 fr: ['Livres et carnets','Vie quotidienne','Animaux','Musique et collections'],
 de: ['Bücher und Notizen','Alltag','Haustiere','Musik und Sammeln'],
 nl: ['Boeken en dagboeken','Dagelijks leven','Huisdieren','Muziek en verzamelen'],
 ms: ['Buku dan jurnal','Kehidupan harian','Haiwan peliharaan','Muzik dan koleksi'],
};
const interests = {
 ko: ['독서','기록','계획','식사 준비','수분','휴식','대화','학습','가계부','놀이','털 관리','산책','수집','음악'],
 en: ['Reading','Journaling','Planning','Meal prep','Hydration','Rest','Conversation','Study','Budgeting','Play','Grooming','Walking','Collecting','Music'],
 ja: ['読書','記録','計画','食事の準備','水分補給','休息','会話','学習','家計簿','遊び','毛のケア','散歩','収集','音楽'],
 'zh-CN': ['阅读','记录','计划','备餐','饮水','休息','交流','学习','记账','玩耍','梳毛','散步','收藏','音乐'],
 'zh-TW': ['閱讀','記錄','計畫','備餐','飲水','休息','交流','學習','記帳','玩耍','梳毛','散步','收藏','音樂'],
 vi: ['Đọc sách','Ghi chép','Lập kế hoạch','Chuẩn bị bữa ăn','Uống nước','Nghỉ ngơi','Trò chuyện','Học tập','Ngân sách','Vui chơi','Chải lông','Đi dạo','Sưu tầm','Âm nhạc'],
 hi: ['पढ़ना','लिखना','योजना','भोजन तैयारी','पानी','आराम','बातचीत','पढ़ाई','बजट','खेल','बालों की देखभाल','सैर','संग्रह','संगीत'],
 es: ['Lectura','Diario','Planificación','Preparar comida','Hidratación','Descanso','Conversación','Estudio','Presupuesto','Juego','Cepillado','Paseos','Colección','Música'],
 fr: ['Lecture','Journal','Organisation','Préparation des repas','Hydratation','Repos','Conversation','Études','Budget','Jeu','Brossage','Promenade','Collection','Musique'],
 de: ['Lesen','Tagebuch','Planung','Essensvorbereitung','Trinken','Ruhe','Gespräche','Lernen','Haushaltsbuch','Spielen','Fellpflege','Spazieren','Sammeln','Musik'],
 nl: ['Lezen','Dagboek','Plannen','Maaltijden voorbereiden','Water drinken','Rust','Gesprekken','Studeren','Budget','Spelen','Vachtverzorging','Wandelen','Verzamelen','Muziek'],
 ms: ['Membaca','Menulis jurnal','Perancangan','Penyediaan makanan','Minum air','Rehat','Perbualan','Belajar','Belanjawan','Bermain','Dandanan','Berjalan','Mengumpul','Muzik'],
};
export function recommendationCopy(locale = 'ko') {
  const key = locale === 'zh' ? 'zh-CN' : locale;
  const row = rows[key] || rows.en;
  return { ...Object.fromEntries(keys.map((k, i) => [k, row[i]])), categories: categories[key] || categories.en, interests: interests[key] || interests.en, criteria: criteria[key] || criteria.en, exclude: exclusions[key] || exclusions.en };
}
export const RECOMMENDATION_COPY_LOCALES = Object.keys(rows);
const exclusions = { ko:'이 상품 제외',en:'Exclude this item',ja:'この商品を除外','zh-CN':'排除此商品','zh-TW':'排除此商品',vi:'Loại sản phẩm này',hi:'यह उत्पाद हटाएँ',es:'Excluir este producto',fr:'Exclure cet article',de:'Diesen Artikel ausschließen',nl:'Dit artikel uitsluiten',ms:'Kecualikan item ini' };
const criteria = {
 ko:'도서는 다루는 체계·판본·독자 수준을, 생활용품은 용도·규격·구성품을 비교해 보세요. 반려동물 용품은 종과 크기에 맞는지 먼저 확인하고, 앨범은 그룹·버전·랜덤 구성을 확인해 주세요. 구매는 운세의 결과를 바꾸거나 보장하지 않습니다.',
 en:'Compare a book’s subject, edition and reading level, and an everyday item’s purpose, size and contents. Check pet species and size first; for albums, check the group, version and random inclusions. Buying a product does not change or guarantee your fortune.',
 ja:'本は体系・版・読者レベル、生活用品は用途・サイズ・内容を比較しましょう。ペット用品は種類と体格、アルバムはグループ・バージョン・ランダム封入を確認してください。購入で運勢の結果が変わる、または保証されることはありません。',
 'zh-CN':'图书可比较主题体系、版本和阅读难度；生活用品可比较用途、尺寸和配件。宠物用品先确认物种及体型，专辑则确认组合、版本和随机配置。购买商品不会改变或保证运势结果。',
 'zh-TW':'圖書可比較主題體系、版本和閱讀難度；生活用品可比較用途、尺寸和配件。寵物用品先確認物種及體型，專輯則確認團體、版本和隨機配置。購買商品不會改變或保證運勢結果。',
 vi:'So sánh chủ đề, phiên bản và độ khó của sách; công dụng, kích thước và thành phần của đồ dùng. Kiểm tra loài và kích cỡ thú cưng; với album, kiểm tra nhóm, phiên bản và nội dung ngẫu nhiên. Mua hàng không thay đổi hay bảo đảm vận mệnh.',
 hi:'किताब का विषय, संस्करण और स्तर तथा वस्तु का उपयोग, आकार और सामग्री देखें। पालतू जानवर की प्रजाति और आकार जाँचें; एल्बम का समूह, संस्करण और यादृच्छिक सामग्री देखें। खरीदारी से भाग्य बदलने या परिणाम की गारंटी नहीं मिलती।',
 es:'Compara el tema, edición y nivel del libro, y el uso, tamaño y contenido de los artículos. Comprueba especie y tamaño de la mascota; en álbumes, grupo, versión e inclusiones aleatorias. Comprar no cambia ni garantiza tu fortuna.',
 fr:'Comparez le sujet, l’édition et le niveau du livre, puis l’usage, les dimensions et le contenu des objets. Vérifiez l’espèce et la taille de l’animal ; pour un album, le groupe, la version et les éléments aléatoires. Un achat ne change ni ne garantit votre destinée.',
 de:'Vergleiche Thema, Ausgabe und Niveau eines Buchs sowie Zweck, Größe und Lieferumfang von Alltagsartikeln. Prüfe Tierart und Größe; bei Alben Gruppe, Version und zufällige Beigaben. Ein Kauf verändert oder garantiert keine Vorhersage.',
 nl:'Vergelijk onderwerp, editie en leesniveau van boeken en doel, maat en inhoud van artikelen. Controleer diersoort en grootte; bij albums de groep, versie en willekeurige extra’s. Een aankoop verandert of garandeert je voorspelling niet.',
 ms:'Bandingkan subjek, edisi dan tahap buku serta tujuan, saiz dan kandungan barangan. Semak spesies dan saiz haiwan; untuk album, semak kumpulan, versi dan kandungan rawak. Pembelian tidak mengubah atau menjamin nasib.',
};
