// 초융합 운세(/fusion-fortune) 공유 컴포넌트(fusion-thread·FusionVisualization·FusionRecentList·
// FusionResultThread) 전용 로케일 카피. FusionFortuneClient.tsx 자체의 카피는 그 파일 안에 남아있고
// (순환 참조 방지를 위해 여기로 옮기지 않았다 — FusionFortuneClient 가 이 형제 파일들을 import 하므로
// 형제 파일이 거꾸로 FusionFortuneClient 를 import 하면 순환이 생긴다), 이 파일은 형제 파일들이
// 공유하는 문구만 담는다. destiny-compass/nakshatra 의 _lib/copy.ts 와 같은 패턴.

import { useEffect, useState } from "react";
import { getCurrentLoadingLocale, type LoadingLocale } from "@/constants/loadingMessages";

export type FusionSystemKeyLabel = "saju" | "ziwei" | "vedic" | "sukuyo" | "astrology" | "tarot";
export type FusionStanceKey = "agree" | "conditional" | "caution";
export type FusionStageKeyLabel = FusionSystemKeyLabel | "fusion";

export interface FusionSharedCopy {
  systemLabels: Record<FusionSystemKeyLabel, string>;
  stanceLabels: Record<FusionStanceKey, string>;
  stageMessages: Record<FusionStageKeyLabel, string>;
  stageDoneMessages: Record<FusionStageKeyLabel, string>;
  orbCoreAlt: string;
  vizSectionAriaLabel: string;
  radarHeading: string;
  radarCaption: string;
  radarAriaLabel: (items: string) => string;
  crossCheckHeading: string;
  crossCheckCaption: string;
  crossCheckGaugeAriaLabel: (label: string, aligned: number, divergent: number) => string;
  crossCheckGaugeCaption: string;
  alignedHeading: string;
  divergentHeading: string;
  timelineHeading: string;
  timelineCaption: string;
  timelineAriaLabel: (months: string) => string;
  recentSectionAriaLabel: string;
  recentHeading: string;
  recentSubtext: string;
  recentFallbackTitle: string;
  recentCurrentBadge: string;
  recentOpeningButton: string;
  recentOpenButton: string;
  analysisCompleteBadge: string;
  firstParagraphSpeaker: string;
  sixSystemsDirectionSpeaker: string;
  collapseButton: string;
  viewEvidenceButton: string;
  whenWhatSpeaker: string;
  viewActionButton: string;
  thingsToDoHeading: string;
  patternsToWatchHeading: string;
  finalVerdictEyebrow: string;
  doNowHeading: string;
  avoidNowHeading: string;
  /** Phase 2 — 결과 차례 레일·섹션 메타·2단계 대기(FusionResultRail·FusionResultThread). */
  railAriaLabel: string;
  statsHeading: string;
  tocHeading: string;
  totalCharsLabel: string;
  readingTimeLabel: string;
  readPositionLabel: string;
  /** 읽는 시간 계산용 분당 글자 수. 한국어·일본어·중국어는 글자 밀도가 높아 낮다. */
  readingCharsPerMinute: number;
  charsCount: (count: string) => string;
  minutesAbout: (minutes: number) => string;
  openingShortLabel: string;
  summaryShortLabel: string;
  integratedShortLabel: string;
  verdictShortLabel: string;
  closingShortLabel: string;
  stageTwoGroupLabel: string;
  stageTwoGeneratingLabel: string;
  stageTwoPendingBadge: string;
  stageTwoPendingMessage: string;
  pendingLabel: string;
  readLabel: string;
  jumpToVerdictButton: string;
  keySentenceLabel: string;
  /** Phase 3 — 모바일 하단 도킹 차례 바·바텀시트(FusionResultDock). */
  dockAriaLabel: string;
  openTocButton: string;
  closeSheetButton: string;
  progressRead: (percent: number) => string;
  remainingAbout: (minutes: number) => string;
}

const FUSION_SHARED_EN: FusionSharedCopy = {
  systemLabels: { saju: "Saju", ziwei: "Ziwei", vedic: "Vedic", sukuyo: "Sukuyo", astrology: "Astrology", tarot: "Tarot" },
  stanceLabels: { agree: "Same direction", conditional: "Conditional", caution: "Slow down" },
  stageMessages: {
    saju: "Reading your Saju season and temperament.",
    ziwei: "Connecting the themes in your Ziwei chart.",
    sukuyo: "Examining the rhythm of your Sukuyo relationships.",
    vedic: "Examining the timing flow in your Vedic chart.",
    astrology: "Organizing your astrology expression and choice patterns.",
    tarot: "Drawing a Tarot spread that fits your question.",
    fusion: "Fusing every flow into one reading.",
  },
  stageDoneMessages: {
    saju: "Finished reading your innate season and temperament.",
    ziwei: "Connected the thematic flow of your chart.",
    sukuyo: "Captured the rhythm your relationships move in.",
    vedic: "Organized the timing flow your dashas trace.",
    astrology: "Organized your expression and choice patterns.",
    tarot: "Laid out six cards that fit your question.",
    fusion: "Wove six flows into one reading.",
  },
  orbCoreAlt: "A fusion core where six fortune systems come together as one",
  vizSectionAriaLabel: "Fusion Fortune reading summary metrics",
  radarHeading: "Signal Strength by System",
  radarCaption: "How clearly each of the six systems signals on this question. Not a score judging you as a person.",
  radarAriaLabel: (items) => `Signal strength by system: ${items}`,
  crossCheckHeading: "Cross-Check",
  crossCheckCaption: "Signals multiple systems point to together become priorities; signals that diverge are left as situational options.",
  crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Cross-system agreement ${label}. ${aligned} overlapping signal(s), ${divergent} diverging signal(s).`,
  crossCheckGaugeCaption: "Agreement Across Systems",
  alignedHeading: "Overlapping Signals",
  divergentHeading: "Diverging Signals",
  timelineHeading: "The Next 12 Months' Timing Line",
  timelineCaption: "Not a line predicting events — how much force is worth applying each month, and what to try then.",
  timelineAriaLabel: (months) => `Flow over the next 12 months: ${months}`,
  recentSectionAriaLabel: "Past Fusion Fortune consultations",
  recentHeading: "Revisit Past Fusion Readings",
  recentSubtext: "This result is already paid for. Reopening it costs nothing extra.",
  recentFallbackTitle: "Fusion Fortune",
  recentCurrentBadge: "Viewing now",
  recentOpeningButton: "Opening…",
  recentOpenButton: "Open",
  analysisCompleteBadge: "Six-system analysis complete",
  firstParagraphSpeaker: "First, in one paragraph",
  sixSystemsDirectionSpeaker: "Where the six systems point",
  collapseButton: "Collapse",
  viewEvidenceButton: "View the evidence",
  whenWhatSpeaker: "When, and what",
  viewActionButton: "View the actions",
  thingsToDoHeading: "Worth trying in this flow",
  patternsToWatchHeading: "Recurring patterns to watch",
  finalVerdictEyebrow: "The Six Systems' Final Cross-Verdict",
  doNowHeading: "Do now",
  avoidNowHeading: "Avoid for now",
  railAriaLabel: "Reading outline",
  statsHeading: "This reading",
  tocHeading: "Contents",
  totalCharsLabel: "Total length",
  readingTimeLabel: "Reading time",
  readPositionLabel: "Progress",
  readingCharsPerMinute: 1000,
  charsCount: (count) => `${count} chars`,
  minutesAbout: (minutes) => `about ${minutes} min`,
  openingShortLabel: "Opening",
  summaryShortLabel: "One-paragraph summary",
  integratedShortLabel: "Integrated reading",
  verdictShortLabel: "Final cross-verdict",
  closingShortLabel: "Closing",
  stageTwoGroupLabel: "Stage 2",
  stageTwoGeneratingLabel: "Stage 2 · writing",
  stageTwoPendingBadge: "Stage 2 in progress",
  stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
  pendingLabel: "Pending",
  readLabel: "Read",
  jumpToVerdictButton: "Go to the final verdict",
  keySentenceLabel: "Key point",
  dockAriaLabel: "Reading navigation",
  openTocButton: "Contents",
  closeSheetButton: "Close contents",
  progressRead: (percent) => `${percent}% read`,
  remainingAbout: (minutes) => `about ${minutes} min left`,
};

const FUSION_SHARED_COPY: Partial<Record<LoadingLocale, FusionSharedCopy>> = {
  ko: {
    systemLabels: { saju: "사주", ziwei: "자미두수", vedic: "베다점", sukuyo: "숙요점", astrology: "점성술", tarot: "타로" },
    stanceLabels: { agree: "같은 방향", conditional: "조건부", caution: "속도 조절" },
    stageMessages: {
      saju: "사주의 계절과 기질을 읽고 있어요.",
      ziwei: "자미두수의 주제 흐름을 연결하고 있어요.",
      sukuyo: "숙요의 관계 리듬을 살피고 있어요.",
      vedic: "베다점의 시기 흐름을 살피고 있어요.",
      astrology: "점성술의 표현과 선택 패턴을 정리하고 있어요.",
      tarot: "질문에 맞는 타로 스프레드를 연결하고 있어요.",
      fusion: "모든 흐름을 하나의 읽기로 융합하고 있어요.",
    },
    stageDoneMessages: {
      saju: "타고난 계절과 기질을 다 읽었어요.",
      ziwei: "명반의 주제 흐름을 연결했어요.",
      sukuyo: "관계가 움직이는 리듬을 잡았어요.",
      vedic: "다샤가 그리는 시기 흐름을 정리했어요.",
      astrology: "표현과 선택의 패턴을 정리했어요.",
      tarot: "질문에 맞는 여섯 장을 펼쳤어요.",
      fusion: "여섯 흐름을 하나의 읽기로 묶었어요.",
    },
    orbCoreAlt: "여섯 운세 체계가 하나로 모인 초융합 코어",
    vizSectionAriaLabel: "초융합 리딩 요약 지표",
    radarHeading: "체계별 신호 강도",
    radarCaption: "여섯 체계가 이번 질문에 얼마나 뚜렷한 신호를 주는지입니다. 사람을 평가하는 점수가 아닙니다.",
    radarAriaLabel: (items) => `체계별 신호 강도: ${items}`,
    crossCheckHeading: "교차 검증",
    crossCheckCaption: "여러 체계가 함께 가리키는 신호는 우선순위로, 엇갈리는 신호는 상황별 선택지로 남깁니다.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `체계 간 합의 강도 ${label}. 겹치는 신호 ${aligned}가지, 엇갈리는 신호 ${divergent}가지.`,
    crossCheckGaugeCaption: "체계 간 합의",
    alignedHeading: "겹치는 신호",
    divergentHeading: "엇갈리는 신호",
    timelineHeading: "앞으로 12개월의 시기 라인",
    timelineCaption: "사건을 예고하는 선이 아니라, 각 달에 힘을 쓸 만한 정도와 그때 해볼 일입니다.",
    timelineAriaLabel: (months) => `앞으로 12개월 흐름: ${months}`,
    recentSectionAriaLabel: "지난 초융합 상담",
    recentHeading: "지난 초융합 다시 보기",
    recentSubtext: "이미 결제한 결과예요. 다시 여는 데 추가 결제는 없습니다.",
    recentFallbackTitle: "초융합 운세",
    recentCurrentBadge: "지금 보는 중",
    recentOpeningButton: "여는 중…",
    recentOpenButton: "열기",
    analysisCompleteBadge: "여섯 체계 분석 완료",
    firstParagraphSpeaker: "먼저, 한 문단으로",
    sixSystemsDirectionSpeaker: "여섯 체계가 가리키는 방향",
    collapseButton: "접기",
    viewEvidenceButton: "근거 보기",
    whenWhatSpeaker: "언제, 무엇을",
    viewActionButton: "행동 보기",
    thingsToDoHeading: "이번 흐름에서 해볼 일",
    patternsToWatchHeading: "주의해서 볼 반복 패턴",
    finalVerdictEyebrow: "여섯 체계의 최종 교차 판정",
    doNowHeading: "지금 할 일",
    avoidNowHeading: "지금은 피할 일",
    railAriaLabel: "결과 차례",
    statsHeading: "이 결과",
    tocHeading: "차례",
    totalCharsLabel: "총 글자",
    readingTimeLabel: "읽는 시간",
    readPositionLabel: "읽은 위치",
    readingCharsPerMinute: 500,
    charsCount: (count) => `${count}자`,
    minutesAbout: (minutes) => `약 ${minutes}분`,
    openingShortLabel: "여는 말",
    summaryShortLabel: "한 문단 요약",
    integratedShortLabel: "통합 해석",
    verdictShortLabel: "최종 교차 판정",
    closingShortLabel: "맺음말",
    stageTwoGroupLabel: "2단계",
    stageTwoGeneratingLabel: "2단계 · 생성 중",
    stageTwoPendingBadge: "2단계 생성 중",
    stageTwoPendingMessage: "여섯 체계의 목소리를 하나로 모으는 중입니다. 완료되면 요약·시기·최종 판정이 이 자리에 이어집니다. 화면을 닫아도 다시 열면 이어서 생성됩니다.",
    pendingLabel: "대기",
    readLabel: "읽음",
    jumpToVerdictButton: "최종 판정으로",
    keySentenceLabel: "핵심",
    dockAriaLabel: "결과 내비게이션",
    openTocButton: "차례",
    closeSheetButton: "차례 닫기",
    progressRead: (percent) => `${percent}% 읽음`,
    remainingAbout: (minutes) => `남은 약 ${minutes}분`,
  },
  ja: {
    systemLabels: { saju: "四柱推命", ziwei: "紫微斗数", vedic: "ヴェーダ占星術", sukuyo: "宿曜", astrology: "占星術", tarot: "タロット" },
    stanceLabels: { agree: "同じ方向", conditional: "条件付き", caution: "ペース調整" },
    stageMessages: {
      saju: "四柱推命の季節と気質を読んでいます。",
      ziwei: "紫微斗数の主題の流れをつないでいます。",
      sukuyo: "宿曜の関係のリズムを見ています。",
      vedic: "ヴェーダ占星術の時期の流れを見ています。",
      astrology: "占星術の表現と選択のパターンを整理しています。",
      tarot: "質問に合うタロットスプレッドをつないでいます。",
      fusion: "すべての流れを一つの読みに融合しています。",
    },
    stageDoneMessages: {
      saju: "生まれ持った季節と気質を読み終えました。",
      ziwei: "命盤の主題の流れをつなげました。",
      sukuyo: "関係が動くリズムをつかみました。",
      vedic: "ダシャが描く時期の流れを整理しました。",
      astrology: "表現と選択のパターンを整理しました。",
      tarot: "質問に合う六枚を並べました。",
      fusion: "六つの流れを一つの読みにまとめました。",
    },
    orbCoreAlt: "六つの運勢体系が一つに集まったフュージョンコア",
    vizSectionAriaLabel: "フュージョンリーディング要約指標",
    radarHeading: "体系別シグナル強度",
    radarCaption: "六つの体系がこの質問にどれほど明確なシグナルを出すかです。人を評価する点数ではありません。",
    radarAriaLabel: (items) => `体系別シグナル強度: ${items}`,
    crossCheckHeading: "クロスチェック",
    crossCheckCaption: "複数の体系が共に指し示すシグナルは優先順位に、食い違うシグナルは状況別の選択肢として残します。",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `体系間の合意度 ${label}。重なるシグナル${aligned}件、食い違うシグナル${divergent}件。`,
    crossCheckGaugeCaption: "体系間の合意",
    alignedHeading: "重なるシグナル",
    divergentHeading: "食い違うシグナル",
    timelineHeading: "今後12か月の時期ライン",
    timelineCaption: "出来事を予告する線ではなく、各月にどれくらい力を注ぐべきか、そのとき試すことです。",
    timelineAriaLabel: (months) => `今後12か月の流れ: ${months}`,
    recentSectionAriaLabel: "過去のフュージョン相談",
    recentHeading: "過去のフュージョンをもう一度見る",
    recentSubtext: "すでに決済済みの結果です。再度開くのに追加決済はありません。",
    recentFallbackTitle: "フュージョン運勢",
    recentCurrentBadge: "現在表示中",
    recentOpeningButton: "開いています…",
    recentOpenButton: "開く",
    analysisCompleteBadge: "六体系分析完了",
    firstParagraphSpeaker: "まず、一段落で",
    sixSystemsDirectionSpeaker: "六つの体系が指し示す方向",
    collapseButton: "閉じる",
    viewEvidenceButton: "根拠を見る",
    whenWhatSpeaker: "いつ、何を",
    viewActionButton: "行動を見る",
    thingsToDoHeading: "この流れで試すべきこと",
    patternsToWatchHeading: "注意して見るべき反復パターン",
    finalVerdictEyebrow: "六体系の最終クロス判定",
    doNowHeading: "今やるべきこと",
    avoidNowHeading: "今は避けるべきこと",
    railAriaLabel: "結果の目次",
    statsHeading: "この結果",
    tocHeading: "目次",
    totalCharsLabel: "総文字数",
    readingTimeLabel: "読了時間",
    readPositionLabel: "読んだ位置",
    readingCharsPerMinute: 500,
    charsCount: (count) => `${count}字`,
    minutesAbout: (minutes) => `約${minutes}分`,
    openingShortLabel: "はじめに",
    summaryShortLabel: "一段落の要約",
    integratedShortLabel: "統合解釈",
    verdictShortLabel: "最終クロス判定",
    closingShortLabel: "結び",
    stageTwoGroupLabel: "第2段階",
    stageTwoGeneratingLabel: "第2段階 · 生成中",
    stageTwoPendingBadge: "第2段階を生成中",
    stageTwoPendingMessage: "六つの体系の声をひとつにまとめています。完了すると要約・時期・最終判定がこの場所に続きます。画面を閉じても、再び開けば続きから生成されます。",
    pendingLabel: "待機",
    readLabel: "既読",
    jumpToVerdictButton: "最終判定へ",
    keySentenceLabel: "要点",
    dockAriaLabel: "結果ナビゲーション",
    openTocButton: "目次",
    closeSheetButton: "目次を閉じる",
    progressRead: (percent) => `${percent}% 読了`,
    remainingAbout: (minutes) => `残り約${minutes}分`,
  },
  "zh-CN": {
    systemLabels: { saju: "八字", ziwei: "紫微斗数", vedic: "吠陀占星", sukuyo: "宿曜", astrology: "占星术", tarot: "塔罗" },
    stanceLabels: { agree: "方向一致", conditional: "有条件", caution: "放慢节奏" },
    stageMessages: {
      saju: "正在解读八字的季节与气质。",
      ziwei: "正在梳理紫微斗数的主题脉络。",
      sukuyo: "正在查看宿曜的关系节奏。",
      vedic: "正在查看吠陀占星的时运脉络。",
      astrology: "正在整理占星术的表达与选择模式。",
      tarot: "正在连接适合你问题的塔罗牌阵。",
      fusion: "正在将所有脉络融合为一次解读。",
    },
    stageDoneMessages: {
      saju: "已解读完天生的季节与气质。",
      ziwei: "已梳理命盘的主题脉络。",
      sukuyo: "已把握关系变动的节奏。",
      vedic: "已整理大运描绘的时运脉络。",
      astrology: "已整理表达与选择的模式。",
      tarot: "已展开与你问题相符的六张牌。",
      fusion: "已将六股脉络编织为一次解读。",
    },
    orbCoreAlt: "六大运势体系汇聚为一体的融合核心",
    vizSectionAriaLabel: "融合解读摘要指标",
    radarHeading: "各体系信号强度",
    radarCaption: "六大体系在这个问题上给出信号的清晰程度。这不是评判你个人的分数。",
    radarAriaLabel: (items) => `各体系信号强度：${items}`,
    crossCheckHeading: "交叉验证",
    crossCheckCaption: "多个体系共同指向的信号将成为优先事项，出现分歧的信号则作为情境化选项保留。",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `体系间共识强度${label}。重叠信号${aligned}项，分歧信号${divergent}项。`,
    crossCheckGaugeCaption: "体系间共识",
    alignedHeading: "重叠信号",
    divergentHeading: "分歧信号",
    timelineHeading: "未来12个月的时运曲线",
    timelineCaption: "这不是预告事件的曲线，而是每月值得投入的力度与当时可尝试的事。",
    timelineAriaLabel: (months) => `未来12个月的走势：${months}`,
    recentSectionAriaLabel: "以往的融合运势咨询",
    recentHeading: "重新查看以往的融合解读",
    recentSubtext: "这是已付款的结果，重新打开无需再次付款。",
    recentFallbackTitle: "融合运势",
    recentCurrentBadge: "正在查看",
    recentOpeningButton: "正在打开…",
    recentOpenButton: "打开",
    analysisCompleteBadge: "六体系分析完成",
    firstParagraphSpeaker: "首先，用一段话概括",
    sixSystemsDirectionSpeaker: "六大体系指向的方向",
    collapseButton: "收起",
    viewEvidenceButton: "查看依据",
    whenWhatSpeaker: "何时，做什么",
    viewActionButton: "查看行动",
    thingsToDoHeading: "在此脉络中值得尝试的事",
    patternsToWatchHeading: "需留意的重复模式",
    finalVerdictEyebrow: "六大体系的最终交叉判定",
    doNowHeading: "现在该做的事",
    avoidNowHeading: "现在该避免的事",
    railAriaLabel: "结果目录",
    statsHeading: "本次结果",
    tocHeading: "目录",
    totalCharsLabel: "总字数",
    readingTimeLabel: "阅读时间",
    readPositionLabel: "阅读进度",
    readingCharsPerMinute: 450,
    charsCount: (count) => `${count}字`,
    minutesAbout: (minutes) => `约${minutes}分钟`,
    openingShortLabel: "开场",
    summaryShortLabel: "一段话摘要",
    integratedShortLabel: "综合解读",
    verdictShortLabel: "最终交叉判定",
    closingShortLabel: "结语",
    stageTwoGroupLabel: "第二阶段",
    stageTwoGeneratingLabel: "第二阶段 · 生成中",
    stageTwoPendingBadge: "第二阶段生成中",
    stageTwoPendingMessage: "正在把六大体系的声音汇成一个答案。完成后，摘要、时机与最终判定会接续在这里。关闭页面也没关系，重新打开会继续生成。",
    pendingLabel: "等待",
    readLabel: "已读",
    jumpToVerdictButton: "前往最终判定",
    keySentenceLabel: "要点",
    dockAriaLabel: "结果导航",
    openTocButton: "目录",
    closeSheetButton: "关闭目录",
    progressRead: (percent) => `已读 ${percent}%`,
    remainingAbout: (minutes) => `剩余约 ${minutes} 分钟`,
  },
  "zh-TW": {
    systemLabels: { saju: "八字", ziwei: "紫微斗數", vedic: "吠陀占星", sukuyo: "宿曜", astrology: "占星術", tarot: "塔羅" },
    stanceLabels: { agree: "方向一致", conditional: "有條件", caution: "放慢節奏" },
    stageMessages: {
      saju: "正在解讀八字的季節與氣質。",
      ziwei: "正在梳理紫微斗數的主題脈絡。",
      sukuyo: "正在查看宿曜的關係節奏。",
      vedic: "正在查看吠陀占星的時運脈絡。",
      astrology: "正在整理占星術的表達與選擇模式。",
      tarot: "正在連接適合你問題的塔羅牌陣。",
      fusion: "正在將所有脈絡融合為一次解讀。",
    },
    stageDoneMessages: {
      saju: "已解讀完天生的季節與氣質。",
      ziwei: "已梳理命盤的主題脈絡。",
      sukuyo: "已掌握關係變動的節奏。",
      vedic: "已整理大運描繪的時運脈絡。",
      astrology: "已整理表達與選擇的模式。",
      tarot: "已展開與你問題相符的六張牌。",
      fusion: "已將六股脈絡編織為一次解讀。",
    },
    orbCoreAlt: "六大運勢體系匯聚為一體的融合核心",
    vizSectionAriaLabel: "融合解讀摘要指標",
    radarHeading: "各體系信號強度",
    radarCaption: "六大體系在這個問題上給出信號的清晰程度。這不是評判你個人的分數。",
    radarAriaLabel: (items) => `各體系信號強度：${items}`,
    crossCheckHeading: "交叉驗證",
    crossCheckCaption: "多個體系共同指向的信號將成為優先事項，出現分歧的信號則作為情境化選項保留。",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `體系間共識強度${label}。重疊信號${aligned}項，分歧信號${divergent}項。`,
    crossCheckGaugeCaption: "體系間共識",
    alignedHeading: "重疊信號",
    divergentHeading: "分歧信號",
    timelineHeading: "未來12個月的時運曲線",
    timelineCaption: "這不是預告事件的曲線，而是每月值得投入的力度與當時可嘗試的事。",
    timelineAriaLabel: (months) => `未來12個月的走勢：${months}`,
    recentSectionAriaLabel: "以往的融合運勢諮詢",
    recentHeading: "重新查看以往的融合解讀",
    recentSubtext: "這是已付款的結果，重新開啟無需再次付款。",
    recentFallbackTitle: "融合運勢",
    recentCurrentBadge: "正在查看",
    recentOpeningButton: "正在開啟…",
    recentOpenButton: "開啟",
    analysisCompleteBadge: "六體系分析完成",
    firstParagraphSpeaker: "首先，用一段話概括",
    sixSystemsDirectionSpeaker: "六大體系指向的方向",
    collapseButton: "收起",
    viewEvidenceButton: "查看依據",
    whenWhatSpeaker: "何時，做什麼",
    viewActionButton: "查看行動",
    thingsToDoHeading: "在此脈絡中值得嘗試的事",
    patternsToWatchHeading: "需留意的重複模式",
    finalVerdictEyebrow: "六大體系的最終交叉判定",
    doNowHeading: "現在該做的事",
    avoidNowHeading: "現在該避免的事",
    railAriaLabel: "結果目錄",
    statsHeading: "本次結果",
    tocHeading: "目錄",
    totalCharsLabel: "總字數",
    readingTimeLabel: "閱讀時間",
    readPositionLabel: "閱讀進度",
    readingCharsPerMinute: 450,
    charsCount: (count) => `${count}字`,
    minutesAbout: (minutes) => `約${minutes}分鐘`,
    openingShortLabel: "開場",
    summaryShortLabel: "一段話摘要",
    integratedShortLabel: "綜合解讀",
    verdictShortLabel: "最終交叉判定",
    closingShortLabel: "結語",
    stageTwoGroupLabel: "第二階段",
    stageTwoGeneratingLabel: "第二階段 · 生成中",
    stageTwoPendingBadge: "第二階段生成中",
    stageTwoPendingMessage: "正在把六大體系的聲音匯成一個答案。完成後，摘要、時機與最終判定會接續在這裡。關閉頁面也沒關係，重新開啟會繼續生成。",
    pendingLabel: "等待",
    readLabel: "已讀",
    jumpToVerdictButton: "前往最終判定",
    keySentenceLabel: "要點",
    dockAriaLabel: "結果導覽",
    openTocButton: "目錄",
    closeSheetButton: "關閉目錄",
    progressRead: (percent) => `已讀 ${percent}%`,
    remainingAbout: (minutes) => `剩餘約 ${minutes} 分鐘`,
  },
  vi: {
    systemLabels: { saju: "Saju", ziwei: "Tử Vi", vedic: "Chiêm tinh Vệ Đà", sukuyo: "Sukuyo", astrology: "Chiêm tinh", tarot: "Tarot" },
    stanceLabels: { agree: "Cùng hướng", conditional: "Có điều kiện", caution: "Nên chậm lại" },
    stageMessages: {
      saju: "Đang đọc mùa và khí chất Saju của bạn.",
      ziwei: "Đang kết nối dòng chủ đề trong lá số Tử Vi.",
      sukuyo: "Đang xem xét nhịp điệu quan hệ Sukuyo.",
      vedic: "Đang xem xét dòng chảy thời vận Vệ Đà.",
      astrology: "Đang sắp xếp cách thể hiện và mô hình lựa chọn chiêm tinh.",
      tarot: "Đang kết nối trải bài Tarot phù hợp với câu hỏi.",
      fusion: "Đang hợp nhất mọi dòng chảy thành một bài đọc.",
    },
    stageDoneMessages: {
      saju: "Đã đọc xong mùa và khí chất bẩm sinh.",
      ziwei: "Đã kết nối dòng chủ đề của lá số.",
      sukuyo: "Đã nắm được nhịp điệu chuyển động của mối quan hệ.",
      vedic: "Đã sắp xếp dòng chảy thời vận mà đại vận vẽ ra.",
      astrology: "Đã sắp xếp mô hình thể hiện và lựa chọn.",
      tarot: "Đã trải sáu lá phù hợp với câu hỏi.",
      fusion: "Đã dệt sáu dòng chảy thành một bài đọc.",
    },
    orbCoreAlt: "Lõi hợp nhất nơi sáu hệ thống vận mệnh quy tụ làm một",
    vizSectionAriaLabel: "Chỉ số tóm tắt bài đọc Vận Mệnh Hợp Nhất",
    radarHeading: "Cường Độ Tín Hiệu Theo Hệ Thống",
    radarCaption: "Mức độ rõ ràng mà mỗi trong sáu hệ thống báo hiệu về câu hỏi này. Không phải điểm số đánh giá con người bạn.",
    radarAriaLabel: (items) => `Cường độ tín hiệu theo hệ thống: ${items}`,
    crossCheckHeading: "Đối Chiếu Chéo",
    crossCheckCaption: "Tín hiệu mà nhiều hệ thống cùng chỉ ra sẽ trở thành ưu tiên; tín hiệu khác biệt được để lại như lựa chọn tùy tình huống.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Mức đồng thuận giữa các hệ thống ${label}. ${aligned} tín hiệu trùng khớp, ${divergent} tín hiệu khác biệt.`,
    crossCheckGaugeCaption: "Đồng Thuận Giữa Các Hệ Thống",
    alignedHeading: "Tín Hiệu Trùng Khớp",
    divergentHeading: "Tín Hiệu Khác Biệt",
    timelineHeading: "Đường Thời Vận 12 Tháng Tới",
    timelineCaption: "Không phải đường báo trước sự kiện — mà là mức độ nên dồn sức mỗi tháng và điều nên thử vào lúc đó.",
    timelineAriaLabel: (months) => `Dòng chảy trong 12 tháng tới: ${months}`,
    recentSectionAriaLabel: "Các buổi tư vấn Vận Mệnh Hợp Nhất trước đây",
    recentHeading: "Xem Lại Các Bài Đọc Hợp Nhất Trước Đây",
    recentSubtext: "Kết quả này đã được thanh toán. Mở lại không tốn thêm phí.",
    recentFallbackTitle: "Vận Mệnh Hợp Nhất",
    recentCurrentBadge: "Đang xem",
    recentOpeningButton: "Đang mở…",
    recentOpenButton: "Mở",
    analysisCompleteBadge: "Đã hoàn tất phân tích sáu hệ thống",
    firstParagraphSpeaker: "Trước tiên, trong một đoạn",
    sixSystemsDirectionSpeaker: "Hướng mà sáu hệ thống chỉ ra",
    collapseButton: "Thu gọn",
    viewEvidenceButton: "Xem căn cứ",
    whenWhatSpeaker: "Khi nào, và điều gì",
    viewActionButton: "Xem hành động",
    thingsToDoHeading: "Đáng thử trong dòng chảy này",
    patternsToWatchHeading: "Các mô hình lặp lại cần lưu ý",
    finalVerdictEyebrow: "Phán Quyết Chéo Cuối Cùng Của Sáu Hệ Thống",
    doNowHeading: "Nên làm ngay",
    avoidNowHeading: "Nên tránh lúc này",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
  hi: {
    systemLabels: { saju: "साजू", ziwei: "ज़ीवेई", vedic: "वैदिक ज्योतिष", sukuyo: "सुक्यो", astrology: "ज्योतिष", tarot: "टैरो" },
    stanceLabels: { agree: "समान दिशा", conditional: "सशर्त", caution: "धीमी गति" },
    stageMessages: {
      saju: "आपके साजू के मौसम और स्वभाव को पढ़ा जा रहा है।",
      ziwei: "ज़ीवेई चार्ट के विषय-प्रवाह को जोड़ा जा रहा है।",
      sukuyo: "सुक्यो संबंध लय की जांच की जा रही है।",
      vedic: "वैदिक चार्ट के समय-प्रवाह की जांच की जा रही है।",
      astrology: "ज्योतिष अभिव्यक्ति और चयन पैटर्न को व्यवस्थित किया जा रहा है।",
      tarot: "आपके प्रश्न के अनुरूप टैरो स्प्रेड जोड़ा जा रहा है।",
      fusion: "सभी प्रवाहों को एक रीडिंग में फ्यूज़ किया जा रहा है।",
    },
    stageDoneMessages: {
      saju: "जन्मजात मौसम और स्वभाव पढ़ना पूरा हुआ।",
      ziwei: "चार्ट का विषय-प्रवाह जोड़ा गया।",
      sukuyo: "संबंधों की गति की लय पकड़ी गई।",
      vedic: "दशा द्वारा दर्शाया गया समय-प्रवाह व्यवस्थित किया गया।",
      astrology: "अभिव्यक्ति और चयन के पैटर्न व्यवस्थित किए गए।",
      tarot: "प्रश्न के अनुरूप छह पत्ते बिछाए गए।",
      fusion: "छह प्रवाहों को एक रीडिंग में पिरोया गया।",
    },
    orbCoreAlt: "छह भाग्य प्रणालियाँ एक साथ मिलकर बना फ्यूज़न कोर",
    vizSectionAriaLabel: "फ्यूज़न भाग्य रीडिंग सारांश मेट्रिक्स",
    radarHeading: "प्रणाली अनुसार संकेत शक्ति",
    radarCaption: "छह प्रणालियों में से प्रत्येक इस प्रश्न पर कितना स्पष्ट संकेत देती है। यह आपको व्यक्ति के रूप में आंकने वाला स्कोर नहीं है।",
    radarAriaLabel: (items) => `प्रणाली अनुसार संकेत शक्ति: ${items}`,
    crossCheckHeading: "क्रॉस-चेक",
    crossCheckCaption: "जिन संकेतों की ओर कई प्रणालियाँ एक साथ इशारा करती हैं वे प्राथमिकता बनते हैं; भिन्न संकेतों को स्थिति-आधारित विकल्पों के रूप में छोड़ दिया जाता है।",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `प्रणालियों के बीच सहमति ${label}। ओवरलैप करने वाले संकेत ${aligned}, भिन्न संकेत ${divergent}।`,
    crossCheckGaugeCaption: "प्रणालियों के बीच सहमति",
    alignedHeading: "ओवरलैप करने वाले संकेत",
    divergentHeading: "भिन्न संकेत",
    timelineHeading: "आगामी 12 महीनों की समय-रेखा",
    timelineCaption: "यह घटनाओं की भविष्यवाणी करने वाली रेखा नहीं है — हर महीने कितना ज़ोर लगाना उचित है और उस समय क्या आज़माना है।",
    timelineAriaLabel: (months) => `आगामी 12 महीनों का प्रवाह: ${months}`,
    recentSectionAriaLabel: "पिछले फ्यूज़न भाग्य परामर्श",
    recentHeading: "पिछली फ्यूज़न रीडिंग फिर से देखें",
    recentSubtext: "यह परिणाम पहले ही भुगतान किया जा चुका है। इसे फिर से खोलने पर कोई अतिरिक्त शुल्क नहीं है।",
    recentFallbackTitle: "फ्यूज़न भाग्य",
    recentCurrentBadge: "अभी देख रहे हैं",
    recentOpeningButton: "खोला जा रहा है…",
    recentOpenButton: "खोलें",
    analysisCompleteBadge: "छह-प्रणाली विश्लेषण पूर्ण",
    firstParagraphSpeaker: "पहले, एक पैराग्राफ में",
    sixSystemsDirectionSpeaker: "छह प्रणालियाँ जिस दिशा की ओर इशारा करती हैं",
    collapseButton: "संक्षिप्त करें",
    viewEvidenceButton: "आधार देखें",
    whenWhatSpeaker: "कब, और क्या",
    viewActionButton: "कार्रवाई देखें",
    thingsToDoHeading: "इस प्रवाह में आज़माने योग्य बातें",
    patternsToWatchHeading: "ध्यान देने योग्य दोहराए जाने वाले पैटर्न",
    finalVerdictEyebrow: "छह प्रणालियों का अंतिम क्रॉस-निर्णय",
    doNowHeading: "अभी करें",
    avoidNowHeading: "अभी से बचें",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
  es: {
    systemLabels: { saju: "Saju", ziwei: "Ziwei", vedic: "Astrología Védica", sukuyo: "Sukuyo", astrology: "Astrología", tarot: "Tarot" },
    stanceLabels: { agree: "Misma dirección", conditional: "Condicional", caution: "Reducir el ritmo" },
    stageMessages: {
      saju: "Leyendo tu estación y temperamento Saju.",
      ziwei: "Conectando los temas de tu carta Ziwei.",
      sukuyo: "Examinando el ritmo de tus relaciones Sukuyo.",
      vedic: "Examinando el flujo temporal de tu carta védica.",
      astrology: "Organizando tus patrones de expresión y elección astrológicos.",
      tarot: "Trazando una tirada de Tarot acorde a tu pregunta.",
      fusion: "Fusionando todos los flujos en una sola lectura.",
    },
    stageDoneMessages: {
      saju: "Terminamos de leer tu estación y temperamento innatos.",
      ziwei: "Conectamos el flujo temático de tu carta.",
      sukuyo: "Capturamos el ritmo en que se mueven tus relaciones.",
      vedic: "Organizamos el flujo temporal que trazan tus dashas.",
      astrology: "Organizamos tus patrones de expresión y elección.",
      tarot: "Dispusimos seis cartas acordes a tu pregunta.",
      fusion: "Entrelazamos seis flujos en una sola lectura.",
    },
    orbCoreAlt: "Un núcleo de fusión donde seis sistemas de fortuna se unen en uno",
    vizSectionAriaLabel: "Métricas resumen de la lectura de Fortuna de Fusión",
    radarHeading: "Intensidad de Señal por Sistema",
    radarCaption: "Qué tan claramente señala cada uno de los seis sistemas sobre esta pregunta. No es una puntuación que te juzgue como persona.",
    radarAriaLabel: (items) => `Intensidad de señal por sistema: ${items}`,
    crossCheckHeading: "Verificación Cruzada",
    crossCheckCaption: "Las señales que varios sistemas señalan juntos se convierten en prioridades; las señales que divergen se dejan como opciones según la situación.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Acuerdo entre sistemas ${label}. ${aligned} señal(es) superpuesta(s), ${divergent} señal(es) divergente(s).`,
    crossCheckGaugeCaption: "Acuerdo Entre Sistemas",
    alignedHeading: "Señales Superpuestas",
    divergentHeading: "Señales Divergentes",
    timelineHeading: "La Línea de Tiempo de los Próximos 12 Meses",
    timelineCaption: "No es una línea que predice eventos — es cuánta fuerza vale la pena aplicar cada mes y qué probar entonces.",
    timelineAriaLabel: (months) => `Flujo de los próximos 12 meses: ${months}`,
    recentSectionAriaLabel: "Consultas de Fortuna de Fusión anteriores",
    recentHeading: "Revisar Lecturas de Fusión Anteriores",
    recentSubtext: "Este resultado ya está pagado. Volver a abrirlo no cuesta nada extra.",
    recentFallbackTitle: "Fortuna de Fusión",
    recentCurrentBadge: "Viendo ahora",
    recentOpeningButton: "Abriendo…",
    recentOpenButton: "Abrir",
    analysisCompleteBadge: "Análisis de seis sistemas completo",
    firstParagraphSpeaker: "Primero, en un párrafo",
    sixSystemsDirectionSpeaker: "Hacia dónde apuntan los seis sistemas",
    collapseButton: "Colapsar",
    viewEvidenceButton: "Ver la evidencia",
    whenWhatSpeaker: "Cuándo, y qué",
    viewActionButton: "Ver las acciones",
    thingsToDoHeading: "Vale la pena intentar en este flujo",
    patternsToWatchHeading: "Patrones recurrentes a observar",
    finalVerdictEyebrow: "El Veredicto Cruzado Final de los Seis Sistemas",
    doNowHeading: "Hacer ahora",
    avoidNowHeading: "Evitar por ahora",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
  fr: {
    systemLabels: { saju: "Saju", ziwei: "Ziwei", vedic: "Astrologie Védique", sukuyo: "Sukuyo", astrology: "Astrologie", tarot: "Tarot" },
    stanceLabels: { agree: "Même direction", conditional: "Conditionnel", caution: "Ralentir" },
    stageMessages: {
      saju: "Lecture de votre saison et tempérament Saju.",
      ziwei: "Connexion des thèmes de votre carte Ziwei.",
      sukuyo: "Examen du rythme de vos relations Sukuyo.",
      vedic: "Examen du flux temporel de votre carte védique.",
      astrology: "Organisation de vos modes d'expression et de choix astrologiques.",
      tarot: "Connexion d'un tirage de Tarot adapté à votre question.",
      fusion: "Fusion de tous les flux en une seule lecture.",
    },
    stageDoneMessages: {
      saju: "Lecture de votre saison et tempérament innés terminée.",
      ziwei: "Flux thématique de votre carte connecté.",
      sukuyo: "Rythme du mouvement de vos relations saisi.",
      vedic: "Flux temporel tracé par vos dashas organisé.",
      astrology: "Modes d'expression et de choix organisés.",
      tarot: "Six cartes adaptées à votre question disposées.",
      fusion: "Six flux tissés en une seule lecture.",
    },
    orbCoreAlt: "Un noyau de fusion où six systèmes de fortune se rejoignent en un seul",
    vizSectionAriaLabel: "Indicateurs récapitulatifs de la lecture Fortune Fusion",
    radarHeading: "Intensité du Signal par Système",
    radarCaption: "À quel point chacun des six systèmes signale clairement sur cette question. Ce n'est pas un score qui vous juge en tant que personne.",
    radarAriaLabel: (items) => `Intensité du signal par système : ${items}`,
    crossCheckHeading: "Vérification Croisée",
    crossCheckCaption: "Les signaux vers lesquels plusieurs systèmes pointent ensemble deviennent des priorités ; les signaux divergents restent des options selon la situation.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Accord entre systèmes ${label}. ${aligned} signal(aux) concordant(s), ${divergent} signal(aux) divergent(s).`,
    crossCheckGaugeCaption: "Accord Entre Systèmes",
    alignedHeading: "Signaux Concordants",
    divergentHeading: "Signaux Divergents",
    timelineHeading: "La Ligne Temporelle des 12 Prochains Mois",
    timelineCaption: "Pas une ligne prédisant des événements — plutôt l'intensité à consacrer chaque mois et ce qu'il vaut la peine d'essayer alors.",
    timelineAriaLabel: (months) => `Flux des 12 prochains mois : ${months}`,
    recentSectionAriaLabel: "Consultations Fortune Fusion précédentes",
    recentHeading: "Revoir les Lectures de Fusion Précédentes",
    recentSubtext: "Ce résultat est déjà payé. Le rouvrir ne coûte rien de plus.",
    recentFallbackTitle: "Fortune Fusion",
    recentCurrentBadge: "En cours de consultation",
    recentOpeningButton: "Ouverture…",
    recentOpenButton: "Ouvrir",
    analysisCompleteBadge: "Analyse des six systèmes terminée",
    firstParagraphSpeaker: "D'abord, en un paragraphe",
    sixSystemsDirectionSpeaker: "Où pointent les six systèmes",
    collapseButton: "Réduire",
    viewEvidenceButton: "Voir les preuves",
    whenWhatSpeaker: "Quand, et quoi",
    viewActionButton: "Voir les actions",
    thingsToDoHeading: "À essayer dans ce flux",
    patternsToWatchHeading: "Schémas récurrents à surveiller",
    finalVerdictEyebrow: "Le Verdict Croisé Final des Six Systèmes",
    doNowHeading: "À faire maintenant",
    avoidNowHeading: "À éviter pour l'instant",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
  de: {
    systemLabels: { saju: "Saju", ziwei: "Ziwei", vedic: "Vedische Astrologie", sukuyo: "Sukuyo", astrology: "Astrologie", tarot: "Tarot" },
    stanceLabels: { agree: "Gleiche Richtung", conditional: "Bedingt", caution: "Tempo drosseln" },
    stageMessages: {
      saju: "Liest deine Saju-Jahreszeit und dein Temperament.",
      ziwei: "Verknüpft die Themen in deinem Ziwei-Chart.",
      sukuyo: "Untersucht den Rhythmus deiner Sukuyo-Beziehungen.",
      vedic: "Untersucht den zeitlichen Verlauf in deinem vedischen Chart.",
      astrology: "Ordnet deine astrologischen Ausdrucks- und Entscheidungsmuster.",
      tarot: "Verbindet ein Tarot-Legesystem, das zu deiner Frage passt.",
      fusion: "Verschmilzt alle Verläufe zu einer Deutung.",
    },
    stageDoneMessages: {
      saju: "Deine angeborene Jahreszeit und dein Temperament fertig gelesen.",
      ziwei: "Den thematischen Verlauf deines Charts verknüpft.",
      sukuyo: "Den Rhythmus erfasst, in dem sich deine Beziehungen bewegen.",
      vedic: "Den zeitlichen Verlauf deiner Dashas geordnet.",
      astrology: "Ausdrucks- und Entscheidungsmuster geordnet.",
      tarot: "Sechs zu deiner Frage passende Karten gelegt.",
      fusion: "Sechs Verläufe zu einer Deutung verwoben.",
    },
    orbCoreAlt: "Ein Fusionskern, in dem sechs Schicksalssysteme zu einem verschmelzen",
    vizSectionAriaLabel: "Zusammenfassende Kennzahlen der Fusion-Schicksal-Deutung",
    radarHeading: "Signalstärke nach System",
    radarCaption: "Wie deutlich jedes der sechs Systeme zu dieser Frage signalisiert. Kein Wert, der dich als Person bewertet.",
    radarAriaLabel: (items) => `Signalstärke nach System: ${items}`,
    crossCheckHeading: "Kreuzabgleich",
    crossCheckCaption: "Signale, auf die mehrere Systeme gemeinsam hinweisen, werden zu Prioritäten; abweichende Signale bleiben als situative Optionen bestehen.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Übereinstimmung zwischen Systemen ${label}. ${aligned} übereinstimmende(s) Signal(e), ${divergent} abweichende(s) Signal(e).`,
    crossCheckGaugeCaption: "Übereinstimmung Zwischen Systemen",
    alignedHeading: "Übereinstimmende Signale",
    divergentHeading: "Abweichende Signale",
    timelineHeading: "Die Zeitlinie der Nächsten 12 Monate",
    timelineCaption: "Keine Linie, die Ereignisse vorhersagt — sondern wie viel Kraft es sich jeden Monat zu investieren lohnt und was dann zu versuchen ist.",
    timelineAriaLabel: (months) => `Verlauf der nächsten 12 Monate: ${months}`,
    recentSectionAriaLabel: "Frühere Fusion-Schicksal-Beratungen",
    recentHeading: "Frühere Fusion-Deutungen Erneut Ansehen",
    recentSubtext: "Dieses Ergebnis ist bereits bezahlt. Es erneut zu öffnen kostet nichts zusätzlich.",
    recentFallbackTitle: "Fusion-Schicksal",
    recentCurrentBadge: "Wird gerade angezeigt",
    recentOpeningButton: "Wird geöffnet…",
    recentOpenButton: "Öffnen",
    analysisCompleteBadge: "Sechs-Systeme-Analyse abgeschlossen",
    firstParagraphSpeaker: "Zunächst, in einem Absatz",
    sixSystemsDirectionSpeaker: "Wohin die sechs Systeme weisen",
    collapseButton: "Einklappen",
    viewEvidenceButton: "Beleg ansehen",
    whenWhatSpeaker: "Wann, und was",
    viewActionButton: "Maßnahmen ansehen",
    thingsToDoHeading: "In diesem Verlauf lohnt sich zu versuchen",
    patternsToWatchHeading: "Wiederkehrende Muster, auf die zu achten ist",
    finalVerdictEyebrow: "Das Endgültige Kreuzurteil der Sechs Systeme",
    doNowHeading: "Jetzt tun",
    avoidNowHeading: "Vorerst vermeiden",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
  nl: {
    systemLabels: { saju: "Saju", ziwei: "Ziwei", vedic: "Vedische Astrologie", sukuyo: "Sukuyo", astrology: "Astrologie", tarot: "Tarot" },
    stanceLabels: { agree: "Zelfde richting", conditional: "Voorwaardelijk", caution: "Vaart minderen" },
    stageMessages: {
      saju: "Leest je Saju-seizoen en temperament.",
      ziwei: "Verbindt de thema's in je Ziwei-kaart.",
      sukuyo: "Onderzoekt het ritme van je Sukuyo-relaties.",
      vedic: "Onderzoekt de timing-stroom in je Vedische kaart.",
      astrology: "Ordent je astrologische expressie- en keuzepatronen.",
      tarot: "Verbindt een Tarot-legging die bij je vraag past.",
      fusion: "Versmelt alle stromen tot één lezing.",
    },
    stageDoneMessages: {
      saju: "Je aangeboren seizoen en temperament klaar gelezen.",
      ziwei: "De thematische stroom van je kaart verbonden.",
      sukuyo: "Het ritme waarin je relaties bewegen vastgelegd.",
      vedic: "De timing-stroom die je dasha's tekenen geordend.",
      astrology: "Expressie- en keuzepatronen geordend.",
      tarot: "Zes kaarten gelegd die bij je vraag passen.",
      fusion: "Zes stromen verweven tot één lezing.",
    },
    orbCoreAlt: "Een fusiekern waar zes lotssystemen samenkomen als één",
    vizSectionAriaLabel: "Samenvattende statistieken van de Fusie Fortuin-lezing",
    radarHeading: "Signaalsterkte per Systeem",
    radarCaption: "Hoe duidelijk elk van de zes systemen signaleert over deze vraag. Geen score die jou als persoon beoordeelt.",
    radarAriaLabel: (items) => `Signaalsterkte per systeem: ${items}`,
    crossCheckHeading: "Kruiscontrole",
    crossCheckCaption: "Signalen waar meerdere systemen samen naar wijzen, worden prioriteiten; afwijkende signalen blijven situationele opties.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Overeenstemming tussen systemen ${label}. ${aligned} overlappende signa(a)l(en), ${divergent} afwijkende signa(a)l(en).`,
    crossCheckGaugeCaption: "Overeenstemming Tussen Systemen",
    alignedHeading: "Overlappende Signalen",
    divergentHeading: "Afwijkende Signalen",
    timelineHeading: "De Tijdlijn van de Komende 12 Maanden",
    timelineCaption: "Geen lijn die gebeurtenissen voorspelt — maar hoeveel kracht het waard is elke maand te investeren en wat dan te proberen.",
    timelineAriaLabel: (months) => `Verloop van de komende 12 maanden: ${months}`,
    recentSectionAriaLabel: "Eerdere Fusie Fortuin-consulten",
    recentHeading: "Eerdere Fusielezingen Opnieuw Bekijken",
    recentSubtext: "Dit resultaat is al betaald. Opnieuw openen kost niets extra.",
    recentFallbackTitle: "Fusie Fortuin",
    recentCurrentBadge: "Wordt nu bekeken",
    recentOpeningButton: "Wordt geopend…",
    recentOpenButton: "Openen",
    analysisCompleteBadge: "Analyse van zes systemen voltooid",
    firstParagraphSpeaker: "Eerst, in één alinea",
    sixSystemsDirectionSpeaker: "Waar de zes systemen naar wijzen",
    collapseButton: "Inklappen",
    viewEvidenceButton: "Bewijs bekijken",
    whenWhatSpeaker: "Wanneer, en wat",
    viewActionButton: "Acties bekijken",
    thingsToDoHeading: "De moeite waard om te proberen in deze stroom",
    patternsToWatchHeading: "Terugkerende patronen om in de gaten te houden",
    finalVerdictEyebrow: "Het Laatste Kruisoordeel van de Zes Systemen",
    doNowHeading: "Nu doen",
    avoidNowHeading: "Voorlopig vermijden",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
  ms: {
    systemLabels: { saju: "Saju", ziwei: "Ziwei", vedic: "Astrologi Veda", sukuyo: "Sukuyo", astrology: "Astrologi", tarot: "Tarot" },
    stanceLabels: { agree: "Arah yang sama", conditional: "Bersyarat", caution: "Perlahankan" },
    stageMessages: {
      saju: "Sedang membaca musim dan perangai Saju anda.",
      ziwei: "Sedang menghubungkan aliran tema dalam carta Ziwei anda.",
      sukuyo: "Sedang meneliti rentak hubungan Sukuyo anda.",
      vedic: "Sedang meneliti aliran masa dalam carta Veda anda.",
      astrology: "Sedang menyusun corak ekspresi dan pilihan astrologi anda.",
      tarot: "Sedang menghubungkan susunan Tarot yang sesuai dengan soalan anda.",
      fusion: "Sedang menggabungkan semua aliran menjadi satu bacaan.",
    },
    stageDoneMessages: {
      saju: "Selesai membaca musim dan perangai semula jadi anda.",
      ziwei: "Aliran tema carta anda telah dihubungkan.",
      sukuyo: "Rentak pergerakan hubungan anda telah ditangkap.",
      vedic: "Aliran masa yang digambarkan dasha anda telah disusun.",
      astrology: "Corak ekspresi dan pilihan telah disusun.",
      tarot: "Enam kad yang sesuai dengan soalan anda telah disusun.",
      fusion: "Enam aliran telah dijalin menjadi satu bacaan.",
    },
    orbCoreAlt: "Teras gabungan di mana enam sistem nasib bersatu menjadi satu",
    vizSectionAriaLabel: "Metrik ringkasan bacaan Takdir Gabungan",
    radarHeading: "Kekuatan Isyarat Mengikut Sistem",
    radarCaption: "Sejauh mana jelasnya setiap enam sistem memberi isyarat tentang soalan ini. Bukan skor yang menilai anda sebagai individu.",
    radarAriaLabel: (items) => `Kekuatan isyarat mengikut sistem: ${items}`,
    crossCheckHeading: "Semakan Silang",
    crossCheckCaption: "Isyarat yang ditunjukkan bersama oleh beberapa sistem menjadi keutamaan; isyarat yang berbeza dikekalkan sebagai pilihan mengikut situasi.",
    crossCheckGaugeAriaLabel: (label, aligned, divergent) => `Kesepakatan antara sistem ${label}. ${aligned} isyarat bertindih, ${divergent} isyarat berbeza.`,
    crossCheckGaugeCaption: "Kesepakatan Antara Sistem",
    alignedHeading: "Isyarat Bertindih",
    divergentHeading: "Isyarat Berbeza",
    timelineHeading: "Garis Masa 12 Bulan Akan Datang",
    timelineCaption: "Bukan garis yang meramalkan peristiwa — tetapi berapa banyak usaha yang berbaloi setiap bulan dan apa yang patut dicuba pada waktu itu.",
    timelineAriaLabel: (months) => `Aliran 12 bulan akan datang: ${months}`,
    recentSectionAriaLabel: "Konsultasi Takdir Gabungan yang lalu",
    recentHeading: "Lihat Semula Bacaan Gabungan Yang Lalu",
    recentSubtext: "Keputusan ini sudah dibayar. Membukanya semula tidak dikenakan caj tambahan.",
    recentFallbackTitle: "Takdir Gabungan",
    recentCurrentBadge: "Sedang dilihat",
    recentOpeningButton: "Sedang membuka…",
    recentOpenButton: "Buka",
    analysisCompleteBadge: "Analisis enam sistem selesai",
    firstParagraphSpeaker: "Mula-mula, dalam satu perenggan",
    sixSystemsDirectionSpeaker: "Arah yang ditunjukkan oleh enam sistem",
    collapseButton: "Kuncupkan",
    viewEvidenceButton: "Lihat bukti",
    whenWhatSpeaker: "Bila, dan apa",
    viewActionButton: "Lihat tindakan",
    thingsToDoHeading: "Berbaloi dicuba dalam aliran ini",
    patternsToWatchHeading: "Corak berulang yang perlu diperhatikan",
    finalVerdictEyebrow: "Keputusan Silang Akhir Enam Sistem",
    doNowHeading: "Buat sekarang",
    avoidNowHeading: "Elak buat masa ini",
    railAriaLabel: "Reading outline",
    statsHeading: "This reading",
    tocHeading: "Contents",
    totalCharsLabel: "Total length",
    readingTimeLabel: "Reading time",
    readPositionLabel: "Progress",
    readingCharsPerMinute: 1000,
    charsCount: (count) => `${count} chars`,
    minutesAbout: (minutes) => `about ${minutes} min`,
    openingShortLabel: "Opening",
    summaryShortLabel: "One-paragraph summary",
    integratedShortLabel: "Integrated reading",
    verdictShortLabel: "Final cross-verdict",
    closingShortLabel: "Closing",
    stageTwoGroupLabel: "Stage 2",
    stageTwoGeneratingLabel: "Stage 2 · writing",
    stageTwoPendingBadge: "Stage 2 in progress",
    stageTwoPendingMessage: "Bringing the six voices together into one answer. When it is done, the summary, timing, and final verdict will continue right here. You can close this page; reopening it resumes where it left off.",
    pendingLabel: "Pending",
    readLabel: "Read",
    jumpToVerdictButton: "Go to the final verdict",
    keySentenceLabel: "Key point",
    dockAriaLabel: "Reading navigation",
    openTocButton: "Contents",
    closeSheetButton: "Close contents",
    progressRead: (percent) => `${percent}% read`,
    remainingAbout: (minutes) => `about ${minutes} min left`,
  },
};

export function getFusionSharedCopy(locale: LoadingLocale): FusionSharedCopy {
  return FUSION_SHARED_COPY[locale] || FUSION_SHARED_EN;
}

export function useFusionSharedCopy(): FusionSharedCopy {
  const [locale, setLocale] = useState<LoadingLocale>(() => getCurrentLoadingLocale());
  useEffect(() => {
    const sync = () => setLocale(getCurrentLoadingLocale());
    window.addEventListener("languagechange", sync);
    window.addEventListener("cd:locale-ready", sync);
    return () => {
      window.removeEventListener("languagechange", sync);
      window.removeEventListener("cd:locale-ready", sync);
    };
  }, []);
  return getFusionSharedCopy(locale);
}
