const en = {
  reviewFlow: "Follow each expert’s completed analysis here.", selectPlace: "Select birthplace",
  valuePoints: [{ title: "Six traditions", description: "Each expert reads the evidence using their own method." }, { title: "Compare the evidence", description: "Explore shared positions and differences on the same question." }, { title: "Your next step", description: "Turn the interpretation into priorities and practical actions." }],
  narrator: "Fusion Fortune Guide", title: "Six expert perspectives. One deeper reading.",
  intro: "Read the evidence from each tradition independently, then explore their shared insights and different perspectives in one consultation.",
  trust: "Saju engine designed and advised by a practitioner with 10 years of experience.",
  required: "Enter your birth date, exact birth time and birthplace before continuing.",
  ready: "Preparing calculation data", review: "Expert analysis", final: "Your integrated fortune reading",
  tarot: "Six cards for this consultation", reveal: "Reveal card", upright: "Upright", reversed: "Reversed",
  positions: { current: "Current situation", inner: "Inner world", obstacle: "Obstacle", external: "External influence", choice: "Choice", action: "Next action" },
  cross: "Shared insights and different perspectives", aligned: "Shared insights", divergent: "Different perspectives",
  domains: { timing: "Timing", relationship: "Relationships", psychology: "Psychology", work: "Work" },
  preferred: "Evidence prioritized for this topic", current: "Current question", noCross: "No shared or conflicting positions were established for the same topic and period.",
  pending: "Completed analyses are saved. Continue the same request to finish the remaining analysis.",
  valueTitle: "From evidence to a practical next step", valueIntro: "Six independent readings, a comparison of their evidence, and concrete actions. Completed reports can be reopened and saved as PDF.",
  price: "Choose an eligible pass, Moonstones or a single payment in the existing checkout.",
  length: "Korean completed report: 30,000–60,000 characters", guide: "How Fusion Fortune works",
  guideBody: "Saju, Ziwei, Vedic astrology, Sukuyo, Western astrology and tarot retain their own methods. Timing, relationships and psychology are compared using the evidence relevant to each topic.",
  retry: "If generation is interrupted, continue with the same paid request without paying again.",
  input: "Confirm your birth details", benefits: "Independent analysis · Evidence comparison · Practical advice",
};
const ko: typeof en = {
  reviewFlow: "각 전문가의 분석이 완료되면 이 화면에서 확인할 수 있습니다.", selectPlace: "출생지를 선택해 주세요",
  valuePoints: [{ title: "여섯 체계", description: "각 전문가는 자기 체계의 계산 근거로 독립적인 해석을 제시합니다." }, { title: "근거의 비교", description: "같은 질문과 시기에서 공통되는 흐름과 관점의 차이를 읽습니다." }, { title: "다음 행동", description: "종합 해석을 바탕으로 지금의 우선순위와 실행할 조언을 정합니다." }],
  narrator: "초융합 상담자", title: "여섯 전문가의 해석, 하나로 깊어지는 나의 운세",
  intro: "각 체계의 근거를 독립적으로 읽고, 함께 가리키는 흐름과 서로 다른 관점을 하나의 상담으로 정리합니다.",
  trust: "사주 엔진 — 실제 경력 10년차 명리학자 설계·자문",
  required: "생년월일·정확한 생시·출생지를 입력한 뒤 상담을 시작해 주세요.",
  ready: "계산 자료 준비 중", review: "전문가 분석", final: "최적 운세 답안",
  tarot: "이번 상담에 펼쳐진 여섯 장", reveal: "카드 뒤집기", upright: "정방향", reversed: "역방향",
  positions: { current: "현재 상황", inner: "내면", obstacle: "장애물", external: "외부 영향", choice: "선택", action: "다음 행동" },
  cross: "함께 가리키는 흐름과 관점의 차이", aligned: "공통 수렴 지점", divergent: "체계별 관점 차이",
  domains: { timing: "시기", relationship: "관계", psychology: "심리", work: "일과 역할" },
  preferred: "이 주제에서 우선한 근거", current: "현재 질문", noCross: "같은 주제와 시기에서 공통되거나 상충하는 입장은 확인되지 않았습니다.",
  pending: "완료된 분석은 저장했습니다. 같은 요청으로 남은 분석을 이어서 받아보세요.",
  valueTitle: "근거를 읽고, 다음 행동을 정합니다", valueIntro: "여섯 전문가의 독립 해석과 근거 비교, 실행할 조언을 담습니다. 완성된 상담은 다시 열고 PDF로 저장할 수 있습니다.",
  price: "기존 결제창에서 적용 가능한 이용권·월정석·단건 결제를 선택합니다.",
  length: "한국어 완성본 30,000~60,000자", guide: "초융합 운세는 이렇게 읽습니다",
  guideBody: "사주·자미두수·베다점성술·숙요점·서양점성술·타로의 체계를 구분해 해석합니다. 시기·관계·심리 등 주제에 맞는 근거를 우선해 서로의 관점을 비교합니다.",
  retry: "생성이 중단되면 같은 결제 요청으로 추가 결제 없이 이어서 받습니다.",
  input: "태어난 순간에서 시작합니다", benefits: "독립 전문가 분석 · 근거 교차 검증 · 실행 조언",
};
export type FusionExpertCopy = typeof en;
// The established fallback language is English. Keys remain stable across locales.
export function getFusionExpertCopy(locale: string): FusionExpertCopy { return locale === "ko" ? ko : en; }
