import type { LoadingLocale } from "@/constants/loadingMessages";
import { MUSIC_TRACK_UNLOCK_PRICE_KRW } from "@/lib/music-access-policy";
import type { RepeatMode } from "../_hooks/useMusicPlayer";

// 가격 문구는 정본 상수에서 만든다 — 로케일마다 숫자를 손으로 적으면 가격 인상 때 화면과 결제가 갈라진다.
const PRICE_LABEL = MUSIC_TRACK_UNLOCK_PRICE_KRW.toLocaleString("ko-KR");

// /music 문안. 실제로 화면에 쓰는 키만 둔다(옛 히어로·저장·앨범 모드·곡별 공유 문안은 제거).
// 저작 로케일은 ko·en·ja·zh-CN·zh-TW 5개, 나머지는 en 으로 폴백한다.
const MUSIC_COPY = {
  ko: {
    brand: "CODE DESTINY",
    home: "Code Destiny 홈으로",
    title: "달빛 플레이리스트",
    tagline: "운명이 잠든 밤, 달빛 아래 음악을 들어보세요.",
    playerAria: "Code Destiny 음악 플레이어",
    playlistAria: "음악 플레이리스트",
    filterAria: "아티스트 필터",
    searchPlaceholder: "트랙 검색",
    searchAria: "트랙 검색",
    tracksCount: (shown: number, total: number) => `${shown} / ${total}곡`,
    emptyTitle: "이 달빛에는 아직 곡이 머물지 않습니다.",
    emptyBody: "다른 아티스트나 검색어로 다시 열어보세요.",
    playTrack: (title: string, artist: string) => `${title} · ${artist} 재생`,
    statusLoading: "달빛을 불러오는 중",
    statusPlaying: "재생 중",
    statusPaused: "일시정지",
    play: "재생",
    pause: "일시정지",
    nextTrack: "다음 곡",
    previousTrack: "이전 곡",
    seek: "재생 위치",
    seekValue: (current: string, total: string) => `${total} 중 ${current}`,
    volume: "볼륨",
    mute: "음소거",
    unmute: "음소거 해제",
    repeat: (mode: RepeatMode) => (mode === "one" ? "한 곡 반복" : mode === "all" ? "전체 반복" : "반복 꺼짐"),
    shuffleOn: "셔플 켜짐",
    shuffleOff: "셔플 꺼짐",
    share: "공유",
    copied: "복사됨",
    shareText: "Code Destiny 달빛 플레이리스트에서 들어보세요.",
    shareMain: "Code Destiny 메인",
    shareTitle: (title: string) => `Code Destiny Music - ${title}`,
    lyrics: "가사",
    lyricsAria: "현재 곡 가사",
    lyricsLoading: "가사 로딩 중...",
    lyricsEmpty: "가사 데이터가 아직 준비되지 않았습니다.",
    close: "닫기",
    previewBadge: "40초 미리듣기",
    fullAccessBadge: "전체듣기 열림",
    passAccessBadge: "이용권으로 전곡 열림",
    buyFullTrack: `전체듣기 ${PRICE_LABEL}원`,
    buyingFullTrack: "결제 확인 중",
    buyForDownload: `다운로드 구매 ${PRICE_LABEL}원`,
    downloadTrack: "다운로드",
    previewLimitReached: "40초 미리듣기가 끝났습니다.",
    purchaseFailed: "결제를 완료하지 못했습니다.",
    priceChanged: "가격이 변경되었습니다. 새로고침 후 다시 시도해 주세요.",
    miniOpen: "지금 재생 중인 곡으로 이동",
  },
  en: {
    brand: "CODE DESTINY",
    home: "Back to Code Destiny home",
    title: "Moonlight Playlist",
    tagline: "On the night fate sleeps, listen under the moonlight.",
    playerAria: "Code Destiny music player",
    playlistAria: "Music playlist",
    filterAria: "Filter by artist",
    searchPlaceholder: "Search tracks",
    searchAria: "Search tracks",
    tracksCount: (shown: number, total: number) => `${shown} of ${total} tracks`,
    emptyTitle: "No tracks found",
    emptyBody: "Try All or clear the search.",
    playTrack: (title: string, artist: string) => `Play ${title} by ${artist}`,
    statusLoading: "Calling in the moonlight",
    statusPlaying: "Playing",
    statusPaused: "Paused",
    play: "Play",
    pause: "Pause",
    nextTrack: "Next track",
    previousTrack: "Previous track",
    seek: "Seek",
    seekValue: (current: string, total: string) => `${current} of ${total}`,
    volume: "Volume",
    mute: "Mute",
    unmute: "Unmute",
    repeat: (mode: RepeatMode) => (mode === "one" ? "Repeat one" : mode === "all" ? "Repeat all" : "Repeat off"),
    shuffleOn: "Shuffle on",
    shuffleOff: "Shuffle off",
    share: "Share",
    copied: "Copied",
    shareText: "Listen inside the Code Destiny moonlight playlist.",
    shareMain: "Code Destiny main",
    shareTitle: (title: string) => `Code Destiny Music - ${title}`,
    lyrics: "Lyrics",
    lyricsAria: "Current track lyrics",
    lyricsLoading: "Loading lyrics...",
    lyricsEmpty: "Lyrics are not ready yet.",
    close: "Close",
    previewBadge: "40 sec preview",
    fullAccessBadge: "Full track open",
    passAccessBadge: "Open with your pass",
    buyFullTrack: `Full track ${PRICE_LABEL} KRW`,
    buyingFullTrack: "Checking payment",
    buyForDownload: `Buy to download ${PRICE_LABEL} KRW`,
    downloadTrack: "Download",
    previewLimitReached: "The 40 second preview has ended.",
    purchaseFailed: "Payment was not completed.",
    priceChanged: "The price has changed. Please refresh and try again.",
    miniOpen: "Go to the current track",
  },
  ja: {
    brand: "CODE DESTINY",
    home: "Code Destiny ホームへ",
    title: "月明かりプレイリスト",
    tagline: "運命が眠る夜、月明かりの下で音楽を。",
    playerAria: "Code Destiny 音楽プレイヤー",
    playlistAria: "音楽プレイリスト",
    filterAria: "アーティストで絞り込む",
    searchPlaceholder: "曲を検索",
    searchAria: "曲を検索",
    tracksCount: (shown: number, total: number) => `${shown} / ${total}曲`,
    emptyTitle: "曲が見つかりません",
    emptyBody: "Allを選ぶか、検索語を消してください。",
    playTrack: (title: string, artist: string) => `${title}（${artist}）を再生`,
    statusLoading: "月明かりを呼び込んでいます",
    statusPlaying: "再生中",
    statusPaused: "一時停止",
    play: "再生",
    pause: "一時停止",
    nextTrack: "次の曲",
    previousTrack: "前の曲",
    seek: "再生位置",
    seekValue: (current: string, total: string) => `${total} 中 ${current}`,
    volume: "音量",
    mute: "ミュート",
    unmute: "ミュート解除",
    repeat: (mode: RepeatMode) => (mode === "one" ? "1曲リピート" : mode === "all" ? "全曲リピート" : "リピート オフ"),
    shuffleOn: "シャッフル オン",
    shuffleOff: "シャッフル オフ",
    share: "共有",
    copied: "コピー済み",
    shareText: "Code Destinyの月明かりプレイリストで聴いてみてください。",
    shareMain: "Code Destiny メイン",
    shareTitle: (title: string) => `Code Destiny Music - ${title}`,
    lyrics: "歌詞",
    lyricsAria: "現在の曲の歌詞",
    lyricsLoading: "歌詞を読み込んでいます...",
    lyricsEmpty: "歌詞データはまだ準備されていません。",
    close: "閉じる",
    previewBadge: "40秒プレビュー",
    fullAccessBadge: "全曲再生が開放されています",
    passAccessBadge: "利用権で全曲開放中",
    buyFullTrack: `全曲再生 ${PRICE_LABEL}ウォン`,
    buyingFullTrack: "決済を確認しています",
    buyForDownload: `ダウンロード購入 ${PRICE_LABEL}ウォン`,
    downloadTrack: "ダウンロード",
    previewLimitReached: "40秒プレビューが終了しました。",
    purchaseFailed: "決済が完了しませんでした。",
    priceChanged: "価格が変更されました。更新後にもう一度お試しください。",
    miniOpen: "再生中の曲へ移動",
  },
  "zh-CN": {
    brand: "CODE DESTINY",
    home: "返回 Code Destiny 首页",
    title: "月光播放列表",
    tagline: "在命运沉睡的夜晚，于月光下聆听音乐。",
    playerAria: "Code Destiny 音乐播放器",
    playlistAria: "音乐播放列表",
    filterAria: "按艺人筛选",
    searchPlaceholder: "搜索曲目",
    searchAria: "搜索曲目",
    tracksCount: (shown: number, total: number) => `${shown} / ${total} 首`,
    emptyTitle: "未找到曲目",
    emptyBody: "请选择全部或清除搜索词。",
    playTrack: (title: string, artist: string) => `播放 ${title}（${artist}）`,
    statusLoading: "正在唤来月光",
    statusPlaying: "播放中",
    statusPaused: "已暂停",
    play: "播放",
    pause: "暂停",
    nextTrack: "下一曲",
    previousTrack: "上一曲",
    seek: "播放进度",
    seekValue: (current: string, total: string) => `${current} / ${total}`,
    volume: "音量",
    mute: "静音",
    unmute: "取消静音",
    repeat: (mode: RepeatMode) => (mode === "one" ? "单曲循环" : mode === "all" ? "全部循环" : "循环关闭"),
    shuffleOn: "随机播放：开",
    shuffleOff: "随机播放：关",
    share: "分享",
    copied: "已复制",
    shareText: "在 Code Destiny 月光播放列表中聆听。",
    shareMain: "Code Destiny 首页",
    shareTitle: (title: string) => `Code Destiny Music - ${title}`,
    lyrics: "歌词",
    lyricsAria: "当前曲目歌词",
    lyricsLoading: "歌词加载中...",
    lyricsEmpty: "歌词数据尚未准备好。",
    close: "关闭",
    previewBadge: "40秒试听",
    fullAccessBadge: "已开放完整播放",
    passAccessBadge: "已用权益开放完整播放",
    buyFullTrack: `完整播放 ${PRICE_LABEL}韩元`,
    buyingFullTrack: "正在确认支付",
    buyForDownload: `购买下载 ${PRICE_LABEL}韩元`,
    downloadTrack: "下载",
    previewLimitReached: "40秒试听已结束。",
    purchaseFailed: "支付未完成。",
    priceChanged: "价格已变更。请刷新后重试。",
    miniOpen: "前往当前曲目",
  },
  "zh-TW": {
    brand: "CODE DESTINY",
    home: "返回 Code Destiny 首頁",
    title: "月光播放清單",
    tagline: "在命運沉睡的夜晚，於月光下聆聽音樂。",
    playerAria: "Code Destiny 音樂播放器",
    playlistAria: "音樂播放清單",
    filterAria: "依藝人篩選",
    searchPlaceholder: "搜尋曲目",
    searchAria: "搜尋曲目",
    tracksCount: (shown: number, total: number) => `${shown} / ${total} 首`,
    emptyTitle: "未找到曲目",
    emptyBody: "請選擇全部或清除搜尋字詞。",
    playTrack: (title: string, artist: string) => `播放 ${title}（${artist}）`,
    statusLoading: "正在喚來月光",
    statusPlaying: "播放中",
    statusPaused: "已暫停",
    play: "播放",
    pause: "暫停",
    nextTrack: "下一首",
    previousTrack: "上一首",
    seek: "播放進度",
    seekValue: (current: string, total: string) => `${current} / ${total}`,
    volume: "音量",
    mute: "靜音",
    unmute: "取消靜音",
    repeat: (mode: RepeatMode) => (mode === "one" ? "單曲循環" : mode === "all" ? "全部循環" : "循環關閉"),
    shuffleOn: "隨機播放：開",
    shuffleOff: "隨機播放：關",
    share: "分享",
    copied: "已複製",
    shareText: "在 Code Destiny 月光播放清單中聆聽。",
    shareMain: "Code Destiny 首頁",
    shareTitle: (title: string) => `Code Destiny Music - ${title}`,
    lyrics: "歌詞",
    lyricsAria: "目前曲目歌詞",
    lyricsLoading: "歌詞載入中...",
    lyricsEmpty: "歌詞資料尚未準備好。",
    close: "關閉",
    previewBadge: "40秒試聽",
    fullAccessBadge: "已開放完整播放",
    passAccessBadge: "已用權益開放完整播放",
    buyFullTrack: `完整播放 ${PRICE_LABEL}韓元`,
    buyingFullTrack: "正在確認付款",
    buyForDownload: `購買下載 ${PRICE_LABEL}韓元`,
    downloadTrack: "下載",
    previewLimitReached: "40秒試聽已結束。",
    purchaseFailed: "付款未完成。",
    priceChanged: "價格已變更。請重新整理後再試一次。",
    miniOpen: "前往目前曲目",
  },
};

export type MusicCopy = typeof MUSIC_COPY.ko;

export function getMusicCopy(locale: LoadingLocale): MusicCopy {
  return MUSIC_COPY[locale as keyof typeof MUSIC_COPY] || MUSIC_COPY.en;
}
