import type { RuntimeLocale } from '@/lib/i18n/dictionary';
const ko = {
  refund_pending: '환불 확인 중', refundLead: '전체 결과를 제공하지 못해 환불을 확인하고 있어요. 다시 결제하지 말고 결제 내역에서 처리 상태를 확인해 주세요.', title: '꿀꿀운세 보관함', lead: '받았던 운세와 상담을 다시 펼쳐보세요',
  hubTitle: '지금, 어떤 답이 필요한가요?', hubLead: '당신의 고민에 맞는 깊이 있는 운명 상담을 골라보세요.',
  all: '전체', report: '대표·심층 상담', chat: '대화 상담', chart: '차트·해석',
  search: '기록 제목과 질문 검색', latest: '최신순', loading: '저장된 기록을 확인하고 있어요.',
  loginTitle: '내 기록을 보려면 로그인해 주세요', loginLead: '상담을 받았던 계정으로 로그인하면 저장된 결과를 찾을 수 있어요.', login: '로그인하기',
  empty: '아직 보관된 기록이 없어요', emptySearch: '검색 조건에 맞는 기록이 없어요', emptyLead: '상담을 마치면 저장된 운세를 이곳에서 다시 읽을 수 있어요.',
  error: '기록을 불러오지 못했어요', errorLead: '조회에 실패했어요. 잠시 후 다시 확인해 주세요.', partialError: '일부 기록을 확인하지 못했어요',
  retry: '다시 확인하기', more: '기록 더 보기', open: '다시 보기', saved: '저장됨', completed: '완료', partial: '일부 내용 저장', generating: '생성 중', failed: '생성 실패', revoked: '취소·환불', conversation: '대화 기록',
  partialLead: '전체 결과가 완성되지 않았어요. 현재 저장된 내용만 보여드려요.', recover: '기존 상담에서 복구 확인하기',
  back: '보관함으로', home: '홈으로', hub: '상담 고르기', detail: '상담 자세히 보기', newConsult: '새 상담 시작하기',
  characters: '캐릭터와 대화하기', charactersLead: '지금 마음에 걸리는 이야기를 연이·네오에게 직접 건네보세요.', yeoni: '연이와 대화하기', neo: '네오와 대화하기',
  original: '기존 결과 화면으로 보기', result: '저장된 결과', formatUnavailable: '저장된 결과 형식을 모두 복원하지 못했어요. 읽을 수 있는 저장 내용만 표시합니다.', noBody: '아직 읽을 수 있는 결과가 저장되지 않았어요.', price: '단건 결제', priceUnknown: '가격은 상담 화면에서 확인해 주세요',
  save: '보관함에 저장하기', saving: '기록 저장 중', saveError: '결과는 완성됐지만 저장을 확인하지 못했어요. 다시 저장해 주세요.',
};
type Copy = typeof ko;
const en: Copy = { ...ko, refund_pending: 'Refund pending', refundLead: 'We could not deliver the full reading and are processing its refund. Do not pay again; check payment history for confirmation.', save: 'Save to archive', saving: 'Saving reading', saveError: 'Your reading is ready, but saving could not be confirmed. Try saving again.', title: 'My reading archive', lead: 'Revisit your readings and consultations', hubTitle: 'What answer do you need today?', hubLead: 'Choose a deeper consultation that fits your concern.', all: 'All', report: 'In-depth readings', chat: 'Conversations', chart: 'Charts & insights', search: 'Search titles and questions', latest: 'Newest first', loading: 'Loading saved readings…', loginTitle: 'Sign in to see your readings', loginLead: 'Use the account that received the consultation.', login: 'Sign in', empty: 'No saved readings yet', emptySearch: 'No readings match your search', emptyLead: 'Completed readings can be revisited here.', error: 'Could not load your readings', errorLead: 'Please try again in a moment.', partialError: 'Some readings could not be loaded', retry: 'Try again', more: 'Load more', open: 'Read again', saved: 'Saved', completed: 'Completed', partial: 'Partially saved', generating: 'In progress', failed: 'Generation failed', revoked: 'Cancelled / refunded', conversation: 'Conversation', partialLead: 'This reading is incomplete. Only saved content is shown.', recover: 'Check recovery in the original consultation', back: 'Back to archive', home: 'Home', hub: 'Choose a consultation', detail: 'View consultation details', newConsult: 'Start a new consultation', characters: 'Talk with a character', charactersLead: 'Share what is on your mind with Yeoni or Neo.', yeoni: 'Talk with Yeoni', neo: 'Talk with Neo', original: 'Open the original reading', result: 'Saved reading', formatUnavailable: 'This saved format could not be fully restored. Only readable saved content is shown.', noBody: 'No readable result has been saved yet.', price: 'Single payment', priceUnknown: 'Check pricing on the consultation page' };
const ja: Copy = { ...en, title: '私の記録保管庫', lead: '受け取った占いと相談をもう一度開きましょう', hubTitle: '今、どんな答えが必要ですか？', hubLead: '悩みに合った深い運命相談を選んでください。', all: 'すべて', report: '深い相談', chat: '会話相談', chart: 'チャート・解釈', search: 'タイトルと質問を検索', latest: '新しい順', loading: '保存した記録を確認中です。', loginTitle: '記録を見るにはログインしてください', loginLead: '相談を受けたアカウントでログインしてください。', login: 'ログイン', empty: '保存した記録はまだありません', emptySearch: '条件に合う記録がありません', error: '記録を読み込めませんでした', partialError: '一部の記録を確認できませんでした', retry: '再確認', more: 'もっと見る', open: 'もう一度見る', completed: '完了', partial: '一部保存', generating: '生成中', failed: '生成失敗', saved: '保存済み', conversation: '会話記録', back: '保管庫へ', home: 'ホーム', hub: '相談を選ぶ', detail: '相談の詳細', newConsult: '新しい相談', characters: 'キャラクターと話す', yeoni: 'ヨニと話す', neo: 'ネオと話す', price: '単発決済' };
const zh: Copy = { ...en, title: '我的记录收藏夹', lead: '重新阅读收到的运势与咨询', hubTitle: '此刻，你需要什么答案？', hubLead: '选择适合你的深入咨询。', all: '全部', report: '深入咨询', chat: '对话咨询', chart: '命盘与解读', search: '搜索标题和问题', latest: '最新优先', loading: '正在读取记录。', loginTitle: '登录后查看记录', loginLead: '请使用接受咨询的账户登录。', login: '登录', empty: '还没有保存的记录', emptySearch: '没有符合条件的记录', error: '无法加载记录', partialError: '部分记录加载失败', retry: '重试', more: '查看更多', open: '再次阅读', completed: '已完成', partial: '部分保存', generating: '生成中', failed: '生成失败', saved: '已保存', conversation: '对话记录', back: '返回收藏夹', home: '首页', hub: '选择咨询', detail: '咨询详情', newConsult: '开始新咨询', characters: '与角色对话', yeoni: '与延伊对话', neo: '与尼奥对话', price: '单次支付' };
const zhTW: Copy = { ...zh, title: '我的記錄收藏夾', lead: '重新閱讀收到的運勢與諮詢', hubTitle: '此刻，你需要什麼答案？', hubLead: '選擇適合你的深入諮詢。', report: '深入諮詢', chat: '對話諮詢', chart: '命盤與解讀', search: '搜尋標題和問題', latest: '最新優先', loading: '正在讀取記錄。', loginTitle: '登入後查看記錄', loginLead: '請使用接受諮詢的帳戶登入。', login: '登入', empty: '還沒有儲存的記錄', emptySearch: '沒有符合條件的記錄', error: '無法載入記錄', partialError: '部分記錄載入失敗', retry: '重試', more: '查看更多', open: '再次閱讀', completed: '已完成', partial: '部分儲存', generating: '生成中', failed: '生成失敗', saved: '已儲存', conversation: '對話記錄', back: '返回收藏夾', home: '首頁', hub: '選擇諮詢', detail: '諮詢詳情', newConsult: '開始新諮詢', characters: '與角色對話', yeoni: '與延伊對話', neo: '與尼奧對話', price: '單次付款' };
export function recordsCopy(locale: RuntimeLocale): Copy { return ({ ko, en, ja, 'zh-CN': zh, 'zh-TW': zhTW } as Partial<Record<RuntimeLocale, Copy>>)[locale] || en; }
