/* eslint-disable @next/next/no-img-element -- optimized local WebP exports with explicit dimensions */
import './service-intro.css';

export default function ServiceIntroduction({text}) {
  return <div className="cd-service-intro">
<section id="about-hero" className="hero wrap"><div className="hero-copy"><h1>{text("intro.hero.text1")}<br />{text("intro.hero.text2")}<br /><em>{text("intro.hero.text3")}</em></h1><p className="lead">{text("intro.hero.text4")}<br />{text("intro.hero.text5")}</p><p>{text("intro.hero.text6")}<br />{text("intro.hero.text7")}</p><div className="actions"><a className="button" href="/ggulggul/">{text("intro.hero.text8")}<span aria-hidden="true">{text("intro.hero.text9")}</span></a><a className="text-link" href="/yeongnyangi/">{text("intro.hero.text10")}</a></div></div><figure className="hero-art"><img src="/assets/service-intro/duo-stars.webp" alt="별이 펼쳐진 책을 함께 읽는 꽃돼지 연이와 영냥이" width="1100" height="733" loading="eager" /><figcaption>{text("intro.hero.text11")}</figcaption></figure></section>
<section id="about-questions" className="intro wrap"><p className="quote">{text("intro.questions.text1")}<br />{text("intro.questions.text2")}</p><div><h2>{text("intro.questions.text3")}<br />{text("intro.questions.text4")}</h2><p>{text("intro.questions.text5")}</p></div></section>
<section id="reading" className="night"><div className="wrap feature"><div><h2>{text("intro.consultation.text1")}<br /><em>{text("intro.consultation.text2")}</em></h2><p className="lead">{text("intro.consultation.text3")}<br />{text("intro.consultation.text4")}</p><p>{text("intro.consultation.text5")}</p><ul className="editorial-list"><li><strong>{text("intro.consultation.text6")}</strong><span>{text("intro.consultation.text7")}</span></li><li><strong>{text("intro.consultation.text8")}</strong><span>{text("intro.consultation.text9")}</span></li><li><strong>{text("intro.consultation.text10")}</strong><span>{text("intro.consultation.text11")}</span></li></ul></div><img className="cat-art" src="/assets/service-intro/cat-reading.webp" alt="별자리 책을 펼쳐 설명하는 영냥이" width="1100" height="880" loading="lazy" /></div></section>
<section id="about-systems" className="wrap systems"><div className="section-head"><h2>{text("intro.systems.text1")}<br />{text("intro.systems.text2")}</h2><p>{text("intro.systems.text3")}<br />{text("intro.systems.text4")}</p></div><dl className="systems-list"><div><dt>{text("intro.systems.text5")}</dt><dd>{text("intro.systems.text6")}</dd></div><div><dt>{text("intro.systems.text7")}</dt><dd>{text("intro.systems.text8")}</dd></div><div><dt>{text("intro.systems.text9")}</dt><dd>{text("intro.systems.text10")}</dd></div><div><dt>{text("intro.systems.text11")}</dt><dd>{text("intro.systems.text12")}</dd></div><div><dt>{text("intro.systems.text13")}</dt><dd>{text("intro.systems.text14")}</dd></div><div><dt>{text("intro.systems.text15")}</dt><dd>{text("intro.systems.text16")}</dd></div></dl><p className="note">{text("intro.systems.text17")}</p></section>
<section id="about-fusion" className="fusion night"><div className="wrap"><div className="section-head"><h2>{text("intro.fusion.text1")}<br /><em>{text("intro.fusion.text2")}</em></h2><p>{text("intro.fusion.text3")}<br />{text("intro.fusion.text4")}</p></div><div className="fusion-flow"><article><h3>{text("intro.fusion.text5")}</h3><p className="big">{text("intro.fusion.text6")}</p><p>{text("intro.fusion.text7")}<br />{text("intro.fusion.text8")}</p></article><article><h3>{text("intro.fusion.text9")}</h3><p className="big">{text("intro.fusion.text10")}</p><p>{text("intro.fusion.text11")}<br />{text("intro.fusion.text12")}</p></article></div><p className="fusion-close">{text("intro.fusion.text13")}<br /><strong>{text("intro.fusion.text14")}</strong></p></div></section>
<section id="about-free" className="wrap feature free"><div><h2>{text("intro.free.text1")}<br /><em>{text("intro.free.text2")}</em></h2><p className="lead">{text("intro.free.text3")}<br />{text("intro.free.text4")}</p><p>{text("intro.free.text5")}</p><a className="button" href="/today/">{text("intro.free.text6")}<span aria-hidden="true">{text("intro.free.text7")}</span></a><p className="note">{text("intro.free.text8")}</p></div><figure className="screen-frame"><img src="/assets/service-intro/free-tarot.webp" alt="연이의 로그인 없는 무료 세 장 타로 실제 화면" width="720" height="2222" loading="lazy" /><figcaption>{text("intro.free.text9")}</figcaption></figure></section>
<section id="about-elements" className="chart-section night"><div className="wrap feature"><figure className="screen-frame chart-screen"><img src="/assets/service-intro/elements.webp" alt="목·화·토·금·수의 저장된 값을 색과 아이콘으로 표시한 영냥이 오행 차트" width="800" height="480" loading="lazy" /><figcaption>{text("intro.elements.text1")}</figcaption></figure><div><h2>{text("intro.elements.text2")}<br /><em>{text("intro.elements.text3")}</em></h2><p className="lead">{text("intro.elements.text4")}<br />{text("intro.elements.text5")}</p><p>{text("intro.elements.text6")}</p><p>{text("intro.elements.text7")}</p><p className="note">{text("intro.elements.text8")}</p></div></div></section>
<section id="about-report" className="wrap feature keep"><div><h2>{text("intro.report.text1")}<br /><em>{text("intro.report.text2")}</em></h2><p className="lead">{text("intro.report.text3")}<br />{text("intro.report.text4")}</p><ol className="journey"><li><strong>{text("intro.report.text5")}</strong><p>{text("intro.report.text6")}</p></li><li><strong>{text("intro.report.text7")}</strong><p>{text("intro.report.text8")}</p></li><li><strong>{text("intro.report.text9")}</strong><p>{text("intro.report.text10")}</p></li></ol></div><figure className="screen-frame report-screen"><img src="/assets/service-intro/report.webp" alt="저장된 상담 근거와 리포트 제작 안내의 실제 컴포넌트 예시" width="760" height="2430" loading="lazy" /><figcaption>{text("intro.report.text11")}</figcaption></figure></section>
<section id="about-reviews" className="reviews"><div className="wrap"><h2>{text("intro.reviews.text1")}<br />{text("intro.reviews.text2")}</h2><blockquote>{text("intro.reviews.text3")}<br />{text("intro.reviews.text4")}</blockquote><p>{text("intro.reviews.text5")}</p><p className="note">{text("intro.reviews.text6")}<br />{text("intro.reviews.text7")}</p><a className="text-link" href="#author">{text("intro.reviews.text8")}</a></div></section>
<section id="start" className="wrap welcome"><div><h2>{text("intro.welcome.text1")}<br /><em>{text("intro.welcome.text2")}</em></h2><p className="lead">{text("intro.welcome.text3")}<br />{text("intro.welcome.text4")}</p><p>{text("intro.welcome.text5")}</p><a className="button" href="/ggulggul/">{text("intro.welcome.text6")}</a><p className="note">{text("intro.welcome.text7")}<br />{text("intro.welcome.text8")}</p></div><img src="/assets/service-intro/yeoni-gift.webp" alt="월정석 선물 상자를 건네는 꽃돼지 연이" width="1100" height="1320" loading="lazy" /></section>
<section id="about-faq" className="wrap faq"><h2>{text("intro.faq.text1")}</h2><details><summary>{text("intro.faq.text2")}</summary><p>{text("intro.faq.text3")}</p></details><details><summary>{text("intro.faq.text4")}</summary><p>{text("intro.faq.text5")}</p></details><details><summary>{text("intro.faq.text6")}</summary><p>{text("intro.faq.text7")}</p></details></section>
</div>;
}
