export type MayaDaySign = {
  index: number;
  name: string;
  koreanName: string;
  symbolTitle: string;
  coreKeywords: string[];
  lightKeywords: string[];
  shadowKeywords: string[];
  personalitySummary: string;
  dailyMessage: string;
  relationshipPattern: string;
  workPattern: string;
  advice: string;
};

export type MayaTone = {
  number: number;
  title: string;
  keywords: string[];
  meaning: string;
  advice: string;
};

export const MAYA_DAY_SIGNS: MayaDaySign[] = [
  {
    index: 0,
    name: "Imix",
    koreanName: "이믹스",
    symbolTitle: "첫 물결",
    coreKeywords: ["시작", "보호", "생명력", "감각"],
    lightKeywords: ["돌봄", "직감", "회복력", "새로운 씨앗"],
    shadowKeywords: ["감정 과잉", "성급한 보호", "흐린 경계"],
    personalitySummary: "이믹스의 나왈은 아직 형태를 갖추지 않은 가능성을 먼저 느낍니다. 마음이 먼저 반응하고, 사람과 일을 살리는 감각이 깊게 흐릅니다.",
    dailyMessage: "오늘은 완성보다 시작의 온도를 살피기 좋습니다. 마음이 움직이는 방향을 작게 열면 다음 흐름이 따라옵니다.",
    relationshipPattern: "가까운 사람을 품으려는 마음이 크지만, 상대가 스스로 설 공간을 남겨둘 때 더 따뜻하게 이어집니다.",
    workPattern: "초기 기획, 아이디어 정리, 돌봄이 필요한 업무에서 힘이 살아납니다.",
    advice: "처음 떠오른 감각을 적어 두고, 바로 큰 결론으로 밀어붙이지 마세요.",
  },
  {
    index: 1,
    name: "Ik’",
    koreanName: "익",
    symbolTitle: "바람의 숨",
    coreKeywords: ["소통", "영감", "호흡", "이동"],
    lightKeywords: ["명료한 말", "빠른 전환", "창의성", "유연함"],
    shadowKeywords: ["말의 과속", "산만함", "약속 흔들림"],
    personalitySummary: "익의 나왈은 말과 바람 사이에서 길을 찾습니다. 생각이 빠르게 움직이고, 막힌 분위기에 새 숨을 불어넣는 힘이 있습니다.",
    dailyMessage: "오늘은 말의 방향이 운을 엽니다. 짧고 솔직한 표현이 흐름을 가볍게 바꿉니다.",
    relationshipPattern: "대화가 살아야 마음도 살아납니다. 다만 설명보다 경청이 먼저 놓이면 관계의 결이 고르게 풀립니다.",
    workPattern: "회의, 글쓰기, 발표, 이동이 필요한 일에서 리듬이 살아납니다.",
    advice: "중요한 말은 한 번 더 숨을 고른 뒤 전하세요.",
  },
  {
    index: 2,
    name: "Ak’bal",
    koreanName: "악발",
    symbolTitle: "밤의 집",
    coreKeywords: ["내면", "꿈", "휴식", "문턱"],
    lightKeywords: ["깊은 통찰", "안정감", "상상력", "회복"],
    shadowKeywords: ["고립", "미루기", "불안의 확대"],
    personalitySummary: "악발의 나왈은 어둠 속에서 답을 숙성합니다. 조용히 머무는 시간 안에서 더 깊은 길을 발견하는 사람입니다.",
    dailyMessage: "오늘은 바깥의 속도보다 안쪽의 목소리를 듣기 좋습니다. 서두르지 않는 선택이 안정감을 만듭니다.",
    relationshipPattern: "감정을 바로 드러내기보다 오래 살핍니다. 안전한 분위기가 생기면 진심이 깊게 열립니다.",
    workPattern: "리서치, 기획 숙성, 비공개 준비, 공간 정리에 잘 맞습니다.",
    advice: "혼자 있는 시간을 죄책감 없이 확보하되, 필요한 연락은 닫지 마세요.",
  },
  {
    index: 3,
    name: "K’an",
    koreanName: "칸",
    symbolTitle: "빛의 씨앗",
    coreKeywords: ["씨앗", "성장", "선택", "풍요"],
    lightKeywords: ["가능성", "학습력", "선명한 목표", "자원 감각"],
    shadowKeywords: ["욕심", "초기 불안", "비교심"],
    personalitySummary: "칸의 나왈은 작은 씨앗 안에 들어 있는 미래를 알아봅니다. 아직 작아 보여도 키워낼 가치가 있는 것을 놓치지 않습니다.",
    dailyMessage: "오늘은 새로 심을 것을 고르기 좋은 날입니다. 한 가지 가능성에 물을 주듯 시간을 주세요.",
    relationshipPattern: "서로의 성장을 응원할 때 관계가 밝아집니다. 비교보다 격려가 더 큰 문을 엽니다.",
    workPattern: "학습, 투자 전 검토, 자료 수집, 장기 목표 설계에 잘 맞습니다.",
    advice: "가장 키우고 싶은 한 가지를 정하고, 작은 실행을 남기세요.",
  },
  {
    index: 4,
    name: "Chikchan",
    koreanName: "칙찬",
    symbolTitle: "살아 있는 힘",
    coreKeywords: ["생명력", "본능", "열정", "감응"],
    lightKeywords: ["추진력", "감각의 정확도", "용기", "집중"],
    shadowKeywords: ["충동", "긴장", "과열"],
    personalitySummary: "칙찬의 나왈은 몸과 감각이 먼저 아는 사람입니다. 강한 생명력으로 흐름을 깨우고, 멈춘 일에 불씨를 붙입니다.",
    dailyMessage: "오늘은 몸의 신호가 또렷합니다. 에너지가 오르는 곳과 빠지는 곳을 구분하면 선택이 쉬워집니다.",
    relationshipPattern: "끌림과 반응이 빠릅니다. 감정이 뜨거울수록 말의 온도를 낮추면 오래 갑니다.",
    workPattern: "실행, 현장 대응, 운동성 있는 프로젝트, 집중 돌파에 힘이 납니다.",
    advice: "중요한 결정 전에는 물을 마시고 몸의 긴장을 먼저 풀어 주세요.",
  },
  {
    index: 5,
    name: "Kimi",
    koreanName: "키미",
    symbolTitle: "마침과 변환",
    coreKeywords: ["정리", "전환", "비움", "재생"],
    lightKeywords: ["담담함", "정리력", "성숙", "회복의 문"],
    shadowKeywords: ["집착", "무기력", "끝에 대한 두려움"],
    personalitySummary: "키미의 나왈은 끝이 사라짐만은 아니라는 것을 압니다. 오래 붙잡은 것을 정리하며 다음 형태로 넘어가는 힘이 있습니다.",
    dailyMessage: "오늘은 덜어낼수록 길이 보입니다. 끝내야 할 일을 조용히 마무리하면 마음의 자리가 넓어집니다.",
    relationshipPattern: "정직한 마무리와 선 긋기가 관계를 건강하게 지킵니다. 침묵보다 부드러운 정리가 좋습니다.",
    workPattern: "마감, 정산, 자료 폐기, 구조 개편, 오래된 일 정리에 잘 맞습니다.",
    advice: "오늘 끝낼 수 있는 작은 일을 하나 정리하세요.",
  },
  {
    index: 6,
    name: "Manik’",
    koreanName: "마닉",
    symbolTitle: "치유의 손",
    coreKeywords: ["치유", "기술", "헌신", "균형"],
    lightKeywords: ["섬세함", "도움", "손의 재능", "조율"],
    shadowKeywords: ["과한 책임", "자기 희생", "완벽주의"],
    personalitySummary: "마닉의 나왈은 손이 닿는 곳을 고르게 다듬습니다. 사람과 일을 회복시키는 능력이 있고, 조용한 헌신 안에서 신뢰를 얻습니다.",
    dailyMessage: "오늘은 고치는 일과 돌보는 일에 복이 머뭅니다. 작게 수선한 것이 큰 안정으로 이어집니다.",
    relationshipPattern: "필요한 도움을 잘 알아차리지만, 대신 짊어지는 습관은 내려놓을수록 관계가 편안해집니다.",
    workPattern: "디테일 점검, 케어 업무, 기술 연마, 품질 개선에 잘 맞습니다.",
    advice: "도움을 주기 전에 내가 감당할 수 있는 범위를 먼저 정하세요.",
  },
  {
    index: 7,
    name: "Lamat",
    koreanName: "라마트",
    symbolTitle: "별의 씨앗",
    coreKeywords: ["아름다움", "조화", "번영", "표현"],
    lightKeywords: ["매력", "예술성", "화합", "밝은 영향력"],
    shadowKeywords: ["과시", "분산", "인정 욕구"],
    personalitySummary: "라마트의 나왈은 빛나는 것을 세상에 나누는 사람입니다. 분위기를 아름답게 만들고, 흩어진 마음을 조화롭게 모읍니다.",
    dailyMessage: "오늘은 아름답게 정돈한 것이 힘이 됩니다. 말투, 옷차림, 공간의 빛을 조금 더 다듬어 보세요.",
    relationshipPattern: "칭찬과 호감 표현이 자연스럽습니다. 다만 모두에게 좋게 보이려 하기보다 진심을 선명히 하는 편이 좋습니다.",
    workPattern: "브랜딩, 디자인, 협업, 발표, 홍보에 리듬이 맞습니다.",
    advice: "보여 주고 싶은 것 하나를 정해 완성도를 높이세요.",
  },
  {
    index: 8,
    name: "Muluk",
    koreanName: "물룩",
    symbolTitle: "바치는 물",
    coreKeywords: ["정화", "감정", "헌신", "흐름"],
    lightKeywords: ["공감", "회복", "정직한 마음", "유연함"],
    shadowKeywords: ["감정 소모", "과한 양보", "흐름에 휩쓸림"],
    personalitySummary: "물룩의 나왈은 감정의 물길을 섬세하게 읽습니다. 마음을 씻어 내고 다시 흐르게 하는 힘이 있습니다.",
    dailyMessage: "오늘은 감정을 억누르기보다 깨끗하게 흘려보내기 좋습니다. 솔직한 표현이 마음을 맑게 합니다.",
    relationshipPattern: "상대의 마음을 잘 받아들이지만, 내 감정까지 물처럼 흩어지지 않도록 중심이 필요합니다.",
    workPattern: "조율, 상담, 정화가 필요한 업무, 막힌 소통 회복에 잘 맞습니다.",
    advice: "감정이 깊어질수록 사실과 느낌을 나누어 적어 보세요.",
  },
  {
    index: 9,
    name: "Ok",
    koreanName: "옥",
    symbolTitle: "충실한 길",
    coreKeywords: ["신뢰", "동행", "약속", "마음"],
    lightKeywords: ["충성심", "협력", "따뜻함", "관계 감각"],
    shadowKeywords: ["의존", "서운함", "기대 과잉"],
    personalitySummary: "옥의 나왈은 함께 걷는 길에서 힘을 얻습니다. 약속을 소중히 여기고, 믿을 수 있는 관계를 오래 지킵니다.",
    dailyMessage: "오늘은 신뢰를 확인하는 행동이 빛납니다. 작은 약속을 지키는 일이 운의 기둥이 됩니다.",
    relationshipPattern: "깊이 연결되면 오래 갑니다. 다만 기대를 말하지 않은 채 알아주길 바라면 마음이 무거워질 수 있습니다.",
    workPattern: "팀워크, 고객 관리, 파트너십, 약속 이행에 잘 맞습니다.",
    advice: "오늘 지킬 수 있는 약속만 선명하게 말하세요.",
  },
  {
    index: 10,
    name: "Chuwen",
    koreanName: "추웬",
    symbolTitle: "창조의 실",
    coreKeywords: ["창조", "놀이", "재치", "이야기"],
    lightKeywords: ["유머", "창의력", "손재주", "회복 탄력"],
    shadowKeywords: ["가벼움", "장난의 과함", "집중 이탈"],
    personalitySummary: "추웬의 나왈은 삶을 다시 엮는 이야기꾼입니다. 굳은 분위기를 풀고, 뜻밖의 방식으로 길을 만드는 재주가 있습니다.",
    dailyMessage: "오늘은 너무 엄숙하게 굳지 않아도 됩니다. 즐겁게 풀어낸 아이디어가 실마리가 됩니다.",
    relationshipPattern: "웃음과 가벼운 대화가 마음을 열지만, 진지한 순간에는 장난보다 진심이 필요합니다.",
    workPattern: "콘텐츠, 교육, 아이디어 회의, 문제를 다른 각도로 푸는 일에 잘 맞습니다.",
    advice: "막힌 일에 새로운 놀이 규칙을 하나 붙여 보세요.",
  },
  {
    index: 11,
    name: "Eb’",
    koreanName: "엡",
    symbolTitle: "사람의 길",
    coreKeywords: ["여정", "배움", "회복", "길"],
    lightKeywords: ["성실함", "경험 지혜", "겸손", "생활력"],
    shadowKeywords: ["자기 의심", "피로 누적", "길 잃음"],
    personalitySummary: "엡의 나왈은 삶을 긴 길로 이해합니다. 한 번에 빛나는 것보다 매일 쌓아 가는 힘으로 자신의 길을 만듭니다.",
    dailyMessage: "오늘은 한 걸음의 가치가 큽니다. 작게라도 이동하면 멈춘 마음이 다시 길을 찾습니다.",
    relationshipPattern: "함께 성장하는 관계에서 안정됩니다. 상대와 속도가 다를 때는 여정을 비교하지 않는 편이 좋습니다.",
    workPattern: "루틴 정비, 학습, 현장 경험, 건강한 습관 만들기에 잘 맞습니다.",
    advice: "오늘 해야 할 일을 세 칸으로 줄이고 첫 칸부터 걸어가세요.",
  },
  {
    index: 12,
    name: "B’en",
    koreanName: "벤",
    symbolTitle: "세워진 기둥",
    coreKeywords: ["방향", "성장", "기준", "가족"],
    lightKeywords: ["리더십", "책임감", "성장 지원", "원칙"],
    shadowKeywords: ["고집", "통제", "기대의 압박"],
    personalitySummary: "벤의 나왈은 길의 기둥을 세웁니다. 사람과 일의 방향을 잡아 주고, 성장할 수 있는 구조를 만드는 힘이 있습니다.",
    dailyMessage: "오늘은 기준을 세울수록 흐름이 안정됩니다. 애매한 약속보다 명확한 원칙이 마음을 편하게 합니다.",
    relationshipPattern: "보호하고 이끌려는 마음이 강합니다. 상대가 스스로 선택할 여지를 남기면 신뢰가 깊어집니다.",
    workPattern: "운영 기준 수립, 팀 리딩, 장기 계획, 가족과 기반을 돌보는 일에 잘 맞습니다.",
    advice: "오늘의 기준 하나를 짧게 정하고 주변과 공유하세요.",
  },
  {
    index: 13,
    name: "Ix",
    koreanName: "이쉬",
    symbolTitle: "보이지 않는 숲",
    coreKeywords: ["직관", "신비", "보호", "자연"],
    lightKeywords: ["감응력", "깊은 관찰", "보호 본능", "치유"],
    shadowKeywords: ["비밀주의", "의심", "감정 방어"],
    personalitySummary: "이쉬의 나왈은 보이지 않는 기척을 감지합니다. 조용히 관찰하며, 자연스럽게 사람과 공간을 보호하는 힘이 있습니다.",
    dailyMessage: "오늘은 눈에 보이는 정보보다 분위기의 결을 살피기 좋습니다. 조용한 직감이 길을 비춥니다.",
    relationshipPattern: "깊이 믿기 전까지 마음을 쉽게 열지 않습니다. 의심보다 확인의 대화가 관계를 부드럽게 합니다.",
    workPattern: "리스크 감지, 상담, 치유, 공간 관리, 깊은 리서치에 잘 맞습니다.",
    advice: "직감이 올라오면 바로 단정하지 말고 근거를 하나 더 확인하세요.",
  },
  {
    index: 14,
    name: "Men",
    koreanName: "멘",
    symbolTitle: "높은 시야",
    coreKeywords: ["비전", "자유", "통찰", "전망"],
    lightKeywords: ["큰 그림", "판단력", "자유로운 사고", "전략"],
    shadowKeywords: ["거리감", "현실 회피", "높은 기준"],
    personalitySummary: "멘의 나왈은 멀리 보는 눈을 가졌습니다. 작은 사건보다 전체의 방향을 읽고, 더 넓은 가능성을 찾습니다.",
    dailyMessage: "오늘은 한 발 물러나 전체 지도를 보는 것이 좋습니다. 높은 시야가 복잡한 문제를 단순하게 만듭니다.",
    relationshipPattern: "자유와 존중이 있어야 편안합니다. 차갑게 보일 때는 마음이 아니라 거리가 필요했을 수 있습니다.",
    workPattern: "전략, 기획, 장기 전망, 시장 읽기, 이동이 필요한 일에 잘 맞습니다.",
    advice: "가까운 걱정에서 잠시 떨어져 한 달 뒤의 그림을 그려 보세요.",
  },
  {
    index: 15,
    name: "Kib’",
    koreanName: "킵",
    symbolTitle: "맑은 지혜",
    coreKeywords: ["정화", "지혜", "용서", "판단"],
    lightKeywords: ["분별력", "성찰", "정리", "품위"],
    shadowKeywords: ["비판", "죄책감", "과거 집착"],
    personalitySummary: "킵의 나왈은 마음의 먼지를 털어 내며 지혜를 얻습니다. 경험을 그냥 지나치지 않고, 더 맑은 판단으로 바꾸는 힘이 있습니다.",
    dailyMessage: "오늘은 마음을 흐리게 하는 생각을 정리하기 좋습니다. 용서와 분별이 함께 있을 때 길이 맑아집니다.",
    relationshipPattern: "상대의 태도를 예리하게 봅니다. 판단이 빠를수록 따뜻한 여지를 남기는 편이 좋습니다.",
    workPattern: "검토, 감사, 정리, 윤리적 판단, 지식 정리에 잘 맞습니다.",
    advice: "과거의 실수 하나를 교훈으로 바꾸고 더 끌고 가지 마세요.",
  },
  {
    index: 16,
    name: "Kab’an",
    koreanName: "카반",
    symbolTitle: "움직이는 땅",
    coreKeywords: ["변화", "지성", "흐름", "동기"],
    lightKeywords: ["학습", "분석", "전환 감각", "현실 적응"],
    shadowKeywords: ["생각 과다", "불안정", "변화 피로"],
    personalitySummary: "카반의 나왈은 땅이 움직이는 신호를 읽습니다. 현실의 변화를 빠르게 감지하고, 배움을 통해 방향을 갱신합니다.",
    dailyMessage: "오늘은 움직이는 흐름을 억지로 멈추기보다 읽어야 합니다. 바뀐 조건을 인정하면 길이 다시 열립니다.",
    relationshipPattern: "대화의 논리와 현실 감각을 중시합니다. 마음을 설명하려 할수록 먼저 감정을 인정하면 편해집니다.",
    workPattern: "분석, 데이터 정리, 변경 대응, 학습 기반 프로젝트에 잘 맞습니다.",
    advice: "바뀐 사실 세 가지를 적고, 오늘 조정할 한 가지를 고르세요.",
  },
  {
    index: 17,
    name: "Etz’nab’",
    koreanName: "에츠납",
    symbolTitle: "거울의 칼",
    coreKeywords: ["진실", "반사", "분별", "절단"],
    lightKeywords: ["명확함", "정직", "결단", "통찰"],
    shadowKeywords: ["날카로움", "냉정함", "상처 주는 말"],
    personalitySummary: "에츠납의 나왈은 흐린 것을 선명하게 비춥니다. 진실을 피하지 않는 힘이 있고, 필요한 결단 앞에서 강해집니다.",
    dailyMessage: "오늘은 진실을 부드럽게 마주하기 좋습니다. 선명함은 차가움이 아니라 정돈된 마음에서 나옵니다.",
    relationshipPattern: "거짓이나 애매함에 예민합니다. 솔직함을 전할 때 말의 결을 다듬으면 신뢰가 깊어집니다.",
    workPattern: "문제 진단, 계약 검토, 기준 정리, 결단이 필요한 일에 잘 맞습니다.",
    advice: "잘라내야 할 것과 더 살릴 것을 한 줄씩 나누어 적으세요.",
  },
  {
    index: 18,
    name: "Kawak",
    koreanName: "카왁",
    symbolTitle: "비와 천둥",
    coreKeywords: ["정화", "감정 해방", "공동체", "회복"],
    lightKeywords: ["강한 회복", "보호", "공동체 감각", "감정 정화"],
    shadowKeywords: ["감정 폭풍", "과민함", "혼란"],
    personalitySummary: "카왁의 나왈은 비와 천둥처럼 막힌 공기를 씻어 냅니다. 감정이 깊고, 공동체 안에서 회복의 힘을 일으킵니다.",
    dailyMessage: "오늘은 쌓인 감정이 비처럼 내려가야 합니다. 안전한 방식으로 털어내면 공기가 맑아집니다.",
    relationshipPattern: "함께 울고 웃는 관계에서 깊어집니다. 다만 감정의 파도가 클 때는 잠시 간격을 두는 편이 좋습니다.",
    workPattern: "팀 회복, 이슈 정리, 보호가 필요한 업무, 분위기 전환에 잘 맞습니다.",
    advice: "감정이 커지면 바로 결론을 내리지 말고 시간을 두고 다시 보세요.",
  },
  {
    index: 19,
    name: "Ajaw",
    koreanName: "아하우",
    symbolTitle: "태양의 문",
    coreKeywords: ["완성", "빛", "존엄", "통합"],
    lightKeywords: ["존재감", "통합력", "따뜻한 리더십", "명예"],
    shadowKeywords: ["자존심", "부담감", "시선 의식"],
    personalitySummary: "아하우의 나왈은 빛을 향해 서는 힘입니다. 흩어진 경험을 하나로 모으고, 자신의 존재감으로 주변을 밝힙니다.",
    dailyMessage: "오늘은 숨기기보다 밝히는 편이 좋습니다. 진심이 선명할수록 필요한 인정이 자연스럽게 따라옵니다.",
    relationshipPattern: "존중받고 존중하는 관계에서 빛납니다. 자존심이 앞설 때는 따뜻한 인정부터 건네면 흐름이 풀립니다.",
    workPattern: "마무리 발표, 공개, 리더십, 성과 정리에 잘 맞습니다.",
    advice: "오늘 완성된 것 하나를 인정하고 다음 주기의 문을 준비하세요.",
  },
];

export const MAYA_TONES: MayaTone[] = [
  {
    number: 1,
    title: "시작의 씨앗",
    keywords: ["시작", "씨앗", "발의"],
    meaning: "1수는 아직 작지만 분명한 시작의 점입니다. 방향을 완전히 증명하기보다 첫 의도를 세우는 흐름입니다.",
    advice: "오늘의 의도를 한 문장으로 정하세요.",
  },
  {
    number: 2,
    title: "선택의 균형",
    keywords: ["선택", "균형", "분리"],
    meaning: "2수는 두 갈래를 마주하며 균형을 찾는 단계입니다. 차이를 인정할수록 선택이 맑아집니다.",
    advice: "비교보다 기준을 먼저 세우세요.",
  },
  {
    number: 3,
    title: "첫 움직임",
    keywords: ["움직임", "실험", "첫 실행"],
    meaning: "3수는 생각이 몸을 얻는 흐름입니다. 완벽한 준비보다 작게 움직이는 실험이 길을 엽니다.",
    advice: "30분 안에 가능한 첫 실행을 남기세요.",
  },
  {
    number: 4,
    title: "안정의 구조",
    keywords: ["구조", "안정", "기준"],
    meaning: "4수는 흩어진 것을 네 방향으로 세우는 단계입니다. 기준과 루틴이 운을 받치는 바닥이 됩니다.",
    advice: "오늘의 규칙을 단순하게 정리하세요.",
  },
  {
    number: 5,
    title: "중심의 추진력",
    keywords: ["중심", "추진력", "집중"],
    meaning: "5수는 가운데 힘이 살아나는 흐름입니다. 무엇에 힘을 실을지 정하면 일이 빠르게 움직입니다.",
    advice: "가장 중요한 한 가지에 에너지를 모으세요.",
  },
  {
    number: 6,
    title: "조율의 흐름",
    keywords: ["조율", "관계", "흐름"],
    meaning: "6수는 관계와 리듬을 맞추는 단계입니다. 혼자 밀기보다 흐름에 맞춘 움직임이 편안합니다.",
    advice: "상대의 속도와 내 속도를 함께 살피세요.",
  },
  {
    number: 7,
    title: "거울의 전환점",
    keywords: ["전환점", "거울", "균형"],
    meaning: "7수는 한가운데에서 흐름을 비춰 보는 자리입니다. 선택의 의미를 다시 확인하면 방향이 선명해집니다.",
    advice: "잠시 멈추고 지금의 선택이 나를 어디로 데려가는지 보세요.",
  },
  {
    number: 8,
    title: "정렬의 책임",
    keywords: ["정렬", "책임", "질서"],
    meaning: "8수는 흐름을 바르게 세우는 단계입니다. 마음과 행동이 같은 방향으로 놓일 때 신뢰가 커집니다.",
    advice: "말한 것과 행동한 것을 맞추는 데 집중하세요.",
  },
  {
    number: 9,
    title: "성장의 파동",
    keywords: ["확장", "성장", "감정의 파동"],
    meaning: "9수는 안쪽에서 바깥으로 넓어지는 흐름입니다. 감정의 파동을 통해 더 큰 성장을 알아차립니다.",
    advice: "마음이 흔들린 지점에서 필요한 배움을 찾으세요.",
  },
  {
    number: 10,
    title: "현실화의 형태",
    keywords: ["결과", "형태", "현실화"],
    meaning: "10수는 보이지 않던 것이 형태를 얻는 단계입니다. 결과를 통해 다음 조정점도 함께 드러납니다.",
    advice: "완성된 형태를 확인하고 보완할 한 곳만 고르세요.",
  },
  {
    number: 11,
    title: "비움의 정화",
    keywords: ["해체", "정화", "비움"],
    meaning: "11수는 낡은 구조를 풀어내는 흐름입니다. 덜어내야 새 질서가 들어올 자리가 생깁니다.",
    advice: "더 하지 말고 하나를 덜어내세요.",
  },
  {
    number: 12,
    title: "이해의 통합",
    keywords: ["이해", "통합", "공유"],
    meaning: "12수는 경험을 이해로 묶는 단계입니다. 혼자만의 깨달음이 나눌 수 있는 지혜로 바뀝니다.",
    advice: "배운 것을 누군가에게 쉽게 설명해 보세요.",
  },
  {
    number: 13,
    title: "완성과 다음 주기",
    keywords: ["완성", "상승", "다음 주기"],
    meaning: "13수는 한 주기의 문이 닫히고 다음 문이 열리는 자리입니다. 마무리와 새로운 상승이 함께 흐릅니다.",
    advice: "완성된 것을 인정하고 다음 시작을 위한 여백을 남기세요.",
  },
];
