import type {LoadingLocale} from '@/constants/loadingMessages';
import {localizedTier} from '@/app/yeongnyangi/_lib/consultation-locale-copy';

const COPY={
  "ko": {
    "scope": "{fish} 상담 전용 · {days}일 · 총 {total}회",
    "title": "영냥이 전용 이용권",
    "intro": "연이가 단골을 위한 생선 세트를 마련했어요. 선택한 생선 상담에만 1회씩 사용할 수 있어요. 다른 생선과 융합 상담에는 사용할 수 없어요.",
    "owned": "내 전용 이용권",
    "empty": "보유한 전용 이용권이 없어요.",
    "unavailable": "보유 상태를 확인하지 못했어요. 다시 확인해 주세요.",
    "loading": "이용권을 확인하고 있어요.",
    "retry": "다시 확인",
    "login": "로그인 후 확인하기",
    "select": "세트 선택",
    "buy": "단건 결제로 구매",
    "consent": "이용 조건과 환불 정책을 확인했어요.",
    "confirm": "결제를 확인하고 있어요. 같은 주문으로 다시 확인할 수 있어요.",
    "recheck": "결제 결과 확인",
    "complete": "전용 이용권이 준비됐어요.",
    "remaining": "{total}회 중 {remaining}회 남음",
    "expires": "{date}까지",
    "validity": "구매 후 {days}일",
    "eligible": "사용 가능한 상담",
    "use": "1회 사용해 상담 시작하기",
    "working": "이용권 사용을 확인하고 있어요.",
    "more": "보유 이용권 더 보기",
    "webOnly": "앱 판매를 준비하고 있어요. 웹에서 구매 내용을 확인해 주세요.",
    "savings": "전체 {total}회 사용 시 단건 합계보다 {amount} 절약",
    "checkout": "이 상담에 쓸 전용 이용권",
    "inactive": "현재 사용할 수 없는 이용권이에요.",
    "emptyCatalog": "판매할 세트를 준비하고 있어요. 기존 보유 이용권은 아래에서 확인할 수 있어요.",
    "chooseConsultation": "상담 고르기",
    "selfPurchase": "내가 사용",
    "giftPurchase": "선물하기",
    "giftPrepare": "마음을 담아 선물 준비하기",
    "senderName": "보내는 이름 (선택)",
    "recipientName": "받는 이름 (선택)",
    "giftMessage": "선물 메시지 (선택)",
    "giftNotice": "받는 분의 계정 정보 없이 선물 링크로 보낼 수 있어요. 링크를 가진 한 계정이 수령하므로 소중한 분께만 보내주세요.",
    "giftBox": "보낸 선물 · 받은 선물",
    "giftUsagePeriod": "수령 후 {days}일 동안 이용할 수 있어요.",
    "giftTotal": "같은 생선 상담 {total}회",
    "giftClaimSuccess": "선물을 받았어요. 내 영냥이 전용 이용권에서 잔여 횟수를 확인해 주세요.",
    "giftViewWallet": "내 영냥이 전용 이용권 보기",
    "giftComplete": "선물 결제 확인 후 링크를 준비해요.",
    "durationLabel": "이용 기간 {days}일",
    "previewSet": "{fish} 세트",
    "packName": "{fish} 세트 {total}회",
    "resumePayment": "기존 주문 결제 이어가기",
    "resumeNotice": "먼저 결제 상태를 확인해요. 아직 결제되지 않은 같은 주문만 단건 결제로 이어가요.",
    "resumeConsent": "같은 주문의 이용 조건과 환불 정책을 다시 확인하고 동의해요.",
    "resumeAtShop": "상점에서 기존 주문 이어가기",
    "allianceKicker": "영냥이 × 꽃돼지 제휴",
    "moonTitle": "월정석으로도 상담할 수 있어요",
    "moonUsable": "꿀꿀 사주에서 받은 월정석을 영냥이 상담 결제에 쓸 수 있어요.",
    "moonExample": "예: {fish} {system} 상담 {price} = 월정석 {stones}개",
    "wonOnly": "전용 횟수권은 단건 결제로 구매해요. 해외에서는 PayPal로 USD 금액을 확인한 뒤 결제할 수 있어요. 횟수권 구매에는 월정석을 사용할 수 없어요.",
    "recommend": "영냥이 추천",
    "cardSubtitle": "원화 단건 결제로 구매하는 {days}일 세트",
    "perUse": "회당 {amount}",
    "buyCta": "구매하기 →",
    "giftCta": "🎁 선물하기",
    "giftPromo": "소중한 사람에게 선물해보세요",
    "payTitle": "영냥이 전용 이용권 결제 방식 선택",
    "conditionsTitle": "{days}일 세트 조건",
    "selfActivation": "결제 확인 즉시 내 전용 이용권에 지급되며, 지급 시각부터 {days}일간 사용할 수 있어요.",
    "refundLink": "자세한 환불 규정 보기",
    "giftGuidanceSummary": "선물 수령·이용·환불 안내",
    "giftGuidance": "결제 확인 후 선물 링크를 보내세요. 로그인한 한 계정이 수령할 수 있으며 본인 수령도 가능합니다. 수령 기한은 구매 후 1년입니다. 이용 기간은 수령 시 시작합니다. 미수령 선물의 환불은 기존 정책에 따라 확인하며, 수령 후에는 운영자 확인이 필요합니다. 수령 기한 만료만으로 환급 권리가 소멸하지 않습니다.",
    "payPrompt": "결제 수단",
    "cardPay": "카드 결제",
    "contentValue": "콘텐츠 가치는 원화로 표시되며 보안 결제창에서 결제합니다.",
    "close": "닫기",
    "notPaid": "결제가 완료되지 않은 주문이에요. 이용권을 다시 골라 주세요.",
    "passesTitle": "내 이용권",
    "flowerPass": "🌸 꽃돼지 달빛 이용권",
    "packPass": "영냥이 전용 이용권",
    "applied": "적용 중",
    "flowerNone": "보유한 달빛 이용권이 없어요.",
    "flowerBrowse": "달빛 이용권 보기",
    "packNone": "보유한 영냥이 세트가 없어요.",
    "packBrowse": "영냥이 세트 보기",
    "packOthers": "외 {count}개 세트 보유",
    "bothApplied": "두 이용권은 따로 적용돼요. 상담 한 건에는 하나만 차감돼요.",
    "ownedBadge": "보유 중 · {remaining}회 남음",
    "appliedDone": "{name} 적용 완료",
    "goConsult": "영냥이 상담하러 가기",
    "viewOwned": "보유 목록 보기",
    "flowerFamilyApply": "결제 방식 선택에서 달빛 이용권으로 적용할 수 있어요.",
    "flowerFamilyOnly": "이 상담은 Family 달빛 이용권부터 적용돼요.",
    "packUsable": "이 상담에 사용할 수 있어요.",
    "packApplied": "적용됨 · {remaining}회 남음"
  },
  "en": {
    "scope": "{fish} consultations only · {days} days · {total} uses",
    "title": "Yeongnyangi consultation passes",
    "intro": "Yeoni has prepared fish sets for returning guests. Each use opens one consultation with the same fish tier.",
    "owned": "My consultation passes",
    "empty": "You have no consultation passes.",
    "unavailable": "We could not confirm your passes. Please check again.",
    "loading": "Checking passes…",
    "retry": "Check again",
    "login": "Sign in to check",
    "select": "Select set",
    "buy": "Buy with one-time payment",
    "consent": "I have read the terms and refund policy.",
    "confirm": "Checking payment. You can check the same order again.",
    "recheck": "Check payment",
    "complete": "Your consultation pass is ready.",
    "remaining": "{remaining} of {total} uses left",
    "expires": "Until {date}",
    "validity": "{days} days after purchase",
    "eligible": "Eligible consultations",
    "use": "Use once and start",
    "working": "Confirming this use…",
    "more": "Show more passes",
    "webOnly": "App sales are being prepared. Check purchase details on the web.",
    "savings": "Using all {total} consultations saves {amount} versus single purchases",
    "checkout": "A pass for this consultation",
    "inactive": "This pass is currently unavailable.",
    "emptyCatalog": "Sets are being prepared for sale. Existing passes are listed below.",
    "chooseConsultation": "Choose a consultation",
    "selfPurchase": "For myself",
    "giftPurchase": "Give as a gift",
    "giftPrepare": "Prepare a thoughtful gift",
    "senderName": "Sender name (optional)",
    "recipientName": "Recipient name (optional)",
    "giftMessage": "Gift message (optional)",
    "giftNotice": "No recipient account details are needed. One account with the link can claim the gift, so share it only with your recipient.",
    "giftBox": "Sent and received gifts",
    "giftUsagePeriod": "Valid for {days} days after claiming.",
    "giftTotal": "{total} consultations of the same fish tier",
    "giftClaimSuccess": "Gift received. Check your remaining uses in your Yeongnyangi passes.",
    "giftViewWallet": "View my Yeongnyangi passes",
    "giftComplete": "Your gift link is prepared after payment is verified.",
    "durationLabel": "{days}-day usage period",
    "previewSet": "{fish} set",
    "packName": "{total}-use {fish} set",
    "resumePayment": "Continue this order payment",
    "resumeNotice": "We check payment first. Only the same unpaid order can continue with a one-time payment.",
    "resumeConsent": "I have reviewed and agree again to this order’s terms and refund policy.",
    "resumeAtShop": "Continue this order in the shop",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Buy reading packs with a one-time payment. Outside Korea, use PayPal and review the USD total before approving. Moonstones cannot be used to buy packs.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "My passes",
    "flowerPass": "🌸 Flower Pig Moonlight Pass",
    "packPass": "Yeongnyangi pass",
    "applied": "Active",
    "flowerNone": "No Moonlight Pass yet.",
    "flowerBrowse": "See Moonlight Passes",
    "packNone": "No Yeongnyangi pack yet.",
    "packBrowse": "See Yeongnyangi packs",
    "packOthers": "+{count} more packs",
    "bothApplied": "Both passes apply separately. Each consultation uses only one.",
    "ownedBadge": "Owned · {remaining} left",
    "appliedDone": "{name} applied",
    "goConsult": "Start a Yeongnyangi consultation",
    "viewOwned": "View my packs",
    "flowerFamilyApply": "You can apply your Moonlight Pass in the payment options.",
    "flowerFamilyOnly": "This consultation is covered from the Family Moonlight Pass.",
    "packUsable": "Usable for this consultation.",
    "packApplied": "Applied · {remaining} left"
  },
  "ja": {
    "scope": "{fish}の相談専用 · {days}日 · 全{total}回",
    "title": "ヨンニャンイ専用利用券",
    "intro": "ヨニが常連さん向けに魚のセットを用意しました。同じ魚の相談に1回ずつ使えます。",
    "owned": "保有している専用利用券",
    "empty": "専用利用券はありません。",
    "unavailable": "利用券を確認できませんでした。もう一度ご確認ください。",
    "loading": "利用券を確認中です。",
    "retry": "再確認",
    "login": "ログインして確認",
    "select": "セットを選択",
    "buy": "単品決済で購入",
    "consent": "利用条件と返金ポリシーを確認しました。",
    "confirm": "決済を確認中です。同じ注文で再確認できます。",
    "recheck": "決済結果を確認",
    "complete": "専用利用券が用意できました。",
    "remaining": "全{total}回中、残り{remaining}回",
    "expires": "{date}まで",
    "validity": "購入後{days}日間",
    "eligible": "利用できる相談",
    "use": "1回使って相談を始める",
    "working": "利用を確認中です。",
    "more": "利用券をもっと見る",
    "webOnly": "アプリ販売は準備中です。Webで購入内容をご確認ください。",
    "savings": "全{total}回利用すると単品購入の合計より{amount}お得",
    "checkout": "この相談で使う専用利用券",
    "inactive": "現在利用できない利用券です。",
    "emptyCatalog": "販売セットを準備中です。保有している利用券は下で確認できます。",
    "chooseConsultation": "相談を選ぶ",
    "selfPurchase": "自分で使う",
    "giftPurchase": "ギフトにする",
    "giftPrepare": "気持ちを込めて贈る",
    "senderName": "送り主の名前（任意）",
    "recipientName": "受取人の名前（任意）",
    "giftMessage": "メッセージ（任意）",
    "giftNotice": "受取人のアカウント情報は不要です。リンクを持つ1アカウントが受け取れるため、贈る相手にだけ送ってください。",
    "giftBox": "送ったギフト・受け取ったギフト",
    "giftUsagePeriod": "受け取り後{days}日間利用できます。",
    "giftTotal": "同じ魚の相談{total}回",
    "giftClaimSuccess": "ギフトを受け取りました。ヨンニャンイ専用利用券で残り回数を確認できます。",
    "giftViewWallet": "ヨンニャンイ専用利用券を見る",
    "giftComplete": "決済確認後にギフトリンクを準備します。",
    "durationLabel": "利用期間{days}日",
    "previewSet": "{fish}セット",
    "packName": "{fish}セット {total}回",
    "resumePayment": "同じ注文の支払いを続ける",
    "resumeNotice": "先に決済状況を確認します。未払いの同じ注文のみ、都度払いで続けられます。",
    "resumeConsent": "この注文の利用条件と返金規定を再確認し、同意します。",
    "resumeAtShop": "ショップで同じ注文を続ける",
    "allianceKicker": "ヨンニャンイ × 花豚 提携",
    "moonTitle": "月精石でも相談できます",
    "moonUsable": "クルクル運勢でもらった月精石をヨンニャンイの相談に使えます。",
    "moonExample": "例: {fish} {system}相談 {price} = 月精石 {stones}個",
    "wonOnly": "回数券は都度払いで購入できます。韓国外ではPayPalで米ドルの総額を確認してからお支払いください。回数券の購入に月光石は使えません。",
    "recommend": "ヨンニャンイのおすすめ",
    "cardSubtitle": "ウォンの単発決済で購入する{days}日間セット",
    "perUse": "1回あたり{amount}",
    "buyCta": "購入する →",
    "giftCta": "🎁 ギフトにする",
    "giftPromo": "大切な人に贈ってみませんか",
    "payTitle": "専用セットの決済方法を選択",
    "conditionsTitle": "{days}日間セットの条件",
    "selfActivation": "決済確認後すぐに専用利用券に付与され、付与時点から{days}日間使えます。",
    "refundLink": "返金規定の詳細を見る",
    "giftGuidanceSummary": "ギフトの受け取り・利用・返金について",
    "giftGuidance": "決済確認後にギフトリンクを送ってください。ログイン中の1アカウントが受け取れ、本人による受け取りも可能です。受け取り期限は購入後1年です。利用期間は受け取り時に開始します。未受領のギフトの返金は既存のポリシーに従って確認し、受け取り後は運営者の確認が必要です。受け取り期限の満了だけでは返金請求権は消滅しません。",
    "payPrompt": "決済手段",
    "cardPay": "カード決済",
    "contentValue": "価格はウォンで表示され、安全な決済画面で支払います。",
    "close": "閉じる",
    "notPaid": "この注文は決済が完了していません。もう一度利用券をお選びください。",
    "passesTitle": "マイ利用券",
    "flowerPass": "🌸 花豚の月光利用券",
    "packPass": "ヨンニャンイ専用利用券",
    "applied": "適用中",
    "flowerNone": "月光利用券はまだありません。",
    "flowerBrowse": "月光利用券を見る",
    "packNone": "ヨンニャンイのセットはまだありません。",
    "packBrowse": "ヨンニャンイのセットを見る",
    "packOthers": "ほか{count}セット保有",
    "bothApplied": "2つの利用券は別々に適用されます。1回の相談で使うのはどちらか1つだけです。",
    "ownedBadge": "保有中 · 残り{remaining}回",
    "appliedDone": "{name} 適用完了",
    "goConsult": "ヨンニャンイに相談する",
    "viewOwned": "保有一覧を見る",
    "flowerFamilyApply": "決済方法の選択で月光利用券を適用できます。",
    "flowerFamilyOnly": "この相談はFamily月光利用券から適用されます。",
    "packUsable": "この相談に使えます。",
    "packApplied": "適用済み · 残り{remaining}回"
  },
  "zh-CN": {
    "scope": "仅限{fish}咨询 · {days}天 · 共{total}次",
    "title": "灵猫专用咨询券",
    "intro": "妍伊为老朋友准备了鱼套餐。同一种鱼的咨询，每次使用1次。",
    "owned": "我的专用咨询券",
    "empty": "暂无专用咨询券。",
    "unavailable": "未能确认咨询券，请重新查询。",
    "loading": "正在查询咨询券。",
    "retry": "重新查询",
    "login": "登录后查询",
    "select": "选择套餐",
    "buy": "单次付款购买",
    "consent": "我已阅读使用条款和退款政策。",
    "confirm": "正在确认付款，可重新查询同一订单。",
    "recheck": "查询付款结果",
    "complete": "专用咨询券已准备好。",
    "remaining": "共{total}次，剩余{remaining}次",
    "expires": "有效至{date}",
    "validity": "购买后{days}天",
    "eligible": "可用咨询",
    "use": "使用1次并开始咨询",
    "working": "正在确认使用记录。",
    "more": "查看更多咨询券",
    "webOnly": "应用内销售准备中，请在网页查看购买详情。",
    "savings": "用完全部{total}次，比逐次购买合计节省{amount}",
    "checkout": "本次咨询可用的专用券",
    "inactive": "此券目前不可用。",
    "emptyCatalog": "正在准备销售套餐，已有咨询券可在下方查询。",
    "chooseConsultation": "选择咨询",
    "selfPurchase": "自己使用",
    "giftPurchase": "赠送礼物",
    "giftPrepare": "准备一份心意",
    "senderName": "赠送人姓名（选填）",
    "recipientName": "接收人姓名（选填）",
    "giftMessage": "礼物留言（选填）",
    "giftNotice": "无需接收人的账号信息。持有链接的一个账号可领取，请只发给想赠送的人。",
    "giftBox": "送出与收到的礼物",
    "giftUsagePeriod": "领取后可使用{days}天。",
    "giftTotal": "同一鱼种咨询{total}次",
    "giftClaimSuccess": "礼物已领取。请在灵喵专用咨询券中查看剩余次数。",
    "giftViewWallet": "查看我的灵喵专用咨询券",
    "giftComplete": "付款验证后准备礼物链接。",
    "durationLabel": "使用期{days}天",
    "previewSet": "{fish}套餐",
    "packName": "{fish}套餐 {total}次",
    "resumePayment": "继续支付原订单",
    "resumeNotice": "先确认支付状态。仅未付款的同一订单可继续单次付款。",
    "resumeConsent": "我已重新阅读并同意此订单的使用条款和退款政策。",
    "resumeAtShop": "在商店继续原订单",
    "allianceKicker": "灵猫 × 花猪 合作",
    "moonTitle": "也可以用月精石咨询",
    "moonUsable": "在咕噜运势获得的月精石可用于灵猫咨询。",
    "moonExample": "例：{fish}{system}咨询 {price} = 月精石 {stones} 个",
    "wonOnly": "次数券支持单次付款购买。韩国境外请通过PayPal确认美元总额后支付。购买次数券不能使用月光石。",
    "recommend": "灵猫推荐",
    "cardSubtitle": "以韩元单次付款购买的{days}天套组",
    "perUse": "每次 {amount}",
    "buyCta": "购买 →",
    "giftCta": "🎁 赠送礼物",
    "giftPromo": "送给重要的人吧",
    "payTitle": "选择专用套组的付款方式",
    "conditionsTitle": "{days}天套组条件",
    "selfActivation": "付款确认后立即发放到你的专用咨询券，自发放时起{days}天内可用。",
    "refundLink": "查看完整退款规定",
    "giftGuidanceSummary": "礼物领取·使用·退款说明",
    "giftGuidance": "付款确认后请发送礼物链接。仅限已登录的一个账号领取，也可以本人领取。领取期限为购买后1年。使用期限自领取时开始。未领取礼物的退款按现有政策处理，领取后需经运营方确认。领取期限届满本身并不会使退款权利消灭。",
    "payPrompt": "付款方式",
    "cardPay": "银行卡付款",
    "contentValue": "价格以韩元显示，并在安全付款窗口中支付。",
    "close": "关闭",
    "notPaid": "该订单未完成付款，请重新选择咨询券。",
    "passesTitle": "我的使用券",
    "flowerPass": "🌸 花猪月光通行证",
    "packPass": "灵猫专用咨询券",
    "applied": "使用中",
    "flowerNone": "还没有月光通行证。",
    "flowerBrowse": "查看月光通行证",
    "packNone": "还没有灵猫套装。",
    "packBrowse": "查看灵猫套装",
    "packOthers": "另有{count}个套装",
    "bothApplied": "两种使用券分别生效。每次咨询只扣除其中一种。",
    "ownedBadge": "已持有 · 剩余{remaining}次",
    "appliedDone": "{name} 已生效",
    "goConsult": "去找灵猫咨询",
    "viewOwned": "查看持有列表",
    "flowerFamilyApply": "可在选择支付方式时使用月光通行证。",
    "flowerFamilyOnly": "此咨询需Family月光通行证才可使用。",
    "packUsable": "可用于本次咨询。",
    "packApplied": "已使用 · 剩余{remaining}次"
  },
  "zh-TW": {
    "scope": "僅限{fish}諮詢 · {days}天 · 共{total}次",
    "title": "靈貓專用諮詢券",
    "intro": "妍伊為老朋友準備了魚套餐。同一種魚的諮詢，每次使用1次。",
    "owned": "我的專用諮詢券",
    "empty": "目前沒有專用諮詢券。",
    "unavailable": "未能確認諮詢券，請重新查詢。",
    "loading": "正在查詢諮詢券。",
    "retry": "重新查詢",
    "login": "登入後查詢",
    "select": "選擇套餐",
    "buy": "單次付款購買",
    "consent": "我已閱讀使用條款與退款政策。",
    "confirm": "正在確認付款，可重新查詢同一筆訂單。",
    "recheck": "查詢付款結果",
    "complete": "專用諮詢券已準備好。",
    "remaining": "共{total}次，剩餘{remaining}次",
    "expires": "有效至{date}",
    "validity": "購買後{days}天",
    "eligible": "可用諮詢",
    "use": "使用1次並開始諮詢",
    "working": "正在確認使用紀錄。",
    "more": "查看更多諮詢券",
    "webOnly": "應用程式內銷售準備中，請在網頁查看購買詳情。",
    "savings": "用完全部{total}次，比逐次購買合計節省{amount}",
    "checkout": "本次諮詢可用的專用券",
    "inactive": "此券目前無法使用。",
    "emptyCatalog": "正在準備銷售套餐，已有諮詢券可在下方查詢。",
    "chooseConsultation": "選擇諮詢",
    "selfPurchase": "自己使用",
    "giftPurchase": "贈送禮物",
    "giftPrepare": "準備一份心意",
    "senderName": "贈送人姓名（選填）",
    "recipientName": "接收人姓名（選填）",
    "giftMessage": "禮物留言（選填）",
    "giftNotice": "無需接收人的帳號資訊。持有連結的一個帳號可領取，請只傳給想贈送的人。",
    "giftBox": "送出與收到的禮物",
    "giftUsagePeriod": "領取後可使用{days}天。",
    "giftTotal": "同一魚種諮詢{total}次",
    "giftClaimSuccess": "禮物已領取。請在靈喵專用諮詢券中查看剩餘次數。",
    "giftViewWallet": "查看我的靈喵專用諮詢券",
    "giftComplete": "付款驗證後準備禮物連結。",
    "durationLabel": "使用期{days}天",
    "previewSet": "{fish}套餐",
    "packName": "{fish}套餐 {total}次",
    "resumePayment": "繼續支付原訂單",
    "resumeNotice": "先確認付款狀態。僅未付款的同一訂單可繼續單次付款。",
    "resumeConsent": "我已重新閱讀並同意此訂單的使用條款與退款政策。",
    "resumeAtShop": "在商店繼續原訂單",
    "allianceKicker": "靈貓 × 花豬 合作",
    "moonTitle": "也可以用月精石諮詢",
    "moonUsable": "在咕嚕運勢獲得的月精石可用於靈貓諮詢。",
    "moonExample": "例：{fish}{system}諮詢 {price} = 月精石 {stones} 個",
    "wonOnly": "次數券支援單次付款購買。韓國境外請透過PayPal確認美元總額後付款。購買次數券不能使用月光石。",
    "recommend": "靈貓推薦",
    "cardSubtitle": "以韓元單次付款購買的{days}天套組",
    "perUse": "每次 {amount}",
    "buyCta": "購買 →",
    "giftCta": "🎁 贈送禮物",
    "giftPromo": "送給重要的人吧",
    "payTitle": "選擇專用套組的付款方式",
    "conditionsTitle": "{days}天套組條件",
    "selfActivation": "付款確認後立即發放到你的專用諮詢券，自發放時起{days}天內可用。",
    "refundLink": "查看完整退款規定",
    "giftGuidanceSummary": "禮物領取·使用·退款說明",
    "giftGuidance": "付款確認後請傳送禮物連結。僅限已登入的一個帳號領取，本人領取也可以。領取期限為購買後1年。使用期限自領取時開始。未領取禮物的退款依現行政策處理，領取後需經營運方確認。領取期限屆滿本身並不會使退款權利消滅。",
    "payPrompt": "付款方式",
    "cardPay": "信用卡付款",
    "contentValue": "價格以韓元顯示，並在安全付款視窗中支付。",
    "close": "關閉",
    "notPaid": "此訂單尚未完成付款，請重新選擇諮詢券。",
    "passesTitle": "我的使用券",
    "flowerPass": "🌸 花豬月光通行證",
    "packPass": "靈貓專用諮詢券",
    "applied": "使用中",
    "flowerNone": "還沒有月光通行證。",
    "flowerBrowse": "查看月光通行證",
    "packNone": "還沒有靈貓套組。",
    "packBrowse": "查看靈貓套組",
    "packOthers": "另有{count}個套組",
    "bothApplied": "兩種使用券分別生效。每次諮詢只扣除其中一種。",
    "ownedBadge": "已持有 · 剩餘{remaining}次",
    "appliedDone": "{name} 已生效",
    "goConsult": "去找靈貓諮詢",
    "viewOwned": "查看持有列表",
    "flowerFamilyApply": "可在選擇支付方式時使用月光通行證。",
    "flowerFamilyOnly": "此諮詢需Family月光通行證才可使用。",
    "packUsable": "可用於本次諮詢。",
    "packApplied": "已使用 · 剩餘{remaining}次"
  },
  "vi": {
    "scope": "Chỉ tư vấn {fish} · {days} ngày · {total} lượt",
    "title": "Vé tư vấn riêng Yeongnyangi",
    "intro": "Yeoni chuẩn bị các bộ cá cho khách quen. Mỗi lượt mở một bài tư vấn cùng hạng cá.",
    "owned": "Vé tư vấn của tôi",
    "empty": "Bạn chưa có vé tư vấn.",
    "unavailable": "Chưa xác nhận được vé. Hãy kiểm tra lại.",
    "loading": "Đang kiểm tra vé…",
    "retry": "Kiểm tra lại",
    "login": "Đăng nhập để xem",
    "select": "Chọn bộ",
    "buy": "Mua bằng thanh toán một lần",
    "consent": "Tôi đã đọc điều kiện và chính sách hoàn tiền.",
    "confirm": "Đang xác nhận thanh toán. Bạn có thể kiểm tra lại cùng đơn.",
    "recheck": "Kiểm tra thanh toán",
    "complete": "Vé tư vấn đã sẵn sàng.",
    "remaining": "Còn {remaining}/{total} lượt",
    "expires": "Đến {date}",
    "validity": "{days} ngày sau khi mua",
    "eligible": "Bài tư vấn áp dụng",
    "use": "Dùng 1 lượt để bắt đầu",
    "working": "Đang xác nhận lượt dùng…",
    "more": "Xem thêm vé",
    "webOnly": "Đang chuẩn bị bán trong ứng dụng. Xem chi tiết trên web.",
    "savings": "Dùng hết {total} lượt tiết kiệm {amount} so với mua lẻ",
    "checkout": "Vé cho bài tư vấn này",
    "inactive": "Vé này hiện không dùng được.",
    "emptyCatalog": "Các bộ đang được chuẩn bị để bán. Vé đã có được hiển thị bên dưới.",
    "chooseConsultation": "Chọn tư vấn",
    "selfPurchase": "Dùng cho mình",
    "giftPurchase": "Tặng quà",
    "giftPrepare": "Chuẩn bị món quà ý nghĩa",
    "senderName": "Tên người gửi (tùy chọn)",
    "recipientName": "Tên người nhận (tùy chọn)",
    "giftMessage": "Lời nhắn (tùy chọn)",
    "giftNotice": "Không cần thông tin tài khoản người nhận. Một tài khoản có liên kết có thể nhận quà, nên chỉ gửi cho người bạn muốn tặng.",
    "giftBox": "Quà đã gửi và đã nhận",
    "giftUsagePeriod": "Có hiệu lực {days} ngày sau khi nhận.",
    "giftTotal": "{total} lượt tư vấn cùng cấp cá",
    "giftClaimSuccess": "Đã nhận quà. Xem số lượt còn lại trong vé Yeongnyangi của bạn.",
    "giftViewWallet": "Xem vé Yeongnyangi của tôi",
    "giftComplete": "Liên kết quà được chuẩn bị sau khi xác minh thanh toán.",
    "durationLabel": "Thời hạn sử dụng {days} ngày",
    "previewSet": "Bộ {fish}",
    "packName": "Bộ {fish} {total} lượt",
    "resumePayment": "Tiếp tục thanh toán đơn này",
    "resumeNotice": "Chúng tôi kiểm tra thanh toán trước. Chỉ đơn cũ chưa thanh toán mới được tiếp tục bằng thanh toán một lần.",
    "resumeConsent": "Tôi đã xem lại và đồng ý với điều khoản cùng chính sách hoàn tiền của đơn này.",
    "resumeAtShop": "Tiếp tục đơn này tại cửa hàng",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Mua gói lượt luận giải bằng thanh toán một lần. Ngoài Hàn Quốc, dùng PayPal và kiểm tra tổng tiền USD trước khi xác nhận. Không thể dùng Đá Ánh Trăng để mua gói.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "Vé của tôi",
    "flowerPass": "🌸 Moonlight Pass Heo Hoa",
    "packPass": "Vé Yeongnyangi",
    "applied": "Đang áp dụng",
    "flowerNone": "Bạn chưa có Moonlight Pass.",
    "flowerBrowse": "Xem Moonlight Pass",
    "packNone": "Bạn chưa có gói Yeongnyangi.",
    "packBrowse": "Xem gói Yeongnyangi",
    "packOthers": "và {count} gói khác",
    "bothApplied": "Hai loại vé được áp dụng riêng. Mỗi lần tư vấn chỉ trừ một loại.",
    "ownedBadge": "Đang có · còn {remaining} lượt",
    "appliedDone": "Đã áp dụng {name}",
    "goConsult": "Tư vấn với Yeongnyangi",
    "viewOwned": "Xem vé đang có",
    "flowerFamilyApply": "Bạn có thể áp dụng Moonlight Pass khi chọn cách thanh toán.",
    "flowerFamilyOnly": "Buổi tư vấn này áp dụng từ Moonlight Pass Family.",
    "packUsable": "Dùng được cho buổi tư vấn này.",
    "packApplied": "Đã áp dụng · còn {remaining} lượt"
  },
  "hi": {
    "scope": "केवल {fish} परामर्श · {days} दिन · {total} उपयोग",
    "title": "योंगन्यांगी के परामर्श पास",
    "intro": "योनी ने नियमित मेहमानों के लिए मछली सेट तैयार किए हैं। हर उपयोग से उसी मछली स्तर का एक परामर्श खुलता है।",
    "owned": "मेरे परामर्श पास",
    "empty": "आपके पास कोई परामर्श पास नहीं है।",
    "unavailable": "पास की पुष्टि नहीं हो सकी। कृपया फिर जाँचें।",
    "loading": "पास जाँचे जा रहे हैं…",
    "retry": "फिर जाँचें",
    "login": "साइन इन करके देखें",
    "select": "सेट चुनें",
    "buy": "एकमुश्त भुगतान से खरीदें",
    "consent": "मैंने उपयोग और रिफंड नीति पढ़ ली है।",
    "confirm": "भुगतान जाँचा जा रहा है। उसी ऑर्डर को फिर जाँच सकते हैं।",
    "recheck": "भुगतान जाँचें",
    "complete": "आपका परामर्श पास तैयार है।",
    "remaining": "{total} में से {remaining} उपयोग शेष",
    "expires": "{date} तक",
    "validity": "खरीद के बाद {days} दिन",
    "eligible": "पात्र परामर्श",
    "use": "1 उपयोग से परामर्श शुरू करें",
    "working": "उपयोग की पुष्टि हो रही है…",
    "more": "और पास देखें",
    "webOnly": "ऐप बिक्री की तैयारी जारी है। वेब पर खरीद विवरण देखें।",
    "savings": "सभी {total} उपयोग करने पर अलग खरीद से {amount} की बचत",
    "checkout": "इस परामर्श के लिए पास",
    "inactive": "यह पास अभी उपलब्ध नहीं है।",
    "emptyCatalog": "बिक्री के लिए सेट तैयार हो रहे हैं। मौजूदा पास नीचे देखें।",
    "chooseConsultation": "परामर्श चुनें",
    "selfPurchase": "अपने लिए",
    "giftPurchase": "उपहार दें",
    "giftPrepare": "प्यार से उपहार तैयार करें",
    "senderName": "भेजने वाले का नाम (वैकल्पिक)",
    "recipientName": "पाने वाले का नाम (वैकल्पिक)",
    "giftMessage": "उपहार संदेश (वैकल्पिक)",
    "giftNotice": "प्राप्तकर्ता के खाते की जानकारी ज़रूरी नहीं। लिंक वाला एक खाता उपहार ले सकता है, इसलिए इसे केवल प्राप्तकर्ता को भेजें।",
    "giftBox": "भेजे और मिले उपहार",
    "giftUsagePeriod": "स्वीकार करने के बाद {days} दिन मान्य।",
    "giftTotal": "उसी मछली स्तर के {total} परामर्श",
    "giftClaimSuccess": "उपहार मिल गया। अपने योंगन्यांगी पास में शेष उपयोग देखें।",
    "giftViewWallet": "मेरे योंगन्यांगी पास देखें",
    "giftComplete": "भुगतान की पुष्टि के बाद उपहार लिंक तैयार होगा।",
    "durationLabel": "{days} दिन की उपयोग अवधि",
    "previewSet": "{fish} सेट",
    "packName": "{fish} सेट ({total} उपयोग)",
    "resumePayment": "इसी ऑर्डर का भुगतान जारी रखें",
    "resumeNotice": "पहले भुगतान की स्थिति जाँची जाएगी। केवल इसी अवैतनिक ऑर्डर का एकमुश्त भुगतान आगे बढ़ सकता है।",
    "resumeConsent": "मैंने इस ऑर्डर की शर्तें और वापसी नीति फिर से पढ़ी हैं और सहमत हूँ।",
    "resumeAtShop": "दुकान में यही ऑर्डर जारी रखें",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "परामर्श पैक एकमुश्त भुगतान से खरीदें। कोरिया के बाहर PayPal का उपयोग करें और स्वीकृति से पहले USD में कुल राशि जाँचें। पैक खरीदने के लिए मूनस्टोन का उपयोग नहीं कर सकते।",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "मेरे पास",
    "flowerPass": "🌸 फ्लावर पिग मूनलाइट पास",
    "packPass": "योंगन्यांगी पास",
    "applied": "लागू",
    "flowerNone": "अभी कोई मूनलाइट पास नहीं है।",
    "flowerBrowse": "मूनलाइट पास देखें",
    "packNone": "अभी कोई योंगन्यांगी पैक नहीं है।",
    "packBrowse": "योंगन्यांगी पैक देखें",
    "packOthers": "+{count} और पैक",
    "bothApplied": "दोनों पास अलग-अलग लागू होते हैं। हर परामर्श में केवल एक ही इस्तेमाल होता है।",
    "ownedBadge": "आपके पास · {remaining} बाकी",
    "appliedDone": "{name} लागू हो गया",
    "goConsult": "योंगन्यांगी से परामर्श शुरू करें",
    "viewOwned": "मेरे पैक देखें",
    "flowerFamilyApply": "भुगतान विकल्पों में मूनलाइट पास लागू कर सकते हैं।",
    "flowerFamilyOnly": "यह परामर्श Family मूनलाइट पास से लागू होता है।",
    "packUsable": "इस परामर्श के लिए उपयोग योग्य।",
    "packApplied": "लागू · {remaining} बाकी"
  },
  "es": {
    "scope": "Solo consultas {fish} · {days} días · {total} usos",
    "title": "Pases de consulta de Yeongnyangi",
    "intro": "Yeoni preparó lotes de pescado para quienes regresan. Cada uso abre una consulta del mismo nivel de pescado.",
    "owned": "Mis pases de consulta",
    "empty": "No tienes pases de consulta.",
    "unavailable": "No pudimos confirmar tus pases. Vuelve a consultar.",
    "loading": "Consultando pases…",
    "retry": "Volver a consultar",
    "login": "Iniciar sesión para consultar",
    "select": "Elegir lote",
    "buy": "Comprar con pago único",
    "consent": "He leído las condiciones y la política de reembolso.",
    "confirm": "Comprobando el pago. Puedes revisar el mismo pedido.",
    "recheck": "Comprobar pago",
    "complete": "Tu pase de consulta está listo.",
    "remaining": "Quedan {remaining} de {total} usos",
    "expires": "Hasta {date}",
    "validity": "{days} días desde la compra",
    "eligible": "Consultas disponibles",
    "use": "Usar 1 vez y empezar",
    "working": "Confirmando el uso…",
    "more": "Ver más pases",
    "webOnly": "Las ventas en la app se están preparando. Consulta la compra en la web.",
    "savings": "Al usar las {total} consultas ahorras {amount} frente a compras individuales",
    "checkout": "Un pase para esta consulta",
    "inactive": "Este pase no está disponible actualmente.",
    "emptyCatalog": "Los lotes se están preparando. Puedes ver tus pases actuales abajo.",
    "chooseConsultation": "Elegir consulta",
    "selfPurchase": "Para mí",
    "giftPurchase": "Regalar",
    "giftPrepare": "Prepara un regalo con cariño",
    "senderName": "Nombre del remitente (opcional)",
    "recipientName": "Nombre del destinatario (opcional)",
    "giftMessage": "Mensaje (opcional)",
    "giftNotice": "No necesitas los datos de la cuenta destinataria. Una sola cuenta con el enlace puede recibirlo; compártelo solo con esa persona.",
    "giftBox": "Regalos enviados y recibidos",
    "giftUsagePeriod": "Válido {days} días desde la aceptación.",
    "giftTotal": "{total} consultas del mismo nivel de pez",
    "giftClaimSuccess": "Regalo recibido. Consulta los usos restantes en tus pases de Yeongnyangi.",
    "giftViewWallet": "Ver mis pases de Yeongnyangi",
    "giftComplete": "El enlace del regalo se prepara tras verificar el pago.",
    "durationLabel": "Periodo de uso de {days} días",
    "previewSet": "Lote {fish}",
    "packName": "Lote {fish} de {total} usos",
    "resumePayment": "Continuar el pago de este pedido",
    "resumeNotice": "Primero comprobamos el pago. Solo este mismo pedido pendiente puede continuar con un pago único.",
    "resumeConsent": "He revisado y acepto de nuevo las condiciones y la política de reembolso de este pedido.",
    "resumeAtShop": "Continuar este pedido en la tienda",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Compra los paquetes de lecturas con un pago único. Fuera de Corea, usa PayPal y revisa el total en USD antes de autorizar. No se pueden comprar paquetes con Piedras Lunares.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "Mis pases",
    "flowerPass": "🌸 Moonlight Pass de Cerdita Flor",
    "packPass": "Pase de Yeongnyangi",
    "applied": "Activo",
    "flowerNone": "Aún no tienes Moonlight Pass.",
    "flowerBrowse": "Ver Moonlight Pass",
    "packNone": "Aún no tienes packs de Yeongnyangi.",
    "packBrowse": "Ver packs de Yeongnyangi",
    "packOthers": "+{count} packs más",
    "bothApplied": "Los dos pases se aplican por separado. Cada consulta usa solo uno.",
    "ownedBadge": "Tuyo · quedan {remaining}",
    "appliedDone": "{name} aplicado",
    "goConsult": "Consultar a Yeongnyangi",
    "viewOwned": "Ver mis packs",
    "flowerFamilyApply": "Puedes aplicar tu Moonlight Pass en las opciones de pago.",
    "flowerFamilyOnly": "Esta consulta se cubre desde el Moonlight Pass Family.",
    "packUsable": "Disponible para esta consulta.",
    "packApplied": "Aplicado · quedan {remaining}"
  },
  "fr": {
    "scope": "Consultations {fish} uniquement · {days} jours · {total} utilisations",
    "title": "Pass de consultation Yeongnyangi",
    "intro": "Yeoni a préparé des lots de poissons pour les habitués. Chaque utilisation ouvre une consultation du même niveau de poisson.",
    "owned": "Mes pass de consultation",
    "empty": "Vous n’avez aucun pass de consultation.",
    "unavailable": "Impossible de confirmer vos pass. Veuillez réessayer.",
    "loading": "Vérification des pass…",
    "retry": "Vérifier à nouveau",
    "login": "Se connecter pour vérifier",
    "select": "Choisir un lot",
    "buy": "Acheter en paiement unique",
    "consent": "J’ai lu les conditions et la politique de remboursement.",
    "confirm": "Vérification du paiement. Vous pouvez revérifier la même commande.",
    "recheck": "Vérifier le paiement",
    "complete": "Votre pass est prêt.",
    "remaining": "{remaining} utilisations restantes sur {total}",
    "expires": "Jusqu’au {date}",
    "validity": "{days} jours après l’achat",
    "eligible": "Consultations disponibles",
    "use": "Utiliser 1 fois et commencer",
    "working": "Confirmation de l’utilisation…",
    "more": "Voir plus de pass",
    "webOnly": "Les ventes dans l’application sont en préparation. Consultez l’achat sur le Web.",
    "savings": "En utilisant les {total} consultations, vous économisez {amount} par rapport aux achats individuels",
    "checkout": "Un pass pour cette consultation",
    "inactive": "Ce pass est actuellement indisponible.",
    "emptyCatalog": "Les lots sont en préparation. Vos pass existants sont indiqués ci-dessous.",
    "chooseConsultation": "Choisir une consultation",
    "selfPurchase": "Pour moi",
    "giftPurchase": "Offrir",
    "giftPrepare": "Préparer une attention",
    "senderName": "Nom de l’expéditeur (facultatif)",
    "recipientName": "Nom du destinataire (facultatif)",
    "giftMessage": "Message (facultatif)",
    "giftNotice": "Aucune information de compte n’est nécessaire. Un seul compte disposant du lien peut recevoir le cadeau ; partagez-le uniquement avec le destinataire.",
    "giftBox": "Cadeaux envoyés et reçus",
    "giftUsagePeriod": "Valable {days} jours après acceptation.",
    "giftTotal": "{total} consultations du même niveau de poisson",
    "giftClaimSuccess": "Cadeau reçu. Consultez les utilisations restantes dans vos pass Yeongnyangi.",
    "giftViewWallet": "Voir mes pass Yeongnyangi",
    "giftComplete": "Le lien cadeau est préparé après vérification du paiement.",
    "durationLabel": "Durée d’utilisation de {days} jours",
    "previewSet": "Lot {fish}",
    "packName": "Lot {fish} de {total} utilisations",
    "resumePayment": "Reprendre le paiement de cette commande",
    "resumeNotice": "Nous vérifions d’abord le paiement. Seule cette même commande non payée peut continuer par paiement unique.",
    "resumeConsent": "J’ai relu et j’accepte à nouveau les conditions et la politique de remboursement de cette commande.",
    "resumeAtShop": "Reprendre cette commande dans la boutique",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Achetez les packs de lectures en un seul paiement. Hors de Corée, utilisez PayPal et vérifiez le total en USD avant de valider. Les Pierres de Lune ne permettent pas d’acheter des packs.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "Mes pass",
    "flowerPass": "🌸 Moonlight Pass Cochon Fleur",
    "packPass": "Pass Yeongnyangi",
    "applied": "Actif",
    "flowerNone": "Aucun Moonlight Pass pour le moment.",
    "flowerBrowse": "Voir les Moonlight Pass",
    "packNone": "Aucun pack Yeongnyangi pour le moment.",
    "packBrowse": "Voir les packs Yeongnyangi",
    "packOthers": "+{count} autres packs",
    "bothApplied": "Les deux pass s’appliquent séparément. Chaque consultation n’en utilise qu’un.",
    "ownedBadge": "Possédé · {remaining} restantes",
    "appliedDone": "{name} appliqué",
    "goConsult": "Consulter Yeongnyangi",
    "viewOwned": "Voir mes packs",
    "flowerFamilyApply": "Vous pouvez appliquer votre Moonlight Pass dans les options de paiement.",
    "flowerFamilyOnly": "Cette consultation est couverte à partir du Moonlight Pass Family.",
    "packUsable": "Utilisable pour cette consultation.",
    "packApplied": "Appliqué · {remaining} restantes"
  },
  "de": {
    "scope": "Nur {fish}-Beratungen · {days} Tage · {total} Nutzungen",
    "title": "Yeongnyangi-Beratungspässe",
    "intro": "Yeoni hat Fischpakete für Stammgäste vorbereitet. Jede Nutzung öffnet eine Beratung derselben Fischstufe.",
    "owned": "Meine Beratungspässe",
    "empty": "Du hast keine Beratungspässe.",
    "unavailable": "Die Pässe konnten nicht bestätigt werden. Bitte erneut prüfen.",
    "loading": "Pässe werden geprüft…",
    "retry": "Erneut prüfen",
    "login": "Anmelden und prüfen",
    "select": "Paket wählen",
    "buy": "Mit Einmalzahlung kaufen",
    "consent": "Ich habe die Nutzungs- und Erstattungsbedingungen gelesen.",
    "confirm": "Die Zahlung wird geprüft. Du kannst dieselbe Bestellung erneut prüfen.",
    "recheck": "Zahlung prüfen",
    "complete": "Dein Beratungspass ist bereit.",
    "remaining": "{remaining} von {total} Nutzungen übrig",
    "expires": "Bis {date}",
    "validity": "{days} Tage nach dem Kauf",
    "eligible": "Verfügbare Beratungen",
    "use": "1 Nutzung einlösen und starten",
    "working": "Nutzung wird bestätigt…",
    "more": "Weitere Pässe anzeigen",
    "webOnly": "Der App-Verkauf wird vorbereitet. Prüfe die Kaufdetails im Web.",
    "savings": "Bei Nutzung aller {total} Beratungen sparst du {amount} gegenüber Einzelkäufen",
    "checkout": "Ein Pass für diese Beratung",
    "inactive": "Dieser Pass ist derzeit nicht verfügbar.",
    "emptyCatalog": "Die Pakete werden vorbereitet. Vorhandene Pässe stehen unten.",
    "chooseConsultation": "Beratung wählen",
    "selfPurchase": "Für mich",
    "giftPurchase": "Verschenken",
    "giftPrepare": "Ein persönliches Geschenk vorbereiten",
    "senderName": "Name des Absenders (optional)",
    "recipientName": "Name des Empfängers (optional)",
    "giftMessage": "Nachricht (optional)",
    "giftNotice": "Kontodaten des Empfängers sind nicht nötig. Ein Konto mit dem Link kann das Geschenk annehmen. Teile ihn nur mit der beschenkten Person.",
    "giftBox": "Gesendete und erhaltene Geschenke",
    "giftUsagePeriod": "Nach Annahme {days} Tage gültig.",
    "giftTotal": "{total} Beratungen derselben Fischstufe",
    "giftClaimSuccess": "Geschenk erhalten. Deine übrigen Nutzungen findest du in deinen Yeongnyangi-Pässen.",
    "giftViewWallet": "Meine Yeongnyangi-Pässe ansehen",
    "giftComplete": "Der Geschenklink wird nach der Zahlungsprüfung vorbereitet.",
    "durationLabel": "Nutzungsdauer: {days} Tage",
    "previewSet": "{fish}-Set",
    "packName": "{fish}-Set mit {total} Nutzungen",
    "resumePayment": "Zahlung dieser Bestellung fortsetzen",
    "resumeNotice": "Wir prüfen zuerst den Zahlungsstatus. Nur dieselbe unbezahlte Bestellung kann mit einer Einmalzahlung fortgesetzt werden.",
    "resumeConsent": "Ich habe die Bedingungen und Erstattungsrichtlinie dieser Bestellung erneut gelesen und stimme zu.",
    "resumeAtShop": "Diese Bestellung im Shop fortsetzen",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Deutungspakete kaufst du per Einmalzahlung. Außerhalb Koreas nutzt du PayPal und prüfst den USD-Gesamtbetrag vor der Freigabe. Mondsteine können nicht zum Kauf von Paketen verwendet werden.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "Meine Pässe",
    "flowerPass": "🌸 Moonlight Pass Blumenschwein",
    "packPass": "Yeongnyangi-Pass",
    "applied": "Aktiv",
    "flowerNone": "Noch kein Moonlight Pass.",
    "flowerBrowse": "Moonlight Pässe ansehen",
    "packNone": "Noch kein Yeongnyangi-Paket.",
    "packBrowse": "Yeongnyangi-Pakete ansehen",
    "packOthers": "+{count} weitere Pakete",
    "bothApplied": "Beide Pässe gelten getrennt. Pro Beratung wird nur einer verwendet.",
    "ownedBadge": "Im Besitz · {remaining} übrig",
    "appliedDone": "{name} angewendet",
    "goConsult": "Beratung mit Yeongnyangi starten",
    "viewOwned": "Meine Pakete ansehen",
    "flowerFamilyApply": "Du kannst deinen Moonlight Pass bei den Zahlungsoptionen anwenden.",
    "flowerFamilyOnly": "Diese Beratung ist ab dem Family Moonlight Pass abgedeckt.",
    "packUsable": "Für diese Beratung nutzbar.",
    "packApplied": "Angewendet · {remaining} übrig"
  },
  "nl": {
    "scope": "Alleen {fish}-consulten · {days} dagen · {total} keer",
    "title": "Yeongnyangi-consultatiepassen",
    "intro": "Yeoni heeft vispakketten voor vaste gasten klaargezet. Elk gebruik opent één consultatie van hetzelfde visniveau.",
    "owned": "Mijn consultatiepassen",
    "empty": "Je hebt geen consultatiepassen.",
    "unavailable": "We konden je passen niet bevestigen. Controleer opnieuw.",
    "loading": "Passen controleren…",
    "retry": "Opnieuw controleren",
    "login": "Inloggen om te bekijken",
    "select": "Pakket kiezen",
    "buy": "Kopen met eenmalige betaling",
    "consent": "Ik heb de gebruiks- en terugbetalingsvoorwaarden gelezen.",
    "confirm": "De betaling wordt gecontroleerd. Je kunt dezelfde bestelling opnieuw controleren.",
    "recheck": "Betaling controleren",
    "complete": "Je consultatiepas is klaar.",
    "remaining": "{remaining} van {total} beurten over",
    "expires": "Tot {date}",
    "validity": "{days} dagen na aankoop",
    "eligible": "Beschikbare consultaties",
    "use": "1 beurt gebruiken en starten",
    "working": "Gebruik bevestigen…",
    "more": "Meer passen bekijken",
    "webOnly": "Verkoop in de app wordt voorbereid. Bekijk de aankoop op het web.",
    "savings": "Bij gebruik van alle {total} consultaties bespaar je {amount} ten opzichte van losse aankopen",
    "checkout": "Een pas voor deze consultatie",
    "inactive": "Deze pas is momenteel niet beschikbaar.",
    "emptyCatalog": "De pakketten worden voorbereid. Je bestaande passen staan hieronder.",
    "chooseConsultation": "Kies een consult",
    "selfPurchase": "Voor mezelf",
    "giftPurchase": "Cadeau geven",
    "giftPrepare": "Maak een persoonlijk cadeau",
    "senderName": "Naam afzender (optioneel)",
    "recipientName": "Naam ontvanger (optioneel)",
    "giftMessage": "Bericht (optioneel)",
    "giftNotice": "Accountgegevens van de ontvanger zijn niet nodig. Eén account met de link kan het cadeau ontvangen. Deel hem alleen met de ontvanger.",
    "giftBox": "Verstuurde en ontvangen cadeaus",
    "giftUsagePeriod": "Na ontvangst {days} dagen geldig.",
    "giftTotal": "{total} consulten van hetzelfde visniveau",
    "giftClaimSuccess": "Cadeau ontvangen. Bekijk je resterende consulten bij je Yeongnyangi-passen.",
    "giftViewWallet": "Mijn Yeongnyangi-passen bekijken",
    "giftComplete": "De cadeaulink wordt na betaalcontrole klaargezet.",
    "durationLabel": "Gebruiksduur: {days} dagen",
    "previewSet": "{fish}-set",
    "packName": "{fish}-set van {total} keer",
    "resumePayment": "Betaling van deze bestelling hervatten",
    "resumeNotice": "We controleren eerst de betaling. Alleen dezelfde onbetaalde bestelling kan doorgaan met een eenmalige betaling.",
    "resumeConsent": "Ik heb de voorwaarden en het terugbetalingsbeleid van deze bestelling opnieuw gelezen en ga akkoord.",
    "resumeAtShop": "Deze bestelling in de winkel hervatten",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Koop duidingspakketten met een eenmalige betaling. Buiten Korea gebruik je PayPal en controleer je eerst het totaal in USD. Je kunt geen pakketten kopen met Maanstenen.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "Mijn passen",
    "flowerPass": "🌸 Moonlight Pass Bloemvarken",
    "packPass": "Yeongnyangi-pas",
    "applied": "Actief",
    "flowerNone": "Nog geen Moonlight Pass.",
    "flowerBrowse": "Moonlight Passen bekijken",
    "packNone": "Nog geen Yeongnyangi-pakket.",
    "packBrowse": "Yeongnyangi-pakketten bekijken",
    "packOthers": "+{count} pakketten meer",
    "bothApplied": "Beide passen gelden apart. Elke consult gebruikt er maar één.",
    "ownedBadge": "In bezit · nog {remaining}",
    "appliedDone": "{name} toegepast",
    "goConsult": "Consult bij Yeongnyangi starten",
    "viewOwned": "Mijn pakketten bekijken",
    "flowerFamilyApply": "Je kunt je Moonlight Pass toepassen bij de betaalopties.",
    "flowerFamilyOnly": "Dit consult valt onder de Family Moonlight Pass.",
    "packUsable": "Bruikbaar voor dit consult.",
    "packApplied": "Toegepast · nog {remaining}"
  },
  "ms": {
    "scope": "Konsultasi {fish} sahaja · {days} hari · {total} penggunaan",
    "title": "Pas konsultasi Yeongnyangi",
    "intro": "Yeoni menyediakan set ikan untuk tetamu tetap. Setiap penggunaan membuka satu konsultasi bagi tahap ikan yang sama.",
    "owned": "Pas konsultasi saya",
    "empty": "Anda tiada pas konsultasi.",
    "unavailable": "Pas tidak dapat disahkan. Sila semak semula.",
    "loading": "Sedang menyemak pas…",
    "retry": "Semak semula",
    "login": "Log masuk untuk semak",
    "select": "Pilih set",
    "buy": "Beli dengan bayaran sekali",
    "consent": "Saya telah membaca syarat penggunaan dan dasar bayaran balik.",
    "confirm": "Sedang menyemak bayaran. Anda boleh menyemak pesanan yang sama semula.",
    "recheck": "Semak bayaran",
    "complete": "Pas konsultasi anda sudah tersedia.",
    "remaining": "Baki {remaining} daripada {total} penggunaan",
    "expires": "Sehingga {date}",
    "validity": "{days} hari selepas pembelian",
    "eligible": "Konsultasi yang tersedia",
    "use": "Guna 1 kali dan mula",
    "working": "Sedang mengesahkan penggunaan…",
    "more": "Lihat lebih banyak pas",
    "webOnly": "Jualan aplikasi sedang disediakan. Semak butiran pembelian di web.",
    "savings": "Menggunakan semua {total} konsultasi menjimatkan {amount} berbanding pembelian berasingan",
    "checkout": "Pas untuk konsultasi ini",
    "inactive": "Pas ini tidak boleh digunakan buat masa ini.",
    "emptyCatalog": "Set sedang disediakan untuk jualan. Pas sedia ada disenaraikan di bawah.",
    "chooseConsultation": "Pilih konsultasi",
    "selfPurchase": "Untuk diri sendiri",
    "giftPurchase": "Hadiahkan",
    "giftPrepare": "Sediakan hadiah ikhlas",
    "senderName": "Nama pengirim (pilihan)",
    "recipientName": "Nama penerima (pilihan)",
    "giftMessage": "Mesej hadiah (pilihan)",
    "giftNotice": "Maklumat akaun penerima tidak diperlukan. Satu akaun dengan pautan boleh menerima hadiah, jadi kongsikan hanya dengan penerima.",
    "giftBox": "Hadiah dihantar dan diterima",
    "giftUsagePeriod": "Sah selama {days} hari selepas diterima.",
    "giftTotal": "{total} konsultasi peringkat ikan yang sama",
    "giftClaimSuccess": "Hadiah diterima. Semak baki penggunaan dalam pas Yeongnyangi anda.",
    "giftViewWallet": "Lihat pas Yeongnyangi saya",
    "giftComplete": "Pautan hadiah disediakan selepas pembayaran disahkan.",
    "durationLabel": "Tempoh penggunaan {days} hari",
    "previewSet": "Set {fish}",
    "packName": "Set {fish} {total} penggunaan",
    "resumePayment": "Sambung bayaran pesanan ini",
    "resumeNotice": "Kami menyemak bayaran dahulu. Hanya pesanan sama yang belum dibayar boleh diteruskan dengan bayaran sekali sahaja.",
    "resumeConsent": "Saya telah menyemak dan bersetuju semula dengan syarat serta dasar bayaran balik pesanan ini.",
    "resumeAtShop": "Sambung pesanan ini di kedai",
    "allianceKicker": "Yeongnyangi × Flower Pig alliance",
    "moonTitle": "Moonlight Stone works here too",
    "moonUsable": "Moonlight Stone from Ggulggul Fortune can pay for Yeongnyangi consultations.",
    "moonExample": "e.g. {fish} {system} consultation {price} = {stones} Moonlight Stone",
    "wonOnly": "Beli pakej bacaan dengan bayaran sekali. Di luar Korea, gunakan PayPal dan semak jumlah USD sebelum meluluskan. Batu Bulan tidak boleh digunakan untuk membeli pakej.",
    "recommend": "Yeongnyangi's pick",
    "cardSubtitle": "A {days}-day pack bought with a one-time KRW payment",
    "perUse": "{amount} per use",
    "buyCta": "Buy →",
    "giftCta": "🎁 Send as a gift",
    "giftPromo": "Give it to someone special",
    "payTitle": "Choose how to pay for this pack",
    "conditionsTitle": "{days}-day pack conditions",
    "selfActivation": "Added to your packs as soon as payment is confirmed, and usable for {days} days from then.",
    "refundLink": "View the full refund policy",
    "giftGuidanceSummary": "Gift claiming, use and refunds",
    "giftGuidance": "After payment is confirmed, send the gift link. It can be claimed by one logged-in account, and self-claiming is also allowed. The claim deadline is 1 year after purchase. The usage period starts when claimed. Refunds for unclaimed gifts follow the existing policy; after claiming, operator confirmation is required. Expiry of the claim deadline alone does not extinguish refund rights.",
    "payPrompt": "Payment method",
    "cardPay": "Card",
    "contentValue": "Prices are shown in KRW and paid in a secure payment window.",
    "close": "Close",
    "notPaid": "This order was not paid. Please choose a pack again.",
    "passesTitle": "Pas saya",
    "flowerPass": "🌸 Moonlight Pass Babi Bunga",
    "packPass": "Pas Yeongnyangi",
    "applied": "Aktif",
    "flowerNone": "Belum ada Moonlight Pass.",
    "flowerBrowse": "Lihat Moonlight Pass",
    "packNone": "Belum ada pek Yeongnyangi.",
    "packBrowse": "Lihat pek Yeongnyangi",
    "packOthers": "+{count} pek lagi",
    "bothApplied": "Kedua-dua pas digunakan secara berasingan. Setiap konsultasi hanya menggunakan satu.",
    "ownedBadge": "Dimiliki · baki {remaining}",
    "appliedDone": "{name} digunakan",
    "goConsult": "Mulakan konsultasi Yeongnyangi",
    "viewOwned": "Lihat pek saya",
    "flowerFamilyApply": "Anda boleh menggunakan Moonlight Pass dalam pilihan pembayaran.",
    "flowerFamilyOnly": "Konsultasi ini dilindungi mulai Moonlight Pass Family.",
    "packUsable": "Boleh digunakan untuk konsultasi ini.",
    "packApplied": "Digunakan · baki {remaining}"
  }
};
export type PackCopy=typeof COPY.ko;
export function servicePackCopy(locale:LoadingLocale):PackCopy{return COPY[locale]||COPY.en;}
export function packText(template:string,values:Record<string,string|number>){return template.replace(/\{(\w+)\}/g,(token,key)=>String(values[key]??token));}
// 세트 이름은 서버 정책표의 한국어 고정값(label)이다. ko 는 그대로, 다른 로케일은 어종·회수로 다시 짓는다(표시 전용 — 주문·스냅샷 비교는 label 원문).
export function packName(pack:{label:string;fishId:string;totalUses:number},locale:LoadingLocale){return locale==='ko'?pack.label:packText(servicePackCopy(locale).packName,{fish:localizedTier(pack.fishId,locale),total:pack.totalUses});}
