import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';
const ko={checking:'로그인 확인 중',signedIn:'로그인됨',account:'내 계정',logout:'로그아웃',logoutFailed:'로그아웃하지 못했어요. 다시 시도해 주세요.',company:'상호',registration:'사업자등록번호',license:'통신판매업 신고번호',address:'주소',serviceInfo:'서비스 안내',today:'오늘의 무료 운세',otherService:'꽃돼지 운세'};
type Copy=typeof ko;
export const accountLocaleCopy:Record<ReadingLocale,Copy>={ko,
 en:{checking:'Checking sign-in',signedIn:'Signed in',account:'My account',logout:'Sign out',logoutFailed:'Could not sign out. Please try again.',company:'Business name',registration:'Business registration',license:'Mail-order registration',address:'Address',serviceInfo:'Service information',today:'Free daily reading',otherService:'Flower Pig readings'},
 ja:{checking:'ログイン確認中',signedIn:'ログイン中',account:'マイアカウント',logout:'ログアウト',logoutFailed:'ログアウトできませんでした。再試行してください。',company:'事業者名',registration:'事業者登録番号',license:'通信販売登録番号',address:'所在地',serviceInfo:'サービス案内',today:'無料の今日の運勢',otherService:'花豚の運勢'},
 'zh-CN':{checking:'正在确认登录',signedIn:'已登录',account:'我的账号',logout:'退出登录',logoutFailed:'暂时无法退出，请重试。',company:'经营者名称',registration:'营业登记编号',license:'网络销售登记编号',address:'地址',serviceInfo:'服务说明',today:'免费每日运势',otherService:'花猪运势'},
 'zh-TW':{checking:'正在確認登入',signedIn:'已登入',account:'我的帳號',logout:'登出',logoutFailed:'暫時無法登出，請重試。',company:'經營者名稱',registration:'營業登記編號',license:'網路銷售登記編號',address:'地址',serviceInfo:'服務說明',today:'免費每日運勢',otherService:'花豬運勢'},
 vi:{checking:'Đang kiểm tra đăng nhập',signedIn:'Đã đăng nhập',account:'Tài khoản của tôi',logout:'Đăng xuất',logoutFailed:'Chưa đăng xuất được. Vui lòng thử lại.',company:'Tên doanh nghiệp',registration:'Mã đăng ký doanh nghiệp',license:'Mã đăng ký bán hàng trực tuyến',address:'Địa chỉ',serviceInfo:'Thông tin dịch vụ',today:'Bài đọc hằng ngày miễn phí',otherService:'Bài đọc Flower Pig'},
 hi:{checking:'लॉग इन की जाँच हो रही है',signedIn:'लॉग इन किया गया',account:'मेरा खाता',logout:'लॉग आउट करें',logoutFailed:'लॉग आउट नहीं हुआ। फिर कोशिश करें।',company:'व्यवसाय का नाम',registration:'व्यवसाय पंजीकरण',license:'ऑनलाइन बिक्री पंजीकरण',address:'पता',serviceInfo:'सेवा की जानकारी',today:'मुफ़्त दैनिक रीडिंग',otherService:'फ्लावर पिग रीडिंग'},
 es:{checking:'Comprobando la sesión',signedIn:'Sesión iniciada',account:'Mi cuenta',logout:'Cerrar sesión',logoutFailed:'No se pudo cerrar la sesión. Inténtalo de nuevo.',company:'Nombre comercial',registration:'Registro comercial',license:'Registro de venta a distancia',address:'Dirección',serviceInfo:'Información del servicio',today:'Lectura diaria gratuita',otherService:'Lecturas Flower Pig'},
 fr:{checking:'Vérification de la connexion',signedIn:'Connecté',account:'Mon compte',logout:'Se déconnecter',logoutFailed:'Déconnexion impossible. Veuillez réessayer.',company:'Nom de l’entreprise',registration:'Immatriculation commerciale',license:'Immatriculation de vente à distance',address:'Adresse',serviceInfo:'Informations sur le service',today:'Lecture quotidienne gratuite',otherService:'Lectures Flower Pig'},
 de:{checking:'Anmeldung wird geprüft',signedIn:'Angemeldet',account:'Mein Konto',logout:'Abmelden',logoutFailed:'Abmeldung fehlgeschlagen. Bitte erneut versuchen.',company:'Unternehmensname',registration:'Gewerberegistrierung',license:'Versandhandelsregistrierung',address:'Adresse',serviceInfo:'Serviceinformationen',today:'Kostenlose Tagesdeutung',otherService:'Flower-Pig-Deutungen'},
 nl:{checking:'Aanmelding wordt gecontroleerd',signedIn:'Aangemeld',account:'Mijn account',logout:'Uitloggen',logoutFailed:'Uitloggen is niet gelukt. Probeer opnieuw.',company:'Bedrijfsnaam',registration:'Bedrijfsregistratie',license:'Registratie verkoop op afstand',address:'Adres',serviceInfo:'Informatie over de dienst',today:'Gratis dagreading',otherService:'Flower Pig-readings'},
 ms:{checking:'Sedang menyemak log masuk',signedIn:'Telah log masuk',account:'Akaun saya',logout:'Log keluar',logoutFailed:'Tidak dapat log keluar. Sila cuba lagi.',company:'Nama perniagaan',registration:'Pendaftaran perniagaan',license:'Pendaftaran jualan dalam talian',address:'Alamat',serviceInfo:'Maklumat perkhidmatan',today:'Bacaan harian percuma',otherService:'Bacaan Flower Pig'},
};
