import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';

// Stable kind IDs, shared by menus and saved reading headings. Korean stays in the source catalog.
export const additionalKindIds=['health','marriage','movement','business','feelings','contact','reunion','career','healing','spread'] as const;
type Labels=readonly [string,string,string,string,string,string,string,string,string,string];
// Descriptions explain the purpose without turning symbolic health readings into diagnosis.
export const additionalKindDescriptions:Record<Exclude<ReadingLocale,'ko'>,Labels>={
 en:['Explore daily rhythms and recovery habits through this tradition’s symbols, without medical diagnosis.','Consider partnership patterns and the conditions for sharing a life.','Reflect on relocation, unfamiliar environments and preparation for change.','Examine how you build resources, cooperate and manage business uncertainty.','Explore the signals you have noticed without claiming to know another person’s thoughts.','Consider communication patterns, boundaries and your next step.','Review recurring difficulties and the conditions for a mutually welcome reconnection.','Compare your current work, strengths and possible changes.','Make room for tired feelings and identify support you can reach for.','Choose a card layout that fits the question and compare its scope before continuing.'],
 ja:['占術の象徴から生活リズムと回復習慣を振り返ります。医学的な診断は行いません。','関係のパターンと、共に暮らすための条件を考えます。','移動や慣れない環境、変化への準備を見つめます。','資源の育て方、協力、事業の不確実性との向き合い方を考えます。','相手の本心を断定せず、気になった言動を読み解きます。','連絡のパターンと境界線、次の行動を考えます。','繰り返す課題と、双方が望む再接近の条件を整理します。','今の仕事、強み、考えている変化を比べます。','疲れた気持ちを受け止め、頼れる支えを探します。','質問に合うカード配置を選び、扱う範囲を確認できます。'],
 'zh-CN':['借助本体系的象征，梳理生活节奏与恢复习惯，不作医学诊断。','了解伴侣关系中的模式与共同生活的条件。','思考迁移、陌生环境与改变前的准备。','梳理资源积累、合作与经营中的不确定性。','从你观察到的言行出发，不断言对方的真实想法。','了解沟通模式、彼此边界与下一步行动。','回顾反复出现的困难，以及双方愿意重新联系的条件。','比较当前工作、个人优势与可能的变化。','给疲惫的情绪留出空间，寻找可以获得的支持。','按问题选择牌阵，继续前了解解读范围。'],
 'zh-TW':['藉由本體系的象徵，整理生活節奏與恢復習慣，不作醫學診斷。','了解伴侶關係中的模式與共同生活的條件。','思考遷移、陌生環境與改變前的準備。','整理資源累積、合作與經營中的不確定性。','從你觀察到的言行出發，不斷言對方的真實想法。','了解溝通模式、彼此界線與下一步行動。','回顧反覆出現的困難，以及雙方願意重新聯繫的條件。','比較目前工作、個人優勢與可能的變化。','給疲憊的情緒留出空間，尋找可以獲得的支持。','依問題選擇牌陣，繼續前了解解讀範圍。'],
 vi:['Nhìn lại nhịp sống và thói quen hồi phục qua biểu tượng của hệ thống, không chẩn đoán y khoa.','Tìm hiểu mô thức quan hệ và điều kiện để chung sống.','Suy ngẫm về chuyển nơi ở, môi trường mới và chuẩn bị thay đổi.','Xem cách tích lũy nguồn lực, hợp tác và ứng phó với bất định trong kinh doanh.','Tìm hiểu tín hiệu bạn quan sát được, không khẳng định suy nghĩ riêng của người khác.','Cân nhắc cách giao tiếp, ranh giới và bước tiếp theo.','Nhìn lại khó khăn lặp lại và điều kiện để cả hai cùng muốn kết nối lại.','So sánh công việc hiện tại, điểm mạnh và những thay đổi có thể có.','Dành chỗ cho cảm xúc mệt mỏi và tìm nguồn hỗ trợ phù hợp.','Chọn cách trải bài phù hợp và xem phạm vi trước khi tiếp tục.'],
 hi:['इस परंपरा के प्रतीकों से दिनचर्या और विश्राम की आदतों पर विचार करें; यह चिकित्सकीय निदान नहीं है।','रिश्ते के ढर्रे और साथ जीवन बिताने की परिस्थितियाँ समझें।','स्थान परिवर्तन, नए माहौल और बदलाव की तैयारी पर विचार करें।','संसाधन, सहयोग और व्यवसाय की अनिश्चितताओं को समझें।','देखे गए संकेत समझें; दूसरे व्यक्ति के निजी विचारों का दावा नहीं किया जाता।','संवाद के ढर्रे, सीमाएँ और अगला कदम समझें।','बार-बार आने वाली कठिनाइयों और दोनों की इच्छा से फिर जुड़ने की शर्तों पर विचार करें।','मौजूदा काम, अपनी खूबियों और संभावित बदलावों की तुलना करें।','थकी हुई भावनाओं को जगह दें और उपलब्ध सहारा पहचानें।','सवाल के अनुसार कार्ड विन्यास चुनें और आगे बढ़ने से पहले उसका दायरा देखें।'],
 es:['Reflexiona sobre tus ritmos y hábitos de recuperación mediante símbolos, sin diagnóstico médico.','Explora patrones de pareja y condiciones para compartir la vida.','Considera mudanzas, entornos nuevos y cómo prepararte.','Examina recursos, cooperación e incertidumbre en tu actividad.','Interpreta lo que has observado sin afirmar qué piensa otra persona.','Revisa la comunicación, los límites y tu próximo paso.','Explora dificultades repetidas y condiciones para volver a acercarse por mutuo acuerdo.','Compara tu trabajo actual, tus fortalezas y posibles cambios.','Da espacio al cansancio emocional e identifica apoyos a tu alcance.','Elige una tirada adecuada y compara su alcance antes de continuar.'],
 fr:['Explorez vos rythmes et habitudes de récupération à travers les symboles, sans diagnostic médical.','Examinez les habitudes du couple et les conditions d’une vie commune.','Réfléchissez au déménagement, aux nouveaux environnements et à la préparation du changement.','Examinez vos ressources, la coopération et les incertitudes de votre activité.','Explorez les signes observés sans prétendre connaître les pensées d’autrui.','Réfléchissez à la communication, aux limites et à votre prochaine action.','Examinez les difficultés récurrentes et les conditions d’un rapprochement souhaité par les deux personnes.','Comparez votre travail actuel, vos atouts et les changements possibles.','Accueillez la fatigue émotionnelle et repérez les soutiens disponibles.','Choisissez un tirage adapté et vérifiez son périmètre avant de poursuivre.'],
 de:['Betrachte Alltagsrhythmen und Erholung anhand der Symbolik, ohne medizinische Diagnose.','Erkunde Beziehungsmuster und Bedingungen für ein gemeinsames Leben.','Denke über Umzug, neue Umgebungen und die Vorbereitung auf Veränderungen nach.','Betrachte Ressourcen, Zusammenarbeit und geschäftliche Unsicherheit.','Ordne beobachtete Signale ein, ohne fremde Gedanken als Tatsache darzustellen.','Betrachte Kommunikationsmuster, Grenzen und deinen nächsten Schritt.','Prüfe wiederkehrende Schwierigkeiten und Bedingungen für eine beiderseits erwünschte Annäherung.','Vergleiche aktuelle Arbeit, Stärken und mögliche Veränderungen.','Gib erschöpften Gefühlen Raum und finde erreichbare Unterstützung.','Wähle eine passende Legung und prüfe ihren Umfang vor dem Fortfahren.'],
 nl:['Bekijk je ritme en herstelgewoonten via symboliek, zonder medische diagnose.','Onderzoek relatiepatronen en voorwaarden voor een leven samen.','Denk na over verhuizen, een nieuwe omgeving en voorbereiding op verandering.','Bekijk middelen, samenwerking en onzekerheid in je onderneming.','Onderzoek waargenomen signalen zonder andermans gedachten als feit te presenteren.','Bekijk communicatiepatronen, grenzen en je volgende stap.','Onderzoek terugkerende problemen en voorwaarden voor toenadering die beiden willen.','Vergelijk je huidige werk, sterke kanten en mogelijke veranderingen.','Geef vermoeide gevoelens ruimte en zoek bereikbare steun.','Kies een passende legging en bekijk de inhoud voordat je doorgaat.'],
 ms:['Renungkan rentak harian dan tabiat pemulihan melalui simbol tradisi ini, tanpa diagnosis perubatan.','Terokai corak hubungan dan syarat untuk hidup bersama.','Fikirkan perpindahan, persekitaran baharu dan persediaan untuk perubahan.','Teliti sumber, kerjasama dan ketidakpastian dalam perniagaan.','Terokai petunjuk yang diperhatikan tanpa mendakwa mengetahui fikiran orang lain.','Pertimbangkan corak komunikasi, batas dan langkah seterusnya.','Tinjau kesukaran berulang dan syarat untuk mendekati semula dengan persetujuan bersama.','Bandingkan kerja semasa, kekuatan dan perubahan yang mungkin.','Beri ruang kepada emosi yang letih dan kenal pasti sokongan yang boleh dicapai.','Pilih susunan yang sesuai dan semak skopnya sebelum meneruskan.'],
};
export function additionalKindDescription(id:string,locale:ReadingLocale){
 const index=additionalKindIds.indexOf(id as typeof additionalKindIds[number]);
 return locale==='ko'||index<0?undefined:additionalKindDescriptions[locale][index];
}
