import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';
import {nativeV7Copy} from './reading-v7-locales';
// v7 chapter and part labels (docs/design/yeongnyangi-v7-chapter-catalog.md §6-7). Keys are the manifest's
// own `titleKey`/`partKey`, so a chapter without them (v5/v6) never reaches this dictionary and its UI is unchanged.
// ko mirrors the catalog titles in reading-v7.ts; __tests__/ui/yeongnyangi-reading-v7-copy.test.mjs fails when
// the two drift or when a catalog entry has no entry here. ja and en follow the reading-copy.ts `Copy=typeof ko`
// pattern; all other runtime locales use native semantic labels from reading-v7-locales.ts.
const ko={
 'yeongnyangi.v7.part.base':'바탕',
 'yeongnyangi.v7.part.love':'연애',
 'yeongnyangi.v7.part.marriage':'결혼·배우자',
 'yeongnyangi.v7.part.wealth':'재물',
 'yeongnyangi.v7.part.career':'직업',
 'yeongnyangi.v7.part.relations':'대인관계·가족',
 'yeongnyangi.v7.part.health':'건강',
 'yeongnyangi.v7.part.depth':'체계 심화',
 'yeongnyangi.v7.part.timing':'운의 시기',
 'yeongnyangi.v7.part.cards':'카드',
 'yeongnyangi.v7.part.flow':'흐름',
 'yeongnyangi.v7.part.choice':'선택',
 'yeongnyangi.v7.saju.anchor':'타고난 중심과 힘의 균형',
 'yeongnyangi.v7.saju.elements':'넘치는 기운과 모자란 기운',
 'yeongnyangi.v7.saju.love':'타고난 연애 스타일',
 'yeongnyangi.v7.saju.expression':'마음을 전하는 표현',
 'yeongnyangi.v7.saju.siksin':'다정하게 전하는 마음(식신)',
 'yeongnyangi.v7.saju.sanggwan':'날이 선 매력(상관)',
 'yeongnyangi.v7.saju.spouse':'결혼운과 배우자 자리',
 'yeongnyangi.v7.saju.wealth':'돈이 모이고 새는 길',
 'yeongnyangi.v7.saju.jeongjae':'지키고 쌓는 돈(정재)',
 'yeongnyangi.v7.saju.pyeonjae':'굴리고 불리는 돈(편재)',
 'yeongnyangi.v7.saju.career':'일하는 방식과 사회적 자리',
 'yeongnyangi.v7.saju.jeonggwan':'조직과 책임(정관)',
 'yeongnyangi.v7.saju.pyeongwan':'압박과 돌파(편관)',
 'yeongnyangi.v7.saju.learning':'배움과 받쳐 주는 힘',
 'yeongnyangi.v7.saju.jeongin':'정석의 배움(정인)',
 'yeongnyangi.v7.saju.pyeonin':'직관과 비주류 배움(편인)',
 'yeongnyangi.v7.saju.relations':'곁의 사람들',
 'yeongnyangi.v7.saju.bigyeon':'나란히 걷는 사람(비견)',
 'yeongnyangi.v7.saju.geopjae':'겨루는 사람(겁재)',
 'yeongnyangi.v7.saju.roots':'부모와 뿌리',
 'yeongnyangi.v7.saju.children':'자녀와 인생 후반',
 'yeongnyangi.v7.saju.health':'몸의 리듬과 회복',
 'yeongnyangi.v7.saju.signals':'귀인과 강한 기운의 신호',
 'yeongnyangi.v7.saju.useful':'나를 살리는 기운(용신·종격 판정)',
 'yeongnyangi.v7.saju.majorArc':'대운으로 보는 인생의 굴곡',
 'yeongnyangi.v7.saju.majorNow':'지금의 대운',
 'yeongnyangi.v7.saju.majorNext':'다음 대운과 준비',
 'yeongnyangi.v7.saju.yearNow':'올해와 내년',
 'yeongnyangi.v7.saju.months':'앞으로 12개월',
 'yeongnyangi.v7.saju.yearsAhead':'앞으로 8년의 세운',
 'yeongnyangi.v7.saju.loveLuck':'연애운의 흐름',
 'yeongnyangi.v7.saju.marriageLuck':'결혼운이 움직이는 시기',
 'yeongnyangi.v7.saju.movement':'이동수와 해외운',
 'yeongnyangi.v7.ziwei.anchor':'삶의 중심(명궁·신궁)',
 'yeongnyangi.v7.ziwei.love':'마음이 끌리는 것과 연애의 즐거움',
 'yeongnyangi.v7.ziwei.spouse':'배우자 자리와 함께 사는 법',
 'yeongnyangi.v7.ziwei.wealth':'돈의 그릇과 쌓는 방식',
 'yeongnyangi.v7.ziwei.property':'집과 자산의 자리',
 'yeongnyangi.v7.ziwei.career':'일하는 방식과 사회적 자리',
 'yeongnyangi.v7.ziwei.travel':'바깥 무대와 이동',
 'yeongnyangi.v7.ziwei.relations':'곁의 사람과 가족',
 'yeongnyangi.v7.ziwei.peers':'형제·동료·친구',
 'yeongnyangi.v7.ziwei.parents':'부모와 윗사람',
 'yeongnyangi.v7.ziwei.children':'자녀와 아랫사람',
 'yeongnyangi.v7.ziwei.health':'몸의 약한 고리와 회복',
 'yeongnyangi.v7.ziwei.hwarok':'풀리는 곳(화록)',
 'yeongnyangi.v7.ziwei.hwagwon':'힘을 쥐는 곳(화권)',
 'yeongnyangi.v7.ziwei.hwagwa':'이름이 나는 곳(화과)',
 'yeongnyangi.v7.ziwei.hwagi':'막히는 곳(화기)',
 'yeongnyangi.v7.ziwei.triad':'삼방사정으로 본 명반의 축',
 'yeongnyangi.v7.ziwei.majorNow':'지금의 대한',
 'yeongnyangi.v7.ziwei.majorNext':'다음 대한과 준비',
 'yeongnyangi.v7.ziwei.yearNow':'올해와 내년',
 'yeongnyangi.v7.ziwei.yearsAhead':'앞으로 8년의 유년',
 'yeongnyangi.v7.vedic.anchor':'라그나로 본 삶의 출발점',
 'yeongnyangi.v7.vedic.mind':'달과 마음의 결',
 'yeongnyangi.v7.vedic.love':'끌림과 연애(금성·5하우스)',
 'yeongnyangi.v7.vedic.spouse':'배우자와 결혼(7하우스)',
 'yeongnyangi.v7.vedic.d9':'나밤샤로 본 결혼의 깊이',
 'yeongnyangi.v7.vedic.wealth':'돈을 모으는 힘(목성·2하우스)',
 'yeongnyangi.v7.vedic.gains':'들어오는 이익과 인맥(11하우스)',
 'yeongnyangi.v7.vedic.career':'일과 사회적 자리(10하우스)',
 'yeongnyangi.v7.vedic.d10':'다샴샤로 본 직업의 방향',
 'yeongnyangi.v7.vedic.relations':'형제·스승·믿음',
 'yeongnyangi.v7.vedic.siblings':'형제와 소통(3하우스)',
 'yeongnyangi.v7.vedic.dharma':'스승과 믿음(9하우스)',
 'yeongnyangi.v7.vedic.home':'집과 어머니(4하우스)',
 'yeongnyangi.v7.vedic.d7':'자녀(D7)',
 'yeongnyangi.v7.vedic.d12':'부모(D12)',
 'yeongnyangi.v7.vedic.health':'몸과 회복(6하우스)',
 'yeongnyangi.v7.vedic.transformation':'위기와 변화(8하우스)',
 'yeongnyangi.v7.vedic.release':'소모와 쉼(12하우스)',
 'yeongnyangi.v7.vedic.yogas':'명식에 맺힌 요가',
 'yeongnyangi.v7.vedic.nodes':'라후와 케투',
 'yeongnyangi.v7.vedic.dashaArc':'다샤로 보는 인생의 흐름',
 'yeongnyangi.v7.vedic.mdNow':'지금의 마하다샤',
 'yeongnyangi.v7.vedic.adNow':'지금의 안타르다샤',
 'yeongnyangi.v7.vedic.mdNext':'다음 마하다샤',
 'yeongnyangi.v7.astrology.anchor':'상승점과 태양',
 'yeongnyangi.v7.astrology.emotion':'달과 감정의 결',
 'yeongnyangi.v7.astrology.love':'금성과 관계의 자리',
 'yeongnyangi.v7.astrology.wealth':'목성과 돈의 흐름',
 'yeongnyangi.v7.astrology.career':'토성·MC 와 사회적 자리',
 'yeongnyangi.v7.astrology.communication':'수성과 말·배움·모임',
 'yeongnyangi.v7.astrology.health':'화성과 몸의 에너지',
 'yeongnyangi.v7.astrology.aspects':'행성들이 주고받는 긴장과 조화',
 'yeongnyangi.v7.astrology.tension':'긴장의 애스펙트',
 'yeongnyangi.v7.astrology.harmony':'조화의 애스펙트',
 'yeongnyangi.v7.astrology.generations':'세대 행성이 남긴 흔적',
 'yeongnyangi.v7.astrology.uranus':'천왕성',
 'yeongnyangi.v7.astrology.neptune':'해왕성',
 'yeongnyangi.v7.astrology.pluto':'명왕성',
 'yeongnyangi.v7.sukuyo.anchor':'본명숙이 말하는 나',
 'yeongnyangi.v7.sukuyo.love':'강하게 끌리고 부딪히는 인연(안괴)',
 'yeongnyangi.v7.sukuyo.an':'편안하게 끌리는 인연(안)',
 'yeongnyangi.v7.sukuyo.goe':'깨지며 배우는 인연(괴)',
 'yeongnyangi.v7.sukuyo.spouse':'오래 함께할 인연(영친)',
 'yeongnyangi.v7.sukuyo.yeong':'서로를 키우는 인연(영)',
 'yeongnyangi.v7.sukuyo.chin':'가족 같은 인연(친)',
 'yeongnyangi.v7.sukuyo.career':'일에서 만나는 인연(성위)',
 'yeongnyangi.v7.sukuyo.seong':'함께 이루는 인연(성)',
 'yeongnyangi.v7.sukuyo.wi':'긴장을 주는 인연(위)',
 'yeongnyangi.v7.sukuyo.friends':'친구와 멀어지는 인연(우쇠)',
 'yeongnyangi.v7.sukuyo.u':'편한 친구(우)',
 'yeongnyangi.v7.sukuyo.soe':'기운을 빼는 인연(쇠)',
 'yeongnyangi.v7.sukuyo.fate':'운명처럼 얽히는 인연(명·업·태)',
 'yeongnyangi.v7.tarot.love.anchor':'질문과 여섯 카드의 뼈대',
 'yeongnyangi.v7.tarot.love.cards12':'내가 보는 상대와 상대가 보는 관계',
 'yeongnyangi.v7.tarot.love.card1':'내가 바라보는 상대',
 'yeongnyangi.v7.tarot.love.card2':'상대가 보는 우리 관계',
 'yeongnyangi.v7.tarot.love.cards34':'상대의 마음과 연애 의지',
 'yeongnyangi.v7.tarot.love.card3':'상대의 마음',
 'yeongnyangi.v7.tarot.love.card4':'상대의 연애 의지',
 'yeongnyangi.v7.tarot.love.cards56':'관계를 막는 것과 가까운 흐름',
 'yeongnyangi.v7.tarot.love.card5':'관계를 막는 것',
 'yeongnyangi.v7.tarot.love.card6':'가까운 흐름',
 'yeongnyangi.v7.tarot.love.flow':'카드들이 함께 말하는 흐름',
 'yeongnyangi.v7.tarot.love.decision':'지금의 선택',
 'yeongnyangi.v7.tarot.choice.anchor':'질문과 세 카드의 뼈대',
 'yeongnyangi.v7.tarot.choice.causeProcess':'원인과 과정',
 'yeongnyangi.v7.tarot.choice.cause':'원인',
 'yeongnyangi.v7.tarot.choice.process':'과정',
 'yeongnyangi.v7.tarot.choice.outcome':'결과',
 'yeongnyangi.v7.tarot.choice.flow':'카드들이 함께 말하는 흐름',
 'yeongnyangi.v7.tarot.choice.decision':'지금의 선택',
};
type Copy=typeof ko;
const en:Copy={
 'yeongnyangi.v7.part.base':'Foundations',
 'yeongnyangi.v7.part.love':'Love',
 'yeongnyangi.v7.part.marriage':'Marriage and partner',
 'yeongnyangi.v7.part.wealth':'Wealth',
 'yeongnyangi.v7.part.career':'Work',
 'yeongnyangi.v7.part.relations':'People and family',
 'yeongnyangi.v7.part.health':'Health',
 'yeongnyangi.v7.part.depth':'Deeper reading',
 'yeongnyangi.v7.part.timing':'Timing',
 'yeongnyangi.v7.part.cards':'Cards',
 'yeongnyangi.v7.part.flow':'Flow',
 'yeongnyangi.v7.part.choice':'Choice',
 'yeongnyangi.v7.saju.anchor':'Your core and the balance of strength',
 'yeongnyangi.v7.saju.elements':'Elements in excess and in short supply',
 'yeongnyangi.v7.saju.love':'Your natural love style',
 'yeongnyangi.v7.saju.expression':'How you express what you feel',
 'yeongnyangi.v7.saju.siksin':'Warmth that reaches others (Siksin)',
 'yeongnyangi.v7.saju.sanggwan':'A sharp, striking charm (Sanggwan)',
 'yeongnyangi.v7.saju.spouse':'Marriage luck and the spouse pillar',
 'yeongnyangi.v7.saju.wealth':'Where money gathers and where it leaks',
 'yeongnyangi.v7.saju.jeongjae':'Money you keep and build (Jeongjae)',
 'yeongnyangi.v7.saju.pyeonjae':'Money you move and grow (Pyeonjae)',
 'yeongnyangi.v7.saju.career':'How you work and your place in society',
 'yeongnyangi.v7.saju.jeonggwan':'Organizations and responsibility (Jeonggwan)',
 'yeongnyangi.v7.saju.pyeongwan':'Pressure and breakthrough (Pyeongwan)',
 'yeongnyangi.v7.saju.learning':'Learning and the support behind you',
 'yeongnyangi.v7.saju.jeongin':'Learning by the book (Jeongin)',
 'yeongnyangi.v7.saju.pyeonin':'Intuition and unconventional learning (Pyeonin)',
 'yeongnyangi.v7.saju.relations':'The people beside you',
 'yeongnyangi.v7.saju.bigyeon':'Those who walk beside you (Bigyeon)',
 'yeongnyangi.v7.saju.geopjae':'Those who compete with you (Geopjae)',
 'yeongnyangi.v7.saju.roots':'Parents and your roots',
 'yeongnyangi.v7.saju.children':'Children and the later years',
 'yeongnyangi.v7.saju.health':"Your body's rhythm and recovery",
 'yeongnyangi.v7.saju.signals':'Signals of helpers and strong energy',
 'yeongnyangi.v7.saju.useful':'The energy that supports you (Yongshin and Jonggyeok)',
 'yeongnyangi.v7.saju.majorArc':"Life's arc through the major luck cycles",
 'yeongnyangi.v7.saju.majorNow':'Your current major luck cycle',
 'yeongnyangi.v7.saju.majorNext':'The next major luck cycle and how to prepare',
 'yeongnyangi.v7.saju.yearNow':'This year and next year',
 'yeongnyangi.v7.saju.months':'The next twelve months',
 'yeongnyangi.v7.saju.yearsAhead':'The yearly luck of the next eight years',
 'yeongnyangi.v7.saju.loveLuck':'How your love luck moves',
 'yeongnyangi.v7.saju.marriageLuck':'When marriage luck stirs',
 'yeongnyangi.v7.saju.movement':'Moves, relocation and overseas luck',
 'yeongnyangi.v7.ziwei.anchor':'The center of your life (Life and Body palaces)',
 'yeongnyangi.v7.ziwei.love':'What draws you and the joy of love',
 'yeongnyangi.v7.ziwei.spouse':'The spouse palace and living together',
 'yeongnyangi.v7.ziwei.wealth':'Your capacity for money and how you build it',
 'yeongnyangi.v7.ziwei.property':'Home and assets',
 'yeongnyangi.v7.ziwei.career':'How you work and your place in society',
 'yeongnyangi.v7.ziwei.travel':'The outside stage and movement',
 'yeongnyangi.v7.ziwei.relations':'The people beside you and your family',
 'yeongnyangi.v7.ziwei.peers':'Siblings, colleagues and friends',
 'yeongnyangi.v7.ziwei.parents':'Parents and elders',
 'yeongnyangi.v7.ziwei.children':'Children and those you lead',
 'yeongnyangi.v7.ziwei.health':'Your weak links and recovery',
 'yeongnyangi.v7.ziwei.hwarok':'Where things open up (Hua Lu)',
 'yeongnyangi.v7.ziwei.hwagwon':'Where you hold power (Hua Quan)',
 'yeongnyangi.v7.ziwei.hwagwa':'Where you gain a name (Hua Ke)',
 'yeongnyangi.v7.ziwei.hwagi':'Where things get blocked (Hua Ji)',
 'yeongnyangi.v7.ziwei.triad':"The chart's axes through San Fang Si Zheng",
 'yeongnyangi.v7.ziwei.majorNow':'Your current decade cycle',
 'yeongnyangi.v7.ziwei.majorNext':'The next decade cycle and how to prepare',
 'yeongnyangi.v7.ziwei.yearNow':'This year and next year',
 'yeongnyangi.v7.ziwei.yearsAhead':'The annual cycles of the next eight years',
 'yeongnyangi.v7.vedic.anchor':'Your starting point through the Lagna',
 'yeongnyangi.v7.vedic.mind':'The Moon and the grain of your mind',
 'yeongnyangi.v7.vedic.love':'Attraction and love (Venus, 5th house)',
 'yeongnyangi.v7.vedic.spouse':'Partner and marriage (7th house)',
 'yeongnyangi.v7.vedic.d9':'Marriage in depth through the Navamsa',
 'yeongnyangi.v7.vedic.wealth':'The power to gather wealth (Jupiter, 2nd house)',
 'yeongnyangi.v7.vedic.gains':'Incoming gains and networks (11th house)',
 'yeongnyangi.v7.vedic.career':'Work and social standing (10th house)',
 'yeongnyangi.v7.vedic.d10':'Career direction through the Dashamsha',
 'yeongnyangi.v7.vedic.relations':'Siblings, teachers and faith',
 'yeongnyangi.v7.vedic.siblings':'Siblings and communication (3rd house)',
 'yeongnyangi.v7.vedic.dharma':'Teachers and faith (9th house)',
 'yeongnyangi.v7.vedic.home':'Home and mother (4th house)',
 'yeongnyangi.v7.vedic.d7':'Children (D7)',
 'yeongnyangi.v7.vedic.d12':'Parents (D12)',
 'yeongnyangi.v7.vedic.health':'Body and recovery (6th house)',
 'yeongnyangi.v7.vedic.transformation':'Crisis and transformation (8th house)',
 'yeongnyangi.v7.vedic.release':'Depletion and rest (12th house)',
 'yeongnyangi.v7.vedic.yogas':'The yogas formed in your chart',
 'yeongnyangi.v7.vedic.nodes':'Rahu and Ketu',
 'yeongnyangi.v7.vedic.dashaArc':"Life's flow through the Dashas",
 'yeongnyangi.v7.vedic.mdNow':'Your current Mahadasha',
 'yeongnyangi.v7.vedic.adNow':'Your current Antardasha',
 'yeongnyangi.v7.vedic.mdNext':'The next Mahadasha',
 'yeongnyangi.v7.astrology.anchor':'Ascendant and Sun',
 'yeongnyangi.v7.astrology.emotion':'The Moon and the grain of your feelings',
 'yeongnyangi.v7.astrology.love':'Venus and the houses of relationship',
 'yeongnyangi.v7.astrology.wealth':'Jupiter and the flow of money',
 'yeongnyangi.v7.astrology.career':'Saturn, the MC and your social standing',
 'yeongnyangi.v7.astrology.communication':'Mercury: words, learning and circles',
 'yeongnyangi.v7.astrology.health':'Mars and your physical energy',
 'yeongnyangi.v7.astrology.aspects':'The tension and harmony between planets',
 'yeongnyangi.v7.astrology.tension':'Aspects of tension',
 'yeongnyangi.v7.astrology.harmony':'Aspects of harmony',
 'yeongnyangi.v7.astrology.generations':'What the generational planets left behind',
 'yeongnyangi.v7.astrology.uranus':'Uranus',
 'yeongnyangi.v7.astrology.neptune':'Neptune',
 'yeongnyangi.v7.astrology.pluto':'Pluto',
 'yeongnyangi.v7.sukuyo.anchor':'Who you are through your birth mansion',
 'yeongnyangi.v7.sukuyo.love':'Bonds that pull and clash (An, Goe)',
 'yeongnyangi.v7.sukuyo.an':'Bonds that feel easy (An)',
 'yeongnyangi.v7.sukuyo.goe':'Bonds that teach by breaking (Goe)',
 'yeongnyangi.v7.sukuyo.spouse':'Bonds that last (Yeong, Chin)',
 'yeongnyangi.v7.sukuyo.yeong':'Bonds that grow each other (Yeong)',
 'yeongnyangi.v7.sukuyo.chin':'Bonds like family (Chin)',
 'yeongnyangi.v7.sukuyo.career':'Bonds you meet through work (Seong, Wi)',
 'yeongnyangi.v7.sukuyo.seong':'Bonds that build together (Seong)',
 'yeongnyangi.v7.sukuyo.wi':'Bonds that bring tension (Wi)',
 'yeongnyangi.v7.sukuyo.friends':'Friends and fading bonds (U, Soe)',
 'yeongnyangi.v7.sukuyo.u':'Easy friends (U)',
 'yeongnyangi.v7.sukuyo.soe':'Bonds that drain you (Soe)',
 'yeongnyangi.v7.sukuyo.fate':'Bonds tangled like fate (Myeong, Eop, Tae)',
 'yeongnyangi.v7.tarot.love.anchor':'Your question and the frame of six cards',
 'yeongnyangi.v7.tarot.love.cards12':'How you see them and how they see the relationship',
 'yeongnyangi.v7.tarot.love.card1':'How you see them',
 'yeongnyangi.v7.tarot.love.card2':'How they see your relationship',
 'yeongnyangi.v7.tarot.love.cards34':'Their feelings and their will to date',
 'yeongnyangi.v7.tarot.love.card3':'Their feelings',
 'yeongnyangi.v7.tarot.love.card4':'Their will to date',
 'yeongnyangi.v7.tarot.love.cards56':'What blocks the relationship and what comes next',
 'yeongnyangi.v7.tarot.love.card5':'What blocks the relationship',
 'yeongnyangi.v7.tarot.love.card6':'The near-term flow',
 'yeongnyangi.v7.tarot.love.flow':'The flow the cards tell together',
 'yeongnyangi.v7.tarot.love.decision':'The choice in front of you',
 'yeongnyangi.v7.tarot.choice.anchor':'Your question and the frame of three cards',
 'yeongnyangi.v7.tarot.choice.causeProcess':'Cause and process',
 'yeongnyangi.v7.tarot.choice.cause':'Cause',
 'yeongnyangi.v7.tarot.choice.process':'Process',
 'yeongnyangi.v7.tarot.choice.outcome':'Outcome',
 'yeongnyangi.v7.tarot.choice.flow':'The flow the cards tell together',
 'yeongnyangi.v7.tarot.choice.decision':'The choice in front of you',
};
const ja:Copy={
 'yeongnyangi.v7.part.base':'土台',
 'yeongnyangi.v7.part.love':'恋愛',
 'yeongnyangi.v7.part.marriage':'結婚・配偶者',
 'yeongnyangi.v7.part.wealth':'財運',
 'yeongnyangi.v7.part.career':'仕事',
 'yeongnyangi.v7.part.relations':'人間関係・家族',
 'yeongnyangi.v7.part.health':'健康',
 'yeongnyangi.v7.part.depth':'体系の深掘り',
 'yeongnyangi.v7.part.timing':'運の時期',
 'yeongnyangi.v7.part.cards':'カード',
 'yeongnyangi.v7.part.flow':'流れ',
 'yeongnyangi.v7.part.choice':'選択',
 'yeongnyangi.v7.saju.anchor':'生まれ持つ中心と力のバランス',
 'yeongnyangi.v7.saju.elements':'あふれる気と足りない気',
 'yeongnyangi.v7.saju.love':'生まれ持つ恋愛スタイル',
 'yeongnyangi.v7.saju.expression':'心を伝える表現',
 'yeongnyangi.v7.saju.siksin':'やさしく伝える心（食神）',
 'yeongnyangi.v7.saju.sanggwan':'鋭さのある魅力（傷官）',
 'yeongnyangi.v7.saju.spouse':'結婚運と配偶者の位置',
 'yeongnyangi.v7.saju.wealth':'お金が集まる道と漏れる道',
 'yeongnyangi.v7.saju.jeongjae':'守り積み上げるお金（正財）',
 'yeongnyangi.v7.saju.pyeonjae':'動かして増やすお金（偏財）',
 'yeongnyangi.v7.saju.career':'働き方と社会的な位置',
 'yeongnyangi.v7.saju.jeonggwan':'組織と責任（正官）',
 'yeongnyangi.v7.saju.pyeongwan':'圧力と突破（偏官）',
 'yeongnyangi.v7.saju.learning':'学びと支えてくれる力',
 'yeongnyangi.v7.saju.jeongin':'定石の学び（正印）',
 'yeongnyangi.v7.saju.pyeonin':'直観と非主流の学び（偏印）',
 'yeongnyangi.v7.saju.relations':'そばにいる人たち',
 'yeongnyangi.v7.saju.bigyeon':'並んで歩く人（比肩）',
 'yeongnyangi.v7.saju.geopjae':'競い合う人（劫財）',
 'yeongnyangi.v7.saju.roots':'親とルーツ',
 'yeongnyangi.v7.saju.children':'子どもと人生の後半',
 'yeongnyangi.v7.saju.health':'体のリズムと回復',
 'yeongnyangi.v7.saju.signals':'貴人と強い気の兆し',
 'yeongnyangi.v7.saju.useful':'自分を活かす気（用神・従格の判定）',
 'yeongnyangi.v7.saju.majorArc':'大運で見る人生の起伏',
 'yeongnyangi.v7.saju.majorNow':'今の大運',
 'yeongnyangi.v7.saju.majorNext':'次の大運と準備',
 'yeongnyangi.v7.saju.yearNow':'今年と来年',
 'yeongnyangi.v7.saju.months':'これからの12か月',
 'yeongnyangi.v7.saju.yearsAhead':'これから8年の歳運',
 'yeongnyangi.v7.saju.loveLuck':'恋愛運の流れ',
 'yeongnyangi.v7.saju.marriageLuck':'結婚運が動く時期',
 'yeongnyangi.v7.saju.movement':'移動運と海外運',
 'yeongnyangi.v7.ziwei.anchor':'人生の中心（命宮・身宮）',
 'yeongnyangi.v7.ziwei.love':'心が惹かれるものと恋愛の楽しみ',
 'yeongnyangi.v7.ziwei.spouse':'配偶者の宮と共に生きる形',
 'yeongnyangi.v7.ziwei.wealth':'お金の器と貯め方',
 'yeongnyangi.v7.ziwei.property':'家と資産の宮',
 'yeongnyangi.v7.ziwei.career':'働き方と社会的な位置',
 'yeongnyangi.v7.ziwei.travel':'外の舞台と移動',
 'yeongnyangi.v7.ziwei.relations':'そばの人と家族',
 'yeongnyangi.v7.ziwei.peers':'兄弟・同僚・友人',
 'yeongnyangi.v7.ziwei.parents':'親と年長者',
 'yeongnyangi.v7.ziwei.children':'子どもと後輩',
 'yeongnyangi.v7.ziwei.health':'体の弱い部分と回復',
 'yeongnyangi.v7.ziwei.hwarok':'開けていく場所（化禄）',
 'yeongnyangi.v7.ziwei.hwagwon':'力を握る場所（化権）',
 'yeongnyangi.v7.ziwei.hwagwa':'名が上がる場所（化科）',
 'yeongnyangi.v7.ziwei.hwagi':'詰まる場所（化忌）',
 'yeongnyangi.v7.ziwei.triad':'三方四正で見る命盤の軸',
 'yeongnyangi.v7.ziwei.majorNow':'今の大限',
 'yeongnyangi.v7.ziwei.majorNext':'次の大限と準備',
 'yeongnyangi.v7.ziwei.yearNow':'今年と来年',
 'yeongnyangi.v7.ziwei.yearsAhead':'これから8年の流年',
 'yeongnyangi.v7.vedic.anchor':'ラグナで見る人生の出発点',
 'yeongnyangi.v7.vedic.mind':'月と心の質',
 'yeongnyangi.v7.vedic.love':'惹かれ方と恋愛（金星・第5室）',
 'yeongnyangi.v7.vedic.spouse':'配偶者と結婚（第7室）',
 'yeongnyangi.v7.vedic.d9':'ナヴァムシャで見る結婚の深さ',
 'yeongnyangi.v7.vedic.wealth':'富を集める力（木星・第2室）',
 'yeongnyangi.v7.vedic.gains':'入ってくる利益と人脈（第11室）',
 'yeongnyangi.v7.vedic.career':'仕事と社会的地位（第10室）',
 'yeongnyangi.v7.vedic.d10':'ダシャムシャで見る職業の方向',
 'yeongnyangi.v7.vedic.relations':'兄弟・師・信念',
 'yeongnyangi.v7.vedic.siblings':'兄弟と対話（第3室）',
 'yeongnyangi.v7.vedic.dharma':'師と信念（第9室）',
 'yeongnyangi.v7.vedic.home':'家と母（第4室）',
 'yeongnyangi.v7.vedic.d7':'子ども（D7）',
 'yeongnyangi.v7.vedic.d12':'親（D12）',
 'yeongnyangi.v7.vedic.health':'体と回復（第6室）',
 'yeongnyangi.v7.vedic.transformation':'危機と変化（第8室）',
 'yeongnyangi.v7.vedic.release':'消耗と休息（第12室）',
 'yeongnyangi.v7.vedic.yogas':'チャートに結ばれたヨーガ',
 'yeongnyangi.v7.vedic.nodes':'ラーフとケートゥ',
 'yeongnyangi.v7.vedic.dashaArc':'ダシャーで見る人生の流れ',
 'yeongnyangi.v7.vedic.mdNow':'今のマハーダシャー',
 'yeongnyangi.v7.vedic.adNow':'今のアンタルダシャー',
 'yeongnyangi.v7.vedic.mdNext':'次のマハーダシャー',
 'yeongnyangi.v7.astrology.anchor':'アセンダントと太陽',
 'yeongnyangi.v7.astrology.emotion':'月と感情の質',
 'yeongnyangi.v7.astrology.love':'金星と関係の部屋',
 'yeongnyangi.v7.astrology.wealth':'木星とお金の流れ',
 'yeongnyangi.v7.astrology.career':'土星・MCと社会的地位',
 'yeongnyangi.v7.astrology.communication':'水星と言葉・学び・集まり',
 'yeongnyangi.v7.astrology.health':'火星と体のエネルギー',
 'yeongnyangi.v7.astrology.aspects':'惑星が交わす緊張と調和',
 'yeongnyangi.v7.astrology.tension':'緊張のアスペクト',
 'yeongnyangi.v7.astrology.harmony':'調和のアスペクト',
 'yeongnyangi.v7.astrology.generations':'世代惑星が残した痕跡',
 'yeongnyangi.v7.astrology.uranus':'天王星',
 'yeongnyangi.v7.astrology.neptune':'海王星',
 'yeongnyangi.v7.astrology.pluto':'冥王星',
 'yeongnyangi.v7.sukuyo.anchor':'本命宿が語る自分',
 'yeongnyangi.v7.sukuyo.love':'強く惹かれぶつかる縁（安・壊）',
 'yeongnyangi.v7.sukuyo.an':'心地よく惹かれる縁（安）',
 'yeongnyangi.v7.sukuyo.goe':'壊れながら学ぶ縁（壊）',
 'yeongnyangi.v7.sukuyo.spouse':'長く共にいる縁（栄・親）',
 'yeongnyangi.v7.sukuyo.yeong':'互いを育てる縁（栄）',
 'yeongnyangi.v7.sukuyo.chin':'家族のような縁（親）',
 'yeongnyangi.v7.sukuyo.career':'仕事で出会う縁（成・危）',
 'yeongnyangi.v7.sukuyo.seong':'共に成し遂げる縁（成）',
 'yeongnyangi.v7.sukuyo.wi':'緊張を与える縁（危）',
 'yeongnyangi.v7.sukuyo.friends':'友と離れていく縁（友・衰）',
 'yeongnyangi.v7.sukuyo.u':'気楽な友（友）',
 'yeongnyangi.v7.sukuyo.soe':'気を削ぐ縁（衰）',
 'yeongnyangi.v7.sukuyo.fate':'運命のように絡む縁（命・業・胎）',
 'yeongnyangi.v7.tarot.love.anchor':'質問と6枚のカードの骨組み',
 'yeongnyangi.v7.tarot.love.cards12':'私が見る相手と相手が見る関係',
 'yeongnyangi.v7.tarot.love.card1':'私が見ている相手',
 'yeongnyangi.v7.tarot.love.card2':'相手が見る二人の関係',
 'yeongnyangi.v7.tarot.love.cards34':'相手の心と恋愛への意思',
 'yeongnyangi.v7.tarot.love.card3':'相手の心',
 'yeongnyangi.v7.tarot.love.card4':'相手の恋愛への意思',
 'yeongnyangi.v7.tarot.love.cards56':'関係を妨げるものと近い流れ',
 'yeongnyangi.v7.tarot.love.card5':'関係を妨げるもの',
 'yeongnyangi.v7.tarot.love.card6':'近い流れ',
 'yeongnyangi.v7.tarot.love.flow':'カードが共に語る流れ',
 'yeongnyangi.v7.tarot.love.decision':'今の選択',
 'yeongnyangi.v7.tarot.choice.anchor':'質問と3枚のカードの骨組み',
 'yeongnyangi.v7.tarot.choice.causeProcess':'原因と過程',
 'yeongnyangi.v7.tarot.choice.cause':'原因',
 'yeongnyangi.v7.tarot.choice.process':'過程',
 'yeongnyangi.v7.tarot.choice.outcome':'結果',
 'yeongnyangi.v7.tarot.choice.flow':'カードが共に語る流れ',
 'yeongnyangi.v7.tarot.choice.decision':'今の選択',
};
export const readingV7Copy=(locale?:ReadingLocale):Copy=>locale==='ko'||!locale?ko:locale==='ja'?ja:locale==='en'?en:nativeV7Copy(Object.keys(ko),locale) as Copy;
// Returns undefined for a v5/v6 chapter (no key) and for a key the dictionary does not know, so every caller
// keeps its existing fallback instead of rendering a raw key.
export const v7Label=(key:string|undefined,locale?:ReadingLocale):string|undefined=>
 key?readingV7Copy(locale)[key as keyof Copy]:undefined;
// The part head belongs to the first chapter of each part; a chapter without partKey never produces one.
export const v7PartHead=(chapters:readonly {partKey?:string;part?:string}[],index:number,locale?:ReadingLocale)=>{
 const key=chapters[index]?.partKey;
 if(!key||key===chapters[index-1]?.partKey)return undefined;
 return v7Label(key,locale)||chapters[index]?.part;
};
