import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';
import {relationshipQuestions,relationshipAdvice} from '@/worker/yeongnyangi/fortune/relationship-contract';
const domains=['tarot','ziwei','saju','sukuyo','vedic','astrology'] as const;
const rows:Record<Exclude<ReadingLocale,'ko'>,readonly [string,string,string]>={
 en:['Question|Two people|Method','How can I understand their feelings?|What should I consider about getting back in touch?|What would marriage mean for us?|What could help this relationship last?|Is this flirting or a misunderstanding?|What should I consider about reconnecting?','Explore your question through card symbols without birth details. This cannot verify private thoughts.|Compare temperament, partnership expectations and living together. Accurate birth times and locations are needed for both people.|Compare expression and everyday patterns in both charts. Mackerel and Salmon omit hour-based evidence when the birth time is unknown.|Compare both birth stars to explore attraction, distance and relationship roles.|Explore the Moon, nakshatra, relationship placements and dasha. Both birth times and locations are needed.|Compare emotion, attraction and long-term relationship patterns. Both birth times and locations are needed.'],
 ja:['質問|二人|方法','相手の気持ちをどう理解すればよいですか？|連絡を再開する前に何を考えればよいですか？|二人にとって結婚とは？|関係を長く育てるには？|好意なのか、思い違いなのか知りたいです。|再びつながる前に何を考えればよいですか？','出生情報なしで、質問とカードの象徴を読みます。相手の本心を確認するものではありません。|気質やパートナー像、共に暮らす条件を比べます。二人の正確な出生時刻と地域が必要です。|二つの命式から表現や生活習慣を比べます。時刻不明の場合、サバ・サーモンでは時刻の根拠を除いて読みます。|二人の本命宿から、惹かれ合い方、距離、関係での役割を読みます。|月・ナクシャトラ・関係の配置・ダシャーを読みます。二人の出生時刻と地域が必要です。|感情、惹かれ合い方、長期的な関係の接点を比べます。二人の出生時刻と地域が必要です。'],
 'zh-CN':['问题|两个人|方式','如何理解对方的情绪？|重新联系前应考虑什么？|婚姻对我们意味着什么？|什么有助于关系长久？|这是好感还是误会？|重新建立关系前应考虑什么？','无需出生资料，通过问题和牌面象征解读，不能核实对方的真实想法。|比较性格、伴侣期待与共同生活的条件，需要双方准确的出生时间和地区。|比较两张命盘的表达与生活模式。生时不明时，鲭鱼和三文鱼档位不使用时辰依据。|通过双方本命宿理解吸引、距离及关系中的角色。|结合月亮、月宿、关系宫位和大运周期解读，需要双方出生时间和地区。|比较情绪、吸引与长期关系的接点，需要双方出生时间和地区。'],
 'zh-TW':['問題|兩個人|方式','如何理解對方的情緒？|重新聯繫前應考慮什麼？|婚姻對我們意味著什麼？|什麼有助於關係長久？|這是好感還是誤會？|重新建立關係前應考慮什麼？','無需出生資料，透過問題和牌面象徵解讀，不能核實對方的真實想法。|比較性格、伴侶期待與共同生活的條件，需要雙方準確的出生時間和地區。|比較兩張命盤的表達與生活模式。生時不明時，鯖魚和鮭魚方案不使用時辰依據。|透過雙方本命宿理解吸引、距離及關係中的角色。|結合月亮、月宿、關係宮位和大運週期解讀，需要雙方出生時間和地區。|比較情緒、吸引與長期關係的接點，需要雙方出生時間和地區。'],
 vi:['Câu hỏi|Hai người|Phương pháp','Làm sao hiểu cảm xúc của đối phương?|Nên cân nhắc gì trước khi liên lạc lại?|Hôn nhân có ý nghĩa gì với hai người?|Điều gì giúp mối quan hệ bền lâu?|Đó là tán tỉnh hay hiểu lầm?|Nên cân nhắc gì trước khi kết nối lại?','Đọc câu hỏi qua biểu tượng lá bài, không cần thông tin sinh và không xác minh suy nghĩ riêng của đối phương.|So sánh tính cách, kỳ vọng về bạn đời và điều kiện sống chung. Cần giờ và nơi sinh chính xác của cả hai.|So sánh cách thể hiện và nếp sống trong hai lá số. Gói Cá thu và Cá hồi bỏ căn cứ theo giờ nếu không biết giờ sinh.|Đọc sức hút, khoảng cách và vai trò qua sao bản mệnh của hai người.|Kết hợp Mặt Trăng, nakshatra, vị trí quan hệ và dasha. Cần giờ và nơi sinh của cả hai.|So sánh cảm xúc, sức hút và mô hình gắn bó lâu dài. Cần giờ và nơi sinh của cả hai.'],
 hi:['प्रश्न|दो लोग|तरीका','उनकी भावनाओं को कैसे समझूँ?|दोबारा संपर्क से पहले क्या सोचूँ?|हमारे लिए विवाह का क्या अर्थ है?|रिश्ता लंबे समय तक कैसे बढ़ सकता है?|यह आकर्षण है या गलतफहमी?|दोबारा जुड़ने से पहले क्या सोचूँ?','जन्म विवरण के बिना कार्ड के प्रतीकों से प्रश्न समझें। इससे दूसरे व्यक्ति के निजी विचारों की पुष्टि नहीं होती।|स्वभाव, साथी से अपेक्षाएँ और साथ रहने की शर्तें देखें। दोनों का सही जन्म समय और स्थान चाहिए।|दोनों जन्म चार्ट में अभिव्यक्ति और दिनचर्या की तुलना करें। समय अज्ञात हो तो मैकेरल और सैल्मन में समय आधारित साक्ष्य नहीं लिया जाता।|दोनों जन्म तारों से आकर्षण, दूरी और रिश्ते की भूमिकाएँ समझें।|चंद्रमा, नक्षत्र, संबंध के भाव और दशा देखें। दोनों का जन्म समय और स्थान चाहिए।|भावना, आकर्षण और लंबे रिश्ते के पैटर्न की तुलना करें। दोनों का जन्म समय और स्थान चाहिए।'],
 es:['Pregunta|Dos personas|Método','¿Cómo puedo comprender sus emociones?|¿Qué conviene pensar antes de retomar el contacto?|¿Qué significaría casarnos?|¿Qué ayudaría a que la relación durase?|¿Es coqueteo o un malentendido?|¿Qué considerar antes de reconectar?','Explora tu pregunta con símbolos de las cartas, sin datos de nacimiento. No verifica pensamientos privados.|Compara temperamento, expectativas y convivencia. Requiere horas y lugares de nacimiento exactos de ambas personas.|Compara formas de expresión y hábitos en ambas cartas. Caballa y Salmón omiten la evidencia horaria cuando se desconoce la hora.|Explora atracción, distancia y papeles en la relación mediante ambas estrellas natales.|Considera la Luna, nakshatra, posiciones de relación y dasha. Requiere las horas y lugares de nacimiento de ambas personas.|Compara emoción, atracción y patrones a largo plazo. Requiere las horas y lugares de nacimiento de ambas personas.'],
 fr:['Question|Deux personnes|Méthode','Comment comprendre ses émotions ?|Que considérer avant de reprendre contact ?|Que signifierait le mariage pour nous ?|Qu’est-ce qui aiderait notre relation à durer ?|Est-ce de l’attirance ou un malentendu ?|Que considérer avant de renouer ?','Explorez votre question à travers les cartes, sans données de naissance. Cela ne vérifie pas les pensées privées.|Comparez tempérament, attentes envers un partenaire et vie commune. Les heures et lieux de naissance exacts des deux personnes sont nécessaires.|Comparez l’expression et les habitudes dans les deux thèmes. Maquereau et Saumon omettent les données horaires lorsque l’heure est inconnue.|Explorez attirance, distance et rôles relationnels à partir des deux étoiles natales.|Explorez la Lune, le nakshatra, les placements relationnels et les dasha. Les heures et lieux de naissance des deux personnes sont nécessaires.|Comparez émotions, attirance et dynamiques à long terme. Les heures et lieux de naissance des deux personnes sont nécessaires.'],
 de:['Frage|Zwei Personen|Methode','Wie kann ich die Gefühle besser verstehen?|Was sollte ich vor erneutem Kontakt bedenken?|Was würde eine Ehe für uns bedeuten?|Was könnte die Beziehung langfristig stärken?|Ist es Flirten oder ein Missverständnis?|Was sollte ich vor einer Wiederannäherung bedenken?','Betrachte deine Frage anhand von Kartensymbolen, ohne Geburtsdaten. Private Gedanken lassen sich damit nicht überprüfen.|Vergleiche Temperament, Partnererwartungen und Zusammenleben. Genaue Geburtszeiten und Orte beider Personen sind nötig.|Vergleiche Ausdruck und Alltagsmuster beider Charts. Makrele und Lachs lassen zeitbezogene Belege bei unbekannter Geburtszeit aus.|Betrachte Anziehung, Abstand und Rollen anhand beider Geburtssterne.|Betrachte Mond, Nakshatra, Beziehungspositionen und Dasha. Geburtszeiten und Orte beider Personen sind nötig.|Vergleiche Gefühle, Anziehung und langfristige Beziehungsmuster. Geburtszeiten und Orte beider Personen sind nötig.'],
 nl:['Vraag|Twee personen|Methode','Hoe kan ik hun gevoelens begrijpen?|Wat moet ik overwegen voor ik contact opneem?|Wat zou een huwelijk voor ons betekenen?|Wat kan onze relatie helpen voortduren?|Is het flirten of een misverstand?|Wat moet ik overwegen voordat we opnieuw verbinden?','Bekijk je vraag via kaartsymbolen zonder geboortegegevens. Dit kan privégedachten niet bevestigen.|Vergelijk karakter, partnerverwachtingen en samenleven. Exacte geboortetijden en plaatsen van beide personen zijn nodig.|Vergelijk uitdrukking en gewoonten in beide horoscopen. Makreel en Zalm laten tijdgebonden gegevens weg bij een onbekende geboortetijd.|Bekijk aantrekkingskracht, afstand en rollen via beide geboortesterren.|Bekijk de Maan, nakshatra, relatieposities en dasha. Geboortetijden en plaatsen van beide personen zijn nodig.|Vergelijk emotie, aantrekkingskracht en langdurige relatiepatronen. Geboortetijden en plaatsen van beide personen zijn nodig.'],
 ms:['Soalan|Dua orang|Kaedah','Bagaimana memahami perasaan mereka?|Apa yang perlu dipertimbangkan sebelum menghubungi semula?|Apakah makna perkahwinan bagi kami?|Apa yang membantu hubungan berkekalan?|Adakah ini tarikan atau salah faham?|Apa yang perlu difikirkan sebelum berhubung semula?','Teliti soalan melalui simbol kad tanpa maklumat kelahiran. Ini tidak mengesahkan fikiran peribadi orang lain.|Bandingkan sifat, jangkaan pasangan dan kehidupan bersama. Masa serta tempat lahir tepat kedua-duanya diperlukan.|Bandingkan cara meluahkan diri dan rutin kedua-dua carta. Ikan Kembung dan Salmon tidak menggunakan bukti masa jika waktu lahir tidak diketahui.|Teliti tarikan, jarak dan peranan hubungan melalui bintang kelahiran kedua-duanya.|Teliti Bulan, nakshatra, kedudukan hubungan dan dasha. Masa serta tempat lahir kedua-duanya diperlukan.|Bandingkan emosi, tarikan dan corak hubungan jangka panjang. Masa serta tempat lahir kedua-duanya diperlukan.'],
};
export function relationshipMethodCopy(locale:ReadingLocale='ko'){
 if(locale==='ko')return {steps:['질문','두 사람','상담 방식'],questions:relationshipQuestions,advice:relationshipAdvice};
 const [steps,questions,advice]=rows[locale].map(row=>row.split('|'));
 if(steps.length!==3||questions.length!==relationshipQuestions.length||advice.length!==domains.length)throw new Error('Relationship method copy shape: '+locale);
 return {steps,questions:relationshipQuestions.map((question,i)=>({...question,label:questions[i]})),advice:Object.fromEntries(domains.map((domain,i)=>[domain,advice[i]]))};
}
