import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';
import {shareCopy} from './share-copy';

type Localized={title:string;intro:string;pillarTitle:string;elementTitle:string;elementNote:string;day:string;stem:string;branch:string;noData:string;noChart:string;source:string;chapter:string;themes:{self:string;love:string;career:string;wealth:string};timing:string;action:string;page:string;full:string;close:string;publicTitle:string;publicNotice:string;sharePrivacy:string;linkConsent:string;linkExpires:string;linkCreate:string;linkRevoke:string;linkCopy:string;viewReading:string;disclaimer:string};
const text:Record<ReadingLocale,Localized>={
 ko:{title:'나의 사주 보고서',intro:'저장된 원국과 상담에서 읽은 나의 흐름',pillarTitle:'사주 원국',elementTitle:'오행의 균형',elementNote:'월령 가중치가 포함된 저장 수치입니다. 높고 낮음만으로 길흉을 단정하지 않습니다.',day:'일주 · 나',stem:'천간',branch:'지지',noData:'자료 없음',noChart:'저장된 원국을 확인할 수 없어 차트는 표시하지 않습니다.',source:'구매 당시 저장된 계산 근거',chapter:'자세한 풀이 보기',themes:{self:'나를 이루는 결',love:'관계의 방식',career:'일하는 방식',wealth:'돈을 다루는 방식'},timing:'저장된 시기의 흐름',action:'지금 해볼 수 있는 일',page:'쪽',full:'보고서 펼치기',close:'보고서 접기',publicTitle:'공유하는 나의 사주 한 장',publicNotice:'공유자가 선택한 공개용 차트 요소입니다. 운세는 선택을 돕는 참고 이야기입니다.',sharePrivacy:'공개 이미지는 허용된 차트 요소만 담습니다. 생년월일·출생지·질문 원문·상담 문장·결제 정보는 포함하지 않습니다. 공유 전에 내용을 확인해 주세요.',linkConsent:'공개 범위를 확인하고 링크 만들기에 동의합니다.',linkExpires:'링크는 30일 뒤 만료되고 언제든 해제할 수 있습니다.',linkCreate:'공개 링크 만들기',linkRevoke:'공유 해제',linkCopy:'링크 복사',viewReading:'내 운세 보기',disclaimer:'운세는 선택을 돕는 참고 이야기입니다.'},
 en:{title:'My Saju Report',intro:'My patterns from the chart and reading saved at purchase',pillarTitle:'Four Pillars',elementTitle:'Five Elements',elementNote:'Saved values include birth-month weighting. A higher or lower value does not determine good or bad fortune.',day:'Day pillar · me',stem:'Stem',branch:'Branch',noData:'No data',noChart:'The saved birth chart is unavailable, so no chart is shown.',source:'Calculation saved at purchase',chapter:'Read the full chapter',themes:{self:'My underlying pattern',love:'How I relate',career:'How I work',wealth:'How I handle money'},timing:'Saved timing',action:'What I can try now',page:'Page',full:'Open full report',close:'Close report',publicTitle:'My Saju at a glance',publicNotice:'These chart details were shared by the owner. Fortune readings are a guide for choices.',sharePrivacy:'The public image contains only allowed chart details. It excludes birth details, questions, counseling text, and payment information. Review it before sharing.',linkConsent:'I understand what will be public and agree to create a link.',linkExpires:'The link expires after 30 days and can be revoked at any time.',linkCreate:'Create public link',linkRevoke:'Revoke link',linkCopy:'Copy link',viewReading:'Explore my reading',disclaimer:'Fortune readings are a guide for choices.'},
 ja:{title:'私の四柱推命レポート',intro:'購入時に保存された命式と鑑定から読む私の流れ',pillarTitle:'四柱の命式',elementTitle:'五行のバランス',elementNote:'月令による重みを含む保存値です。数値の高低だけで吉凶は決まりません。',day:'日柱・自分',stem:'天干',branch:'地支',noData:'データなし',noChart:'保存された命式を確認できないため、チャートは表示しません。',source:'購入時に保存された計算根拠',chapter:'詳しい鑑定を読む',themes:{self:'私の基礎となる気質',love:'関係の築き方',career:'仕事の進め方',wealth:'お金との付き合い方'},timing:'保存された時期の流れ',action:'今できること',page:'ページ',full:'レポートを開く',close:'レポートを閉じる',publicTitle:'私の四柱推命を一枚で',publicNotice:'本人が公開した命式の要素です。鑑定は選択の参考としてご覧ください。',sharePrivacy:'公開画像には許可された命式の要素のみを載せます。生年月日・出生地・質問・鑑定文・決済情報は含みません。共有前に確認してください。',linkConsent:'公開範囲を確認し、リンク作成に同意します。',linkExpires:'リンクは30日後に期限切れとなり、いつでも解除できます。',linkCreate:'公開リンクを作成',linkRevoke:'共有を解除',linkCopy:'リンクをコピー',viewReading:'自分の鑑定を見る',disclaimer:'鑑定は選択の参考としてご覧ください。'},
 'zh-CN':{title:'我的四柱命理报告',intro:'从购买时保存的命盘与解读看自己的走势',pillarTitle:'四柱命盘',elementTitle:'五行平衡',elementNote:'保存数值包含月令权重。不能仅凭高低判断吉凶。',day:'日柱 · 自己',stem:'天干',branch:'地支',noData:'无资料',noChart:'无法确认已保存的命盘，因此不显示图表。',source:'购买时保存的计算依据',chapter:'阅读完整解读',themes:{self:'我的基本气质',love:'关系模式',career:'工作方式',wealth:'理财方式'},timing:'已保存的运势阶段',action:'现在可以做的事',page:'页',full:'展开报告',close:'收起报告',publicTitle:'我的四柱一页摘要',publicNotice:'这些命盘信息由本人选择公开。运势仅供决策时参考。',sharePrivacy:'公开图片只包含允许分享的命盘信息，不包含出生资料、问题、咨询文字和付款信息。分享前请确认。',linkConsent:'我已确认公开范围并同意创建链接。',linkExpires:'链接在30天后失效，也可以随时撤销。',linkCreate:'创建公开链接',linkRevoke:'撤销分享',linkCopy:'复制链接',viewReading:'查看我的运势',disclaimer:'运势仅供决策时参考。'},
 'zh-TW':{title:'我的四柱命理報告',intro:'從購買時儲存的命盤與解讀看自己的走勢',pillarTitle:'四柱命盤',elementTitle:'五行平衡',elementNote:'儲存數值包含月令權重，不能只憑高低判斷吉凶。',day:'日柱 · 自己',stem:'天干',branch:'地支',noData:'無資料',noChart:'無法確認已儲存的命盤，因此不顯示圖表。',source:'購買時儲存的計算依據',chapter:'閱讀完整解讀',themes:{self:'我的基本氣質',love:'關係模式',career:'工作方式',wealth:'理財方式'},timing:'已儲存的運勢階段',action:'現在可以做的事',page:'頁',full:'展開報告',close:'收起報告',publicTitle:'我的四柱一頁摘要',publicNotice:'這些命盤資訊由本人選擇公開。運勢僅供決策時參考。',sharePrivacy:'公開圖片只包含允許分享的命盤資訊，不包含出生資料、問題、諮詢文字和付款資訊。分享前請確認。',linkConsent:'我已確認公開範圍並同意建立連結。',linkExpires:'連結在30天後失效，也可以隨時撤銷。',linkCreate:'建立公開連結',linkRevoke:'撤銷分享',linkCopy:'複製連結',viewReading:'查看我的運勢',disclaimer:'運勢僅供決策時參考。'},
 vi:{title:'Báo cáo Tứ trụ của tôi',intro:'Dòng chảy từ lá số và lời luận đã lưu khi mua',pillarTitle:'Tứ trụ',elementTitle:'Cân bằng ngũ hành',elementNote:'Giá trị lưu có tính trọng số tháng sinh. Không thể kết luận tốt xấu chỉ từ độ cao thấp.',day:'Trụ ngày · tôi',stem:'Thiên can',branch:'Địa chi',noData:'Không có dữ liệu',noChart:'Không thể xác nhận lá số đã lưu nên không hiển thị biểu đồ.',source:'Căn cứ tính toán lưu khi mua',chapter:'Đọc luận giải đầy đủ',themes:{self:'Nền tảng tính cách',love:'Cách kết nối',career:'Cách làm việc',wealth:'Cách quản lý tiền'},timing:'Giai đoạn đã lưu',action:'Việc có thể làm lúc này',page:'Trang',full:'Mở báo cáo',close:'Thu gọn báo cáo',publicTitle:'Tứ trụ của tôi trong một trang',publicNotice:'Các chi tiết này do chủ sở hữu chọn công khai. Chỉ dùng để tham khảo khi quyết định.',sharePrivacy:'Ảnh công khai chỉ có các chi tiết lá số được phép chia sẻ; không có dữ liệu sinh, câu hỏi, lời luận hay thông tin thanh toán. Hãy kiểm tra trước khi chia sẻ.',linkConsent:'Tôi đã xem phạm vi công khai và đồng ý tạo liên kết.',linkExpires:'Liên kết hết hạn sau 30 ngày và có thể thu hồi bất kỳ lúc nào.',linkCreate:'Tạo liên kết công khai',linkRevoke:'Thu hồi liên kết',linkCopy:'Sao chép liên kết',viewReading:'Xem vận mệnh của tôi',disclaimer:'Chỉ dùng để tham khảo khi quyết định.'},
 hi:{title:'मेरी साजू रिपोर्ट',intro:'खरीद के समय सहेजे चार्ट और परामर्श से मेरी प्रवृत्तियाँ',pillarTitle:'चार स्तंभ',elementTitle:'पाँच तत्वों का संतुलन',elementNote:'सहेजे मानों में जन्म-माह का भार शामिल है। अधिक या कम मान अपने आप शुभ-अशुभ तय नहीं करते।',day:'दिन का स्तंभ · मैं',stem:'स्वर्गीय तना',branch:'पृथ्वी शाखा',noData:'डेटा उपलब्ध नहीं',noChart:'सहेजा जन्म चार्ट उपलब्ध नहीं है, इसलिए चार्ट नहीं दिखाया गया।',source:'खरीद के समय सहेजी गणना',chapter:'पूरा विवरण पढ़ें',themes:{self:'मेरा मूल स्वभाव',love:'संबंधों का ढंग',career:'काम करने का ढंग',wealth:'धन संभालने का ढंग'},timing:'सहेजे गए समय चरण',action:'अभी क्या कर सकते हैं',page:'पृष्ठ',full:'पूरी रिपोर्ट खोलें',close:'रिपोर्ट बंद करें',publicTitle:'मेरी साजू एक नज़र में',publicNotice:'ये विवरण मालिक ने सार्वजनिक किए हैं। रीडिंग चुनाव के लिए संदर्भ है।',sharePrivacy:'सार्वजनिक चित्र में केवल अनुमत चार्ट विवरण हैं। जन्म जानकारी, प्रश्न, परामर्श और भुगतान जानकारी शामिल नहीं हैं। साझा करने से पहले जाँचें।',linkConsent:'मैंने सार्वजनिक जानकारी देख ली है और लिंक बनाने की सहमति देता/देती हूँ।',linkExpires:'लिंक 30 दिन बाद समाप्त होता है और कभी भी हटाया जा सकता है।',linkCreate:'सार्वजनिक लिंक बनाएँ',linkRevoke:'लिंक हटाएँ',linkCopy:'लिंक कॉपी करें',viewReading:'मेरी रीडिंग देखें',disclaimer:'रीडिंग चुनाव के लिए संदर्भ है।'},
 es:{title:'Mi informe de Saju',intro:'Mis patrones según la carta y la lectura guardadas al comprar',pillarTitle:'Cuatro pilares',elementTitle:'Equilibrio de los cinco elementos',elementNote:'Los valores guardados incluyen la ponderación del mes de nacimiento. Un valor alto o bajo no determina la suerte.',day:'Pilar del día · yo',stem:'Tronco',branch:'Rama',noData:'Sin datos',noChart:'La carta de nacimiento guardada no está disponible; no se muestra el gráfico.',source:'Cálculo guardado al comprar',chapter:'Leer la interpretación completa',themes:{self:'Mi carácter de base',love:'Mi forma de relacionarme',career:'Mi forma de trabajar',wealth:'Mi relación con el dinero'},timing:'Etapas guardadas',action:'Qué puedo intentar ahora',page:'Página',full:'Abrir informe completo',close:'Cerrar informe',publicTitle:'Mi Saju de un vistazo',publicNotice:'Estos detalles fueron compartidos por su titular. La lectura orienta las decisiones.',sharePrivacy:'La imagen pública solo incluye detalles permitidos de la carta. No incluye datos de nacimiento, preguntas, consulta ni pago. Revísala antes de compartir.',linkConsent:'He revisado lo que será público y acepto crear el enlace.',linkExpires:'El enlace caduca tras 30 días y puede revocarse en cualquier momento.',linkCreate:'Crear enlace público',linkRevoke:'Revocar enlace',linkCopy:'Copiar enlace',viewReading:'Ver mi lectura',disclaimer:'La lectura orienta las decisiones.'},
 fr:{title:'Mon rapport Saju',intro:'Mes tendances selon le thème et la lecture enregistrés lors de l’achat',pillarTitle:'Quatre piliers',elementTitle:'Équilibre des cinq éléments',elementNote:'Les valeurs enregistrées tiennent compte du mois de naissance. Une valeur élevée ou faible ne détermine pas la chance.',day:'Pilier du jour · moi',stem:'Tronc',branch:'Branche',noData:'Aucune donnée',noChart:'Le thème de naissance enregistré est indisponible ; aucun graphique ne s’affiche.',source:'Calcul enregistré lors de l’achat',chapter:'Lire l’interprétation complète',themes:{self:'Mon tempérament',love:'Ma façon de créer des liens',career:'Ma façon de travailler',wealth:'Ma relation à l’argent'},timing:'Périodes enregistrées',action:'Ce que je peux essayer maintenant',page:'Page',full:'Ouvrir le rapport complet',close:'Fermer le rapport',publicTitle:'Mon Saju en un regard',publicNotice:'Ces éléments ont été rendus publics par leur propriétaire. La lecture aide à réfléchir aux choix.',sharePrivacy:'L’image publique ne contient que les éléments autorisés du thème. Elle exclut les données de naissance, les questions, la consultation et le paiement. Vérifiez-la avant de partager.',linkConsent:'J’ai vérifié les données publiques et j’accepte de créer un lien.',linkExpires:'Le lien expire après 30 jours et peut être révoqué à tout moment.',linkCreate:'Créer un lien public',linkRevoke:'Révoquer le lien',linkCopy:'Copier le lien',viewReading:'Voir ma lecture',disclaimer:'La lecture aide à réfléchir aux choix.'},
 de:{title:'Mein Saju-Bericht',intro:'Meine Muster aus dem beim Kauf gespeicherten Horoskop und der Deutung',pillarTitle:'Vier Säulen',elementTitle:'Gleichgewicht der fünf Elemente',elementNote:'Die gespeicherten Werte berücksichtigen den Geburtsmonat. Hohe oder niedrige Werte bestimmen kein gutes oder schlechtes Schicksal.',day:'Tagessäule · ich',stem:'Himmelsstamm',branch:'Erdzweig',noData:'Keine Daten',noChart:'Das gespeicherte Geburtshoroskop ist nicht verfügbar; es wird keine Grafik angezeigt.',source:'Beim Kauf gespeicherte Berechnung',chapter:'Ausführliche Deutung lesen',themes:{self:'Mein Grundmuster',love:'Meine Beziehungen',career:'Meine Arbeitsweise',wealth:'Mein Umgang mit Geld'},timing:'Gespeicherte Zeitabschnitte',action:'Was ich jetzt versuchen kann',page:'Seite',full:'Gesamten Bericht öffnen',close:'Bericht schließen',publicTitle:'Mein Saju auf einen Blick',publicNotice:'Diese Details wurden vom Eigentümer freigegeben. Deutungen helfen bei Entscheidungen.',sharePrivacy:'Das öffentliche Bild enthält nur erlaubte Horoskopdetails. Geburtsdaten, Fragen, Beratungstext und Zahlungsdaten sind ausgeschlossen. Bitte vor dem Teilen prüfen.',linkConsent:'Ich habe den öffentlichen Inhalt geprüft und stimme dem Link zu.',linkExpires:'Der Link läuft nach 30 Tagen ab und kann jederzeit widerrufen werden.',linkCreate:'Öffentlichen Link erstellen',linkRevoke:'Link widerrufen',linkCopy:'Link kopieren',viewReading:'Meine Deutung ansehen',disclaimer:'Deutungen helfen bei Entscheidungen.'},
 nl:{title:'Mijn Saju-rapport',intro:'Mijn patronen uit de bij aankoop opgeslagen kaart en duiding',pillarTitle:'Vier pijlers',elementTitle:'Balans van de vijf elementen',elementNote:'De opgeslagen waarden wegen de geboortemaand mee. Een hoge of lage waarde bepaalt geen goed of slecht lot.',day:'Dagpijler · ik',stem:'Hemelse stam',branch:'Aardse tak',noData:'Geen gegevens',noChart:'De opgeslagen geboortekaart is niet beschikbaar; er wordt geen grafiek getoond.',source:'Berekening opgeslagen bij aankoop',chapter:'Volledige uitleg lezen',themes:{self:'Mijn basispatroon',love:'Mijn relaties',career:'Mijn manier van werken',wealth:'Mijn omgang met geld'},timing:'Opgeslagen perioden',action:'Wat ik nu kan proberen',page:'Pagina',full:'Volledig rapport openen',close:'Rapport sluiten',publicTitle:'Mijn Saju in één oogopslag',publicNotice:'Deze details zijn door de eigenaar gedeeld. De duiding helpt bij keuzes.',sharePrivacy:'De openbare afbeelding bevat alleen toegestane kaartdetails. Geboortegegevens, vragen, adviestekst en betaalgegevens staan er niet in. Controleer dit voor het delen.',linkConsent:'Ik heb de openbare inhoud gecontroleerd en ga akkoord met de link.',linkExpires:'De link verloopt na 30 dagen en kan altijd worden ingetrokken.',linkCreate:'Openbare link maken',linkRevoke:'Link intrekken',linkCopy:'Link kopiëren',viewReading:'Mijn duiding bekijken',disclaimer:'De duiding helpt bij keuzes.'},
 ms:{title:'Laporan Saju saya',intro:'Corak saya daripada carta dan bacaan yang disimpan semasa pembelian',pillarTitle:'Empat tiang',elementTitle:'Keseimbangan lima unsur',elementNote:'Nilai tersimpan mengambil kira berat bulan kelahiran. Nilai tinggi atau rendah tidak menentukan nasib baik atau buruk.',day:'Tiang hari · saya',stem:'Batang langit',branch:'Cabang bumi',noData:'Tiada data',noChart:'Carta kelahiran tersimpan tidak tersedia, jadi carta tidak dipaparkan.',source:'Pengiraan disimpan semasa pembelian',chapter:'Baca tafsiran penuh',themes:{self:'Corak asas saya',love:'Cara saya berhubung',career:'Cara saya bekerja',wealth:'Cara saya mengurus wang'},timing:'Tempoh yang disimpan',action:'Apa yang boleh saya cuba sekarang',page:'Halaman',full:'Buka laporan penuh',close:'Tutup laporan',publicTitle:'Saju saya sepintas lalu',publicNotice:'Butiran ini dikongsi oleh pemiliknya. Bacaan membantu membuat pilihan.',sharePrivacy:'Imej awam hanya mengandungi butiran carta yang dibenarkan. Maklumat kelahiran, soalan, teks rundingan dan bayaran tidak disertakan. Semak sebelum berkongsi.',linkConsent:'Saya telah menyemak kandungan awam dan bersetuju membuat pautan.',linkExpires:'Pautan tamat selepas 30 hari dan boleh dibatalkan pada bila-bila masa.',linkCreate:'Buat pautan awam',linkRevoke:'Batalkan pautan',linkCopy:'Salin pautan',viewReading:'Lihat bacaan saya',disclaimer:'Bacaan membantu membuat pilihan.'}
};
export function sajuReportCopy(locale?:ReadingLocale){return text[locale&&locale in text?locale:'ko'];}
const linkStatus:Record<ReadingLocale,[string,string,string,string,string,string]>={
 ko:['공개 링크가 만들어졌어요.','링크를 만들지 못했어요. 다시 시도해 주세요.','공개 링크를 해제했어요. 저장된 이미지는 회수할 수 없습니다.','공유 해제에 실패했어요. 다시 시도해 주세요.','공개 링크를 복사했어요.','직접 복사할 링크:'],
 en:['Public link created.','Could not create the link. Please try again.','Public link revoked. Saved images cannot be recalled.','Could not revoke the link. Please try again.','Public link copied.','Copy this link:'],
 ja:['公開リンクを作成しました。','リンクを作成できませんでした。もう一度お試しください。','公開リンクを解除しました。保存済みの画像は回収できません。','解除できませんでした。もう一度お試しください。','公開リンクをコピーしました。','直接コピーするリンク：'],
 'zh-CN':['公开链接已创建。','无法创建链接，请重试。','公开链接已撤销。已保存的图片无法收回。','撤销失败，请重试。','公开链接已复制。','请复制此链接：'],
 'zh-TW':['公開連結已建立。','無法建立連結，請再試一次。','公開連結已撤銷。已儲存的圖片無法收回。','撤銷失敗，請再試一次。','公開連結已複製。','請複製此連結：'],
 vi:['Đã tạo liên kết công khai.','Không tạo được liên kết. Vui lòng thử lại.','Đã thu hồi liên kết. Không thể thu hồi ảnh đã lưu.','Không thể thu hồi liên kết. Vui lòng thử lại.','Đã sao chép liên kết.','Sao chép liên kết này:'],
 hi:['सार्वजनिक लिंक बन गया है।','लिंक नहीं बन सका। फिर कोशिश करें।','लिंक हटा दिया गया है। सहेजी गई तस्वीरें वापस नहीं ली जा सकतीं।','लिंक नहीं हट सका। फिर कोशिश करें।','लिंक कॉपी हो गया है।','यह लिंक कॉपी करें:'],
 es:['Enlace público creado.','No se pudo crear el enlace. Inténtalo de nuevo.','Enlace revocado. Las imágenes guardadas no se pueden retirar.','No se pudo revocar el enlace. Inténtalo de nuevo.','Enlace público copiado.','Copia este enlace:'],
 fr:['Lien public créé.','Impossible de créer le lien. Réessayez.','Lien révoqué. Les images enregistrées ne peuvent pas être retirées.','Impossible de révoquer le lien. Réessayez.','Lien public copié.','Copiez ce lien :'],
 de:['Öffentlicher Link erstellt.','Link konnte nicht erstellt werden. Bitte erneut versuchen.','Link widerrufen. Gespeicherte Bilder können nicht zurückgerufen werden.','Link konnte nicht widerrufen werden. Bitte erneut versuchen.','Öffentlichen Link kopiert.','Diesen Link kopieren:'],
 nl:['Openbare link gemaakt.','De link kon niet worden gemaakt. Probeer opnieuw.','Link ingetrokken. Opgeslagen afbeeldingen kunnen niet worden teruggehaald.','Intrekken mislukt. Probeer opnieuw.','Openbare link gekopieerd.','Kopieer deze link:'],
 ms:['Pautan awam telah dibuat.','Pautan gagal dibuat. Cuba lagi.','Pautan dibatalkan. Imej yang telah disimpan tidak boleh ditarik balik.','Pautan gagal dibatalkan. Cuba lagi.','Pautan awam disalin.','Salin pautan ini:']
};
export function sajuShareControls(locale?:ReadingLocale){const copy=shareCopy(locale),[linkReady,linkError,linkRemoved,linkRemoveError,linkCopied,copyManual]=linkStatus[locale&&locale in linkStatus?locale:'ko'];return {save:copy.save,share:copy.summary,openSheet:copy.native,kakao:copy.kakao,imageLoading:copy.imageLoading,imageError:copy.imageError,imageReady:copy.preview,copied:copy.copied,copyFailed:copy.fallback,opened:copy.opened,cancelled:copy.cancelled,failed:copy.failed,downloaded:copy.downloaded,previewAlt:copy.previewAlt,linkReady,linkError,linkRemoved,linkRemoveError,linkCopied,copyManual};}
const promptText:Record<ReadingLocale,[string,string,string,string,string,string,string]>={
 ko:['외부 AI로 이미지 다듬기','저장된 결과만 넣은 제작 요청문입니다. 외부 서비스에 붙여 넣기 전에 개인적인 문장이 있는지 확인해 주세요.','프롬프트 복사','프롬프트를 복사했어요. 원하는 이미지 생성 서비스에 붙여 넣고 영냥이 에셋을 첨부하세요.','복사하지 못했어요. 아래 문장을 직접 선택해 주세요.','영냥이 에셋 저장','제작 요청문 보기'],
 en:['Refine with an external AI','This prompt uses your saved result. Review personal passages before pasting it into another service.','Copy prompt','Prompt copied. Paste it into your image service and attach the Yeongnyangi asset.','Could not copy. Select the text below.','Save Yeongnyangi asset','Show image prompt'],
 ja:['外部AIで画像を整える','保存された結果を使った依頼文です。他のサービスに貼る前に個人的な文章を確認してください。','プロンプトをコピー','コピーしました。画像生成サービスに貼り、ヨンニャンイの画像を添付してください。','コピーできませんでした。下の文章を選択してください。','ヨンニャンイ画像を保存','依頼文を見る'],
 'zh-CN':['用外部AI优化图片','提示词使用已保存的结果。粘贴到其他服务前，请检查私人内容。','复制提示词','已复制。请粘贴到图像服务并附上英喵角色图。','复制失败，请手动选择下方文字。','保存英喵角色图','查看图像提示词'],
 'zh-TW':['用外部AI優化圖片','提示詞使用已儲存的結果。貼到其他服務前，請檢查私人內容。','複製提示詞','已複製。請貼到圖片服務並附上角色圖。','複製失敗，請手動選取下方文字。','儲存角色圖片','查看圖片提示詞'],
 vi:['Tinh chỉnh ảnh bằng AI khác','Lời nhắc dùng kết quả đã lưu. Hãy xem lại nội dung riêng tư trước khi dán vào dịch vụ khác.','Sao chép lời nhắc','Đã sao chép. Dán vào dịch vụ tạo ảnh và đính kèm hình Yeongnyangi.','Không sao chép được. Hãy chọn văn bản bên dưới.','Lưu hình Yeongnyangi','Xem lời nhắc tạo ảnh'],
 hi:['बाहरी AI से छवि सँवारें','यह निर्देश सहेजे परिणाम का उपयोग करता है। दूसरी सेवा में डालने से पहले निजी पाठ जाँच लें।','प्रॉम्प्ट कॉपी करें','प्रॉम्प्ट कॉपी हो गया। छवि सेवा में डालें और योंगन्यांगी चित्र जोड़ें।','कॉपी नहीं हुआ। नीचे का पाठ चुनें।','योंगन्यांगी चित्र सहेजें','छवि निर्देश देखें'],
 es:['Mejorar la imagen con otra IA','El texto usa el resultado guardado. Revisa los datos personales antes de pegarlo en otro servicio.','Copiar instrucción','Copiado. Pégalo en el servicio de imágenes y adjunta el personaje de Yeongnyangi.','No se pudo copiar. Selecciona el texto de abajo.','Guardar personaje','Ver instrucción de imagen'],
 fr:['Affiner avec une autre IA','Cette demande utilise votre résultat enregistré. Vérifiez les passages privés avant de la coller ailleurs.','Copier la demande','Copié. Collez-la dans un service d’image et joignez le personnage Yeongnyangi.','Copie impossible. Sélectionnez le texte ci-dessous.','Enregistrer le personnage','Voir la demande d’image'],
 de:['Bild mit externer KI verfeinern','Diese Vorlage enthält Ihr gespeichertes Ergebnis. Prüfen Sie private Stellen, bevor Sie sie anderswo einfügen.','Vorlage kopieren','Kopiert. In den Bilddienst einfügen und die Yeongnyangi-Grafik anhängen.','Kopieren fehlgeschlagen. Text unten auswählen.','Yeongnyangi-Grafik speichern','Bildvorlage anzeigen'],
 nl:['Afbeelding verfijnen met externe AI','Deze opdracht gebruikt het opgeslagen resultaat. Controleer privétekst voordat je hem elders plakt.','Opdracht kopiëren','Gekopieerd. Plak in de afbeeldingsdienst en voeg Yeongnyangi toe.','Kopiëren mislukt. Selecteer de tekst hieronder.','Yeongnyangi-afbeelding opslaan','Afbeeldingsopdracht tonen'],
 ms:['Perhalus imej dengan AI luar','Arahan ini menggunakan hasil tersimpan. Semak teks peribadi sebelum menampalnya pada perkhidmatan lain.','Salin arahan','Disalin. Tampal pada perkhidmatan imej dan lampirkan aset Yeongnyangi.','Gagal menyalin. Pilih teks di bawah.','Simpan aset Yeongnyangi','Lihat arahan imej']
};
export function sajuPromptCopy(locale?:ReadingLocale){const [title,privacy,copy,copied,error,saveAsset,show]=promptText[locale&&locale in promptText?locale:'ko'];return {title,privacy,copy,copied,error,saveAsset,show};}
