import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';

const ko={
 section:'영냥이 타로 드로우 의식',focusTitle:'질문을 마음에 담아봐',focusBody:'눈을 감고, 지금 가장 알고 싶은 장면을 천천히 떠올려 봐. 세 번 숨을 고르면 카드를 섞을게.',breath:'호흡 가이드',ready:'질문에 집중했어',shuffleTitle:'달빛 아래에서 카드를 섞는 중',shuffleBody:'영냥이가 앞발로 덱을 고르고 있어. 마음이 멈추는 순간 셔플을 멈춰줘.',stopShuffle:'이 순간에 멈추기',chooseTitle:'끌리는 자리를 골라줘',chooseBody:'카드는 결제된 상담에 이미 안전하게 저장되어 있어. 여기서는 질문에 마음을 모으며 자리를 직접 골라.',chooseProgress:(n:number,total:number)=>`${total}장 중 ${n}장 선택`,cardBack:(n:number)=>`카드 뒷면 ${n}`,selected:'선택됨',confirm:'선택 확정하기',revealTitle:'카드를 한 장씩 공개해봐',revealBody:'빛나는 카드부터 차례로 눌러줘. 저장된 카드의 순서와 정·역방향은 바뀌지 않아.',revealCard:(n:number)=>`${n}번째 카드 공개`,upright:'정방향',reversed:'역방향',readingTitle:'영냥이가 카드를 읽고 있다냥…',readingBody:'공개한 카드와 질문을 맞춰 보며 저장된 상담으로 이어가는 중이야.',continue:'영냥이 상담 펼치기',soundOn:'효과음 켜짐',soundOff:'효과음 꺼짐',soundToggle:'카드 공개 효과음',restore:'이 상담의 드로우 의식을 이어서 보여주고 있어.',major:'메이저 아르카나',
};
type Copy=typeof ko;
const en:Copy={section:'Yeongnyangi tarot draw ritual',focusTitle:'Hold your question in mind',focusBody:'Close your eyes and picture what you most want to understand. Take three slow breaths before the cards are shuffled.',breath:'Breathing guide',ready:'I am focused',shuffleTitle:'Shuffling under the moonlight',shuffleBody:'Yeongnyangi is tapping the deck into place. Stop the shuffle when the moment feels right.',stopShuffle:'Stop the shuffle here',chooseTitle:'Choose the positions that call to you',chooseBody:'Your paid reading already has a securely saved draw. Choosing here is a way to focus your attention on each position.',chooseProgress:(n,total)=>`${n} of ${total} selected`,cardBack:n=>`Card back ${n}`,selected:'Selected',confirm:'Confirm selection',revealTitle:'Reveal the cards one by one',revealBody:'Open the glowing card in order. The saved order and upright or reversed direction never change.',revealCard:n=>`Reveal card ${n}`,upright:'Upright',reversed:'Reversed',readingTitle:'Yeongnyangi is reading the cards…',readingBody:'Matching your question with the revealed cards and continuing to your saved reading.',continue:'Open my reading',soundOn:'Sound on',soundOff:'Sound off',soundToggle:'Card reveal sound',restore:'Continuing this reading’s saved draw ritual.',major:'Major Arcana'};
const ja:Copy={section:'ヨンニャンイのタロットドロー儀式',focusTitle:'質問を心に浮かべて',focusBody:'目を閉じて、いちばん知りたい場面をゆっくり思い浮かべてください。三回呼吸を整えたらカードを混ぜます。',breath:'呼吸ガイド',ready:'質問に集中できた',shuffleTitle:'月明かりの下でシャッフル中',shuffleBody:'ヨンニャンイが前足でデッキを整えています。心が止まる瞬間にシャッフルを止めてください。',stopShuffle:'この瞬間で止める',chooseTitle:'惹かれる位置を選んで',chooseBody:'支払い済みの鑑定カードはすでに安全に保存されています。ここでは質問に心を向けながら位置を選びます。',chooseProgress:(n,total)=>`${total}枚中${n}枚を選択`,cardBack:n=>`カード裏面${n}`,selected:'選択済み',confirm:'選択を確定',revealTitle:'一枚ずつカードを公開して',revealBody:'光るカードから順に押してください。保存済みの順番と正位置・逆位置は変わりません。',revealCard:n=>`${n}枚目を公開`,upright:'正位置',reversed:'逆位置',readingTitle:'ヨンニャンイがカードを読んでいるにゃ…',readingBody:'公開したカードと質問を照らし合わせ、保存済みの鑑定へ進んでいます。',continue:'鑑定を開く',soundOn:'効果音オン',soundOff:'効果音オフ',soundToggle:'カード公開の効果音',restore:'この鑑定の保存済みドロー儀式を続けています。',major:'大アルカナ'};
const zhCN:Copy={section:'灵喵塔罗抽牌仪式',focusTitle:'把问题放在心里',focusBody:'闭上眼睛，慢慢想起你最想了解的画面。完成三次呼吸后，我们开始洗牌。',breath:'呼吸引导',ready:'我已集中注意',shuffleTitle:'正在月光下洗牌',shuffleBody:'灵喵正在用前爪轻点牌组。感觉合适时，请停下洗牌。',stopShuffle:'停在这一刻',chooseTitle:'选择吸引你的牌位',chooseBody:'本次付费咨询的牌面已经安全保存。这里的选择用于让你把注意力放在每个牌位上。',chooseProgress:(n,total)=>`已选 ${n}/${total} 张`,cardBack:n=>`牌背 ${n}`,selected:'已选择',confirm:'确认选择',revealTitle:'逐张翻开卡牌',revealBody:'请按顺序翻开正在发光的牌。已保存的顺序与正逆位不会改变。',revealCard:n=>`翻开第 ${n} 张牌`,upright:'正位',reversed:'逆位',readingTitle:'灵喵正在解读卡牌…',readingBody:'正在结合你的问题与已翻开的卡牌，继续读取已保存的咨询。',continue:'展开灵喵咨询',soundOn:'音效已开',soundOff:'音效已关',soundToggle:'翻牌音效',restore:'正在继续本次咨询已保存的抽牌仪式。',major:'大阿尔卡那'};
const zhTW:Copy={section:'靈喵塔羅抽牌儀式',focusTitle:'把問題放在心裡',focusBody:'閉上眼睛，慢慢想起你最想了解的畫面。完成三次呼吸後，我們開始洗牌。',breath:'呼吸引導',ready:'我已集中注意',shuffleTitle:'正在月光下洗牌',shuffleBody:'靈喵正在用前爪輕點牌組。感覺合適時，請停下洗牌。',stopShuffle:'停在這一刻',chooseTitle:'選擇吸引你的牌位',chooseBody:'本次付費諮詢的牌面已經安全保存。這裡的選擇用來讓你把注意力放在每個牌位上。',chooseProgress:(n,total)=>`已選 ${n}/${total} 張`,cardBack:n=>`牌背 ${n}`,selected:'已選擇',confirm:'確認選擇',revealTitle:'逐張翻開牌卡',revealBody:'請依序翻開正在發光的牌。已保存的順序與正逆位不會改變。',revealCard:n=>`翻開第 ${n} 張牌`,upright:'正位',reversed:'逆位',readingTitle:'靈喵正在解讀牌卡…',readingBody:'正在結合你的問題與已翻開的牌卡，繼續讀取已保存的諮詢。',continue:'展開靈喵諮詢',soundOn:'音效已開',soundOff:'音效已關',soundToggle:'翻牌音效',restore:'正在繼續本次諮詢已保存的抽牌儀式。',major:'大阿爾克那'};

export const tarotRitualCopy=(locale?:ReadingLocale):Copy=>locale==='ko'||!locale?ko:locale==='ja'?ja:locale==='zh-CN'?zhCN:locale==='zh-TW'?zhTW:en;
