// Korean-only chrome for the v3 question-first tarot order and card pick (UI is 해요체; 영냥이's own lines end in ~냥).
export const tarotSpreadCopy={
 questionHeading:'무엇이 궁금해요?',
 questionIntro:'고민을 한 문장으로 적어 주세요. 질문의 모양을 보고 영냥이가 맞는 카드 배열을 골라 줘요.',
 presetsLabel:'자주 묻는 질문',
 questionLabel:'내 질문',
 questionPlaceholder:'예: 지금 회사에 남을지 옮길지 고민돼요.',
 questionPrivacy:'생년월일이나 상대의 이름·연락처는 필요 없어요. 질문은 해석에만 쓰고 공유 화면에는 나오지 않아요.',
 recommendHeading:'영냥이가 고른 배열',
 recommendEmpty:'질문을 적으면 배열을 골라 줄게냥.',
 primary:'추천',
 alternative:'다른 선택',
 cards:(n:number)=>`${n}장`,
 tierNeeded:(fish:string)=>`${fish} 이상`,
 chooseDirect:'스프레드 직접 선택',
 groupOriginal:'영냥이 배열',
 groupTraditional:'전통 배열',
 inputsHeading:'조금만 더 알려 주세요',
 inputsOptional:'선택 사항이에요. 비워 두면 질문 문장에서 읽어요.',
 optionA:'선택지 A',optionB:'선택지 B',
 optionPlaceholderA:'예: 지금 회사',optionPlaceholderB:'예: 제안받은 회사',
 periodLabel:'살펴볼 기간',
 relationLabel:'지금 관계',
 relationNone:'말하지 않을래요',
 previewHeading:'이번 배열이 살펴보는 것',
 previewPositions:'자리와 읽는 순서',
 tierRaised:(fish:string,n:number)=>`${n}장 배열이라 ${fish}로 바꿨어요. 가격을 확인해 주세요.`,
 tierLocked:(n:number,fish:string)=>`${n}장 배열은 ${fish} 이상`,
 // card pick
 pickHeading:'카드를 골라 주세요',
 pickIntro:'78장을 섞어 엎어 두었어요. 마음이 가는 카드를 자리 순서대로 골라 주세요. 고른 카드는 결제 뒤에 펼쳐요.',
 pickProgress:(k:number,n:number)=>`${k} / ${n}장`,
 pickNow:(label:string)=>`지금 고르는 자리: ${label}`,
 pickDone:'모든 자리를 골랐어요.',
 pickCard:(n:number)=>`${n}번째 엎어 둔 카드`,
 pickedAs:(label:string)=>`${label} 자리로 고름`,
 undo:'마지막 선택 되돌리기',
 auto:'영냥이에게 맡기기',
 autoHint:'같은 덱에서 영냥이가 대신 뽑아요. 직접 고른 것과 똑같이 저장돼요.',
 confirm:'이 카드로 정하고 결제하기',
 saving:'카드를 저장하는 중이에요…',
 saved:'카드를 저장했어요. 결제 뒤에 펼쳐 볼게요.',
 toCheckout:'결제하러 가기',
 sealed:'고른 카드는 저장됐고, 결제 뒤에 펼쳐요. 새로고침해도 바뀌지 않아요.',
 failed:'카드를 저장하지 못했어요. 고른 순서는 그대로 있으니 다시 눌러 주세요.',
 mapLabel:(title:string)=>`${title} 배열 지도`,
 // after payment
 revealHeading:'고른 카드를 펼쳐요',
 revealIntro:'결제 전에 직접 고른 카드예요. 읽는 순서대로 한 장씩 펼쳐 주세요. 순서와 정·역방향은 바뀌지 않아요.',
 revealNext:(n:number,label:string)=>`${n}번째 카드 펼치기 · ${label}`,
 revealDone:'모든 카드를 펼쳤어요.',
 resultHeading:'이번 상담의 카드 배열',
 periodLine:(period:string)=>`살펴본 기간: ${period}`,
 optionsLine:(a:string,b:string)=>`A: ${a} · B: ${b}`,
 reversed:'역방향',upright:'정방향',
} as const;
