import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';
import {consultationInputCopy} from './consultation-input-copy';
import {readingCopy} from './reading-copy';
import {chartTerm} from './reading-chart-copy';
import {localizedSystem,consultationLocaleCopy} from './consultation-locale-copy';
const rows={
 vi:{focusBody:'Nhắm mắt, nghĩ về điều muốn hiểu và hít thở chậm ba lần.',breath:'Hướng dẫn thở',shuffleTitle:'Đang xào bài dưới ánh trăng',shuffleBody:'Dừng lại khi bạn thấy thời điểm phù hợp.',stopShuffle:'Dừng xào bài',chooseTitle:'Chọn vị trí bạn cảm thấy thu hút',chooseBody:'Các lá bài của bài đọc đã thanh toán được lưu an toàn. Việc chọn vị trí ở đây giúp bạn tập trung; không thay đổi kết quả đã lưu.',confirm:'Xác nhận lựa chọn',revealTitle:'Lật từng lá bài',revealBody:'Lật lá bài phát sáng theo thứ tự. Thứ tự và chiều xuôi/ngược đã lưu không thay đổi.',readingBody:'Đang kết nối câu hỏi với các lá bài và mở bài đọc đã lưu.',soundOn:'Bật âm thanh',soundOff:'Tắt âm thanh',soundToggle:'Âm thanh lật bài',restore:'Đang tiếp tục lượt rút bài đã lưu.',major:'Ẩn chính'},
 hi:{focusBody:'आँखें बंद करें, अपना प्रश्न याद करें और तीन बार धीरे साँस लें।',breath:'साँस लेने का मार्गदर्शन',shuffleTitle:'चाँदनी में कार्ड मिलाए जा रहे हैं',shuffleBody:'जब समय सही लगे, मिलाना रोक दें।',stopShuffle:'कार्ड मिलाना रोकें',chooseTitle:'अपनी पसंद की जगहें चुनें',chooseBody:'भुगतान वाली रीडिंग के कार्ड सुरक्षित सहेजे गए हैं। यहाँ स्थान चुनना ध्यान केंद्रित करने के लिए है; सहेजे गए कार्ड नहीं बदलते।',confirm:'चयन की पुष्टि करें',revealTitle:'कार्ड एक-एक करके खोलें',revealBody:'चमकते कार्ड क्रम में खोलें। सहेजा गया क्रम और सीधी या उल्टी दिशा नहीं बदलती।',readingBody:'आपके प्रश्न और कार्ड को जोड़कर सहेजी गई रीडिंग खोली जा रही है।',soundOn:'ध्वनि चालू',soundOff:'ध्वनि बंद',soundToggle:'कार्ड खोलने की ध्वनि',restore:'सहेजे गए कार्ड चयन को जारी रखा जा रहा है।',major:'मेजर आर्काना'},
 es:{focusBody:'Cierra los ojos, piensa en tu pregunta y respira despacio tres veces.',breath:'Guía de respiración',shuffleTitle:'Barajando bajo la luz de la luna',shuffleBody:'Detén la baraja cuando sientas que es el momento.',stopShuffle:'Detener la baraja',chooseTitle:'Elige las posiciones que te atraen',chooseBody:'Las cartas de tu lectura pagada ya están guardadas. Elegir posiciones te ayuda a concentrarte, sin cambiar la tirada.',confirm:'Confirmar selección',revealTitle:'Revela las cartas una a una',revealBody:'Abre la carta iluminada en orden. No cambian el orden guardado ni su orientación.',readingBody:'Relacionamos tu pregunta con las cartas y abrimos tu lectura guardada.',soundOn:'Sonido activado',soundOff:'Sonido desactivado',soundToggle:'Sonido al revelar cartas',restore:'Continuamos la tirada guardada de esta lectura.',major:'Arcanos mayores'},
 fr:{focusBody:'Fermez les yeux, pensez à votre question et prenez trois respirations lentes.',breath:'Guide de respiration',shuffleTitle:'Mélange des cartes au clair de lune',shuffleBody:'Arrêtez le mélange lorsque le moment vous semble juste.',stopShuffle:'Arrêter le mélange',chooseTitle:'Choisissez les positions qui vous attirent',chooseBody:'Les cartes de votre lecture payée sont déjà enregistrées. Choisir les positions aide à vous concentrer, sans modifier le tirage.',confirm:'Confirmer le choix',revealTitle:'Révélez les cartes une à une',revealBody:'Ouvrez la carte lumineuse dans l’ordre. L’ordre enregistré et l’orientation ne changent pas.',readingBody:'Nous relions votre question aux cartes et ouvrons votre lecture enregistrée.',soundOn:'Son activé',soundOff:'Son désactivé',soundToggle:'Son de révélation des cartes',restore:'Reprise du tirage enregistré de cette lecture.',major:'Arcanes majeurs'},
 de:{focusBody:'Schließe die Augen, denke an deine Frage und atme dreimal langsam.',breath:'Atemhilfe',shuffleTitle:'Karten werden im Mondlicht gemischt',shuffleBody:'Stoppe das Mischen, wenn der Moment richtig erscheint.',stopShuffle:'Mischen stoppen',chooseTitle:'Wähle die Positionen, die dich ansprechen',chooseBody:'Die Karten deiner bezahlten Deutung sind bereits gespeichert. Die Positionswahl hilft beim Fokussieren und ändert die Legung nicht.',confirm:'Auswahl bestätigen',revealTitle:'Decke die Karten nacheinander auf',revealBody:'Öffne die leuchtende Karte der Reihe nach. Gespeicherte Reihenfolge und Ausrichtung bleiben erhalten.',readingBody:'Deine Frage wird mit den Karten verbunden und die gespeicherte Deutung geöffnet.',soundOn:'Ton an',soundOff:'Ton aus',soundToggle:'Ton beim Aufdecken',restore:'Die gespeicherte Kartenlegung wird fortgesetzt.',major:'Große Arkana'},
 nl:{focusBody:'Sluit je ogen, denk aan je vraag en adem drie keer rustig.',breath:'Ademhalingshulp',shuffleTitle:'Kaarten schudden in het maanlicht',shuffleBody:'Stop met schudden wanneer het moment goed voelt.',stopShuffle:'Stoppen met schudden',chooseTitle:'Kies de posities die je aanspreken',chooseBody:'De kaarten van je betaalde reading zijn al opgeslagen. De posities kiezen helpt je concentreren en verandert de legging niet.',confirm:'Keuze bevestigen',revealTitle:'Draai de kaarten één voor één om',revealBody:'Open de oplichtende kaart op volgorde. De opgeslagen volgorde en richting blijven gelijk.',readingBody:'We verbinden je vraag met de kaarten en openen je opgeslagen reading.',soundOn:'Geluid aan',soundOff:'Geluid uit',soundToggle:'Geluid bij het omdraaien',restore:'De opgeslagen kaartlegging wordt voortgezet.',major:'Grote arcana'},
 ms:{focusBody:'Pejamkan mata, fikirkan soalan anda dan tarik nafas perlahan tiga kali.',breath:'Panduan pernafasan',shuffleTitle:'Mengocok kad di bawah cahaya bulan',shuffleBody:'Hentikan kocokan apabila masanya terasa sesuai.',stopShuffle:'Hentikan kocokan',chooseTitle:'Pilih kedudukan yang menarik perhatian',chooseBody:'Kad bacaan berbayar anda telah disimpan dengan selamat. Pilihan kedudukan membantu tumpuan tanpa mengubah kad disimpan.',confirm:'Sahkan pilihan',revealTitle:'Buka kad satu demi satu',revealBody:'Buka kad bercahaya mengikut urutan. Urutan dan arah tegak atau terbalik yang disimpan tidak berubah.',readingBody:'Menghubungkan soalan dengan kad dan membuka bacaan disimpan.',soundOn:'Bunyi dihidupkan',soundOff:'Bunyi dimatikan',soundToggle:'Bunyi pembukaan kad',restore:'Meneruskan cabutan kad disimpan untuk bacaan ini.',major:'Arcana utama'},
};
export function nativeTarotRitualCopy(locale:Exclude<ReadingLocale,'ko'|'en'|'ja'|'zh-CN'|'zh-TW'>){
 const t=rows[locale],input=consultationInputCopy(locale),c=readingCopy(locale),card=chartTerm('카드',locale);
 return {...t,section:localizedSystem('tarot',locale),focusTitle:input.tarotHeading,ready:c.continue,
  chooseProgress:(n:number,total:number)=>`${n}/${total}`,cardBack:(n:number)=>`${card} ${n}`,selected:consultationLocaleCopy(locale).selected,
  revealCard:(n:number)=>`${t.revealTitle} ${n}`,upright:chartTerm('정방향',locale),reversed:chartTerm('역방향',locale),readingTitle:c.preparing,continue:c.view};
}
