import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';

// Display-only names. Saved spread keys, card order and interpretation evidence stay intact.
const labels='원인|과정|결과|내가 바라보는 상대|상대가 관계 전체를 보는 시각|상대가 나를 바라보는 마음|상대의 연애 의지와 열망|관계를 가로막는 핵심 요인|앞으로 펼쳐질 단기적 결말|겉으로 보이는 태도|감정의 경향|다가오지 않는 이유|숨겨진 욕구|관계에 대한 판단|현재의 거리|소통을 막는 것|다가갈 조건|가까운 흐름|행동 조언|아직 남아 있는 마음|상대가 보이는 마음의 결|연락이 멈춘 현실 신호|다시 닿을 수 있는 거리|관계 회복의 조건과 기준|내 현재 마음|상대 쪽 관계 흐름|두 사람 사이의 끌림|겉으로 드러난 관계와 숨은 과제|가까운 미래의 가능성|관계 조언과 종합 판단|살아나는 일의 결|덜 소모되는 방향|마음의 소명|문턱 너머의 생활|현실로 여는 첫 행동|놓아야 할 낡은 기준|남길 기준과 옮길 방향|현재의 돈 습관|활용할 자원|주의할 부담|조정할 선택|숨겨진 진실|감정 수용|회복 단서|다음 행동'.split('|');
const rows:Record<Exclude<ReadingLocale,'ko'>,string>={
 en:'Cause|Process|Possible outcome|How I see them|Their possible view of the relationship|Their possible feelings toward me|Willingness to explore romance|The main obstacle between us|Possible near-term direction|Outward attitude|Emotional tendencies|What may keep them distant|Unspoken needs|Perspective on the relationship|The distance between us now|What blocks communication|Conditions for reaching out|The near-term outlook|Practical next steps|Feelings that may remain|The feelings their actions suggest|Real-world signs behind the silence|Room to reconnect|Conditions and boundaries for rebuilding|My feelings now|The relationship from their side|Attraction between us|The visible relationship and hidden challenges|Near-term possibilities|Relationship advice and perspective|Work that brings me alive|A less draining direction|A sense of calling|Life beyond the next step|A first practical action|Old expectations to release|Values to keep and directions to explore|Current money habits|Resources I can use|Pressures to watch|Choices to adjust|What lies beneath|Making room for feelings|Clues to recovery|The next step',
 ja:'原因|過程|結果の可能性|私から見た相手|相手から見た関係の可能性|私に向ける感情の可能性|恋愛に向き合う意欲|関係を妨げる主な要因|近い将来の方向性|表に出ている態度|感情の傾向|距離を置く理由の可能性|言葉にならない願い|関係への見方|今の二人の距離|会話を妨げるもの|歩み寄るための条件|近い時期の流れ|行動のヒント|まだ残っているかもしれない思い|行動からうかがえる感情|連絡が途絶えた現実のサイン|再びつながる余地|関係を立て直す条件と境界|今の私の気持ち|相手側から見た関係の流れ|二人の間の引力|表に見える関係と隠れた課題|近い未来の可能性|関係への助言と全体像|自分が生きる仕事の形|消耗を減らす方向|心が求める役割|一歩先にある暮らし|現実を動かす最初の行動|手放したい古い基準|残す価値観と進む方向|今のお金の習慣|活用できる資源|気をつけたい負担|見直せる選択|奥にあるもの|感情を受け止める|回復の手がかり|次の一歩',
 'zh-CN':'原因|过程|可能的结果|我眼中的对方|对方可能如何看待关系|对方对我的情感倾向|投入恋爱的意愿|关系中的主要阻碍|近期可能的方向|表露的态度|情感倾向|保持距离的可能原因|未说出口的需求|对关系的看法|眼下的距离|沟通的阻碍|靠近的条件|近期的走向|行动建议|可能仍在的感情|行为流露的情绪|停止联系的现实信号|重新连接的空间|修复关系的条件与界限|我此刻的心情|对方视角下的关系|两人之间的吸引力|表面的关系与隐藏的课题|近期的可能性|关系建议与整体判断|让我发挥所长的工作|减少消耗的方向|内心的使命感|跨出下一步后的生活|切实可行的第一步|可以放下的旧标准|保留的价值与探索的方向|当前的金钱习惯|可利用的资源|需要留意的负担|可以调整的选择|表象之下|接纳情绪|恢复的线索|下一步行动',
 'zh-TW':'原因|過程|可能的結果|我眼中的對方|對方可能如何看待關係|對方對我的情感傾向|投入戀愛的意願|關係中的主要阻礙|近期可能的方向|表露的態度|情感傾向|保持距離的可能原因|未說出口的需求|對關係的看法|眼下的距離|溝通的阻礙|靠近的條件|近期的走向|行動建議|可能仍在的感情|行為流露的情緒|停止聯絡的現實訊號|重新連結的空間|修復關係的條件與界線|我此刻的心情|對方視角下的關係|兩人之間的吸引力|表面的關係與隱藏的課題|近期的可能性|關係建議與整體判斷|讓我發揮所長的工作|減少消耗的方向|內心的使命感|跨出下一步後的生活|切實可行的第一步|可以放下的舊標準|保留的價值與探索的方向|目前的金錢習慣|可利用的資源|需要留意的負擔|可以調整的選擇|表象之下|接納情緒|恢復的線索|下一步行動',
 vi:'Nguyên nhân|Quá trình|Kết quả có thể xảy ra|Cách tôi nhìn người ấy|Góc nhìn có thể có của người ấy về mối quan hệ|Xu hướng tình cảm của người ấy dành cho tôi|Mong muốn bước vào tình yêu|Trở ngại chính giữa hai người|Hướng đi có thể có trong thời gian tới|Thái độ thể hiện ra ngoài|Xu hướng cảm xúc|Điều có thể khiến người ấy giữ khoảng cách|Nhu cầu chưa nói thành lời|Cách nhìn về mối quan hệ|Khoảng cách hiện tại|Điều cản trở giao tiếp|Điều kiện để tiến gần|Xu hướng sắp tới|Gợi ý hành động|Tình cảm có thể còn lại|Cảm xúc gợi ra từ hành động|Dấu hiệu thực tế đằng sau sự im lặng|Không gian để kết nối lại|Điều kiện và ranh giới để hàn gắn|Cảm xúc hiện tại của tôi|Mối quan hệ từ phía người ấy|Sức hút giữa hai người|Bề ngoài của mối quan hệ và vấn đề tiềm ẩn|Khả năng trong tương lai gần|Lời khuyên và góc nhìn tổng thể|Công việc giúp tôi phát huy|Hướng đi ít hao tổn hơn|Tiếng gọi trong lòng|Cuộc sống sau bước chuyển|Hành động thực tế đầu tiên|Tiêu chuẩn cũ có thể buông bỏ|Giá trị giữ lại và hướng đi mới|Thói quen tiền bạc hiện tại|Nguồn lực có thể sử dụng|Áp lực cần lưu ý|Lựa chọn có thể điều chỉnh|Điều nằm bên dưới|Đón nhận cảm xúc|Manh mối hồi phục|Bước tiếp theo',
 hi:'कारण|प्रक्रिया|संभावित परिणाम|मैं उन्हें कैसे देखता हूँ|रिश्ते पर उनका संभावित दृष्टिकोण|मेरे प्रति उनकी संभावित भावनाएँ|प्रेम की ओर बढ़ने की इच्छा|रिश्ते की मुख्य बाधा|निकट भविष्य की संभावित दिशा|बाहर दिखता व्यवहार|भावनात्मक रुझान|दूरी बनाए रखने के संभावित कारण|अनकही ज़रूरतें|रिश्ते को देखने का नज़रिया|अभी की दूरी|संवाद में बाधा|करीब आने की परिस्थितियाँ|आने वाले समय का रुझान|व्यावहारिक सुझाव|शायद अब भी बची भावनाएँ|व्यवहार से झलकती भावनाएँ|खामोशी के पीछे वास्तविक संकेत|फिर जुड़ने की गुंजाइश|रिश्ता सँवारने की शर्तें और सीमाएँ|अभी मेरी भावनाएँ|उनकी ओर से रिश्ते का रुझान|दोनों के बीच आकर्षण|दिखता रिश्ता और छिपी चुनौतियाँ|निकट भविष्य की संभावनाएँ|रिश्ते पर सलाह और समग्र दृष्टि|वह काम जिसमें मैं खिलता हूँ|कम थकाने वाली दिशा|मन की पुकार|अगले कदम के बाद का जीवन|पहला व्यावहारिक कदम|पुरानी अपेक्षाएँ जिन्हें छोड़ सकते हैं|सहेजने वाले मूल्य और नई दिशाएँ|पैसों की मौजूदा आदतें|उपयोगी संसाधन|ध्यान देने योग्य बोझ|बदल सकने वाले चुनाव|सतह के नीचे क्या है|भावनाओं को स्वीकारना|संभलने के संकेत|अगला कदम',
 es:'Causa|Proceso|Posible resultado|Cómo veo a esa persona|Su posible visión de la relación|Sus posibles sentimientos hacia mí|Disposición a explorar el amor|El principal obstáculo entre ambos|Posible rumbo a corto plazo|Actitud visible|Tendencias emocionales|Qué podría mantener la distancia|Necesidades no expresadas|Perspectiva sobre la relación|La distancia actual|Qué dificulta la comunicación|Condiciones para acercarse|La tendencia próxima|Consejos prácticos|Sentimientos que podrían permanecer|Lo que sugieren sus acciones|Señales reales detrás del silencio|Espacio para reconectar|Condiciones y límites para reconstruir|Mis sentimientos actuales|La relación desde su lado|Atracción entre ambos|La relación visible y sus retos ocultos|Posibilidades a corto plazo|Consejos y perspectiva de la relación|Un trabajo que me da vida|Una dirección menos agotadora|Mi vocación interior|La vida tras el siguiente paso|Una primera acción concreta|Expectativas antiguas que soltar|Valores que conservar y rumbos que explorar|Hábitos actuales con el dinero|Recursos disponibles|Cargas que conviene observar|Decisiones que ajustar|Lo que hay bajo la superficie|Dar espacio a las emociones|Pistas para recuperarse|El siguiente paso',
 fr:'Cause|Déroulement|Issue possible|Mon regard sur cette personne|Sa vision possible de la relation|Ses sentiments possibles envers moi|Son envie de vivre une relation|Le principal obstacle entre nous|Orientation possible à court terme|Attitude visible|Tendances émotionnelles|Ce qui peut maintenir la distance|Besoins non exprimés|Regard sur la relation|La distance actuelle|Ce qui freine la communication|Conditions pour se rapprocher|La tendance à venir|Conseils concrets|Sentiments qui peuvent subsister|Ce que ses gestes suggèrent|Signes concrets derrière le silence|Une place pour renouer|Conditions et limites pour reconstruire|Mes sentiments actuels|La relation de son côté|Attirance entre nous|La relation visible et les défis cachés|Possibilités à court terme|Conseils et vue d’ensemble|Un travail qui me fait vibrer|Une direction moins épuisante|Ma vocation profonde|La vie après le prochain pas|Une première action concrète|D’anciennes attentes à laisser partir|Valeurs à garder et directions à explorer|Habitudes financières actuelles|Ressources disponibles|Charges à surveiller|Choix à ajuster|Ce qui se trouve sous la surface|Accueillir ses émotions|Pistes pour se rétablir|Le prochain pas',
 de:'Ursache|Verlauf|Mögliches Ergebnis|Mein Blick auf die andere Person|Ihr möglicher Blick auf die Beziehung|Ihre möglichen Gefühle für mich|Bereitschaft für eine Liebesbeziehung|Das wichtigste Hindernis zwischen uns|Mögliche kurzfristige Richtung|Sichtbares Verhalten|Emotionale Tendenzen|Mögliche Gründe für den Abstand|Unausgesprochene Bedürfnisse|Blick auf die Beziehung|Der aktuelle Abstand|Was die Kommunikation erschwert|Bedingungen für eine Annäherung|Die nächste Entwicklung|Praktische Handlungsideen|Gefühle, die noch da sein könnten|Was ihr Verhalten andeutet|Reale Hinweise hinter der Funkstille|Raum für einen neuen Kontakt|Bedingungen und Grenzen für den Wiederaufbau|Meine aktuellen Gefühle|Die Beziehung aus ihrer Sicht|Anziehung zwischen uns|Die sichtbare Beziehung und verborgene Aufgaben|Möglichkeiten in naher Zukunft|Beziehungsrat und Gesamtbild|Arbeit, die mich aufleben lässt|Eine weniger belastende Richtung|Meine innere Berufung|Das Leben nach dem nächsten Schritt|Eine erste konkrete Handlung|Alte Erwartungen loslassen|Werte bewahren und neue Wege erkunden|Aktuelle Geldgewohnheiten|Nutzbare Ressourcen|Belastungen im Blick behalten|Entscheidungen anpassen|Was unter der Oberfläche liegt|Gefühlen Raum geben|Hinweise zur Erholung|Der nächste Schritt',
 nl:'Oorzaak|Verloop|Mogelijke uitkomst|Hoe ik de ander zie|Hun mogelijke kijk op de relatie|Hun mogelijke gevoelens voor mij|Bereidheid voor een liefdesrelatie|Het belangrijkste obstakel tussen ons|Mogelijke richting op korte termijn|Zichtbaar gedrag|Emotionele tendensen|Mogelijke redenen voor de afstand|Onuitgesproken behoeften|Kijk op de relatie|De huidige afstand|Wat communicatie belemmert|Voorwaarden om toenadering te zoeken|De komende ontwikkeling|Praktische stappen|Gevoelens die er nog kunnen zijn|Wat hun gedrag laat zien|Concrete signalen achter de stilte|Ruimte om weer contact te maken|Voorwaarden en grenzen voor herstel|Mijn huidige gevoelens|De relatie vanuit hun kant|Aantrekking tussen ons|De zichtbare relatie en verborgen uitdagingen|Mogelijkheden op korte termijn|Relatieadvies en overzicht|Werk waarin ik opleef|Een minder uitputtende richting|Mijn innerlijke roeping|Het leven na de volgende stap|Een eerste concrete actie|Oude verwachtingen loslaten|Waarden behouden en richtingen verkennen|Huidige geldgewoonten|Beschikbare middelen|Belastingen om op te letten|Keuzes om bij te stellen|Wat onder de oppervlakte ligt|Ruimte voor gevoelens|Aanwijzingen voor herstel|De volgende stap',
 ms:'Punca|Proses|Hasil yang mungkin|Cara saya melihat dia|Pandangan yang mungkin tentang hubungan ini|Kemungkinan perasaannya terhadap saya|Kesediaan menjalinkan cinta|Halangan utama antara kami|Arah yang mungkin dalam masa terdekat|Sikap yang terlihat|Kecenderungan emosi|Perkara yang mungkin membuatnya menjauh|Keperluan yang tidak diluahkan|Pandangan tentang hubungan|Jarak antara kami sekarang|Penghalang komunikasi|Syarat untuk mendekati|Arah dalam masa terdekat|Cadangan tindakan|Perasaan yang mungkin masih ada|Perasaan yang dibayangkan oleh tindakannya|Petunjuk sebenar di sebalik kesunyian|Ruang untuk berhubung semula|Syarat dan batas untuk membina semula|Perasaan saya sekarang|Hubungan dari sudutnya|Tarikan antara kami|Hubungan yang terlihat dan cabaran tersembunyi|Kemungkinan masa terdekat|Nasihat hubungan dan pandangan keseluruhan|Kerja yang menghidupkan semangat|Arah yang kurang meletihkan|Panggilan hati|Kehidupan selepas langkah seterusnya|Tindakan praktikal pertama|Jangkaan lama untuk dilepaskan|Nilai untuk dikekalkan dan arah untuk diterokai|Tabiat kewangan semasa|Sumber yang boleh digunakan|Beban yang perlu diperhatikan|Pilihan yang boleh diselaraskan|Apa di sebalik permukaan|Menerima perasaan|Petunjuk pemulihan|Langkah seterusnya',
};
const localized=Object.fromEntries(Object.entries(rows).map(([locale,row])=>{
 const values=row.split('|');
 if(values.length!==labels.length)throw new Error(`Tarot position copy mismatch: ${locale}`);
 return [locale,Object.fromEntries(labels.map((label,index)=>[label,values[index]]))];
})) as Record<Exclude<ReadingLocale,'ko'>,Record<string,string>>;
export function tarotPositionCopy(label:string,locale?:ReadingLocale):string|undefined{
 return locale&&locale!=='ko'?localized[locale][label]:undefined;
}
