import type {ReadingLocale} from '@/worker/yeongnyangi/fortune/reading-locale';

/**
 * 자미 명반 화면(ZiweiReadingChart) 문구. 별·궁 이름은 모든 언어에서 한글 그대로 두고 한자를 곁에 단다.
 * 모든 ReadingLocale의 현지어를 제공한다.
 * 등급 설명은 강약 정본(lib/ziwei-star-strength.js GRADES.label)의 뜻을 옮긴 것이다 — 좋고 나쁨이 아니라 별의 성질이 드러나는 정도다.
 */
type Grade='묘'|'왕'|'득'|'리'|'평'|'불'|'함'|'한';
type Hua='화록'|'화권'|'화과'|'화기';
type Copy={chart:string;select:string;legend:string;body:string;noMain:string;noMainShort:string;modern:string;
 kinds:Record<'main'|'assistant'|'malefic',string>;grades:Record<Grade,string>;hua:Record<Hua,string>;
 howTitle:string;how:string[];notes:string;hint:string};

const QUOTE='「入庙不加吉，平等」';
const ko:Copy={chart:'명반',select:'궁 선택',legend:'왼쪽일수록 별의 성질이 또렷한 자리 · 길흉 아님',body:'신궁',
 noMain:'주성이 없는 궁이에요. 마주 보는 궁의 주성을 빌려 함께 읽어요.',noMainShort:'주성 없음',modern:'현대 표',
 kinds:{main:'주성',assistant:'보조성',malefic:'긴장 요소'},
 grades:{묘:'성질이 가장 또렷하고 안정적으로 드러나는 자리',왕:'성질이 힘 있게 드러나는 자리',득:'자리를 얻어 무난히 드러나는 자리',리:'쓸 만하지만 힘이 한 단계 덜한 자리',평:'중간 — 함께 앉은 별·사화·마주 보는 궁의 영향을 크게 받는 자리',불:'자리를 얻지 못해 힘이 약한 자리(평과 함 사이)',함:'성질이 막히거나 비틀려 드러나기 쉬운 자리 — 보완 조건을 함께 봐요',한:'힘이 한가해 잘 쓰이지 않는 자리'},
 hua:{화록:'化祿 화록',화권:'化權 화권',화과:'化科 화과',화기:'化忌 화기'},
 howTitle:'이 별의 강약을 어떻게 읽었나',
 how:['별 옆 글자는 그 별이 이 궁의 지지에서 얼마나 또렷하게 드러나는지를 『紫微斗數全書』 권3의 별 줄에서 옮긴 거예요. 廟가 가장 또렷하고, 陷이 가장 막힌 자리예요.',
  '원전이 적지 않은 칸은 현대 표(iztro)로 채우고 "현대 표"라고 따로 적었어요. 다른 현대 표(紫微人生)도 같은 값이지만, 두 표가 같은 계열일 수 있어 원전만큼 단단하지는 않아요. 어느 표에도 없는 별은 글자를 비워 두었어요.',
  `강약은 길흉 점수가 아니에요. 원전도 ${QUOTE}(묘에 들어도 길성이 더하지 않으면 평범하다)이라 해서, 강한 자리만으로 좋다고 보지 않아요. 같은 궁의 다른 별·사화·마주 보는 궁과 함께 읽어요.`,
  '명반은 구매 때 저장한 계산값으로 화면을 열 때마다 다시 그려요. 이미 받은 풀이 글은 바뀌지 않아요.'],
 notes:'이 궁에서 함께 본 조건',hint:'이 소절이 짚은 궁'};
const en:Copy={chart:'Chart',select:'Select a palace',legend:'Further left, the star’s nature shows more clearly · not good or bad',body:'Body palace',
 noMain:'This palace has no main star. It is read together with the main stars of the opposite palace.',noMainShort:'no main star',modern:'modern table',
 kinds:{main:'Main stars',assistant:'Supporting stars',malefic:'Tension stars'},
 grades:{묘:'Its nature shows most clearly and steadily here',왕:'Its nature shows with strength here',득:'It finds its footing and shows without strain',리:'Usable, though one step weaker',평:'Middle — strongly shaped by companion stars, transformations and the opposite palace',불:'It lacks footing, so its force is weak (between 平 and 陷)',함:'Its nature tends to show blocked or bent — read it with the supporting conditions',한:'Its force sits idle and is little used'},
 hua:{화록:'化祿 Lu (prosperity)',화권:'化權 Quan (authority)',화과:'化科 Ke (recognition)',화기:'化忌 Ji (obstruction)'},
 howTitle:'How this star’s strength was read',
 how:['The character beside each star records how clearly that star shows in this palace’s earthly branch, taken from the star rows in volume 3 of the classical 紫微斗數全書. 廟 is the clearest and 陷 the most blocked.',
  'Where the classic gives no entry, the gap is filled from a modern table (iztro) and marked “modern table”. A second modern table (紫微人生) gives the same values, but the two may share a lineage, so these cells are not as firm as the classic. Stars that neither table rates are left without a character.',
  `Strength is not a score of good or bad fortune. The classic itself says ${QUOTE} — entering 廟 without auspicious stars is ordinary — so a strong position alone is not read as good. Each star is read with its companions, transformations and the opposite palace.`,
  'The chart is redrawn from the values saved at purchase each time you open it. The reading you already received does not change.'],
 notes:'Conditions read in this palace',hint:'Palaces this section reads'};
const ja:Copy={chart:'命盤',select:'宮を選択',legend:'左ほど星の性質がはっきり出る位置 · 吉凶ではありません',body:'身宮',
 noMain:'主星のない宮です。向かい合う宮の主星を借りて一緒に読みます。',noMainShort:'主星なし',modern:'現代の表',
 kinds:{main:'主星',assistant:'補佐星',malefic:'緊張要素'},
 grades:{묘:'性質が最もはっきり、安定して現れる位置',왕:'性質が力強く現れる位置',득:'居場所を得て無理なく現れる位置',리:'使えるが、力が一段弱い位置',평:'中間 — 同宮の星・四化・対宮の影響を大きく受ける位置',불:'居場所を得られず力が弱い位置(平と陷の間)',함:'性質が詰まったり歪んだりして現れやすい位置 — 補う条件と合わせて読みます',한:'力が遊んでいて、あまり使われない位置'},
 hua:{화록:'化禄',화권:'化権',화과:'化科',화기:'化忌'},
 howTitle:'この星の強弱をどう読んだか',
 how:['星の横の文字は、その星がこの宮の地支でどれだけはっきり現れるかを『紫微斗數全書』巻三の星の行から写したものです。廟が最もはっきりし、陷が最も詰まった位置です。',
  '原典に記載のない欄は現代の表(iztro)で補い、「現代の表」と別に記しました。別の現代の表(紫微人生)も同じ値ですが、同じ系統の可能性があり、原典ほど確かではありません。どちらの表にもない星は文字を空けています。',
  `強弱は吉凶の点数ではありません。原典も${QUOTE}(廟に入っても吉星が加わらなければ平凡)と述べ、強い位置だけで良いとは見ません。同宮の星・四化・対宮と合わせて読みます。`,
  '命盤は購入時に保存した計算値から、開くたびに描き直します。受け取った鑑定文は変わりません。'],
 notes:'この宮で合わせて見た条件',hint:'この節が読んだ宮'};
const zhCN:Copy={chart:'命盘',select:'选择宫位',legend:'越靠左，星性显现越鲜明 · 不代表吉凶',body:'身宫',
 noMain:'此宫没有主星，借对宫的主星一起解读。',noMainShort:'无主星',modern:'现代表',
 kinds:{main:'主星',assistant:'辅星',malefic:'紧张要素'},
 grades:{묘:'星性最鲜明、最稳定地显现的位置',왕:'星性有力地显现的位置',득:'得其位、平稳显现的位置',리:'可用，但力量弱一级的位置',평:'居中——受同宫星曜、四化与对宫影响很大的位置',불:'不得其位、力量偏弱的位置（介于平与陷之间）',함:'星性易受阻或扭曲的位置——需结合补救条件一起看',한:'力量闲置、不太发挥作用的位置'},
 hua:{화록:'化禄',화권:'化权',화과:'化科',화기:'化忌'},
 howTitle:'这颗星的强弱是怎么读的',
 how:['星旁的字记录该星在此宫地支显现得多鲜明，取自《紫微斗數全書》卷三的星曜条目。廟最鲜明，陷最受阻。',
  '原典未载的格子用现代表（iztro）补上，并另标“现代表”。另一张现代表（紫微人生）给出相同的值，但两者可能同出一系，不如原典确定。两张表都没有的星不标字。',
  `强弱不是吉凶分数。原典也说${QUOTE}（入庙而无吉星相加则平常），不以位置强就论好。要与同宫星曜、四化及对宫一起看。`,
  '命盘每次打开时都按购买时保存的计算值重新绘制，已收到的解读文字不会改变。'],
 notes:'此宫一并参考的条件',hint:'本节解读的宫位'};
const zhTW:Copy={chart:'命盤',select:'選擇宮位',legend:'越靠左，星性顯現越鮮明 · 不代表吉凶',body:'身宮',
 noMain:'此宮沒有主星，借對宮的主星一起解讀。',noMainShort:'無主星',modern:'現代表',
 kinds:{main:'主星',assistant:'輔星',malefic:'緊張要素'},
 grades:{묘:'星性最鮮明、最穩定地顯現的位置',왕:'星性有力地顯現的位置',득:'得其位、平穩顯現的位置',리:'可用，但力量弱一級的位置',평:'居中——受同宮星曜、四化與對宮影響很大的位置',불:'不得其位、力量偏弱的位置（介於平與陷之間）',함:'星性易受阻或扭曲的位置——需結合補救條件一起看',한:'力量閒置、不太發揮作用的位置'},
 hua:{화록:'化祿',화권:'化權',화과:'化科',화기:'化忌'},
 howTitle:'這顆星的強弱是怎麼讀的',
 how:['星旁的字記錄該星在此宮地支顯現得多鮮明，取自《紫微斗數全書》卷三的星曜條目。廟最鮮明，陷最受阻。',
  '原典未載的格子用現代表（iztro）補上，並另標「現代表」。另一張現代表（紫微人生）給出相同的值，但兩者可能同出一系，不如原典確定。兩張表都沒有的星不標字。',
  `強弱不是吉凶分數。原典也說${QUOTE}（入廟而無吉星相加則平常），不以位置強就論好。要與同宮星曜、四化及對宮一起看。`,
  '命盤每次打開時都依購買時保存的計算值重新繪製，已收到的解讀文字不會改變。'],
 notes:'此宮一併參考的條件',hint:'本節解讀的宮位'};

const localized:Record<ReadingLocale,Copy>={ko,en,ja,"zh-CN":zhCN,"zh-TW":zhTW,
vi:{"chart":"Lá số Tử Vi","select":"Chọn cung","legend":"Về bên trái: tính chất sao thể hiện rõ hơn · không phải mức tốt xấu","body":"Cung Thân","noMain":"Cung vô chính diệu. Luận giải cùng chính tinh ở cung đối diện.","noMainShort":"Không có chính tinh","modern":"Bảng hiện đại","kinds":{"main":"Chính tinh","assistant":"Phụ tinh","malefic":"Yếu tố căng thẳng"},"grades":{"묘":"Tính chất rõ và ổn định nhất","왕":"Tính chất thể hiện mạnh","득":"Có vị trí phù hợp, thể hiện thuận lợi","리":"Có thể phát huy nhưng yếu hơn một bậc","평":"Trung bình; phụ thuộc nhiều vào sao cùng cung, Tứ Hóa và cung đối diện","불":"Vị trí kém thuận lợi, yếu hơn mức trung bình","함":"Dễ bị cản trở hoặc biểu hiện lệch; cần xem yếu tố bù đắp","한":"Sức mạnh ít được phát huy"},"hua":{"화록":"化祿 Hóa Lộc · nguồn lực","화권":"化權 Hóa Quyền · quyền chủ động","화과":"化科 Hóa Khoa · sự ghi nhận","화기":"化忌 Hóa Kỵ · trở ngại"},"howTitle":"Cách đọc độ mạnh của sao","how":["Ký hiệu cạnh sao biểu thị mức độ tính chất sao hiện rõ tại địa chi của cung, theo quyển 3 của 紫微斗數全書. 廟 rõ nhất, 陷 bị cản trở nhiều nhất.","Ô không có trong cổ thư dùng bảng hiện đại iztro và được đánh dấu. Bảng 紫微人生 có cùng giá trị nhưng có thể chung nguồn, nên không được xem là chứng cứ độc lập. Sao không có ở cả hai bảng để trống.","Độ mạnh không phải điểm tốt xấu. Cổ thư nói 「入庙不加吉，平等」: vào miếu mà không có sao cát thì vẫn bình thường. Cần xét sao đi cùng, Tứ Hóa và cung đối diện.","Lá số được dựng lại từ dữ liệu lưu khi mua. Bài luận giải đã nhận không thay đổi."],"notes":"Các điều kiện trong cung này","hint":"Các cung được luận giải trong mục này"},
hi:{"chart":"ज़िवेई जन्म-मानचित्र","select":"भाव चुनें","legend":"बाईं ओर तारे का स्वभाव अधिक स्पष्ट · शुभ-अशुभ का अंक नहीं","body":"शरीर भाव","noMain":"यहाँ मुख्य तारा नहीं है। सामने के भाव के मुख्य तारों के साथ पढ़ें।","noMainShort":"मुख्य तारा नहीं","modern":"आधुनिक तालिका","kinds":{"main":"मुख्य तारे","assistant":"सहायक तारे","malefic":"तनाव के संकेत"},"grades":{"묘":"स्वभाव सबसे स्पष्ट और स्थिर","왕":"स्वभाव प्रबल रूप से व्यक्त","득":"अनुकूल स्थान में सहज अभिव्यक्ति","리":"उपयोगी, पर एक स्तर कम प्रबल","평":"मध्यम; साथ के तारों, चार रूपांतरणों और सामने के भाव पर अधिक निर्भर","불":"अनुकूल स्थान न मिलने से मध्यम से कमज़ोर","함":"स्वभाव बाधित या असंतुलित हो सकता है; संतुलनकारी स्थितियाँ भी देखें","한":"शक्ति कम सक्रिय या कम उपयोग में"},"hua":{"화록":"化祿 लू · संसाधन","화권":"化權 छ्वेन · अधिकार","화과":"化科 के · मान्यता","화기":"化忌 जी · बाधा"},"howTitle":"तारे की शक्ति कैसे समझी गई","how":["तारे के पास का चिह्न बताता है कि इस भाव की पार्थिव शाखा में उसका स्वभाव कितना स्पष्ट है। स्रोत 紫微斗數全書 का खंड 3 है। 廟 सबसे स्पष्ट और 陷 सबसे बाधित स्थिति है।","मूल ग्रंथ में खाली स्थान आधुनिक iztro तालिका से भरे गए हैं और अलग चिह्नित हैं। 紫微人生 में भी वही मान हैं, पर दोनों का स्रोत समान हो सकता है; यह स्वतंत्र पुष्टि नहीं है। दोनों में अनुपस्थित तारों को खाली रखा गया है।","शक्ति शुभ-अशुभ का अंक नहीं है। ग्रंथ का 「入庙不加吉，平等」 बताता है कि अनुकूल स्थिति में भी शुभ साथ न हो तो फल सामान्य हो सकता है। साथ के तारे, रूपांतरण और सामने का भाव भी पढ़े जाते हैं।","मानचित्र खरीद के समय सहेजे गए मानों से फिर बनता है। पहले प्राप्त विश्लेषण नहीं बदलता।"],"notes":"इस भाव में देखी गई स्थितियाँ","hint":"इस खंड में समझाए गए भाव"},
es:{"chart":"Carta de Zi Wei Dou Shu","select":"Elegir palacio","legend":"Hacia la izquierda, expresión más clara del astro · no indica buena o mala suerte","body":"Palacio del cuerpo","noMain":"Este palacio no tiene astro principal. Se interpreta junto con los del palacio opuesto.","noMainShort":"Sin astro principal","modern":"Tabla moderna","kinds":{"main":"Astros principales","assistant":"Astros auxiliares","malefic":"Factores de tensión"},"grades":{"묘":"Expresión más clara y estable","왕":"Expresión intensa","득":"Posición favorable para expresarse","리":"Expresión útil, algo menos intensa","평":"Intermedia; depende de los astros cercanos, transformaciones y palacio opuesto","불":"Posición menos favorable, por debajo del nivel intermedio","함":"Expresión bloqueada o distorsionada; considerar factores compensatorios","한":"Potencial poco activo o aprovechado"},"hua":{"화록":"化祿 Lu · recursos","화권":"化權 Quan · autoridad","화과":"化科 Ke · reconocimiento","화기":"化忌 Ji · obstáculos"},"howTitle":"Cómo se interpreta la fuerza del astro","how":["El signo junto al astro refleja su expresión en la rama terrestre de este palacio, según el volumen 3 de 紫微斗數全書. 廟 es la expresión más clara y 陷 la más bloqueada.","Los huecos del texto clásico se completan con iztro y se marcan como tabla moderna. 紫微人生 coincide, pero ambas tablas pueden compartir origen y no constituyen confirmación independiente. Los astros sin dato quedan en blanco.","La fuerza no mide buena o mala suerte. El clásico dice 「入庙不加吉，平等」: una posición fuerte sin astros favorables puede ser ordinaria. Se consideran compañeros, transformaciones y palacio opuesto.","La carta se vuelve a dibujar con los datos guardados al comprar. La lectura recibida no cambia."],"notes":"Condiciones de este palacio","hint":"Palacios analizados en esta sección"},
fr:{"chart":"Thème de Zi Wei Dou Shu","select":"Choisir un palais","legend":"Vers la gauche, expression plus nette de l’astre · sans valeur de chance","body":"Palais du corps","noMain":"Ce palais n’a pas d’astre principal. Il se lit avec ceux du palais opposé.","noMainShort":"Sans astre principal","modern":"Table moderne","kinds":{"main":"Astres principaux","assistant":"Astres auxiliaires","malefic":"Facteurs de tension"},"grades":{"묘":"Expression la plus nette et stable","왕":"Expression puissante","득":"Position permettant une expression aisée","리":"Expression utile, un degré moins forte","평":"Intermédiaire ; dépend des autres astres, transformations et du palais opposé","불":"Position moins favorable, sous le niveau intermédiaire","함":"Expression entravée ou déformée ; examiner les compensations","한":"Potentiel peu mobilisé"},"hua":{"화록":"化祿 Lu · ressources","화권":"化權 Quan · autorité","화과":"化科 Ke · reconnaissance","화기":"化忌 Ji · obstacles"},"howTitle":"Comment lire la force de cet astre","how":["Le signe près de l’astre indique son expression dans la branche terrestre du palais, d’après le volume 3 du 紫微斗數全書. 廟 est la plus nette et 陷 la plus entravée.","Les cases absentes du classique sont complétées par iztro et signalées comme table moderne. 紫微人生 donne les mêmes valeurs, mais les tables peuvent partager une origine : ce n’est pas une confirmation indépendante. Sans donnée, la case reste vide.","La force ne mesure pas la chance. Le classique dit 「入庙不加吉，平等」 : une position forte sans astres favorables peut rester ordinaire. Les astres voisins, transformations et le palais opposé sont aussi pris en compte.","Le thème est redessiné à partir des valeurs enregistrées lors de l’achat. La lecture déjà reçue ne change pas."],"notes":"Conditions étudiées dans ce palais","hint":"Palais étudiés dans cette section"},
de:{"chart":"Zi-Wei-Dou-Shu-Horoskop","select":"Palast wählen","legend":"Weiter links: deutlichere Sterneigenschaft · keine Wertung von Glück oder Unglück","body":"Körperpalast","noMain":"Dieser Palast hat keinen Hauptstern. Die Hauptsterne des gegenüberliegenden Palasts werden mitgedeutet.","noMainShort":"Kein Hauptstern","modern":"Moderne Tabelle","kinds":{"main":"Hauptsterne","assistant":"Begleitsterne","malefic":"Spannungsfaktoren"},"grades":{"묘":"Klarste und stabilste Ausprägung","왕":"Kraftvolle Ausprägung","득":"Günstige Stellung für eine klare Ausprägung","리":"Nutzbare, etwas schwächere Ausprägung","평":"Mittel; stark von Begleitsternen, Wandlungen und Gegenpalast abhängig","불":"Weniger passende Stellung, unterhalb der mittleren Stärke","함":"Gehemmte oder verzerrte Ausprägung; Ausgleichsfaktoren mitlesen","한":"Wenig aktiviertes Potenzial"},"hua":{"화록":"化祿 Lu · Ressourcen","화권":"化權 Quan · Autorität","화과":"化科 Ke · Anerkennung","화기":"化忌 Ji · Hindernisse"},"howTitle":"So wird die Sternstärke gelesen","how":["Das Zeichen am Stern beschreibt seine Ausprägung im Erdzweig dieses Palasts nach Band 3 des 紫微斗數全書. 廟 ist am klarsten, 陷 am stärksten gehemmt.","Lücken im klassischen Werk werden mit iztro ergänzt und als moderne Tabelle markiert. 紫微人生 zeigt dieselben Werte, kann aber dieselbe Quelle haben und ist daher keine unabhängige Bestätigung. Ohne Tabellenwert bleibt das Feld leer.","Stärke ist keine Glücksskala. Der Satz 「入庙不加吉，平等」 besagt, dass eine starke Stellung ohne günstige Begleitsterne gewöhnlich bleiben kann. Begleitsterne, Wandlungen und Gegenpalast werden einbezogen.","Das Horoskop wird aus den beim Kauf gespeicherten Werten neu gezeichnet. Die bereits erhaltene Deutung bleibt unverändert."],"notes":"Bedingungen in diesem Palast","hint":"In diesem Abschnitt gedeutete Paläste"},
nl:{"chart":"Zi Wei Dou Shu-horoscoop","select":"Kies een paleis","legend":"Verder links: duidelijkere stereigenschappen · geen oordeel over geluk","body":"Lichaamspaleis","noMain":"Dit paleis heeft geen hoofdster. De hoofdsterren van het tegenoverliggende paleis worden meegelezen.","noMainShort":"Geen hoofdster","modern":"Moderne tabel","kinds":{"main":"Hoofdsterren","assistant":"Ondersteunende sterren","malefic":"Spanningsfactoren"},"grades":{"묘":"Duidelijkste en stabielste uitdrukking","왕":"Krachtige uitdrukking","득":"Passende positie met soepele uitdrukking","리":"Bruikbaar, maar iets minder krachtig","평":"Gemiddeld; sterk afhankelijk van andere sterren, transformaties en het tegenoverliggende paleis","불":"Minder passende positie, zwakker dan gemiddeld","함":"Geremde of vervormde uitdrukking; bekijk ook compenserende factoren","한":"Weinig actief of benut potentieel"},"hua":{"화록":"化祿 Lu · middelen","화권":"化權 Quan · gezag","화과":"化科 Ke · erkenning","화기":"化忌 Ji · belemmering"},"howTitle":"Zo wordt de stersterkte gelezen","how":["Het teken naast de ster toont hoe duidelijk deze zich uit in de aardse tak van dit paleis, volgens deel 3 van 紫微斗數全書. 廟 is het duidelijkst, 陷 het meest geremd.","Ontbrekende klassieke waarden worden aangevuld met iztro en als moderne tabel gemarkeerd. 紫微人生 geeft dezelfde waarden, maar kan dezelfde bron hebben en is geen onafhankelijke bevestiging. Zonder tabelwaarde blijft het veld leeg.","Sterkte is geen geluksscore. 「入庙不加吉，平等」 betekent dat een sterke positie zonder gunstige sterren gewoon kan blijven. Andere sterren, transformaties en het tegenoverliggende paleis tellen mee.","De kaart wordt opnieuw getekend met de gegevens die bij aankoop zijn opgeslagen. Je ontvangen duiding verandert niet."],"notes":"Voorwaarden in dit paleis","hint":"Paleizen die dit deel bespreekt"},
ms:{"chart":"Carta Zi Wei Dou Shu","select":"Pilih istana","legend":"Ke kiri: sifat bintang lebih jelas · bukan ukuran tuah atau malang","body":"Istana tubuh","noMain":"Istana ini tiada bintang utama. Baca bersama bintang utama di istana bertentangan.","noMainShort":"Tiada bintang utama","modern":"Jadual moden","kinds":{"main":"Bintang utama","assistant":"Bintang sokongan","malefic":"Faktor ketegangan"},"grades":{"묘":"Sifat paling jelas dan stabil","왕":"Sifat terserlah dengan kuat","득":"Kedudukan sesuai untuk sifat terserlah","리":"Boleh dimanfaatkan tetapi sedikit lebih lemah","평":"Sederhana; bergantung pada bintang bersama, transformasi dan istana bertentangan","불":"Kedudukan kurang sesuai, di bawah tahap sederhana","함":"Sifat terhalang atau terpesong; pertimbangkan faktor pengimbang","한":"Potensi kurang aktif atau dimanfaatkan"},"hua":{"화록":"化祿 Lu · sumber","화권":"化權 Quan · kuasa","화과":"化科 Ke · pengiktirafan","화기":"化忌 Ji · halangan"},"howTitle":"Cara kekuatan bintang dibaca","how":["Tanda di sebelah bintang menunjukkan kejelasan sifatnya pada cabang bumi istana ini, berdasarkan jilid 3 紫微斗數全書. 廟 paling jelas dan 陷 paling terhalang.","Ruang tanpa catatan klasik diisi daripada iztro dan dilabel jadual moden. 紫微人生 memberikan nilai sama tetapi mungkin berkongsi sumber, maka bukan pengesahan bebas. Bintang tanpa nilai dibiarkan kosong.","Kekuatan bukan markah tuah. 「入庙不加吉，平等」 bermaksud kedudukan kuat tanpa bintang baik boleh tetap biasa. Bintang bersama, transformasi dan istana bertentangan turut dibaca.","Carta dilukis semula daripada nilai yang disimpan ketika pembelian. Bacaan yang telah diterima tidak berubah."],"notes":"Keadaan yang dibaca dalam istana ini","hint":"Istana yang dihuraikan dalam bahagian ini"}
};

export function ziweiChartCopy(locale?:ReadingLocale):Copy{
 return localized[locale||'ko'];
}
export const gradeText=(copy:Copy,grade:string|null)=>grade&&grade in copy.grades?copy.grades[grade as Grade]:null;
export const huaText=(copy:Copy,hua?:string)=>hua&&hua in copy.hua?copy.hua[hua as Hua]:null;
/** 칸 안의 한 글자. 得地·不得地는 첫 글자만 쓴다(범례와 같은 글자). */
export const gradeGlyph=(gradeHanja:string|null)=>gradeHanja?gradeHanja[0]:null;
export const HUA_GLYPH:Record<string,string>={화록:'祿',화권:'權',화과:'科',화기:'忌'};
export const GRADE_LEGEND='廟 旺 得 利 平 不 陷';
