/**
 * `/insights/<slug>` 문서 제목(head 의 title) 전용 문구.
 *
 * 왜 별도 표인가 — 기사 데이터의 `title` 은 화면 H1 이자 허브 카드 제목이라 설명적으로 길고,
 * 그대로 문서 제목으로 쓰면 SERP 에서 잘린다. 2026-08-27 실측(dist 기준, 색인 대상 388개):
 * 문서 제목을 **표시 폭**(한중일 글자 = 라틴 2배)으로 재면 `/insights` 기사 125개 중 111개가
 * 한계(약 60)를 넘었고 중앙값이 75, 최대 111 이었다. 글자 수로만 재면 5개로 보여 놓치던 층이다.
 *
 * 🔴 기사 레코드의 `metaTitle`/`seoTitle` 에 넣지 않는 이유 — 그 두 필드는 정규화를 거쳐
 * `seed-articles.js` 의 `seoTitle` 이 되고, 그 값을 인사이트 허브 카드(`app/insights/page.js`,
 * `InsightsCosmicClient.js`)가 화면 문구로 읽는다. 즉 거기에 쓰면 문서 제목만이 아니라
 * 목록 UI 까지 함께 바뀐다. 여기서 바꿔야 하는 것은 문서 제목 하나뿐이다.
 *
 * 규칙: 접미사(` | 운세 인사이트`)를 붙이지 않는 **완성된 제목**을 적는다. 대상 키워드를 앞에
 * 두고 표시 폭 60 이하를 지킨다. 강제는 `scripts/verify-adsense-readiness.mjs` 의
 * `verifyIndexableTitleWidth` 가 산출물에서 사이트맵 URL 전량을 훑어서 한다.
 */
export const INSIGHT_SEO_TITLES = {
  "africa-divination-traditions-deep-guide": "아프리카 점복 전통 — 이파(Ifa)와 공동체의 지혜",
  "asia-divination-traditions-deep-guide": "아시아 점복 전통 — 주역·사주·자미두수의 세계",
  "astrology-birth-chart-guide": "네이탈 차트 완전 가이드 — 태양·달·상승궁",
  "astrology-houses-what-is": "점성술 하우스란? 12하우스 완벽 가이드",
  "astrology-mercury-retrograde-practical-guide": "수성 역행 실전 대응 — 3주 체크리스트",
  "astrology-synastry-compatibility-fun-guide": "시나스트리 궁합 차트 — 별자리 궁합 가이드",
  "byeongo-year-reorder-signals": "2026 병오년 종합 운세 — 재물·연애 가이드",
  "career-luck-interview-exam-prep-strategy": "커리어 운 — 면접·시험 합격률 높이는 전략",
  "cheongan-jiji-complete-explanation": "천간·지지 완전 해설 — 십천간·십이지 가이드",
  "daewoon-sewoon-reading-complete-guide": "대운·세운 읽는 법 — 명리학 운 해석의 핵심",
  "europe-divination-traditions-deep-guide": "유럽 점복 전통 — 타로·룬·찻잎점의 역사",
  "famous-saju-day-master-reading-practice": "유명인 사주로 배우는 일간(日干) 읽기",
  "five-elements-ohang-complete-guide": "오행(목화토금수) 균형·성격 완전 가이드",
  "how-to-raise-luck-daily-routine-practical-guide": "매일 운을 높이는 루틴 — 아침·점심·밤 15분",
  "how-we-calculate-saju": "명식은 어떻게 세워지나 — 사주 계산 기준",
  "iljoo-personality-complete-guide-60-pillars": "일간·일주 성격 완전 해설 — 육십갑자 가이드",
  "lucky-day-selection-without-superstition": "길일 택일 체크리스트 — 미신 없이 고르는 법",
  "manseoryeok-what-is": "만세력(萬歲曆)이란? 만세력 보는 법 가이드",
  "middle-east-divination-traditions-deep-guide": "중동 점복 전통 — 지오맨시·커피점·해몽",
  "midnight-birth-day-pillar": "자정 출생, 일주가 갈리는 이유 — 야자시",
  "money-luck-habits-and-saju-finance-rules": "재물운 습관과 사주 재정 규칙 가이드",
  "new-moon-full-moon-fortune-routine": "신월·보름달 운세 루틴 — 달의 흐름 따라",
  "new-year-fortune-framework": "신년운세 완전 가이드 — 1년을 설계하는 법",
  "relationship-luck-and-communication-rules": "숙요점 관계운과 소통 규칙 실전 가이드",
  "saju-12-unseong-complete-guide": "십이운성(十二運星) — 기운의 12단계 가이드",
  "saju-2026-monthly-planning-framework": "2026 병오년 월별 계획 — 일간별 로드맵",
  "saju-2027-monthly-planning-framework": "2027 정미년 월별 계획 — 일간별 로드맵",
  "saju-and-tarot-combined-reading-framework": "사주+타로 통합 리딩 — 두 체계 함께 쓰기",
  "saju-compatibility-how-to": "사주 궁합 보는 법 — 일간·오행·십성 총정리",
  "saju-how-to-read-step-by-step-beginner-guide": "사주 입문 — 사주팔자와 네 기둥 개념",
  "saju-job-change-timing-checklist-2026": "이직 타이밍 체크리스트 — 명리학 15단계",
  "saju-without-birth-time-three-pillars-guide": "출생시간 모를 때 사주 — 세 기둥 읽는 법",
  "singang-sinyak-judgment-complete-guide": "신강·신약 판단법 — 일간 강약 읽는 기준",
  "sleep-rhythm-energy-and-luck-connection": "수면 리듬과 운의 관계 — 시진 숙면 가이드",
  "sukuyo-27-guardian-animals-origin-guide": "27숙 수호동물 유래 — 역사적 근거와 상징",
  "sukuyo-27-mansions": "27숙 완전 정리 — 각 숙의 성격과 기질",
  "sukuyo-ankai": "숙요점 안괴관계 — 근거리·중거리·원거리 안괴 궁합",
  "sukuyo-antai": "숙요점 업태관계 — 업태 궁합과 거리별 끌림의 차이",
  "sukuyo-beginner-terms-easy-dictionary": "숙요점 초심자 용어 사전 — 쉬운 말 핵심",
  "sukuyo-bonmyeongsuk-vs-wolmyeongsuk": "본명숙 vs 월명숙 — 숙요 궁합의 기준",
  "sukuyo-boundary-setting-practical-guide": "숙요점 경계 설정 — 건강한 거리 두기",
  "sukuyo-compatibility-guide": "숙요점 궁합 — 영친·업태·안괴 6유형 총정리",
  "sukuyo-conflict-repair-dialogue-templates": "숙요점 갈등 회복 — 재조정하는 대화법",
  "sukuyo-couple-finance-rhythm-guide": "숙요점 커플 재정 리듬 — 돈과 사랑의 관계",
  "sukuyo-day-by-day-rhythm-usage": "숙요점 일상 리듬 활용법 — 반복 습관의 힘",
  "sukuyo-eishin": "숙요점 영친관계 — 영친 궁합이 편안한 이유",
  "sukuyo-friendship-teamwork-guide": "숙요점 우정·팀워크 — 친구와 동료의 인연",
  "sukuyo-love-communication-rules": "숙요점 연애 소통 규칙 — 전달 방식의 힘",
  "sukuyo-love": "숙요점 연애 궁합 — 6유형으로 보는 전개",
  "sukuyo-marriage": "숙요점 결혼 궁합 — 6유형 결혼 생활 패턴",
  "sukuyo-myeongseong": "숙요점 명성관계 — 명성 궁합의 목표와 성취",
  "sukuyo-qa-most-asked-questions": "숙요점 자주 묻는 질문 Q&A — 초보 핵심",
  "sukuyo-useo": "숙요점 우쇠관계 — 우쇠 궁합이 오래가는 이유",
  "sukuyo-vs-saju-compatibility": "숙요점과 사주의 차이 — 무엇이 다른가",
  "sukuyo-what-is": "숙요점이란? 숙요 점성술과 본명숙 27수 입문",
  "sukuyo-wiseong": "숙요점 위성관계 — 위성 궁합과 거리별 해석",
  "tarot-career-reading-7-question-framework": "타로 직업운 리딩 — 7질문 프레임워크",
  "tarot-compatibility-reading-game": "타로 궁합 리딩 게임 — 재미로 보는 케미",
  "tarot-court-cards-personality-and-relationship-guide": "타로 코트 카드 — 성격·관계 해석 가이드",
  "tarot-how-to-read": "타로 보는 법 & 질문 설계 완전 가이드",
  "tarot-major-arcana-22-complete-meanings": "메이저 아르카나 22장 완전 해설",
  "tarot-minor-arcana-four-suits-practical-guide": "마이너 아르카나 4수트 실전 가이드",
  "tarot-partner-mind-reading": "상대 속마음 타로 리딩 — 윤리적으로 읽기",
  "tarot-practical-reading-casebook-by-question": "질문 유형별 타로 실전 리딩 케이스북",
  "tarot-reunion-reading": "재회 타로 리딩 — 희망과 현실을 함께 읽기",
  "tarot-reversed-card-framework": "타로 역방향 해석 — 다섯 패턴 프레임",
  "tarot-spread-design-principles": "타로 스프레드 설계 원칙 — 질문에 맞는 배치",
  "ten-gods-practical-map-love-work-money": "십성 실전 지도 — 연애·일·돈의 5가지 언어",
  "today-tarot-routine": "오늘의 타로 루틴 — 하루 한 장으로 배우기",
  "vedic-astrology-12-rasi-complete-personality-guide": "베다 점성술 12라시 — 성격 완전 총정리",
  "vedic-astrology-navamsa-basics": "나밤샤(D9) 가이드 — 결혼과 행성의 힘",
  "vedic-compatibility-synastry-basics": "베다 궁합 구나 밀라나 36점법 기초",
  "vedic-dasha-transit-remedy-practical-guide": "다샤·고차르·우파야 — 베다 실전 가이드",
  "vedic-lagna-what-is": "라그나(Lagna)란? 베다 상승점 가이드",
  "vedic-moon-sign-emotion-routine-guide": "문라시 감정 관리 루틴 — 하루 6분 실천",
  "vedic-retrograde-planets-practical-decoding": "베다 역행 행성(바크리) 완전 해석",
  "vedic-transit-journal-template-90days": "베다 90일 트랜짓 저널 템플릿",
  "vedic-what-is": "베다점성술(조티쉬)이란? 초보 입문 가이드",
  "why-saju-results-differ-between-services": "같은 생일인데 사주가 다른 4가지 이유",
  "world-strange-divination-guide-including-pig-oracle": "세계의 신기한 점술 — 돼지점부터 주역까지",
  "yongshin-finding-method-practical-guide": "용신(用神) 찾는 법 — 명리학의 핵심 정리",
  "ziwei-14-main-stars-complete-guide": "자미두수 14주성 총론 — 명반의 중심 별",
  "ziwei-career-palace-action": "자미두수 직업운·승진운 — 12궁 실천 체크",
  "ziwei-compatibility-palace-method": "자미두수 궁합 — 부처궁으로 배우자 운 읽기",
  "ziwei-decade-and-annual-flow-reading-guide": "자미두수 대한·유년 흐름 읽는 법",
  "ziwei-four-transformations-lu-quan-ke-ji-guide": "사화(四化) 가이드 — 화록·화권·화과·화기",
  "ziwei-jumen-star-speech-and-doubt": "거문성(巨門星) 해설 — 말·분석의 암성",
  "ziwei-lianzhen-star-principle-and-passion": "염정성(廉貞星) 해설 — 원칙·집념의 수성",
  "ziwei-life-palaces": "자미두수 12궁 전체 해석 — 명궁부터 부모궁",
  "ziwei-minggong": "자미두수 명궁(命宮) 해석 — 명반의 중심",
  "ziwei-pojun-star-change-and-rebuild": "파군성(破軍星) 해설 — 변혁·재창조의 모성",
  "ziwei-qisha-star-decision-and-frontier": "칠살성(七殺星) 해설 — 결단·개척의 장성",
  "ziwei-star-brightness": "별 밝기(廟旺利平陷) — 별의 힘 읽는 법",
  "ziwei-star-combinations-for-beginners": "자미두수 별 조합 입문 — 14주성 함께 읽기",
  "ziwei-sun-moon-balance": "태양·태음 균형 — 자미두수 음양 조화",
  "ziwei-tanlang-star-desire-and-talent": "탐랑성(貪狼星) 해설 — 욕망·재능·도화",
  "ziwei-tiandong-meaning-and-palaces": "천동성(天同星) 해설 — 복과 온화함의 별",
  "ziwei-tianfu-star-wealth-and-stability": "천부성(天府星) 해설 — 재물창고와 안정",
  "ziwei-tianji-star-strategy-and-change": "천기성(天機星) 해설 — 지혜·기획의 참모별",
  "ziwei-tianliang-star-guardian-and-principle": "천량성(天梁星) 해설 — 보호·원칙의 음성",
  "ziwei-tianxiang-star-coordination-and-trust": "천상성(天相星) 해설 — 보좌·조정의 인성",
  "ziwei-vs-saju": "자미두수 vs 사주 — 무엇이 다르고 언제 함께 보나",
  "ziwei-wugok-meaning-and-palaces": "무곡성(武曲星) 해설 — 재물·결단의 재성",
  "ziwei-ziwei-star-beginner-guide": "자미성(紫微星) 해설 — 자미두수의 황제별",
};
