import type {CheckoutCopy} from './checkout-copy';
import type {LoadingLocale} from '@/constants/loadingMessages';
import {consultationLocaleCopy} from '../yeongnyangi/_lib/consultation-locale-copy';
import {consultationInputCopy} from '../yeongnyangi/_lib/consultation-input-copy';
import {resultStateCopy} from '../yeongnyangi/_lib/result-state-copy';
import {chromeCopy} from '../yeongnyangi/_lib/chrome-copy';
const labels={
 vi:{amount:'Giá thanh toán từng lần',eligibility:"Điều kiện gói Family không đổi. Các hạng gói thông thường khác không áp dụng.",auth:'Đang kiểm tra đăng nhập',opening:'Đang mở cửa sổ thanh toán',returning:'Đang trở về Yeongnyangi',pay:'Chọn cách thanh toán',method:'Chọn phương thức thanh toán ở màn hình tiếp theo.',cancelled:'Đã hủy thanh toán. Bạn có thể chọn lại khi sẵn sàng.',missing:'Chưa xác nhận được sản phẩm. Hãy quay lại và chọn bài đọc.',mismatch:'Bài đọc và gói đã chọn không khớp. Hãy chọn lại trước khi thanh toán.',failed:'Chưa tiếp tục được thanh toán. Vui lòng thử lại.'},
 hi:{amount:'एक बार के भुगतान की कीमत',eligibility:"Family पास की शर्तें पहले जैसी हैं। अन्य सामान्य पास लागू नहीं होते।",auth:'लॉग इन की स्थिति जाँची जा रही है',opening:'भुगतान विंडो खुल रही है',returning:'येओंगन्यांगी पर लौट रहे हैं',pay:'भुगतान का तरीका चुनें',method:'अगले पेज पर भुगतान का तरीका चुनें।',cancelled:'भुगतान रद्द हुआ। तैयार होने पर फिर चुनें।',missing:'चुने उत्पाद की पुष्टि नहीं हुई। वापस जाकर रीडिंग चुनें।',mismatch:'रीडिंग और चुना पैकेज मेल नहीं खाते। भुगतान से पहले फिर चुनें।',failed:'भुगतान जारी नहीं हो सका। फिर कोशिश करें।'},
 es:{amount:'Precio del pago único',eligibility:"Las condiciones de Family no cambian. No se aplican otros pases generales.",auth:'Comprobando tu sesión',opening:'Abriendo la ventana de pago',returning:'Volviendo a Yeongnyangi',pay:'Elegir forma de pago',method:'Elige el método de pago en la siguiente pantalla.',cancelled:'El pago se ha cancelado. Vuelve a elegir cuando estés listo.',missing:'No se pudo confirmar el producto. Vuelve y elige la lectura.',mismatch:'La lectura y el paquete elegido no coinciden. Vuelve a elegir antes de pagar.',failed:'No se pudo continuar el pago. Inténtalo de nuevo.'},
 fr:{amount:'Prix à l’unité',eligibility:"Les conditions du pass Family restent les mêmes. Les autres pass généraux ne s’appliquent pas.",auth:'Vérification de votre connexion',opening:'Ouverture de la fenêtre de paiement',returning:'Retour vers Yeongnyangi',pay:'Choisir un mode de paiement',method:'Choisissez le moyen de paiement sur l’écran suivant.',cancelled:'Le paiement a été annulé. Réessayez lorsque vous serez prêt.',missing:'Le produit n’a pas été confirmé. Revenez choisir votre lecture.',mismatch:'La lecture et la formule choisie ne correspondent pas. Sélectionnez-les à nouveau avant de payer.',failed:'Impossible de poursuivre le paiement. Veuillez réessayer.'},
 de:{amount:'Preis der Einzelzahlung',eligibility:"Für den Family-Pass gelten dieselben Bedingungen. Andere allgemeine Pass-Stufen gelten hier nicht.",auth:'Anmeldung wird geprüft',opening:'Zahlungsfenster wird geöffnet',returning:'Zurück zu Yeongnyangi',pay:'Zahlungsart wählen',method:'Wähle deine Zahlungsart auf der nächsten Seite.',cancelled:'Die Zahlung wurde abgebrochen. Wähle erneut, wenn du bereit bist.',missing:'Das Produkt konnte nicht bestätigt werden. Gehe zurück und wähle die Deutung.',mismatch:'Deutung und gewähltes Paket stimmen nicht überein. Bitte vor der Zahlung erneut wählen.',failed:'Die Zahlung konnte nicht fortgesetzt werden. Bitte erneut versuchen.'},
 nl:{amount:'Prijs voor losse betaling',eligibility:"De voorwaarden van Family blijven gelijk. Andere algemene passen gelden hier niet.",auth:'Je aanmelding wordt gecontroleerd',opening:'Betaalvenster wordt geopend',returning:'Terug naar Yeongnyangi',pay:'Betaalmethode kiezen',method:'Kies je betaalmethode op het volgende scherm.',cancelled:'De betaling is geannuleerd. Kies opnieuw wanneer je klaar bent.',missing:'Het product kon niet worden bevestigd. Ga terug en kies je reading.',mismatch:'De reading en het gekozen pakket komen niet overeen. Kies opnieuw voordat je betaalt.',failed:'De betaling kon niet doorgaan. Probeer opnieuw.'},
 ms:{amount:'Harga bayaran sekali',eligibility:"Syarat pas Family tidak berubah. Pas umum lain tidak terpakai.",auth:'Sedang menyemak log masuk',opening:'Sedang membuka tetingkap bayaran',returning:'Kembali ke Yeongnyangi',pay:'Pilih kaedah bayaran',method:'Pilih kaedah bayaran pada skrin seterusnya.',cancelled:'Bayaran dibatalkan. Pilih semula apabila sedia.',missing:'Produk tidak dapat disahkan. Kembali dan pilih bacaan.',mismatch:'Bacaan dan pakej pilihan tidak sepadan. Pilih semula sebelum membayar.',failed:'Bayaran tidak dapat diteruskan. Sila cuba lagi.'},
};
type NativeLocale=keyof typeof labels;
export const checkoutLocales:Record<NativeLocale,CheckoutCopy>=Object.fromEntries(Object.keys(labels).map(value=>{
 const locale=value as NativeLocale,t=labels[locale],ui=consultationLocaleCopy(locale),input=consultationInputCopy(locale),state=resultStateCopy(locale),chrome=chromeCopy(locale);
 const copy:CheckoutCopy={navAria:ui.paymentTitle,backToRoom:`← ${chrome.home}`,heroAlt:'Yeongnyangi',hostLine1:ui.guideTitle,hostLine2:ui.guideIntro,title:input.checkout,intro:ui.priceHint,shellLoading:input.busy,
  noticeTitle:ui.summary,noticeBody:t.missing,noticeLink:chrome.home,rowComposition:ui.structure,chapters:n=>`${n} ${ui.chapters}`,rowMethod:ui.paymentTitle,methodDirect:ui.payment,rowAmount:t.amount,
  policyLine1:ui.payment,policyLine2:t.eligibility,payAuthChecking:t.auth,payOrderChecking:input.busy,payUnavailable:input.unavailable,payOpening:t.opening,payReturning:t.returning,payAction:()=>t.pay,
  methodNote:t.method,cancelled:t.cancelled,reselect:ui.depth,legalTerms:chrome.terms,legalRefund:chrome.refund,legalSupport:chrome.contact,errResumePrepare:`${state.paymentRequired} ${state.paidWarning}`,errProductMismatch:t.mismatch,
  errPaymentFailed:t.failed,errPaymentUnknown:t.failed,won:(amount,intlLocale)=>`KRW ${Number(amount||0).toLocaleString(intlLocale)}`};
 return [locale,copy];
})) as Record<NativeLocale,CheckoutCopy>;
export function nativeCheckoutCopy(locale:LoadingLocale){return checkoutLocales[locale as NativeLocale];}
