import type {RuntimeLocale} from '../i18n/locale-normalize';
const rows:Record<RuntimeLocale,string[]>={
 ko:['이어서 상담하기','프롬프트를 복사해 원하는 AI에 붙여넣고, 같은 대화에서 후속 질문을 적어 주세요. 정보는 자동 전송되지 않으며 외부 서비스의 이용 조건이 적용됩니다.','상담 프롬프트 복사하기','복사했어요','자동 복사를 하지 못했어요. 아래 프롬프트를 직접 선택해 복사해 주세요.','외부 AI 선택','열기','상담 프롬프트 확인'],
 en:['Continue the consultation','Copy this prompt into your preferred AI, then ask follow-up questions in the same conversation. Nothing is sent automatically. The external service’s terms apply.','Copy consultation prompt','Copied','Copy failed. Select and copy the prompt below.','Choose an external AI','Open','View consultation prompt'],
 ja:['相談を続ける','プロンプトをお好みのAIに貼り付け、同じ会話で追加質問をしてください。情報は自動送信されません。外部サービスの利用条件が適用されます。','相談プロンプトをコピー','コピーしました','コピーできませんでした。下の文章を選択してコピーしてください。','外部AIを選ぶ','開く','相談プロンプトを見る'],
 'zh-CN':['继续咨询','将提示词复制到你选择的AI，在同一对话中继续提问。不会自动发送信息，适用外部服务的条款。','复制咨询提示词','已复制','复制失败，请手动选择下方提示词并复制。','选择外部AI','打开','查看咨询提示词'],
 'zh-TW':['繼續諮詢','將提示詞複製到你選擇的AI，在同一對話中繼續提問。不會自動傳送資訊，適用外部服務的條款。','複製諮詢提示詞','已複製','複製失敗，請手動選取下方提示詞並複製。','選擇外部AI','開啟','查看諮詢提示詞'],
 vi:['Tiếp tục tham vấn','Sao chép lời nhắc vào AI bạn chọn rồi hỏi tiếp trong cùng cuộc trò chuyện. Không tự động gửi dữ liệu. Áp dụng điều khoản của dịch vụ bên ngoài.','Sao chép lời nhắc','Đã sao chép','Chưa sao chép được. Hãy chọn và sao chép nội dung bên dưới.','Chọn AI bên ngoài','Mở','Xem lời nhắc'],
 hi:['परामर्श जारी रखें','प्रॉम्प्ट को अपने चुने AI में पेस्ट करें और उसी बातचीत में आगे पूछें। जानकारी स्वतः नहीं भेजी जाती। बाहरी सेवा की शर्तें लागू होती हैं।','परामर्श प्रॉम्प्ट कॉपी करें','कॉपी हो गया','कॉपी नहीं हुआ। नीचे का प्रॉम्प्ट चुनकर कॉपी करें।','बाहरी AI चुनें','खोलें','परामर्श प्रॉम्प्ट देखें'],
 es:['Continuar la consulta','Copia el prompt en la IA que prefieras y pregunta en la misma conversación. No se envía información automáticamente. Se aplican las condiciones del servicio externo.','Copiar prompt','Copiado','No se pudo copiar. Selecciona y copia el texto de abajo.','Elegir IA externa','Abrir','Ver prompt'],
 fr:['Poursuivre la consultation','Collez le prompt dans l’IA de votre choix, puis posez vos questions dans la même conversation. Rien n’est envoyé automatiquement. Les conditions du service externe s’appliquent.','Copier le prompt','Copié','Échec de la copie. Sélectionnez et copiez le texte ci-dessous.','Choisir une IA externe','Ouvrir','Voir le prompt'],
 de:['Beratung fortsetzen','Füge den Prompt in eine KI deiner Wahl ein und stelle Nachfragen im selben Gespräch. Nichts wird automatisch gesendet. Es gelten die Bedingungen des externen Dienstes.','Beratungs-Prompt kopieren','Kopiert','Kopieren fehlgeschlagen. Markiere und kopiere den Text unten.','Externe KI wählen','Öffnen','Prompt ansehen'],
 nl:['Consult voortzetten','Plak de prompt in een AI naar keuze en stel vervolgvragen in hetzelfde gesprek. Er wordt niets automatisch verzonden. De voorwaarden van de externe dienst gelden.','Prompt kopiëren','Gekopieerd','Kopiëren mislukt. Selecteer en kopieer de tekst hieronder.','Externe AI kiezen','Openen','Prompt bekijken'],
 ms:['Teruskan konsultasi','Tampal arahan dalam AI pilihan anda dan tanya soalan susulan dalam perbualan yang sama. Tiada maklumat dihantar secara automatik. Syarat perkhidmatan luar terpakai.','Salin arahan konsultasi','Disalin','Gagal menyalin. Pilih dan salin teks di bawah.','Pilih AI luar','Buka','Lihat arahan'],
};
export function continuationCopy(locale:RuntimeLocale){const [title,description,copy,copied,error,navigation,open,view]=rows[locale];return {title,description,copy,copied,error,navigation,open,view};}
