import type {QuestionGuide} from './question-journey';

// Editorial examples only. Price and consultation structure remain in the catalog.
export const everydayConcerns:QuestionGuide[]=[
 {id:'love-01',group:'연애·재회',question:'연락은 나만 먼저 하는데 계속 다가가도 될까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-02',group:'연애·재회',question:'썸이 길어질수록 불안해지는 마음을 어떻게 다룰까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-03',group:'연애·재회',question:'헤어진 사람의 소식이 자꾸 궁금해져',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-04',group:'연애·재회',question:'다시 만난다면 같은 이유로 헤어지지 않을 수 있을까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-05',group:'연애·재회',question:'상대의 답장이 늦으면 하루가 흔들려',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-06',group:'연애·재회',question:'좋아하는 마음을 언제 어떻게 표현하면 좋을까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-07',group:'연애·재회',question:'연애를 시작하면 내 생활이 사라지는 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-08',group:'연애·재회',question:'좋은 사람인데 설레지 않는 이유가 뭘까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-09',group:'연애·재회',question:'거절이 두려워 마음을 숨기게 돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'love-10',group:'연애·재회',question:'이별 뒤 나를 돌보는 시간은 어떻게 보낼까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-01',group:'결혼·동행',question:'결혼 이야기를 꺼내면 서로 부담스러워져',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-02',group:'결혼·동행',question:'함께 살기 전에 어떤 차이를 살펴봐야 할까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-03',group:'결혼·동행',question:'결혼에 대한 두 사람의 속도가 달라',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-04',group:'결혼·동행',question:'가족의 기대와 내 선택 사이에서 고민이야',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-05',group:'결혼·동행',question:'생활 습관이 다른 사람과 잘 맞춰갈 수 있을까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-06',group:'결혼·동행',question:'결혼 준비 중 작은 일에도 자꾸 다투게 돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-07',group:'결혼·동행',question:'비혼을 선택해도 마음이 편안할 수 있을까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-08',group:'결혼·동행',question:'장거리 관계를 오래 이어갈 방법이 궁금해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-09',group:'결혼·동행',question:'사랑과 현실적인 조건 사이에서 망설여',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'marriage-10',group:'결혼·동행',question:'동반자에게 기대하는 것이 너무 많은 걸까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'love'},
 {id:'work-01',group:'직장·이직',question:'일은 익숙한데 더는 성장하는 느낌이 없어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-02',group:'직장·이직',question:'상사에게 내 의견을 말하기 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-03',group:'직장·이직',question:'퇴사를 생각하지만 다음 선택이 막막해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-04',group:'직장·이직',question:'안정적인 직장과 하고 싶은 일 사이에서 고민이야',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-05',group:'직장·이직',question:'새로운 팀에 적응하는 데 시간이 걸려',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-06',group:'직장·이직',question:'성과를 내도 인정받지 못하는 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-07',group:'직장·이직',question:'일을 거절하면 무책임해 보일까 봐 걱정돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-08',group:'직장·이직',question:'승진 뒤 늘어난 책임이 부담스러워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-09',group:'직장·이직',question:'동료와 비교하며 자신감을 잃고 있어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'work-10',group:'직장·이직',question:'경력 공백 후 다시 일하려니 두려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'money-01',group:'돈·생활',question:'월급날마다 지출 계획이 무너져',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-02',group:'돈·생활',question:'불안할 때 물건을 사는 습관을 바꾸고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-03',group:'돈·생활',question:'돈 이야기를 가족과 편하게 나누고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-04',group:'돈·생활',question:'모으는 재미보다 못 쓰는 답답함이 커',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-05',group:'돈·생활',question:'수입이 불규칙해서 생활 리듬이 흔들려',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-06',group:'돈·생활',question:'친구들과 소비 기준이 달라서 눈치가 보여',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-07',group:'돈·생활',question:'새로운 수입원을 준비할 여유를 어떻게 만들까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-08',group:'돈·생활',question:'돈을 빌려달라는 부탁에 선을 긋기 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-09',group:'돈·생활',question:'경제적으로 독립하는 첫걸음이 막막해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'money-10',group:'돈·생활',question:'큰 지출을 앞두고 내 판단 기준을 세우고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'money'},
 {id:'family-01',group:'가족·독립',question:'부모님의 조언이 간섭처럼 느껴져',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-02',group:'가족·독립',question:'가족에게 내 선택을 설명하기가 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-03',group:'가족·독립',question:'독립하고 싶은데 죄책감이 들어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-04',group:'가족·독립',question:'형제자매와 비교되는 상황이 지쳐',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-05',group:'가족·독립',question:'가족 모임에 다녀오면 마음이 무거워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-06',group:'가족·독립',question:'돌봄의 책임을 혼자 짊어진 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-07',group:'가족·독립',question:'가족과 가까워지고 싶지만 대화가 잘 안 돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-08',group:'가족·독립',question:'부모님과 다른 가치관을 어떻게 나눌까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'family-09',group:'가족·독립',question:'가족의 부탁을 거절해도 괜찮을까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-01',group:'친구·인간관계',question:'친구를 만나고 돌아오면 유난히 피곤해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-02',group:'친구·인간관계',question:'나만 관계를 유지하려 애쓰는 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-03',group:'친구·인간관계',question:'오래된 친구와 관심사가 달라졌어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-04',group:'친구·인간관계',question:'새로운 모임에서 말을 꺼내기 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-05',group:'친구·인간관계',question:'단체 대화방에서 소외되는 기분이 들어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-06',group:'친구·인간관계',question:'친구의 좋은 소식을 진심으로 축하하고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-07',group:'친구·인간관계',question:'부탁을 거절한 뒤에도 마음이 불편해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-08',group:'친구·인간관계',question:'상처받은 일을 말할지 그냥 넘길지 고민돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'friends-09',group:'친구·인간관계',question:'친밀함을 유지하면서 내 시간을 지키고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'relationship'},
 {id:'self-01',group:'마음·자존감',question:'작은 실수도 오래 곱씹게 돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-02',group:'마음·자존감',question:'칭찬을 받아도 쉽게 믿기 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-03',group:'마음·자존감',question:'쉬고 있어도 뒤처지는 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-04',group:'마음·자존감',question:'남의 시선보다 내 기준으로 선택하고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-05',group:'마음·자존감',question:'잘하고 싶은 마음이 시작을 막는 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-06',group:'마음·자존감',question:'다른 사람의 기분을 너무 살피게 돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-07',group:'마음·자존감',question:'내가 좋아하는 것이 무엇인지 잘 모르겠어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-08',group:'마음·자존감',question:'결정을 하고도 자꾸 확신을 잃어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'self-09',group:'마음·자존감',question:'스스로에게 조금 더 다정해지고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'study-01',group:'공부·진로',question:'열심히 하는데 공부 방향이 맞는지 모르겠어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-02',group:'공부·진로',question:'전공을 계속할지 다른 길을 찾을지 고민이야',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-03',group:'공부·진로',question:'시험 결과가 내 가치처럼 느껴져',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-04',group:'공부·진로',question:'새로운 분야를 배우기에 늦은 건 아닐까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-05',group:'공부·진로',question:'진로를 정하라는 말이 부담스러워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-06',group:'공부·진로',question:'하고 싶은 일이 많아 하나를 고르기 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-07',group:'공부·진로',question:'면접에서 내 강점을 어떻게 드러낼까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-08',group:'공부·진로',question:'주변의 기대와 다른 진로를 선택하고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'study-09',group:'공부·진로',question:'긴 준비 기간 동안 의욕을 유지하고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'work'},
 {id:'change-01',group:'변화·새출발',question:'낯선 도시에서 다시 시작하려니 두려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-02',group:'변화·새출발',question:'이사 후 달라질 생활에 잘 적응할 수 있을까?',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-03',group:'변화·새출발',question:'새로운 도전을 미루는 이유를 알고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-04',group:'변화·새출발',question:'오래 해온 일을 내려놓기 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-05',group:'변화·새출발',question:'계획대로 되지 않을 때 유연해지고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-06',group:'변화·새출발',question:'작은 실패 뒤 다시 시작할 용기가 필요해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-07',group:'변화·새출발',question:'변화가 필요하지만 무엇부터 바꿀지 모르겠어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-08',group:'변화·새출발',question:'새로운 역할을 맡고 내 모습이 낯설어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'change-09',group:'변화·새출발',question:'익숙한 환경을 떠날지 머무를지 고민이야',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-01',group:'일상·균형',question:'하루가 바쁜데 내게 남는 것이 없는 것 같아',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-02',group:'일상·균형',question:'취미를 즐기면서도 생산성을 따지게 돼',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-03',group:'일상·균형',question:'혼자 있는 시간과 사람 만나는 시간의 균형이 어려워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-04',group:'일상·균형',question:'계획을 많이 세우지만 꾸준히 이어가지 못해',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-05',group:'일상·균형',question:'주말이 끝날 때마다 마음이 무거워',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-06',group:'일상·균형',question:'휴식이 필요한 순간을 알아차리고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-07',group:'일상·균형',question:'자꾸 미루는 습관 뒤의 마음을 이해하고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-08',group:'일상·균형',question:'내 속도에 맞는 생활 리듬을 찾고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
 {id:'daily-09',group:'일상·균형',question:'작은 성취를 스스로 인정하는 연습을 하고 싶어',next:'지금의 고민과 반복되는 선택을 차분히 살펴봐요.',productId:'saju_mackerel',kind:'ask',topic:'self'},
];
