import type {RuntimeLocale as ReadingLocale} from '../i18n/locale-normalize';
export const symbolicCopyKeys=["title","horaryTitle","intro","description","question","questionHint","topic","topicHint","relationship","city","cityPick","location","cityHint","time","timeHint","situation","situationHint","boundary","paidSummary","paidPrice","freeSummary","freePrice","freeSubmit","busy","unavailable","validation","error","imageAlt","navigation","other","consultedAt","region","regionSuffix","answer","complete","awaiting","followup","followupHint","followupSubmit","followupUsed","final","share","copied","shareError","followupError","birthIntro","birthUnknown","birthTiming","spiritIntro","spiritScope","relationshipPick","login","saved","freeDone","locationQuestion","locationApply","shareDone","shareCancelled"] as const;
export type SymbolicCopyKey=typeof symbolicCopyKeys[number];
export const symbolicCopyRows:Record<Exclude<ReadingLocale,'ko'>,string[]>={
  "en": [
    "Yeongnyangi Oracle",
    "Yeongnyangi Horary",
    "Explore your question through the sky at the moment it arose.",
    "This traditional symbolic reading considers the conditions around your question and the choices available to you.",
    "One question for Yeongnyangi",
    "Write the one thing you most want to understand.",
    "Topic",
    "Your written question takes priority over the selected topic.",
    "Your relationship",
    "Where you were when the question arose",
    "Choose your city",
    "Confirmed location · time zone:",
    "Choose a city centre or confirm your current location. Use your own location when the question arose, not another person’s.",
    "Date and time of the question",
    "Enter the time you remember. The server resolves the city’s time zone. If uncertain, use the moment you clearly restate your question. Birth details are not needed.",
    "What you already know",
    "Describe the situation without names, addresses or contact details.",
    "The other person has refused contact or blocked me",
    "Oracle reading · initial result and one follow-up",
    "Family Pass or one-time payment",
    "Traditional Western horary calculations and a prompt for an external AI",
    "Free · prompt provided",
    "Create a free horary prompt",
    "Preparing your reading",
    "The reading is currently unavailable. No payment will proceed.",
    "Check your question, relationship and required profile or question location and time.",
    "We could not prepare this step. Please try again.",
    "Yeongnyangi in traditional Korean dress",
    "Reading navigation",
    "Choose another reading",
    "Reading reference",
    "Question location",
    "Symbolic reading based on the selected location",
    "Key answer",
    "Your reading has been saved.",
    "Your first answer is ready. You can ask one follow-up below.",
    "Explore one point further",
    "Choose one point from the first answer and ask for more detail.",
    "Send follow-up",
    "The included follow-up has been used.",
    "A closing note from Yeongnyangi",
    "Share an anonymous introduction",
    "Copied",
    "Sharing could not finish. Please try again.",
    "Enter one follow-up of 5–600 characters after the first result is ready.",
    "This reading needs your birth date. You can leave the birth time unknown; the interpretation will reflect that limit.",
    "Use an unknown birth time for this reading",
    "The server records the submission time and time zone. This reading does not collect your location or another person’s whereabouts.",
    "Let’s separate what you know from what remains uncertain.",
    "This reading considers your own birth-based tendencies and relationship choices. It cannot establish another person’s thoughts, whereabouts or the timing of contact or reunion.",
    "Choose a relationship",
    "Sign in to start",
    "saved",
    "Your horary calculation is ready",
    "Were you here when the question arose?",
    "Yes, use this question location",
    "Sharing completed.",
    "Sharing cancelled."
  ],
  "ja": [
    "Yeongnyangi オラクル",
    "Yeongnyangi ホラリー",
    "質問が浮かんだ瞬間の空から、今の選択を見つめます。",
    "質問時の条件と選択肢を、伝統的な象徴として読み解く相談です。",
    "聞きたいことを一つ",
    "いちばん知りたいことを書いてください。",
    "相談テーマ",
    "選んだテーマより、実際の質問を優先します。",
    "相手との関係",
    "質問が浮かんだときにいた都市",
    "都市を選択",
    "確認した現在地・タイムゾーン：",
    "都市の中心、または確認した現在地を使います。相手の居場所ではなく、質問したあなた自身の場所です。",
    "質問が浮かんだ日時",
    "覚えている時刻を入力してください。都市のタイムゾーンはサーバーで確認します。不明な場合は、質問を整理し直した瞬間を使ってください。出生情報は不要です。",
    "すでにわかっている状況",
    "名前・住所・連絡先を含めず、状況を説明してください。",
    "相手に連絡を断られた、またはブロックされた",
    "オラクル鑑定・最初の結果と追加相談1回",
    "Familyパスまたは都度払い",
    "伝統的な西洋ホラリーの計算と外部AI用プロンプト",
    "無料・プロンプトを提供",
    "無料ホラリープロンプトを作成",
    "鑑定を準備しています",
    "現在は準備中です。支払いは行われません。",
    "質問・関係と、必要なプロフィールまたは質問時の場所・日時を確認してください。",
    "準備できませんでした。もう一度お試しください。",
    "韓服姿のYeongnyangi",
    "鑑定メニュー",
    "別の鑑定を選ぶ",
    "鑑定の基準",
    "質問時の地域",
    "選択した場所に基づく象徴の解釈",
    "要点",
    "鑑定を保存しました。",
    "最初の回答ができました。下から追加質問を一つ送れます。",
    "もう少し詳しく聞く",
    "最初の回答から気になる点を一つ選んでください。",
    "追加質問を送る",
    "含まれる追加相談は利用済みです。",
    "Yeongnyangiからの結び",
    "匿名の紹介を共有",
    "コピーしました",
    "共有できませんでした。もう一度お試しください。",
    "最初の結果ができてから、5〜600文字の追加質問を一つ入力してください。",
    "生年月日が必要です。出生時刻は不明でも利用でき、その場合は解釈の範囲を限定します。",
    "今回は出生時刻を不明として扱う",
    "受付時刻とタイムゾーンはサーバーで保存します。あなたや相手の居場所は収集しません。",
    "わかっていることと、まだわからないことを分けてみましょう。",
    "あなた自身の出生傾向から関係での選択を考えます。相手の本心・居場所・連絡や復縁の時期は判断できません。",
    "関係を選択",
    "ログインして始める",
    "保存済み",
    "ホラリーの計算ができました",
    "質問が浮かんだときもこの場所でしたか？",
    "はい、この場所を使います",
    "共有操作が完了しました。",
    "共有をキャンセルしました。"
  ],
  "zh-CN": [
    "Yeongnyangi 问事咨询",
    "Yeongnyangi 卜卦占星",
    "从问题浮现时的天空，梳理当下的选择。",
    "以传统象征解读问题提出时的条件，帮助你思考可选的行动。",
    "想问的一个问题",
    "写下你最想了解的一件事。",
    "咨询主题",
    "优先参考你实际写下的问题。",
    "你与对方的关系",
    "问题浮现时你所在的城市",
    "选择城市",
    "已确认位置·时区：",
    "使用城市中心或你确认的当前位置。这是提问时你自己的位置，不是对方的位置。",
    "问题浮现的日期与时间",
    "请输入记得的时间。服务器会确认城市时区。不确定时，请以重新理清问题的时刻为准。无需出生资料。",
    "已经知道的情况",
    "描述情况即可，请勿填写姓名、地址或联系方式。",
    "对方已拒绝联系或将我拉黑",
    "问事咨询·初次结果与一次深入追问",
    "Family 通行券或单次支付",
    "传统西洋卜卦占星计算与外部AI提示词",
    "免费·提供提示词",
    "生成免费卜卦占星提示词",
    "正在准备咨询",
    "目前暂不可用，不会进行支付。",
    "请确认问题、关系及所需档案，或提问时的地点与时间。",
    "未能准备完成，请重试。",
    "身穿韩服的Yeongnyangi",
    "咨询导航",
    "选择其他咨询",
    "解读基准",
    "提问者地区",
    "基于所选地点的象征解读",
    "核心回答",
    "咨询内容已保存。",
    "首次回答已完成，可在下方追问一次。",
    "进一步了解一点",
    "从首次回答中选一个想深入了解的点。",
    "发送追问",
    "本次包含的追问已使用。",
    "Yeongnyangi 的寄语",
    "分享匿名介绍",
    "已复制",
    "分享未完成，请重试。",
    "首次结果完成后，请填写一个5至600字的追问。",
    "需要你的出生日期。出生时间可留为未知，解读会保留相应限制。",
    "本次按出生时间未知处理",
    "服务器记录提交时刻与时区，不收集你或对方的所在位置。",
    "一起区分已知情况与尚不确定的部分。",
    "根据你自身的出生倾向思考关系中的选择，不能确定对方想法、位置或联系与复合的时间。",
    "选择关系",
    "登录后开始",
    "已保存",
    "卜卦占星计算已完成",
    "问题浮现时，你在这里吗？",
    "是，使用这个提问地点",
    "分享操作已完成。",
    "已取消分享。"
  ],
  "zh-TW": [
    "Yeongnyangi 問事諮詢",
    "Yeongnyangi 卜卦占星",
    "從問題浮現時的天空，整理當下的選擇。",
    "以傳統象徵解讀提問時的條件，幫助你思考可選的行動。",
    "想問的一個問題",
    "寫下你最想了解的一件事。",
    "諮詢主題",
    "優先參考你實際寫下的問題。",
    "你與對方的關係",
    "問題浮現時你所在的城市",
    "選擇城市",
    "已確認位置・時區：",
    "使用城市中心或你確認的目前位置。這是提問時你自己的位置，不是對方的位置。",
    "問題浮現的日期與時間",
    "請輸入記得的時間。伺服器會確認城市時區。不確定時，請以重新釐清問題的時刻為準。無需出生資料。",
    "已經知道的情況",
    "描述情況即可，請勿填寫姓名、地址或聯絡方式。",
    "對方已拒絕聯絡或將我封鎖",
    "問事諮詢・首次結果與一次深入追問",
    "Family 通行券或單次付款",
    "傳統西洋卜卦占星計算與外部AI提示詞",
    "免費・提供提示詞",
    "產生免費卜卦占星提示詞",
    "正在準備諮詢",
    "目前暫不可用，不會進行付款。",
    "請確認問題、關係及所需檔案，或提問時的地點與時間。",
    "未能準備完成，請重試。",
    "身穿韓服的Yeongnyangi",
    "諮詢導覽",
    "選擇其他諮詢",
    "解讀基準",
    "提問者地區",
    "依所選地點進行的象徵解讀",
    "核心回答",
    "諮詢內容已儲存。",
    "首次回答已完成，可在下方追問一次。",
    "進一步了解一點",
    "從首次回答中選一個想深入了解的地方。",
    "送出追問",
    "本次包含的追問已使用。",
    "Yeongnyangi 的寄語",
    "分享匿名介紹",
    "已複製",
    "分享未完成，請重試。",
    "首次結果完成後，請填寫一個5至600字的追問。",
    "需要你的出生日期。出生時間可留為未知，解讀會保留相應限制。",
    "本次按出生時間未知處理",
    "伺服器記錄提交時刻與時區，不收集你或對方的所在位置。",
    "一起區分已知情況與尚不確定的部分。",
    "依你自身的出生傾向思考關係中的選擇，不能確定對方想法、位置或聯絡與復合的時間。",
    "選擇關係",
    "登入後開始",
    "已儲存",
    "卜卦占星計算已完成",
    "問題浮現時，你在這裡嗎？",
    "是，使用這個提問地點",
    "分享操作已完成。",
    "已取消分享。"
  ],
  "es": [
    "Oráculo de Yeongnyangi",
    "Horaria de Yeongnyangi",
    "Explora tu pregunta a partir del cielo del momento en que surgió.",
    "Una lectura simbólica tradicional sobre las condiciones de tu pregunta y tus opciones.",
    "Una pregunta para Yeongnyangi",
    "Escribe lo que más quieres comprender.",
    "Tema",
    "Tu pregunta escrita tiene prioridad sobre el tema elegido.",
    "Tu relación",
    "Ciudad donde surgió la pregunta",
    "Elige una ciudad",
    "Ubicación confirmada · zona horaria:",
    "Usamos el centro de la ciudad o tu ubicación confirmada cuando surgió la pregunta, nunca la de otra persona.",
    "Fecha y hora de la pregunta",
    "Indica la hora que recuerdas. El servidor confirma la zona horaria. Si no la sabes, usa el momento en que reformulas la pregunta. No se necesitan datos de nacimiento.",
    "Lo que ya sabes",
    "Describe la situación sin nombres, direcciones ni datos de contacto.",
    "La otra persona rechazó el contacto o me bloqueó",
    "Lectura oracular · resultado inicial y una consulta adicional",
    "Pase Family o pago único",
    "Cálculo de astrología horaria occidental y un prompt para una IA externa",
    "Gratis · incluye prompt",
    "Crear prompt gratuito de horaria",
    "Preparando la lectura",
    "No disponible por ahora. No se realizará ningún pago.",
    "Revisa la pregunta, la relación y el perfil necesario, o el lugar y la hora de la pregunta.",
    "No se pudo preparar. Inténtalo de nuevo.",
    "Yeongnyangi con traje tradicional coreano",
    "Navegación de lecturas",
    "Elegir otra lectura",
    "Referencia de la lectura",
    "Lugar de la pregunta",
    "Interpretación simbólica del lugar elegido",
    "Respuesta principal",
    "La lectura se ha guardado.",
    "Tu primera respuesta está lista. Puedes hacer una pregunta adicional.",
    "Profundizar en un punto",
    "Elige un punto de la primera respuesta para explorarlo con más detalle.",
    "Enviar pregunta adicional",
    "Ya has usado la consulta adicional incluida.",
    "Unas palabras finales de Yeongnyangi",
    "Compartir una presentación anónima",
    "Copiado",
    "No se pudo compartir. Inténtalo de nuevo.",
    "Tras recibir el primer resultado, escribe una pregunta adicional de 5 a 600 caracteres.",
    "Se necesita tu fecha de nacimiento. Puedes dejar la hora como desconocida; la lectura respetará ese límite.",
    "Usar hora de nacimiento desconocida",
    "El servidor registra la hora de envío y la zona horaria. No recoge tu ubicación ni la de otra persona.",
    "Separemos lo que sabes de lo que sigue siendo incierto.",
    "Explora tus propias tendencias natales y decisiones en las relaciones. No establece pensamientos ajenos, ubicaciones ni fechas de contacto o reconciliación.",
    "Elige la relación",
    "Iniciar sesión y comenzar",
    "guardado",
    "Tu cálculo de horaria está listo",
    "¿Estabas aquí cuando surgió la pregunta?",
    "Sí, usar este lugar",
    "Se completó la acción de compartir.",
    "Se canceló el uso compartido."
  ],
  "fr": [
    "Oracle de Yeongnyangi",
    "Astrologie horaire de Yeongnyangi",
    "Explorez votre question à travers le ciel du moment où elle est apparue.",
    "Une lecture symbolique traditionnelle des conditions de votre question et des choix possibles.",
    "Une question pour Yeongnyangi",
    "Écrivez ce que vous souhaitez le plus comprendre.",
    "Thème",
    "Votre question écrite passe avant le thème choisi.",
    "Votre relation",
    "Ville où la question est apparue",
    "Choisir une ville",
    "Position confirmée · fuseau horaire :",
    "Le centre-ville ou votre position confirmée sert de référence. Indiquez votre propre lieu au moment de la question, jamais celui d’une autre personne.",
    "Date et heure de la question",
    "Saisissez l’heure dont vous vous souvenez. Le serveur confirme le fuseau horaire. En cas de doute, utilisez le moment où vous reformulez la question. Aucune donnée de naissance n’est nécessaire.",
    "Ce que vous savez déjà",
    "Décrivez la situation sans nom, adresse ni coordonnées.",
    "L’autre personne a refusé le contact ou m’a bloqué",
    "Lecture oraculaire · premier résultat et une question complémentaire",
    "Pass Family ou paiement unique",
    "Calcul d’astrologie horaire occidentale et prompt pour une IA externe",
    "Gratuit · prompt fourni",
    "Créer un prompt horaire gratuit",
    "Préparation de la lecture",
    "Indisponible pour le moment. Aucun paiement ne sera effectué.",
    "Vérifiez la question, la relation et le profil requis, ou le lieu et l’heure de la question.",
    "La préparation a échoué. Veuillez réessayer.",
    "Yeongnyangi en tenue traditionnelle coréenne",
    "Navigation des lectures",
    "Choisir une autre lecture",
    "Référence de la lecture",
    "Lieu de la question",
    "Lecture symbolique du lieu choisi",
    "Réponse essentielle",
    "Votre lecture est enregistrée.",
    "La première réponse est prête. Vous pouvez poser une question complémentaire.",
    "Approfondir un point",
    "Choisissez un point de la première réponse à explorer davantage.",
    "Envoyer la question complémentaire",
    "La question complémentaire incluse a été utilisée.",
    "Le mot de la fin de Yeongnyangi",
    "Partager une présentation anonyme",
    "Copié",
    "Le partage a échoué. Veuillez réessayer.",
    "Après le premier résultat, saisissez une question complémentaire de 5 à 600 caractères.",
    "Votre date de naissance est nécessaire. L’heure peut rester inconnue ; la lecture respectera cette limite.",
    "Considérer l’heure de naissance comme inconnue",
    "Le serveur enregistre l’heure d’envoi et le fuseau horaire. Il ne recueille ni votre position ni celle d’une autre personne.",
    "Distinguons ce que vous savez de ce qui reste incertain.",
    "Cette lecture explore vos tendances natales et vos choix relationnels. Elle ne détermine pas les pensées ou la position d’autrui, ni la date d’un contact ou d’une réconciliation.",
    "Choisir la relation",
    "Se connecter et commencer",
    "enregistré",
    "Votre calcul horaire est prêt",
    "Étiez-vous ici lorsque la question est apparue ?",
    "Oui, utiliser ce lieu",
    "Le partage est terminé.",
    "Le partage a été annulé."
  ],
  "de": [
    "Yeongnyangi-Orakel",
    "Yeongnyangi-Stundenastrologie",
    "Betrachte deine Frage anhand des Himmels zu dem Zeitpunkt, als sie entstand.",
    "Eine traditionelle symbolische Deutung der Bedingungen deiner Frage und deiner Möglichkeiten.",
    "Eine Frage an Yeongnyangi",
    "Schreibe auf, was du am meisten verstehen möchtest.",
    "Thema",
    "Deine geschriebene Frage hat Vorrang vor dem gewählten Thema.",
    "Deine Beziehung",
    "Stadt, in der die Frage entstand",
    "Stadt wählen",
    "Bestätigter Standort · Zeitzone:",
    "Wir verwenden das Stadtzentrum oder deinen bestätigten Standort zum Zeitpunkt der Frage, niemals den einer anderen Person.",
    "Datum und Uhrzeit der Frage",
    "Trage die erinnerte Uhrzeit ein. Der Server bestätigt die Zeitzone. Bei Unsicherheit nutze den Moment, in dem du die Frage neu formulierst. Geburtsdaten sind nicht nötig.",
    "Was du bereits weißt",
    "Beschreibe die Situation ohne Namen, Adressen oder Kontaktdaten.",
    "Die andere Person hat Kontakt abgelehnt oder mich blockiert",
    "Orakeldeutung · erstes Ergebnis und eine Vertiefung",
    "Family-Pass oder Einmalzahlung",
    "Traditionelle westliche Stundenastrologie mit einem Prompt für eine externe KI",
    "Kostenlos · Prompt enthalten",
    "Kostenlosen Horary-Prompt erstellen",
    "Deutung wird vorbereitet",
    "Derzeit nicht verfügbar. Es erfolgt keine Zahlung.",
    "Prüfe Frage, Beziehung und erforderliches Profil oder Ort und Zeit der Frage.",
    "Vorbereitung fehlgeschlagen. Bitte erneut versuchen.",
    "Yeongnyangi in traditioneller koreanischer Kleidung",
    "Navigation der Beratungen",
    "Andere Deutung wählen",
    "Bezugszeit der Deutung",
    "Ort der Frage",
    "Symbolische Deutung des gewählten Ortes",
    "Kernaussage",
    "Deine Deutung wurde gespeichert.",
    "Die erste Antwort ist fertig. Du kannst eine Nachfrage stellen.",
    "Einen Punkt vertiefen",
    "Wähle einen Punkt aus der ersten Antwort, den du genauer betrachten möchtest.",
    "Nachfrage senden",
    "Die enthaltene Nachfrage wurde genutzt.",
    "Abschließende Worte von Yeongnyangi",
    "Anonyme Vorstellung teilen",
    "Kopiert",
    "Teilen fehlgeschlagen. Bitte erneut versuchen.",
    "Gib nach dem ersten Ergebnis eine Nachfrage mit 5 bis 600 Zeichen ein.",
    "Dein Geburtsdatum wird benötigt. Die Uhrzeit darf unbekannt bleiben; die Deutung berücksichtigt diese Grenze.",
    "Geburtszeit für diese Deutung als unbekannt behandeln",
    "Der Server speichert Eingangszeit und Zeitzone. Dein Standort und der anderer Personen werden nicht erhoben.",
    "Trennen wir gesicherte Informationen von offenen Fragen.",
    "Die Deutung betrachtet deine eigenen Geburtstendenzen und Beziehungsentscheidungen. Sie bestimmt weder fremde Gedanken oder Aufenthaltsorte noch Termine für Kontakt oder Versöhnung.",
    "Beziehung wählen",
    "Anmelden und beginnen",
    "gespeichert",
    "Deine Stundenastrologie wurde berechnet",
    "Warst du hier, als die Frage entstand?",
    "Ja, diesen Ort verwenden",
    "Teilen abgeschlossen.",
    "Teilen abgebrochen."
  ],
  "nl": [
    "Yeongnyangi-orakel",
    "Yeongnyangi-uurhoekastrologie",
    "Verken je vraag via de hemel op het moment waarop ze ontstond.",
    "Een traditionele symbolische lezing over de omstandigheden van je vraag en je keuzemogelijkheden.",
    "Eén vraag aan Yeongnyangi",
    "Schrijf op wat je het liefst wilt begrijpen.",
    "Onderwerp",
    "Je eigen vraag krijgt voorrang op het gekozen onderwerp.",
    "Jullie relatie",
    "Stad waar de vraag ontstond",
    "Kies een stad",
    "Bevestigde locatie · tijdzone:",
    "We gebruiken het stadscentrum of jouw bevestigde locatie toen de vraag ontstond, nooit de locatie van iemand anders.",
    "Datum en tijd van de vraag",
    "Vul de tijd in die je je herinnert. De server bevestigt de tijdzone. Gebruik bij twijfel het moment waarop je je vraag opnieuw helder formuleert. Geboortegegevens zijn niet nodig.",
    "Wat je al weet",
    "Beschrijf de situatie zonder namen, adressen of contactgegevens.",
    "De ander heeft contact geweigerd of mij geblokkeerd",
    "Orakellezing · eerste resultaat en één vervolgvraag",
    "Family-pas of eenmalige betaling",
    "Traditionele westerse uurhoekberekening en een prompt voor externe AI",
    "Gratis · prompt inbegrepen",
    "Gratis uurhoekprompt maken",
    "Je lezing wordt voorbereid",
    "Nu niet beschikbaar. Er wordt geen betaling uitgevoerd.",
    "Controleer je vraag, relatie en vereiste profiel, of de plaats en tijd van de vraag.",
    "Voorbereiden is niet gelukt. Probeer het opnieuw.",
    "Yeongnyangi in traditionele Koreaanse kleding",
    "Navigatie van lezingen",
    "Een andere lezing kiezen",
    "Referentie van de lezing",
    "Plaats van de vraag",
    "Symbolische lezing van de gekozen locatie",
    "Kernantwoord",
    "Je lezing is opgeslagen.",
    "Je eerste antwoord is klaar. Je kunt hieronder één vervolgvraag stellen.",
    "Eén punt verder verkennen",
    "Kies één punt uit het eerste antwoord om verder uit te diepen.",
    "Vervolgvraag versturen",
    "De inbegrepen vervolgvraag is gebruikt.",
    "Slotwoorden van Yeongnyangi",
    "Anonieme introductie delen",
    "Gekopieerd",
    "Delen is niet gelukt. Probeer het opnieuw.",
    "Schrijf na het eerste resultaat één vervolgvraag van 5 tot 600 tekens.",
    "Je geboortedatum is nodig. Je geboortetijd mag onbekend blijven; de lezing houdt rekening met die beperking.",
    "Geboortetijd voor deze lezing als onbekend behandelen",
    "De server bewaart de inzendtijd en tijdzone. Jouw locatie en die van anderen worden niet verzameld.",
    "Laten we onderscheid maken tussen wat je weet en wat onzeker blijft.",
    "Deze lezing verkent je eigen geboortetendensen en keuzes in relaties. Ze bepaalt geen gedachten of locaties van anderen en geen contact- of verzoeningsdatum.",
    "Kies de relatie",
    "Inloggen en beginnen",
    "opgeslagen",
    "Je uurhoekberekening is klaar",
    "Was je hier toen de vraag ontstond?",
    "Ja, deze locatie gebruiken",
    "De deelactie is voltooid.",
    "Delen geannuleerd."
  ],
  "vi": [
    "Tham vấn biểu tượng Yeongnyangi",
    "Chiêm tinh giờ hỏi Yeongnyangi",
    "Khám phá câu hỏi qua bầu trời vào lúc câu hỏi xuất hiện.",
    "Cách đọc biểu tượng truyền thống về hoàn cảnh của câu hỏi và những lựa chọn dành cho bạn.",
    "Một câu hỏi cho Yeongnyangi",
    "Viết điều bạn muốn hiểu nhất.",
    "Chủ đề",
    "Câu hỏi bạn viết được ưu tiên hơn chủ đề đã chọn.",
    "Mối quan hệ của bạn",
    "Thành phố nơi câu hỏi xuất hiện",
    "Chọn thành phố",
    "Vị trí đã xác nhận · múi giờ:",
    "Dùng trung tâm thành phố hoặc vị trí bạn xác nhận khi đặt câu hỏi, không dùng vị trí của người khác.",
    "Ngày và giờ của câu hỏi",
    "Nhập thời gian bạn nhớ. Máy chủ xác nhận múi giờ. Nếu không chắc, dùng lúc bạn làm rõ câu hỏi một lần nữa. Không cần thông tin sinh.",
    "Tình hình bạn đã biết",
    "Mô tả tình hình, không nhập tên, địa chỉ hay thông tin liên hệ.",
    "Người ấy đã từ chối liên lạc hoặc chặn tôi",
    "Tham vấn · kết quả đầu tiên và một câu hỏi đào sâu",
    "Thẻ Family hoặc thanh toán một lần",
    "Tính toán chiêm tinh giờ hỏi phương Tây và lời nhắc cho AI bên ngoài",
    "Miễn phí · cung cấp lời nhắc",
    "Tạo lời nhắc chiêm tinh giờ hỏi miễn phí",
    "Đang chuẩn bị bài đọc",
    "Hiện chưa khả dụng. Không tiến hành thanh toán.",
    "Kiểm tra câu hỏi, mối quan hệ và hồ sơ cần thiết, hoặc nơi và giờ đặt câu hỏi.",
    "Chưa thể chuẩn bị. Vui lòng thử lại.",
    "Yeongnyangi mặc trang phục truyền thống Hàn Quốc",
    "Điều hướng bài đọc",
    "Chọn bài đọc khác",
    "Mốc tham chiếu",
    "Nơi đặt câu hỏi",
    "Đọc biểu tượng theo địa điểm đã chọn",
    "Câu trả lời chính",
    "Bài đọc đã được lưu.",
    "Câu trả lời đầu tiên đã sẵn sàng. Bạn có thể hỏi thêm một câu.",
    "Tìm hiểu sâu một điểm",
    "Chọn một điểm trong câu trả lời đầu tiên để tìm hiểu thêm.",
    "Gửi câu hỏi đào sâu",
    "Bạn đã dùng câu hỏi đào sâu đi kèm.",
    "Lời kết của Yeongnyangi",
    "Chia sẻ giới thiệu ẩn danh",
    "Đã sao chép",
    "Chia sẻ chưa hoàn tất. Vui lòng thử lại.",
    "Sau kết quả đầu tiên, viết một câu hỏi đào sâu dài 5–600 ký tự.",
    "Cần ngày sinh của bạn. Có thể để giờ sinh chưa rõ; bài đọc sẽ giữ giới hạn tương ứng.",
    "Xem giờ sinh là chưa rõ trong lần này",
    "Máy chủ lưu thời gian gửi và múi giờ. Không thu thập vị trí của bạn hay người khác.",
    "Cùng phân biệt điều đã biết và điều còn chưa chắc chắn.",
    "Bài đọc xem xét khuynh hướng từ ngày sinh của chính bạn và lựa chọn trong quan hệ. Không xác định suy nghĩ, nơi ở hay thời điểm liên lạc hoặc tái hợp của người khác.",
    "Chọn mối quan hệ",
    "Đăng nhập để bắt đầu",
    "đã lưu",
    "Đã tính xong chiêm tinh giờ hỏi",
    "Bạn có ở đây khi câu hỏi xuất hiện không?",
    "Đúng, dùng nơi này",
    "Đã hoàn tất thao tác chia sẻ.",
    "Đã hủy chia sẻ."
  ],
  "hi": [
    "Yeongnyangi प्रतीकात्मक परामर्श",
    "Yeongnyangi प्रश्न ज्योतिष",
    "प्रश्न उठने के क्षण के आकाश से अपने विकल्पों पर विचार करें।",
    "यह पारंपरिक प्रतीकात्मक व्याख्या आपके प्रश्न की परिस्थितियों और उपलब्ध विकल्पों पर केंद्रित है।",
    "Yeongnyangi से एक प्रश्न",
    "वह एक बात लिखें जिसे आप सबसे अधिक समझना चाहते हैं।",
    "विषय",
    "चुने हुए विषय से अधिक आपके लिखे प्रश्न को प्राथमिकता मिलती है।",
    "आपका संबंध",
    "प्रश्न उठते समय आप किस शहर में थे",
    "शहर चुनें",
    "पुष्ट स्थान · समय क्षेत्र:",
    "शहर का केंद्र या प्रश्न के समय आपका पुष्ट स्थान लिया जाता है, किसी दूसरे व्यक्ति का स्थान नहीं।",
    "प्रश्न की तारीख और समय",
    "याद किया हुआ समय लिखें। सर्वर शहर का समय क्षेत्र जाँचता है। समय स्पष्ट न हो तो प्रश्न दोबारा साफ़ करने के क्षण का उपयोग करें। जन्म विवरण आवश्यक नहीं है।",
    "आपको पहले से क्या पता है",
    "नाम, पते और संपर्क जानकारी के बिना स्थिति लिखें।",
    "दूसरे व्यक्ति ने संपर्क से मना किया है या मुझे ब्लॉक किया है",
    "प्रतीकात्मक परामर्श · पहला परिणाम और एक अनुवर्ती प्रश्न",
    "Family पास या एक बार का भुगतान",
    "पारंपरिक पश्चिमी प्रश्न ज्योतिष की गणना और बाहरी AI के लिए प्रॉम्प्ट",
    "निःशुल्क · प्रॉम्प्ट उपलब्ध",
    "निःशुल्क प्रश्न ज्योतिष प्रॉम्प्ट बनाएँ",
    "परामर्श तैयार हो रहा है",
    "अभी उपलब्ध नहीं है। भुगतान नहीं किया जाएगा।",
    "प्रश्न, संबंध और आवश्यक प्रोफ़ाइल या प्रश्न के स्थान और समय की जाँच करें।",
    "तैयारी पूरी नहीं हुई। कृपया फिर प्रयास करें।",
    "पारंपरिक कोरियाई पोशाक में Yeongnyangi",
    "परामर्श नेविगेशन",
    "अन्य परामर्श चुनें",
    "व्याख्या का संदर्भ",
    "प्रश्न का स्थान",
    "चुने हुए स्थान पर आधारित प्रतीकात्मक व्याख्या",
    "मुख्य उत्तर",
    "आपका परामर्श सहेजा गया है।",
    "पहला उत्तर तैयार है। नीचे एक अनुवर्ती प्रश्न पूछ सकते हैं।",
    "एक बिंदु को और समझें",
    "पहले उत्तर से एक बिंदु चुनकर उसके बारे में विस्तार से पूछें।",
    "अनुवर्ती प्रश्न भेजें",
    "शामिल अनुवर्ती प्रश्न का उपयोग हो चुका है।",
    "Yeongnyangi का अंतिम संदेश",
    "अनाम परिचय साझा करें",
    "कॉपी हो गया",
    "साझा नहीं हो सका। कृपया फिर प्रयास करें।",
    "पहला परिणाम आने के बाद 5–600 अक्षरों का एक अनुवर्ती प्रश्न लिखें।",
    "आपकी जन्मतिथि चाहिए। जन्म समय अज्ञात रह सकता है; व्याख्या उसी सीमा में होगी।",
    "इस परामर्श में जन्म समय अज्ञात मानें",
    "सर्वर भेजने का समय और समय क्षेत्र सहेजता है। आपका या किसी दूसरे व्यक्ति का स्थान एकत्र नहीं किया जाता।",
    "जो पता है और जो अनिश्चित है, उन्हें अलग करके देखें।",
    "यह आपके जन्म पर आधारित रुझानों और संबंधों में आपके विकल्पों पर विचार करता है। दूसरे व्यक्ति के विचार, स्थान या संपर्क और मेल-मिलाप का समय तय नहीं करता।",
    "संबंध चुनें",
    "लॉग इन करके शुरू करें",
    "सहेजा गया",
    "आपकी प्रश्न ज्योतिष गणना तैयार है",
    "क्या प्रश्न उठते समय आप यहीं थे?",
    "हाँ, इसी स्थान का उपयोग करें",
    "साझा करने की प्रक्रिया पूरी हुई।",
    "साझा करना रद्द हुआ।"
  ],
  "ms": [
    "Bacaan simbolik Yeongnyangi",
    "Astrologi horari Yeongnyangi",
    "Terokai soalan melalui langit ketika soalan itu timbul.",
    "Bacaan simbolik tradisional tentang keadaan soalan dan pilihan yang ada untuk anda.",
    "Satu soalan untuk Yeongnyangi",
    "Tulis perkara yang paling ingin difahami.",
    "Topik",
    "Soalan yang anda tulis diutamakan berbanding topik pilihan.",
    "Hubungan anda",
    "Bandar ketika soalan timbul",
    "Pilih bandar",
    "Lokasi disahkan · zon waktu:",
    "Gunakan pusat bandar atau lokasi anda yang disahkan ketika soalan timbul, bukan lokasi orang lain.",
    "Tarikh dan masa soalan",
    "Masukkan masa yang diingati. Pelayan mengesahkan zon waktu. Jika tidak pasti, gunakan saat anda menjelaskan semula soalan. Maklumat kelahiran tidak diperlukan.",
    "Keadaan yang sudah diketahui",
    "Terangkan keadaan tanpa nama, alamat atau butiran hubungan.",
    "Orang tersebut menolak hubungan atau menyekat saya",
    "Bacaan simbolik · hasil awal dan satu soalan susulan",
    "Pas Family atau bayaran sekali",
    "Pengiraan horari Barat tradisional dan arahan untuk AI luar",
    "Percuma · arahan disediakan",
    "Bina arahan horari percuma",
    "Sedang menyediakan bacaan",
    "Belum tersedia. Tiada bayaran akan dijalankan.",
    "Semak soalan, hubungan dan profil yang diperlukan, atau tempat dan masa soalan.",
    "Persediaan tidak berjaya. Sila cuba lagi.",
    "Yeongnyangi dalam pakaian tradisional Korea",
    "Navigasi bacaan",
    "Pilih bacaan lain",
    "Rujukan bacaan",
    "Tempat soalan",
    "Bacaan simbolik berdasarkan tempat pilihan",
    "Jawapan utama",
    "Bacaan anda telah disimpan.",
    "Jawapan pertama siap. Anda boleh bertanya satu soalan susulan.",
    "Dalami satu perkara",
    "Pilih satu perkara daripada jawapan pertama untuk diperincikan.",
    "Hantar soalan susulan",
    "Soalan susulan yang disertakan telah digunakan.",
    "Pesanan akhir Yeongnyangi",
    "Kongsi pengenalan tanpa nama",
    "Disalin",
    "Perkongsian tidak selesai. Sila cuba lagi.",
    "Selepas hasil pertama siap, masukkan satu soalan susulan sepanjang 5–600 aksara.",
    "Tarikh lahir diperlukan. Masa lahir boleh dibiarkan tidak diketahui; tafsiran akan mengikut batas itu.",
    "Anggap masa lahir tidak diketahui untuk bacaan ini",
    "Pelayan menyimpan masa penghantaran dan zon waktu. Lokasi anda atau orang lain tidak dikumpulkan.",
    "Mari bezakan perkara yang diketahui daripada yang belum pasti.",
    "Bacaan ini meneliti kecenderungan kelahiran anda sendiri dan pilihan dalam hubungan. Ia tidak menentukan fikiran, lokasi atau masa hubungan kembali bagi orang lain.",
    "Pilih hubungan",
    "Log masuk untuk bermula",
    "disimpan",
    "Pengiraan horari anda siap",
    "Adakah anda di sini ketika soalan timbul?",
    "Ya, gunakan tempat ini",
    "Tindakan perkongsian selesai.",
    "Perkongsian dibatalkan."
  ]
};

export const nativeSymbolicCopy=(locale:Exclude<ReadingLocale,'ko'>)=>Object.fromEntries(symbolicCopyKeys.map((key,i)=>[key,symbolicCopyRows[locale][i]])) as Record<SymbolicCopyKey,string>;
