// Generated by node scripts/generate-mobile-nav-copy.mjs; source: public/i18n.
export const MOBILE_NAV_SSR_COPY: Record<string, Record<string, string>> = {
  "ja": {
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "下部メニューの折りたたみ/展開",
    "home.nav.home": "ホーム",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "占い一覧",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "すべての占いを見る",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "相談",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "運命相談を選ぶ",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "保管箱",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "マイ保管箱",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "マイ",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "マイページ"
  },
  "en": {
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "Collapse/expand bottom menu",
    "home.nav.home": "Home",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "Readings",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "Browse all readings",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "Chat",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "Choose a fortune consultation",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "Library",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "My library",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "My",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "My page"
  },
  "zh": {
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "折叠/展开底部菜单",
    "home.nav.home": "首页",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "全部运势",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "浏览全部运势",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "咨询",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "选择命运咨询",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "收藏夹",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "我的收藏夹",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "我的",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "我的页面"
  },
  "zh-TW": {
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "摺疊/展開底部選單",
    "home.nav.home": "首頁",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "全部運勢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "瀏覽全部運勢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "諮詢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "選擇命運諮詢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "收藏夾",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "我的收藏夾",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "我的",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "我的頁面"
  }
};
