// Generated by node scripts/generate-mobile-nav-copy.mjs; source: public/i18n.
export const MOBILE_NAV_SSR_COPY: Record<string, Record<string, string>> = {
  "ja": {
    "home.nav.home": "ホーム",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "占い一覧",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "すべての占いを見る",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "相談",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "ヨニ・ネオに相談",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "保管箱",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "マイ保管箱",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "マイ",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "マイページ",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "下部メニューの折りたたみ/展開"
  },
  "en": {
    "home.nav.home": "Home",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "Readings",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "Browse all readings",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "Chat",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "Chat with Yeoni & Neo",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "Library",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "My library",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "My",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "My page",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "Collapse/expand bottom menu"
  },
  "zh": {
    "home.nav.home": "首页",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "全部运势",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "浏览全部运势",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "咨询",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "与 Yeoni·Neo 咨询",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "收藏夹",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "我的收藏夹",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "我的",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "我的页面",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "折叠/展开底部菜单"
  },
  "zh-TW": {
    "home.nav.home": "首頁",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "全部運勢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "瀏覽全部運勢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consult": "諮詢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.consultTab.ariaLabel": "與 Yeoni·Neo 諮詢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.library": "收藏夾",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.libraryTab.ariaLabel": "我的收藏夾",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "我的",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "我的頁面",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "摺疊/展開底部選單"
  }
};
