// Generated by node scripts/generate-mobile-nav-copy.mjs; source: public/i18n.
export const MOBILE_NAV_SSR_COPY: Record<string, Record<string, string>> = {
  "ja": {
    "home.nav.home": "ホーム",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kxvio": "四柱推命",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kb86wy0.ariaLabel": "自分のプロフィールで四柱推命を見る",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "占い一覧",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "すべての占いを見る",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.ku6gdz": "パス",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16eawmw.ariaLabel": "パスストア",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "マイ",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "マイページ",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "下部メニューの折りたたみ/展開"
  },
  "en": {
    "home.nav.home": "Home",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kxvio": "Four Pillars",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kb86wy0.ariaLabel": "Read my Four Pillars with my profile",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "Readings",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "Browse all readings",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.ku6gdz": "Pass",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16eawmw.ariaLabel": "Pass store",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "My",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "My page",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "Collapse/expand bottom menu"
  },
  "zh": {
    "home.nav.home": "首页",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kxvio": "四柱八字",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kb86wy0.ariaLabel": "以我的资料查看四柱八字",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "全部运势",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "浏览全部运势",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.ku6gdz": "通行证",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16eawmw.ariaLabel": "通行证商店",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "我的",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "我的页面",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "折叠/展开底部菜单"
  },
  "zh-TW": {
    "home.nav.home": "首頁",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kxvio": "四柱八字",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kb86wy0.ariaLabel": "以我的資料查看四柱八字",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16cq4to": "全部運勢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k1mpcz5w.ariaLabel": "瀏覽全部運勢",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.ku6gdz": "通行證",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k16eawmw.ariaLabel": "通行證商店",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.kwp0s": "我的",
    "shell.cdMobileBottomNav.cdMobileBottomNavMain.k164wabc.ariaLabel": "我的頁面",
    "shell.cdMobileBottomNav.k13uxius.ariaLabel": "摺疊/展開底部選單"
  }
};
