// Generated by scripts/extract-saju-runtime.mjs; original formulas unchanged.
import { calcPower, GAN, JI, detectJong, whoControls } from '../../../lib/saju/natal-power.js';
function _applyTrueSolarTimeCorrection(input) {
  var year = Number(input && input.year);
  var month = Number(input && input.month);
  var day = Number(input && input.day);
  var hour = Number(input && input.hour);
  var minute = Number(input && input.minute);
  var longitude = Number(input && input.longitude);
  var standardMeridian = Number(input && input.standardMeridian);

  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;
  if (!Number.isFinite(hour) || !Number.isFinite(minute)) return null;
  if (!Number.isFinite(longitude) || !Number.isFinite(standardMeridian)) return null;

  var clockTotalMinutes = hour * 60 + minute;
  var longitudeCorrectionMinutes = (longitude - standardMeridian) * 4;
  var correctedTotal = clockTotalMinutes + longitudeCorrectionMinutes;
  var roundedTotal = Math.round(correctedTotal);
  var dayOffset = Math.floor(roundedTotal / 1440);
  var minuteOfDay = ((roundedTotal % 1440) + 1440) % 1440;
  var correctedHour = Math.floor(minuteOfDay / 60);
  var correctedMinute = minuteOfDay % 60;
  var shiftedDate = _shiftDatePartsByDays(year, month, day, dayOffset);

  return {
    correctedYear: shiftedDate.year,
    correctedMonth: shiftedDate.month,
    correctedDay: shiftedDate.day,
    correctedHour: correctedHour,
    correctedMinute: correctedMinute,
    dayOffset: dayOffset,
    longitudeCorrectionMinutes: longitudeCorrectionMinutes,
    totalCorrectionMinutes: longitudeCorrectionMinutes
  };
}

function _shiftDatePartsByDays(year, month, day, dayOffset) {
  var baseUtc = Date.UTC(year, month - 1, day, 0, 0, 0);
  var shifted = new Date(baseUtc + (dayOffset * 86400000));
  return {
    year: shifted.getUTCFullYear(),
    month: shifted.getUTCMonth() + 1,
    day: shifted.getUTCDate()
  };
}

function _cdCivilDayPillar(year, month, day, hour) {
  var y = Number(year), m = Number(month), d = Number(day);
  if (!Number.isFinite(y) || !Number.isFinite(m) || !Number.isFinite(d)) return null;
  // 야자시(夜子時): 23시대 출생은 익일 일진 (기존 KasiEngine.getGanji 규칙과 동일하게 원본 시각에 적용)
  if (Number(hour) >= 23) {
    var shifted = new Date(Date.UTC(y, m - 1, d) + 86400000);
    y = shifted.getUTCFullYear(); m = shifted.getUTCMonth() + 1; d = shifted.getUTCDate();
  }
  var serial = Math.floor(Date.UTC(y, m - 1, d) / 86400000) + 17;
  return {
    g: _CD_STEMS_HANJA[((serial % 10) + 10) % 10],
    j: _CD_BRANCHES_HANJA[((serial % 12) + 12) % 12]
  };
}

var _CD_STEMS_HANJA = ['甲','乙','丙','丁','戊','己','庚','辛','壬','癸'];

var _CD_BRANCHES_HANJA = ['子','丑','寅','卯','辰','巳','午','未','申','酉','戌','亥'];

function _cdHourPillarFromDayStem(dayStemHanja, correctedHour) {
  var h = Number(correctedHour);
  if (!Number.isFinite(h)) h = 0;
  // 시지(時支): 진태양시 보정 시각의 2시간지. 자시는 23:00~00:59로 자정을 감싸므로 날짜와 무관하게 산출.
  var branchIndex = Math.floor((h + 1) / 2) % 12;
  var dayStemIndex = _CD_STEMS_HANJA.indexOf(dayStemHanja);
  if (dayStemIndex < 0) return null;
  // 시간(時干): 오자둔(五鼠遁) — 민용일 일간으로 자시 천간을 정하고 시지만큼 진행
  var ziStemStart = [0, 2, 4, 6, 8][dayStemIndex % 5];
  return {
    g: _CD_STEMS_HANJA[(ziStemStart + branchIndex) % 10],
    j: _CD_BRANCHES_HANJA[branchIndex]
  };
}

function calcNatalElement(p){
  var cnt={wood:0,fire:0,earth:0,metal:0,water:0};
  [p.y.g,p.y.j,p.m.g,p.m.j,p.d.g,p.d.j,p.h.g,p.h.j].forEach(function(e){
    var inf=GAN[e]||JI[e];if(inf&&inf.e)cnt[inf.e]++;
  });
  if(p.m.j&&JI[p.m.j])cnt[JI[p.m.j].e]++;
  var total=Object.values(cnt).reduce(function(a,b){return a+b;},0)||1;
  var ratios={};for(var k in cnt)ratios[k]=cnt[k]/total*100;
  var dominant='wood',max=0;
  for(var k2 in cnt){if(cnt[k2]>max){max=cnt[k2];dominant=k2;}}
  return{dominant:dominant,ratios:ratios,counts:cnt};
}

function analyzeJohu(p){
  var yg=p.y.g,yz=p.y.j,mg=p.m.g,mz=p.m.j,dg=p.d.g,dz=p.d.j,hg=p.h.g,hz=p.h.j;
  var score=0;
  var seasonMap={'寅':'봄','卯':'봄','辰':'봄','巳':'여름','午':'여름','未':'여름','申':'가을','酉':'가을','戌':'가을','亥':'겨울','子':'겨울','丑':'겨울'};
  var season=seasonMap[mz]||'봄';
  if(season==='여름')score+=4;else if(season==='봄')score+=2;else if(season==='가을')score-=2;else score-=4;
  var fc=0,wc=0,wdc=0,mc=0;
  var moistCnt=0,dryCnt=0;
  [yg,yz,mg,mz,dg,dz,hg,hz].forEach(function(c){
    var g=GAN[c],j=JI[c];
    var e=(g||j||{}).e;
    if(e==='fire'){score+=1.5;fc++;dryCnt++;}else if(e==='water'){score-=1.5;wc++;moistCnt++;}
    else if(e==='wood'){score+=0.5;wdc++;moistCnt++;}
    else if(e==='metal'){score-=0.5;mc++;dryCnt++;}
    if(j){
      if(c==='辰'||c==='丑')moistCnt++;
      if(c==='戌'||c==='未')dryCnt++;
    }
  });
  var type,advice,badgeCls,badgeTxt;
  if(score>=5){type='hot';advice='사주가 매우 뜨겁습니다. 水·金 기운이 절실히 필요합니다.';badgeCls='jb-hot';badgeTxt='🔥 뜨거운 사주';}
  else if(score>=2){type='warm';advice='사주가 따뜻한 편입니다. 水 기운으로 조절하면 좋습니다.';badgeCls='jb-warm';badgeTxt='🌞 따뜻한 사주';}
  else if(score>=-2){type='neutral';advice='사주의 온도가 시원하게 균형잡혀 있습니다. 계절 변화에 맞춰 음양을 조절하세요.';badgeCls='jb-neutral';badgeTxt='🌤️ 시원한 사주';}
  else if(score>=-5){type='cool';advice='사주가 서늘한 편입니다. 火·木 기운으로 온기를 보충하면 좋습니다.';badgeCls='jb-cool';badgeTxt='🍃 서늘한 사주';}
  else{type='cold';advice='사주가 매우 차갑습니다. 火·木 기운이 절실히 필요합니다.';badgeCls='jb-cold';badgeTxt='❄️ 차가운 사주';}
  var moistType,moistAdvice;
  var diff=moistCnt-dryCnt;
  if(diff>=3){moistType='wet';moistAdvice='사주에 습기가 많은 편입니다. 건조한 환경, 금(金)·불(火) 기운을 적절히 써주면 균형이 좋아집니다.';}
  else if(diff<=-3){moistType='dry';moistAdvice='사주가 건조한 편입니다. 물(水)·나무(木) 기운과 실제 수분(물·목욕·자연)을 통해 촉촉함을 채워주는 것이 좋습니다.';}
  else{moistType='balanced';moistAdvice='습조(濕燥)는 비교적 균형잡힌 편입니다. 한난만 잘 맞춰주면 좋습니다.';}
  var improve=(type==='hot'||type==='warm')
    ?'시원하고 차가운 기운 필요. 북쪽 방향, 파란색·검은색 컬러, 수영·물가 활동.'
    :(type==='cold'||type==='cool')
    ?'따뜻하고 밝은 기운 필요. 남쪽 방향, 빨간색·주황색 컬러, 캠핑·BBQ 활동.'
    :'균형잡힌 사주입니다. 다양한 오행을 골고루 활용하세요.';
  return{
    score:score,
    type:type,
    advice:advice,
    badgeCls:badgeCls,
    badgeTxt:badgeTxt,
    improve:improve,
    season:season,
    fc:fc,wc:wc,wdc:wdc,mc:mc,
    moistType:moistType,
    moistAdvice:moistAdvice,
    moistCnt:moistCnt,
    dryCnt:dryCnt
  };
}

function applyRuntimeYongshinPolicy(power, jong, johu) {
  if (!power) return power;
  var eokbuYongshin = _dfArrayCopy(power.yongshin);
  var eokbuKijishin = _dfArrayCopy(power.kijishin);
  var johuSet = _dfJohuUsefulSet(johu);
  var finalYongshin = eokbuYongshin;
  var finalKijishin = eokbuKijishin;
  if (jong && jong.isJong) {
    finalYongshin = _dfUniqueElements([jong.dominant, jong.parEl].concat(johuSet.useful));
    finalKijishin = _dfUniqueElements([whoControls(jong.dominant)].concat(johuSet.caution))
      .filter(function(el) { return finalYongshin.indexOf(el) < 0; });
  } else if (johuSet.useful.length || johuSet.caution.length) {
    // 억부가 이미 명확히 판단한 오행은 조후로 뒤집지 않는다 (억부 우선)
    var johuUseful = johuSet.useful.filter(function(el) { return eokbuKijishin.indexOf(el) < 0; });
    var johuCaution = johuSet.caution.filter(function(el) { return eokbuYongshin.indexOf(el) < 0; });
    finalYongshin = _dfUniqueElements(johuUseful.concat(eokbuYongshin));
    finalKijishin = _dfUniqueElements(johuCaution.concat(eokbuKijishin));
  }
  power.eokbuYongshin = eokbuYongshin;
  power.eokbuKijishin = eokbuKijishin;
  power.johuYongshin = johuSet.useful;
  power.johuKijishin = johuSet.caution;
  power.yongshin = finalYongshin;
  power.kijishin = finalKijishin;
  power.yongshinPolicy = CD_SAJU_DAEWUN_YONGSHIN_FIX;
  return power;
}

function _dfArrayCopy(v) {
  return Array.isArray(v) ? v.slice() : [];
}

function _dfJohuUsefulSet(johu) {
  var useful = [];
  var caution = [];
  var type = johu && johu.type;
  var moistType = johu && johu.moistType;
  if (type === 'hot' || type === 'warm') {
    useful.push('water', 'metal');
    caution.push('fire', 'wood');
  } else if (type === 'cold' || type === 'cool') {
    useful.push('fire', 'wood');
    caution.push('water', 'metal');
  }
  if (moistType === 'dry') {
    useful.push('water', 'wood');
    caution.push('fire');
  } else if (moistType === 'wet') {
    useful.push('fire', 'earth');
    caution.push('water');
  }
  return {
    useful: _dfUniqueElements(useful),
    caution: _dfUniqueElements(caution)
  };
}

function _dfUniqueElements(list) {
  var out = [];
  (Array.isArray(list) ? list : []).forEach(function(el) {
    if (el && out.indexOf(el) < 0) out.push(el);
  });
  return out;
}

var CD_SAJU_DAEWUN_YONGSHIN_FIX = 'daewun-yongshin-policy-v20260810';

function resolveBirthTimezoneOffset(year, month, day, hour, minute, tz, baseOffsetHours) {
  var base = (typeof baseOffsetHours === 'number' && !isNaN(baseOffsetHours)) ? baseOffsetHours : 9;
  var effective = getTimeZoneOffsetHoursAtDate(year, month, day, hour, minute, tz, base);
  var dstMinutes = Math.round((effective - base) * 60);
  return {
    tzOffsetHours: effective,
    baseOffsetHours: base,
    dstMinutes: dstMinutes,
    isDstApplied: dstMinutes !== 0
  };
}

function getTimeZoneOffsetHoursAtDate(year, month, day, hour, minute, tz, fallbackOffsetHours) {
  var fallback = (typeof fallbackOffsetHours === 'number' && !isNaN(fallbackOffsetHours)) ? fallbackOffsetHours : 9;
  if (!tz || typeof Intl === 'undefined' || typeof Intl.DateTimeFormat !== 'function') return fallback;
  try {
    var probeUtc = new Date(Date.UTC(year, (month || 1) - 1, day || 1, hour || 12, minute || 0, 0));
    var fmt = new Intl.DateTimeFormat('en-US', {
      timeZone: tz,
      hour12: false,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'shortOffset'
    });
    var parts = fmt.formatToParts(probeUtc);
    var tzName = '';
    for (var i = 0; i < parts.length; i++) {
      if (parts[i].type === 'timeZoneName') {
        tzName = parts[i].value || '';
        break;
      }
    }
    var parsed = parseTimeZoneOffsetName(tzName);
    return parsed == null ? fallback : parsed;
  } catch (e) {
    return fallback;
  }
}

function parseTimeZoneOffsetName(name) {
  if (!name) return null;
  var m = String(name).match(/(?:GMT|UTC)([+-])(\d{1,2})(?::?(\d{2}))?/i);
  if (!m) return null;
  var sign = m[1] === '-' ? -1 : 1;
  var hh = parseInt(m[2], 10) || 0;
  var mm = parseInt(m[3] || '0', 10) || 0;
  return sign * (hh + mm / 60);
}
export { _applyTrueSolarTimeCorrection, _cdCivilDayPillar, _cdHourPillarFromDayStem, calcPower, calcNatalElement, analyzeJohu, detectJong, applyRuntimeYongshinPolicy, resolveBirthTimezoneOffset };
