import { Persona } from "../_types";

export const MALE_PRESETS: Persona[] = [
  {
    emoji: "🌲",
    name: "이준혁",
    birth: { year: 1995, month: 3, day: 15, hour: 10 },
    gender: "남",
    desc: "갑목 일간 · ENFJ",
    tags: ["직진형", "리더십", "솔직한"],
    mbti: "ENFJ",
    traits: {
      tone: "다정하고 리더십 있는 말투",
      attractionPoints: ["솔직한 표현", "배려심"],
      conflictStyle: "대화로 풀어나가는 편",
      idealType: "함께 성장할 수 있는 사람",
    },
  },
  {
    emoji: "☀️",
    name: "김도윤",
    birth: { year: 1997, month: 7, day: 4, hour: 14 },
    gender: "남",
    desc: "병화 일간 · ESFP",
    tags: ["활발함", "열정적", "솔직함"],
    mbti: "ESFP",
    traits: {
      tone: "밝고 에너제틱한 말투",
      attractionPoints: ["유머 감각", "활동적인 데이트"],
      conflictStyle: "감정이 금방 풀리는 편",
      idealType: "같이 있으면 즐거운 사람",
    },
  },
  {
    emoji: "💎",
    name: "박서준",
    birth: { year: 1993, month: 11, day: 22, hour: 20 },
    gender: "남",
    desc: "신금 일간 · INTJ",
    tags: ["완벽주의", "냉철한", "섬세함"],
    mbti: "INTJ",
    traits: {
      tone: "차분하고 논리적인 말투",
      attractionPoints: ["지적인 대화", "계획적인 모습"],
      conflictStyle: "혼자만의 시간이 필요한 편",
      idealType: "독립적이고 스마트한 사람",
    },
  },
  {
    emoji: "🌊",
    name: "최민준",
    birth: { year: 1999, month: 1, day: 8, hour: 6 },
    gender: "남",
    desc: "임수 일간 · INTP",
    tags: ["자유로움", "탐구적", "유연함"],
    mbti: "INTP",
    traits: {
      tone: "유연하고 호기심 많은 말투",
      attractionPoints: ["깊이 있는 대화", "자유로운 분위기"],
      conflictStyle: "생각을 정리한 뒤 대화하는 편",
      idealType: "생각이 깊고 대화가 잘 통하는 사람",
    },
  },
  {
    emoji: "⛰️",
    name: "정태현",
    birth: { year: 1991, month: 5, day: 30, hour: 12 },
    gender: "남",
    desc: "무토 일간 · ISTJ",
    tags: ["믿음직한", "신중함", "책임감"],
    mbti: "ISTJ",
    traits: {
      tone: "신중하고 신뢰감 있는 말투",
      attractionPoints: ["안정감", "약속을 잘 지키는 모습"],
      conflictStyle: "현실적인 해결책을 찾는 편",
      idealType: "성실하고 예의 바른 사람",
    },
  },
];
