import type { LoadingLocale } from '@/constants/loadingMessages';

export const COMPANION_COPY = {
  ko: { savedDone: '문구를 저장했어요.', unavailable: '오늘의 결과를 아직 받지 못했어요. 연결을 확인하고 다시 시도해 주세요.', retry: '다시 확인하기', title: '영냥이의 오늘 한마디', quote: '명언', affirmation: '긍정 확언', daily: '일일 운세', close: '앱으로 돌아가기', previous: '이전', next: '다음', settings: '잠금화면 설정', quiet: '조용한 시간', start: '시작', end: '종료', privacy: '개인 운세는 잠금 해제 후 앱에서 확인해요. 생년월일·상담·결제 정보는 알림에 표시하지 않아요.', test: '테스트 알림', posted: '알림을 게시했어요. 잠금화면 표시는 시스템 설정을 따라요.', blocked: '알림을 게시하지 못했어요. 기능과 시스템 알림 설정을 확인해 주세요.', system: '시스템 알림 설정', enabled: '선호 시간에 알림을 받아요. 절전 상태에서는 늦게 도착할 수 있어요.', textSize: '글자 크기는 앱 안의 카드에 적용돼요. 알림은 시스템 글자 크기를 따라요.', privateSummary: '오늘의 운세는 잠금 해제 후 앱에서 확인해 주세요.', source: '기존 오프라인 참고 해석 · 기준일 KST', web: '웹과 같은 오늘의 운세 보기', noContent: '설정에서 보고 싶은 콘텐츠를 선택해 주세요.', ownLine: '오늘 할 수 있는 한 가지부터 시작해도 충분해.', ownAuthor: '영냥이의 한마디', ownAffirmation: '나는 내 속도로 한 걸음씩 나아가도 괜찮아.', kind: '표시할 콘텐츠', saved: '문구 저장', shared: '공유', themeCharacter: '캐릭터', yeongnyangi: '영냥이' },
  en: { savedDone: 'Text saved.', unavailable: 'Today’s result is not available yet. Check your connection and try again.', retry: 'Try again', title: 'A daily word from Yeongnyangi', quote: 'Quote', affirmation: 'Affirmation', daily: 'Daily fortune', close: 'Back to app', previous: 'Previous', next: 'Next', settings: 'Lock screen settings', quiet: 'Quiet hours', start: 'From', end: 'Until', privacy: 'Open the app after unlocking to read your fortune. Birth details, consultations and payments are never shown in notifications.', test: 'Test notification', posted: 'Notification posted. Visibility depends on system settings.', blocked: 'Could not post. Check the feature switch and system notification settings.', system: 'System notification settings', enabled: 'Receive reminders near your preferred times. Battery saving may delay them.', textSize: 'Text size applies to cards inside the app. Notifications use system text size.', privateSummary: 'Unlock and open the app to view your daily fortune.', source: 'Existing offline reference reading · KST date', web: 'Open the shared daily fortune', noContent: 'Choose content in settings.', ownLine: 'Starting with one small thing today is enough.', ownAuthor: 'A word from Yeongnyangi', ownAffirmation: 'I can move forward one step at my own pace.', kind: 'Content to show', saved: 'Save text', shared: 'Share', themeCharacter: 'Character', yeongnyangi: 'Yeongnyangi' },
  ja: { savedDone: '文章を保存しました。', unavailable: '今日の結果をまだ取得できていません。接続を確認して再試行してください。', retry: '再試行', title: 'ヨンニャンイの今日のひとこと', quote: '名言', affirmation: 'アファメーション', daily: '今日の運勢', close: 'アプリに戻る', previous: '前へ', next: '次へ', settings: 'ロック画面の設定', quiet: '通知を控える時間', start: '開始', end: '終了', privacy: '個人の運勢はロック解除後にアプリで確認できます。生年月日・相談・決済情報は通知に表示しません。', test: 'テスト通知', posted: '通知を投稿しました。表示はシステム設定に従います。', blocked: '通知できませんでした。機能とシステム通知の設定をご確認ください。', system: 'システムの通知設定', enabled: '希望時刻の前後に通知します。省電力状態では遅れることがあります。', textSize: '文字サイズはアプリ内カードに適用されます。通知はシステムの文字サイズを使います。', privateSummary: 'ロックを解除してアプリで今日の運勢をご確認ください。', source: '既存のオフライン参考解釈 · 韓国標準時', web: '共通の今日の運勢を見る', noContent: '設定で表示する内容を選んでください。', ownLine: '今日できる小さなことから始めれば十分。', ownAuthor: 'ヨンニャンイのひとこと', ownAffirmation: '自分のペースで、一歩ずつ進んでいい。', kind: '表示する内容', saved: '文章を保存', shared: '共有', themeCharacter: 'キャラクター', yeongnyangi: 'ヨンニャンイ' },
  'zh-CN': { savedDone: '文字已保存。', unavailable: '尚未获取今日结果，请检查网络后重试。', retry: '重试', title: '灵喵今日一语', quote: '名言', affirmation: '积极肯定', daily: '今日运势', close: '返回应用', previous: '上一条', next: '下一条', settings: '锁屏设置', quiet: '免打扰时段', start: '开始', end: '结束', privacy: '请解锁后在应用中查看个人运势。通知不会显示出生日期、咨询或付款信息。', test: '测试通知', posted: '通知已发布，是否显示取决于系统设置。', blocked: '未能发布通知，请检查功能开关和系统通知设置。', system: '系统通知设置', enabled: '在偏好时间附近接收提醒，省电模式可能延迟通知。', textSize: '字号设置适用于应用内卡片，通知使用系统字号。', privateSummary: '请解锁后在应用中查看今日运势。', source: '现有离线参考解读 · 韩国标准时间', web: '查看共同的今日运势', noContent: '请在设置中选择内容。', ownLine: '从今天能做的一件小事开始，就已经足够。', ownAuthor: '灵喵一语', ownAffirmation: '我可以按自己的步调，一步一步向前。', kind: '显示内容', saved: '保存文字', shared: '分享', themeCharacter: '角色', yeongnyangi: '灵喵' },
} as const;
export function companionCopy(locale: string) {
  return COMPANION_COPY[locale as keyof typeof COMPANION_COPY] || EXTRA_COPY[locale as keyof typeof EXTRA_COPY] || COMPANION_COPY.en;
}

type CompanionText = { [K in keyof typeof COMPANION_COPY.en]: string };
const EXTRA_COPY: Record<Exclude<LoadingLocale, keyof typeof COMPANION_COPY>, CompanionText> = {
 'zh-TW': { savedDone:'文字已儲存。', unavailable:'尚未取得今日結果，請檢查網路後重試。', retry:'重試', title:'靈喵今日一語', quote:'名言', affirmation:'正向肯定', daily:'今日運勢', close:'返回應用程式', previous:'上一則', next:'下一則', settings:'鎖定畫面設定', quiet:'勿擾時段', start:'開始', end:'結束', privacy:'請解鎖後在應用程式中查看個人運勢。通知不會顯示出生日期、諮詢或付款資訊。', test:'測試通知', posted:'通知已發布，是否顯示取決於系統設定。', blocked:'無法發布通知，請檢查功能開關與系統通知設定。', system:'系統通知設定', enabled:'在偏好時間附近接收提醒，省電模式可能延遲通知。', textSize:'字級設定適用於應用程式內卡片，通知使用系統字級。', privateSummary:'請解鎖後在應用程式中查看今日運勢。', source:'既有離線參考解讀 · 韓國標準時間', web:'查看共同的今日運勢', noContent:'請在設定中選擇內容。', ownLine:'從今天能做的一件小事開始，就已經足夠。', ownAuthor:'靈喵一語', ownAffirmation:'我可以按自己的步調，一步一步向前。', kind:'顯示內容', saved:'儲存文字', shared:'分享', themeCharacter:'角色', yeongnyangi:'靈喵' },
 vi: { savedDone:'Đã lưu câu nói.', unavailable:'Chưa có kết quả hôm nay. Hãy kiểm tra kết nối và thử lại.', retry:'Thử lại', title:'Lời nhắn mỗi ngày từ Yeongnyangi', quote:'Danh ngôn', affirmation:'Lời khẳng định', daily:'Vận trình hôm nay', close:'Về ứng dụng', previous:'Trước', next:'Tiếp', settings:'Cài đặt màn hình khóa', quiet:'Giờ yên lặng', start:'Từ', end:'Đến', privacy:'Mở khóa rồi vào ứng dụng để xem vận trình cá nhân. Thông báo không hiển thị ngày sinh, nội dung tư vấn hay thông tin thanh toán.', test:'Thông báo thử', posted:'Đã đăng thông báo. Việc hiển thị tùy thuộc cài đặt hệ thống.', blocked:'Chưa thể đăng thông báo. Hãy kiểm tra công tắc tính năng và cài đặt thông báo hệ thống.', system:'Cài đặt thông báo hệ thống', enabled:'Nhận nhắc nhở gần giờ bạn chọn. Chế độ tiết kiệm pin có thể làm thông báo đến muộn.', textSize:'Cỡ chữ áp dụng cho thẻ trong ứng dụng. Thông báo dùng cỡ chữ hệ thống.', privateSummary:'Mở khóa và vào ứng dụng để xem vận trình hôm nay.', source:'Diễn giải tham khảo ngoại tuyến hiện có · Ngày theo giờ Hàn Quốc', web:'Xem vận trình hôm nay dùng chung', noContent:'Chọn nội dung trong cài đặt.', ownLine:'Bắt đầu bằng một việc nhỏ hôm nay là đủ.', ownAuthor:'Lời nhắn từ Yeongnyangi', ownAffirmation:'Tôi có thể tiến từng bước theo nhịp độ của mình.', kind:'Nội dung hiển thị', saved:'Lưu câu nói', shared:'Chia sẻ', themeCharacter:'Nhân vật', yeongnyangi:'Yeongnyangi' },
 hi: { savedDone:'वाक्य सहेजा गया।', unavailable:'आज का परिणाम अभी उपलब्ध नहीं है। कनेक्शन जाँचकर फिर कोशिश करें।', retry:'फिर कोशिश करें', title:'योंगन्यांगी का आज का संदेश', quote:'विचार', affirmation:'सकारात्मक संकल्प', daily:'आज का भाग्यफल', close:'ऐप पर लौटें', previous:'पिछला', next:'अगला', settings:'लॉक स्क्रीन सेटिंग', quiet:'शांत समय', start:'शुरू', end:'समाप्त', privacy:'निजी भाग्यफल देखने के लिए फ़ोन अनलॉक करके ऐप खोलें। सूचनाओं में जन्म विवरण, परामर्श या भुगतान की जानकारी नहीं दिखाई जाती।', test:'परीक्षण सूचना', posted:'सूचना भेजी गई। उसका दिखना सिस्टम सेटिंग पर निर्भर है।', blocked:'सूचना नहीं भेज सके। सुविधा का स्विच और सिस्टम की सूचना सेटिंग जाँचें।', system:'सिस्टम की सूचना सेटिंग', enabled:'चुने हुए समय के आसपास सूचनाएँ पाएँ। बैटरी बचत मोड में देरी हो सकती है।', textSize:'अक्षर आकार ऐप के कार्ड पर लागू होता है। सूचनाएँ सिस्टम का अक्षर आकार इस्तेमाल करती हैं।', privateSummary:'आज का भाग्यफल देखने के लिए अनलॉक करके ऐप खोलें।', source:'मौजूदा ऑफ़लाइन संदर्भ व्याख्या · कोरियाई मानक समय की तारीख', web:'साझा दैनिक भाग्यफल देखें', noContent:'सेटिंग में सामग्री चुनें।', ownLine:'आज एक छोटी चीज़ से शुरुआत करना भी पर्याप्त है।', ownAuthor:'योंगन्यांगी का संदेश', ownAffirmation:'मैं अपनी गति से एक-एक कदम आगे बढ़ सकता हूँ।', kind:'दिखाई जाने वाली सामग्री', saved:'वाक्य सहेजें', shared:'साझा करें', themeCharacter:'पात्र', yeongnyangi:'योंगन्यांगी' },
 es: { savedDone:'Texto guardado.', unavailable:'El resultado de hoy aún no está disponible. Comprueba la conexión e inténtalo de nuevo.', retry:'Reintentar', title:'Una palabra diaria de Yeongnyangi', quote:'Cita', affirmation:'Afirmación', daily:'Fortuna diaria', close:'Volver a la app', previous:'Anterior', next:'Siguiente', settings:'Ajustes de pantalla de bloqueo', quiet:'Horas de silencio', start:'Desde', end:'Hasta', privacy:'Desbloquea y abre la app para leer tu fortuna. Las notificaciones no muestran datos de nacimiento, consultas ni pagos.', test:'Notificación de prueba', posted:'Notificación publicada. Su visibilidad depende de los ajustes del sistema.', blocked:'No se pudo publicar. Revisa el interruptor de la función y los ajustes de notificaciones del sistema.', system:'Notificaciones del sistema', enabled:'Recibe recordatorios cerca de la hora elegida. El ahorro de batería puede retrasarlos.', textSize:'El tamaño de texto se aplica a las tarjetas de la app. Las notificaciones usan el tamaño del sistema.', privateSummary:'Desbloquea y abre la app para ver tu fortuna diaria.', source:'Interpretación de referencia sin conexión existente · Fecha KST', web:'Ver la fortuna diaria compartida', noContent:'Elige contenido en los ajustes.', ownLine:'Basta con empezar hoy por una pequeña cosa.', ownAuthor:'Una palabra de Yeongnyangi', ownAffirmation:'Puedo avanzar un paso a la vez, a mi propio ritmo.', kind:'Contenido que mostrar', saved:'Guardar texto', shared:'Compartir', themeCharacter:'Personaje', yeongnyangi:'Yeongnyangi' },
 fr: { savedDone:'Texte enregistré.', unavailable:'Le résultat du jour est encore indisponible. Vérifiez votre connexion et réessayez.', retry:'Réessayer', title:'Un mot quotidien de Yeongnyangi', quote:'Citation', affirmation:'Affirmation', daily:'Prévisions du jour', close:'Retour à l’application', previous:'Précédent', next:'Suivant', settings:'Réglages de l’écran verrouillé', quiet:'Heures calmes', start:'De', end:'À', privacy:'Déverrouillez et ouvrez l’application pour lire vos prévisions. Les notifications ne montrent ni données de naissance, ni consultations, ni paiements.', test:'Notification de test', posted:'Notification publiée. Son affichage dépend des réglages du système.', blocked:'Envoi impossible. Vérifiez l’activation de la fonction et les notifications du système.', system:'Notifications du système', enabled:'Recevez des rappels autour de l’heure choisie. L’économie de batterie peut les retarder.', textSize:'La taille du texte concerne les cartes de l’application. Les notifications utilisent celle du système.', privateSummary:'Déverrouillez et ouvrez l’application pour lire vos prévisions du jour.', source:'Interprétation de référence hors ligne existante · Date KST', web:'Voir les prévisions du jour communes', noContent:'Choisissez le contenu dans les réglages.', ownLine:'Commencer par une petite chose aujourd’hui suffit.', ownAuthor:'Un mot de Yeongnyangi', ownAffirmation:'Je peux avancer un pas à la fois, à mon rythme.', kind:'Contenu à afficher', saved:'Enregistrer le texte', shared:'Partager', themeCharacter:'Personnage', yeongnyangi:'Yeongnyangi' },
 de: { savedDone:'Text gespeichert.', unavailable:'Das heutige Ergebnis ist noch nicht verfügbar. Prüfe die Verbindung und versuche es erneut.', retry:'Erneut versuchen', title:'Ein tägliches Wort von Yeongnyangi', quote:'Zitat', affirmation:'Affirmation', daily:'Tagesdeutung', close:'Zurück zur App', previous:'Zurück', next:'Weiter', settings:'Sperrbildschirm-Einstellungen', quiet:'Ruhezeiten', start:'Von', end:'Bis', privacy:'Entsperre das Gerät und öffne die App für deine persönliche Deutung. Mitteilungen zeigen keine Geburtsdaten, Beratungen oder Zahlungsdaten.', test:'Testmitteilung', posted:'Mitteilung gesendet. Die Anzeige hängt von den Systemeinstellungen ab.', blocked:'Senden nicht möglich. Prüfe den Funktionsschalter und die Mitteilungseinstellungen des Systems.', system:'System-Mitteilungen', enabled:'Erinnerungen kommen ungefähr zur gewählten Zeit. Der Energiesparmodus kann sie verzögern.', textSize:'Die Schriftgröße gilt für Karten in der App. Mitteilungen verwenden die Systemschriftgröße.', privateSummary:'Entsperre das Gerät und öffne die App für deine Tagesdeutung.', source:'Vorhandene Offline-Referenzdeutung · Datum nach KST', web:'Gemeinsame Tagesdeutung öffnen', noContent:'Wähle Inhalte in den Einstellungen.', ownLine:'Es reicht, heute mit einer kleinen Sache anzufangen.', ownAuthor:'Ein Wort von Yeongnyangi', ownAffirmation:'Ich darf Schritt für Schritt in meinem Tempo vorangehen.', kind:'Anzuzeigende Inhalte', saved:'Text speichern', shared:'Teilen', themeCharacter:'Figur', yeongnyangi:'Yeongnyangi' },
 nl: { savedDone:'Tekst opgeslagen.', unavailable:'Het resultaat van vandaag is nog niet beschikbaar. Controleer je verbinding en probeer opnieuw.', retry:'Opnieuw proberen', title:'Een dagelijks woord van Yeongnyangi', quote:'Citaat', affirmation:'Affirmatie', daily:'Dagduiding', close:'Terug naar de app', previous:'Vorige', next:'Volgende', settings:'Instellingen voor het vergrendelscherm', quiet:'Stille uren', start:'Van', end:'Tot', privacy:'Ontgrendel je toestel en open de app voor je persoonlijke duiding. Meldingen tonen geen geboortegegevens, gesprekken of betalingen.', test:'Testmelding', posted:'Melding geplaatst. De zichtbaarheid hangt af van je systeeminstellingen.', blocked:'Plaatsen is niet gelukt. Controleer de functieschakelaar en de meldingsinstellingen van het systeem.', system:'Systeemmeldingen', enabled:'Ontvang herinneringen rond je gekozen tijd. Batterijbesparing kan ze vertragen.', textSize:'De tekstgrootte geldt voor kaarten in de app. Meldingen gebruiken de systeemgrootte.', privateSummary:'Ontgrendel je toestel en open de app voor je dagduiding.', source:'Bestaande offline referentieduiding · Datum volgens KST', web:'Gedeelde dagduiding bekijken', noContent:'Kies inhoud in de instellingen.', ownLine:'Vandaag met één klein ding beginnen is genoeg.', ownAuthor:'Een woord van Yeongnyangi', ownAffirmation:'Ik mag stap voor stap in mijn eigen tempo vooruitgaan.', kind:'Te tonen inhoud', saved:'Tekst opslaan', shared:'Delen', themeCharacter:'Personage', yeongnyangi:'Yeongnyangi' },
 ms: { savedDone:'Teks disimpan.', unavailable:'Keputusan hari ini belum tersedia. Semak sambungan dan cuba lagi.', retry:'Cuba lagi', title:'Pesanan harian daripada Yeongnyangi', quote:'Kata-kata', affirmation:'Afirmasi', daily:'Ramalan harian', close:'Kembali ke aplikasi', previous:'Sebelumnya', next:'Seterusnya', settings:'Tetapan skrin kunci', quiet:'Waktu senyap', start:'Dari', end:'Hingga', privacy:'Buka kunci dan aplikasi untuk membaca ramalan peribadi. Notifikasi tidak memaparkan maklumat kelahiran, perundingan atau bayaran.', test:'Notifikasi ujian', posted:'Notifikasi dihantar. Paparannya bergantung pada tetapan sistem.', blocked:'Notifikasi tidak dapat dihantar. Semak suis ciri dan tetapan notifikasi sistem.', system:'Tetapan notifikasi sistem', enabled:'Terima peringatan sekitar waktu pilihan anda. Mod penjimatan bateri boleh melambatkannya.', textSize:'Saiz teks digunakan pada kad dalam aplikasi. Notifikasi menggunakan saiz teks sistem.', privateSummary:'Buka kunci dan aplikasi untuk melihat ramalan harian anda.', source:'Tafsiran rujukan luar talian sedia ada · Tarikh KST', web:'Lihat ramalan harian yang sama', noContent:'Pilih kandungan dalam tetapan.', ownLine:'Memulakan satu perkara kecil hari ini sudah memadai.', ownAuthor:'Pesanan daripada Yeongnyangi', ownAffirmation:'Saya boleh maju selangkah demi selangkah mengikut rentak sendiri.', kind:'Kandungan untuk dipaparkan', saved:'Simpan teks', shared:'Kongsi', themeCharacter:'Watak', yeongnyangi:'Yeongnyangi' },
};

const SYSTEM_LABELS: Record<string, Record<string, string>> = {
  'zh-TW': { saju:'四柱', sukuyo:'宿曜', astro:'西方占星', vedic:'吠陀占星', ziwei:'紫微斗數' },
  vi: { saju:'Tứ trụ', sukuyo:'Sukuyo', astro:'Chiêm tinh phương Tây', vedic:'Chiêm tinh Vệ Đà', ziwei:'Tử Vi Đẩu Số' },
  hi: { saju:'चार स्तंभ', sukuyo:'सुकुयो', astro:'पाश्चात्य ज्योतिष', vedic:'वैदिक ज्योतिष', ziwei:'ज़ी वेई दोउ शू' },
  es: { saju:'Cuatro pilares', sukuyo:'Sukuyo', astro:'Astrología occidental', vedic:'Astrología védica', ziwei:'Zi Wei Dou Shu' },
  fr: { saju:'Quatre piliers', sukuyo:'Sukuyo', astro:'Astrologie occidentale', vedic:'Astrologie védique', ziwei:'Zi Wei Dou Shu' },
  de: { saju:'Vier Säulen', sukuyo:'Sukuyo', astro:'Westliche Astrologie', vedic:'Vedische Astrologie', ziwei:'Zi Wei Dou Shu' },
  nl: { saju:'Vier pijlers', sukuyo:'Sukuyo', astro:'Westerse astrologie', vedic:'Vedische astrologie', ziwei:'Zi Wei Dou Shu' },
  ms: { saju:'Empat tiang', sukuyo:'Sukuyo', astro:'Astrologi Barat', vedic:'Astrologi Veda', ziwei:'Zi Wei Dou Shu' },
  en: { saju: 'Four pillars', sukuyo: 'Sukuyo', astro: 'Western astrology', vedic: 'Vedic astrology', ziwei: 'Zi Wei Dou Shu' },
  ja: { saju: '四柱推命', sukuyo: '宿曜', astro: '西洋占星術', vedic: 'インド占星術', ziwei: '紫微斗数' },
  'zh-CN': { saju: '四柱', sukuyo: '宿曜', astro: '西方占星', vedic: '吠陀占星', ziwei: '紫微斗数' },
};
export function systemLabel(locale: string, key: string, fallback: string) {
  return locale === 'ko' ? fallback : (SYSTEM_LABELS[locale] || SYSTEM_LABELS.en)[key] || fallback;
}
const CATEGORY_LABELS: Record<string, string[]> = {
  'zh-TW':['韌性','自我照顧','勇氣','成長','自我尊重','關係','感恩','平靜','夢想','智慧','健康','豐盛'],
  vi:['Sự kiên cường','Chăm sóc bản thân','Can đảm','Trưởng thành','Giá trị bản thân','Các mối quan hệ','Biết ơn','Bình yên','Ước mơ','Trí tuệ','Sức khỏe','Sự đủ đầy'],
  hi:['लचीलापन','आत्म-देखभाल','साहस','विकास','आत्म-मूल्य','रिश्ते','कृतज्ञता','शांति','सपने','विवेक','स्वास्थ्य','समृद्धि'],
  es:['Resiliencia','Autocuidado','Valor','Crecimiento','Autoestima','Relaciones','Gratitud','Paz','Sueños','Sabiduría','Salud','Abundancia'],
  fr:['Résilience','Prendre soin de soi','Courage','Évolution','Estime de soi','Relations','Gratitude','Paix','Rêves','Sagesse','Santé','Abondance'],
  de:['Widerstandskraft','Selbstfürsorge','Mut','Wachstum','Selbstwert','Beziehungen','Dankbarkeit','Ruhe','Träume','Weisheit','Gesundheit','Fülle'],
  nl:['Veerkracht','Zelfzorg','Moed','Groei','Eigenwaarde','Relaties','Dankbaarheid','Rust','Dromen','Wijsheid','Gezondheid','Overvloed'],
  ms:['Ketabahan','Penjagaan diri','Keberanian','Pertumbuhan','Harga diri','Hubungan','Kesyukuran','Ketenangan','Impian','Kebijaksanaan','Kesihatan','Kelimpahan'],
  en: ['Resilience','Self-care','Courage','Growth','Self-worth','Relationships','Gratitude','Peace','Dreams','Wisdom','Health','Abundance'],
  ja: ['立ち直る力','セルフケア','勇気','成長','自己尊重','人間関係','感謝','心の平和','夢','知恵','健康','豊かさ'],
  'zh-CN': ['韧性','自我照顾','勇气','成长','自我尊重','关系','感恩','平静','梦想','智慧','健康','丰盛'],
};
export function categoryLabel(locale: string, index: number, fallback: string) {
  return locale === 'ko' ? fallback : (CATEGORY_LABELS[locale] || CATEGORY_LABELS.en)[index] || fallback;
}
