"use client";
import {depthDescriptions} from '@/worker/yeongnyangi/fortune/reading-policy';
import {useEffect,useState} from 'react';
import type {Product} from '@/worker/yeongnyangi/payments/catalog';

const reactions:Record<string,[string,string]>={mackerel:['어? 고등어잖아! 눈이 번쩍 뜨인다냥.','고등어 잘 받았다냥. 네 핵심부터 야무지게 읽어줄게.'],salmon:['연어라니, 입꼬리가 자꾸 올라간다냥.','부드러운 연어 고맙다냥. 네 이야기도 찬찬히 풀어볼게.'],flounder:['광어 앞에서는 앞발부터 들린다냥!','광어 잘 받았다냥! 네 선택의 흐름까지 꼼꼼히 보자.'],tuna:['참치는… 살짝 안아봐도 되냥?','참치 품에 안고 힘냈다냥. 긴 이야기는 목차부터 천천히 읽어봐.'],assorted:['이것도 저것도? 어디부터 볼지 행복한 고민이다냥!','모둠 잘 받았다냥! 두 체계의 공통점과 다른 점을 나란히 펼쳐볼게.'],omakase:['잠깐, 이게 전부 내 거라고?! 앞발이 가만히 안 있는다냥!','오마카세라니, 냐아앙! 고맙다냥! 여섯 시선을 모은 네 운명서를 펼쳐볼게!']};
export function FishReaction({product,paid=false}:{product:Product;paid?:boolean}) {return <aside className={`fish-reaction ${paid?'fish-thanks':''} ${paid&&product.fishId==='omakase'?'omakase-burst':''}`} aria-live="polite"><img src={product.reactionAsset} width={300} height={300} alt={`${product.fishName}에 기뻐하는 영냥이`}/><div><small>{paid?'구매 확인 · 영냥이의 감사 인사':'생선을 고르는 중 · 영냥이의 기대'}</small><p>{reactions[product.fishId]?.[paid?1:0]}</p></div></aside>;}
export default function FishCatalog({fusionOnly=false,layout='grid'}:{fusionOnly?:boolean;layout?:'grid'|'list'}) {
 const [products,setProducts]=useState<(Product&{available:boolean})[]>([]),[failed,setFailed]=useState(false);
 useEffect(()=>{fetch('/api/yeongnyangi/products').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{setProducts(d.products);}).catch(()=>setFailed(true));},[]);
 const items=fusionOnly?products.filter(p=>p.readingKind!=='single'):products.filter((p,i,a)=>a.findIndex(x=>x.fishId===p.fishId)===i);
 return <section className={`fish-catalog${layout==='list'?' fish-catalog-compact':''}`} aria-label={fusionOnly?'초융합 상담 선택':'생선 오마카세 가격표'}><h2>{fusionOnly?'서로 다른 시선으로 읽는 나':'영냥이의 생선 오마카세 가격표'}</h2><p>{fusionOnly?'여러 체계의 공통점과 차이까지 한 권으로. 원하는 조합을 고르면 차트부터 시작해.':'한 분야를 깊게, 또는 여러 체계의 공통점과 차이까지.'}</p>{failed&&<p role="alert">가격표를 불러오지 못했어요. 새로고침해 주세요.</p>}<div className={layout==='list'?'fish-catalog-list':'fish-catalog-grid'}>{items.map(p=><a key={p.id} href={p.available?(p.readingKind==='single'?`/yeongnyangi/fortune/?domain=${p.domain}&fish=${p.fishId}`:`/yeongnyangi/fortune/?product=${p.id}`):undefined} aria-disabled={p.available?undefined:true}><img src={p.image} width={220} height={180} alt="" loading="lazy"/><span>{fusionOnly?p.name:p.fishName}</span><strong>{p.priceKRW.toLocaleString('ko-KR')}원</strong><small>{p.chapterCount}챕터 · {p.readingKind==='single'?'선택한 한 분야':p.readingKind==='pair'?'두 체계 교차분석':'여섯 체계 전체 통합'}</small><p>{depthDescriptions[p.fishId]}</p><b>{p.available?'차트부터 살펴보기 →':'준비 중'}</b></a>)}</div></section>;
}
