import type { VedicPdfChapterDefinition } from "./types";

export const VEDIC_PDF_PERSONAL_CHAPTERS: VedicPdfChapterDefinition[] = [
  {
    number: 1,
    id: "ch01_total",
    titleKo: "I. 베다 차트 총론 — 나의 카르마 설계도",
    subtitleKo: "출생 정보·라시·행성/하우스 총론",
    icon: "🕉️",
    objective: "차트 전체 구조를 집약해 이번 생의 핵심 과제와 인생 기조를 제시한다.",
  },
  {
    number: 2,
    id: "ch02_lagna",
    titleKo: "II. 라그나 분석 — 이번 생의 출발점과 인생 방향",
    subtitleKo: "라그나·라그나 로드 집중 분석",
    icon: "♈",
    objective: "라그나와 라그나 로드를 중심으로 기본 성향과 인생 방향성을 해석한다.",
  },
  {
    number: 3,
    id: "ch03_moon",
    titleKo: "III. 달 차트 분석 — 마음, 감정, 무의식의 흐름",
    subtitleKo: "찬드라 라시·정서 패턴",
    icon: "🌙",
    objective: "달의 강약과 하우스 위치를 기반으로 감정 기질과 회복 조건을 제시한다.",
  },
  {
    number: 4,
    id: "ch04_sun",
    titleKo: "IV. 태양 분석 — 자아, 명예, 삶의 중심성",
    subtitleKo: "수리야 라시·리더십 성향",
    icon: "☀️",
    objective: "태양의 배치와 강약을 바탕으로 자아 축, 명예 축, 성공 방향을 해석한다.",
  },
  {
    number: 5,
    id: "ch05_planets",
    titleKo: "V. 9행성 완전 해석 — 운명을 움직이는 행성의 힘",
    subtitleKo: "9그라하 상호작용·밸런스",
    icon: "🪐",
    objective: "9행성의 별자리·하우스·강약과 상호작용을 통합해 운명 동력을 해석한다.",
  },
  {
    number: 6,
    id: "ch06_houses",
    titleKo: "VI. 12하우스 분석 — 인생 영역별 카르마 지도",
    subtitleKo: "하우스 강약·집중 영역",
    icon: "🗺️",
    objective: "12하우스의 강약과 반복 영역을 통해 현실 카르마 지도를 제시한다.",
  },
  {
    number: 7,
    id: "ch07_nakshatra",
    titleKo: "VII. 나크샤트라 분석 — 영혼의 성향과 본능",
    subtitleKo: "달·라그나·태양 나크샤트라",
    icon: "✨",
    objective: "나크샤트라 및 파다를 기반으로 본능, 관계 반응, 전생 습관을 해석한다.",
  },
  {
    number: 8,
    id: "ch08_yoga",
    titleKo: "VIII. 요가 분석 — 성공, 재물, 명예의 특수 구조",
    subtitleKo: "라자·다나·특수 요가 진단",
    icon: "🧭",
    objective: "주요 요가의 성립 여부와 작동 조건, 약화 조건을 분석한다.",
  },
  {
    number: 9,
    id: "ch09_dosha",
    titleKo: "IX. 도샤와 리스크 분석 — 막힘과 반복되는 시련",
    subtitleKo: "도샤·6/8/12 리스크",
    icon: "⚠️",
    objective: "도샤/리스크 요인을 식별하고 반복 실패 패턴과 완화 방향을 제시한다.",
  },
  {
    number: 10,
    id: "ch10_career",
    titleKo: "X. 직업·재물·성공운 — 현실 성취의 구조",
    subtitleKo: "10/2/11/6 하우스 성취 전략",
    icon: "💼",
    objective: "직업, 수익, 평판, 전환 가능성을 기반으로 장기 성공 전략을 제시한다.",
  },
  {
    number: 11,
    id: "ch11_love",
    titleKo: "XI. 연애·결혼·배우자운 — 인연과 파트너십 분석",
    subtitleKo: "7하우스·금성·목성·다라카라카",
    icon: "💞",
    objective: "연애/결혼 패턴과 갈등 조건을 해석해 관계 안정 전략을 제시한다.",
  },
  {
    number: 12,
    id: "ch12_health",
    titleKo: "XII. 건강·심리·생활운 — 몸과 마음의 균형",
    subtitleKo: "건강 기질·심리 리듬 관리",
    icon: "🧘",
    objective: "건강/심리 패턴과 생활 리듬을 연결해 회복 전략을 제시한다.",
  },
  {
    number: 13,
    id: "ch13_dasha",
    titleKo: "XIII. 다샤 분석 — 인생 시기별 운의 흐름",
    subtitleKo: "마하다샤·안타르다샤 전환",
    icon: "⏳",
    objective: "현재 다샤의 핵심 주제와 전환점, 시기별 행동 전략을 제시한다.",
  },
  {
    number: 14,
    id: "ch14_divisional",
    titleKo: "XIV. 고차원 차트 분석 — 세부 운명 보정",
    subtitleKo: "D9·D10 보정 해석",
    icon: "🔭",
    objective: "나밤샤/다샴샤를 활용해 표면 운과 심층 운의 차이를 보정한다.",
  },
  {
    number: 15,
    id: "ch15_transit",
    titleKo: "XV. 트랜짓 분석 — 현재 하늘이 여는 운의 변화",
    subtitleKo: "목성·토성·라후/케투 이동",
    icon: "🌌",
    objective: "현재 트랜짓 흐름에서 기회/주의 시기를 구분해 활용 전략을 제시한다.",
  },
  {
    number: 16,
    id: "ch16_final",
    titleKo: "XVI. 최종 종합 리포트 — 나의 카르마 사용법",
    subtitleKo: "핵심 전략·최종 조언",
    icon: "📜",
    objective: "차트 전체를 통합해 실행 전략, 장기 성장 방향, 최종 조언을 제시한다.",
  },
];

export const VEDIC_PDF_COMPAT_CHAPTERS: VedicPdfChapterDefinition[] = [
  {
    number: 1,
    id: "compat_first_meeting",
    titleKo: "두 영혼의 첫 만남 — 관계가 시작된 이유",
    subtitleKo: "관계 시작 테마",
    icon: "💫",
    objective: "두 사람의 첫 끌림과 초기 관계 기대/착각을 관계 중심으로 해석한다.",
  },
  {
    number: 2,
    id: "compat_emotional_attachment",
    titleKo: "마음의 궁합 — 감정 안정과 애착의 구조",
    subtitleKo: "감정·애착 궁합",
    icon: "🌙",
    objective: "A/B 정서 반응과 애착 패턴 차이를 분석해 안전한 관계 리듬을 제시한다.",
  },
  {
    number: 3,
    id: "compat_love_desire",
    titleKo: "사랑과 끌림 — 금성·화성의 관계 에너지",
    subtitleKo: "사랑·욕망 에너지",
    icon: "❤️",
    objective: "금성/화성 기반 끌림, 욕망, 애정 표현 차이를 건강한 방식으로 해석한다.",
  },
  {
    number: 4,
    id: "compat_communication",
    titleKo: "말과 생각의 궁합 — 소통, 오해, 이해의 방식",
    subtitleKo: "소통 구조 분석",
    icon: "🗣️",
    objective: "말투, 사고 속도, 갈등 대화 패턴을 분석해 관계 회복 대화법을 제시한다.",
  },
  {
    number: 5,
    id: "compat_partnership",
    titleKo: "결혼과 파트너십 — 장기 관계의 가능성",
    subtitleKo: "장기 동반자 설계",
    icon: "🤝",
    objective: "결혼/동거/장기 관계의 장단점과 합의 기준을 제시한다.",
  },
  {
    number: 6,
    id: "compat_reality_balance",
    titleKo: "현실 궁합 — 돈, 일, 생활 리듬의 조화",
    subtitleKo: "현실 운영 궁합",
    icon: "🏠",
    objective: "돈·일·생활 리듬 충돌 포인트를 파악하고 현실 합의안을 제시한다.",
  },
  {
    number: 7,
    id: "compat_conflict_wound",
    titleKo: "갈등과 상처 패턴 — 관계가 흔들리는 이유",
    subtitleKo: "갈등·회복 패턴",
    icon: "⚠️",
    objective: "반복 충돌 트리거와 상처 패턴을 분석해 회복 조건을 구체화한다.",
  },
  {
    number: 8,
    id: "compat_karma_growth",
    titleKo: "카르마와 성장 — 두 사람이 서로에게 주는 배움",
    subtitleKo: "관계 성장 과제",
    icon: "🪷",
    objective: "관계가 주는 성장 과제를 카르마 관점에서 현실 변화 전략으로 정리한다.",
  },
  {
    number: 9,
    id: "compat_yearly_flow",
    titleKo: "올해 두 사람의 관계 흐름",
    subtitleKo: "연간 관계 운영",
    icon: "📅",
    objective: "올해 관계 흐름을 시기별 전략과 금지 선택 기준으로 제시한다.",
  },
  {
    number: 10,
    id: "compat_final_letter",
    titleKo: "최종 궁합 봉서 — 사랑, 인연, 동반자 가능성",
    subtitleKo: "최종 관계 봉서",
    icon: "📜",
    objective: "관계 강약점과 유지/정리 기준을 상담 편지 형태로 마무리한다.",
  },
  {
    number: 11,
    id: "compat_reality_problems",
    titleKo: "현실 문제 궁합 — 돈, 일, 가족, 생활 방식",
    subtitleKo: "현실 운영 합의 전략",
    icon: "🏠",
    objective: "돈·일·가족·생활 방식의 충돌 포인트를 파악하고 현실 합의 기준을 제시한다.",
  },
  {
    number: 12,
    id: "compat_final_strategy",
    titleKo: "최종 베다 궁합 전략 — 두 사람이 선택해야 할 방향",
    subtitleKo: "최종 관계 마스터플랜",
    icon: "🌟",
    objective: "두 사람의 관계 전체를 통합해 지속/전환/종료 기준과 최종 전략을 제시한다.",
  },
];

export const VEDIC_PDF_CHAPTERS: VedicPdfChapterDefinition[] = VEDIC_PDF_PERSONAL_CHAPTERS;

export function getVedicPdfChapters(mode: "personal" | "single" | "compatibility" = "personal"): VedicPdfChapterDefinition[] {
  return mode === "compatibility" ? VEDIC_PDF_COMPAT_CHAPTERS : VEDIC_PDF_PERSONAL_CHAPTERS;
}

export function getVedicChapterByNumber(
  chapter: number,
  mode: "personal" | "single" | "compatibility" = "personal",
): VedicPdfChapterDefinition {
  const chapterList = getVedicPdfChapters(mode);
  const fallback = chapterList[0] || VEDIC_PDF_PERSONAL_CHAPTERS[0];
  return chapterList.find((item) => item.number === chapter) || fallback;
}
