import FeatureLandingPage from "../components/FeatureLandingPage";

export const SECTION_LABELS = {
  tarot: "타로",
  saju: "사주",
  astrology: "점성술",
  ziwei: "자미두수",
  oracle: "신탁",
};

const SAJU_BASIC_LOCALIZED = {
  en: {
    title: "Basic Saju Manse Calendar Reading - Five Elements, Ten Gods, and birth chart flow",
    h1: "Basic Saju Manse Calendar Reading",
    description: "Your birth date and time open a Four Pillars chart where the balance of the Five Elements and the movement of the Ten Gods are read with calm clarity.",
    seoText: "The Saju Manse Calendar reading follows the Four Pillars, Five Elements, Ten Gods, and timing currents to reveal the structure of your nature, relationships, work, and turning points.",
    landingPoints: ["Generate the Four Pillars chart", "Read Five Elements balance", "Interpret Ten Gods flow"],
  },
  ja: {
    title: "四柱推命 万歳暦 基本鑑定 - 五行・十神・命式の流れ",
    h1: "四柱推命 万歳暦 基本鑑定",
    description: "生年月日と出生時間から開かれる命式の中で、五行のバランスと十神の流れが静かに立ち上がります。",
    seoText: "四柱推命の万歳暦鑑定は、四柱・五行・十神・時期の流れをたどり、性質、関係、仕事、転機の輪郭を読み解きます。",
    landingPoints: ["四柱推命の命式を作成", "五行バランスを読む", "十神の流れを解釈"],
  },
  "zh-CN": {
    title: "四柱推命万年历基础解读 - 五行、十神与命式流动",
    h1: "四柱推命万年历基础解读",
    description: "出生年月日时打开你的四柱命式，五行的平衡与十神的流动会在其中安静显现。",
    seoText: "四柱推命万年历解读沿着四柱、五行、十神与时间运势，读出性格、关系、事业与转折点的命理结构。",
    landingPoints: ["生成四柱命式", "读取五行平衡", "解读十神流动"],
  },
  "zh-TW": {
    title: "四柱推命萬年曆基礎解讀 - 五行、十神與命式流動",
    h1: "四柱推命萬年曆基礎解讀",
    description: "出生年月日時打開你的四柱命式，五行的平衡與十神的流動會在其中安靜顯現。",
    seoText: "四柱推命萬年曆解讀沿著四柱、五行、十神與時間運勢，讀出性格、關係、事業與轉折點的命理結構。",
    landingPoints: ["生成四柱命式", "讀取五行平衡", "解讀十神流動"],
  },
  vi: {
    title: "Luận Saju Manse cơ bản - Ngũ hành, Thập Thần và dòng mệnh cục",
    h1: "Luận Saju Manse cơ bản",
    description: "Ngày giờ sinh mở ra lá số Tứ trụ, nơi cân bằng Ngũ hành và dòng chảy Thập Thần hiện lên một cách lặng lẽ.",
    seoText: "Bài luận Saju Manse đi theo Tứ trụ, Ngũ hành, Thập Thần và vận thời gian để đọc cấu trúc tính cách, quan hệ, công việc và các điểm chuyển mình.",
    landingPoints: ["Tạo mệnh cục Tứ trụ", "Đọc cân bằng Ngũ hành", "Giải dòng chảy Thập Thần"],
  },
  hi: {
    title: "Saju Manse मूल रीडिंग - पाँच तत्व, दश देव और जन्मपत्र प्रवाह",
    h1: "Saju Manse मूल रीडिंग",
    description: "जन्म तिथि और समय से खुली Four Pillars जन्मपत्री में पाँच तत्वों का संतुलन और दश देवों की धारा शांत रूप से दिखाई देती है.",
    seoText: "Saju Manse रीडिंग Four Pillars, पाँच तत्व, दश देव और समय प्रवाह के सहारे स्वभाव, संबंध, काम और मोड़ के भाग्य ढाँचे को पढ़ती है.",
    landingPoints: ["Four Pillars जन्मपत्री बनाएँ", "पाँच तत्व संतुलन पढ़ें", "दश देवों की धारा समझें"],
  },
  es: {
    title: "Lectura básica de Saju Manse - Cinco Elementos, Diez Dioses y flujo de carta natal",
    h1: "Lectura básica de Saju Manse",
    description: "La fecha y hora de nacimiento abren una carta de Cuatro Pilares donde el equilibrio de los Cinco Elementos y el movimiento de los Diez Dioses aparecen con calma.",
    seoText: "La lectura Saju Manse sigue los Cuatro Pilares, Cinco Elementos, Diez Dioses y corrientes del tiempo para revelar la estructura de naturaleza, relaciones, trabajo y giros vitales.",
    landingPoints: ["Generar carta de Cuatro Pilares", "Leer equilibrio de Cinco Elementos", "Interpretar flujo de Diez Dioses"],
  },
  fr: {
    title: "Lecture Saju Manse de base - Cinq Éléments, Dix Dieux et flux du thème",
    h1: "Lecture Saju Manse de base",
    description: "La date et l'heure de naissance ouvrent un thème des Quatre Piliers où l'équilibre des Cinq Éléments et le mouvement des Dix Dieux se révèlent avec calme.",
    seoText: "La lecture Saju Manse suit les Quatre Piliers, les Cinq Éléments, les Dix Dieux et les courants du temps pour éclairer la nature, les relations, le travail et les passages de vie.",
    landingPoints: ["Créer le thème des Quatre Piliers", "Lire l'équilibre des Cinq Éléments", "Interpréter le flux des Dix Dieux"],
  },
  de: {
    title: "Basisdeutung Saju Manse - Fünf Elemente, Zehn Götter und Geburtschartfluss",
    h1: "Basisdeutung Saju Manse",
    description: "Geburtsdatum und Uhrzeit öffnen ein Vier-Säulen-Chart, in dem das Gleichgewicht der Fünf Elemente und die Bewegung der Zehn Götter ruhig sichtbar werden.",
    seoText: "Die Saju-Manse-Lesung folgt Vier Säulen, Fünf Elementen, Zehn Göttern und Zeitströmungen, um Wesen, Beziehungen, Arbeit und Wendepunkte zu lesen.",
    landingPoints: ["Vier-Säulen-Chart erstellen", "Balance der Fünf Elemente lesen", "Fluss der Zehn Götter deuten"],
  },
  nl: {
    title: "Basis Saju Manse lezing - Vijf Elementen, Ten Gods en geboortechartstroom",
    h1: "Basis Saju Manse lezing",
    description: "Geboortedatum en -tijd openen een Vierpijlerchart waarin de balans van de Vijf Elementen en de beweging van Ten Gods rustig zichtbaar worden.",
    seoText: "De Saju Manse lezing volgt Vier Pilaren, Vijf Elementen, Ten Gods en tijdstromen om natuur, relaties, werk en keerpunten te lezen.",
    landingPoints: ["Vierpijlerchart maken", "Balans van Vijf Elementen lezen", "Stroom van Ten Gods duiden"],
  },
  ms: {
    title: "Bacaan asas Saju Manse - Lima Unsur, Ten Gods dan aliran carta kelahiran",
    h1: "Bacaan asas Saju Manse",
    description: "Tarikh dan masa lahir membuka carta Empat Tiang, tempat keseimbangan Lima Unsur dan gerak Ten Gods muncul dengan tenang.",
    seoText: "Bacaan Saju Manse menelusuri Empat Tiang, Lima Unsur, Ten Gods dan arus masa untuk membaca sifat, hubungan, kerja dan titik perubahan hidup.",
    landingPoints: ["Jana carta Empat Tiang", "Baca keseimbangan Lima Unsur", "Tafsir aliran Ten Gods"],
  },
};

const DESTINY_BIAS_LOCALIZED = {
  en: {
    title: "Destiny Bias - Saju-based fandom resonance reading",
    h1: "Destiny Bias",
    description: "Your Saju and your bias's symbolic energy are placed side by side, revealing resonance score, elemental support, Ten Gods roles, and a small action for today.",
    seoText: "Destiny Bias reads fandom affection through Saju resonance, showing how your elemental rhythm meets the symbolic presence of the person you cherish.",
    landingPoints: ["My Saju x bias resonance score", "Elemental support and Ten Gods roles", "KRW 5,000 one-time reading card"],
  },
  ja: {
    title: "推し運命 - 四柱推命ベースのファンダム共鳴リーディング",
    h1: "推し運命",
    description: "あなたの四柱推命の気と推しの象徴エネルギーを重ね、共鳴スコア、五行の補い、十神の役割、今日の小さなアクションをカードに映します。",
    seoText: "推し運命は、推しへの想いを四柱推命の共鳴として読み、あなたの五行リズムと大切な存在の象徴がどのように響き合うかを照らします。",
    landingPoints: ["私の四柱推命 × 推しの共鳴スコア", "五行補完と十神の役割", "1回5,000ウォンの分析カード"],
  },
  "zh-CN": {
    title: "本命偏爱 - 基于四柱推命的粉丝共鸣解读",
    h1: "本命偏爱",
    description: "你的四柱能量与本命的象征能量并列展开，共鸣分数、五行补足、十神角色与今天的小行动会浮现出来。",
    seoText: "本命偏爱以四柱推命读取粉丝心意的共鸣，看你的五行节奏如何与珍视之人的象征气场相互呼应。",
    landingPoints: ["我的四柱 × 本命共鸣分数", "五行补足与十神角色", "单次5,000韩元分析卡"],
  },
  "zh-TW": {
    title: "本命偏愛 - 基於四柱推命的粉絲共鳴解讀",
    h1: "本命偏愛",
    description: "你的四柱能量與本命的象徵能量並列展開，共鳴分數、五行補足、十神角色與今天的小行動會浮現出來。",
    seoText: "本命偏愛以四柱推命讀取粉絲心意的共鳴，看你的五行節奏如何與珍視之人的象徵氣場相互呼應。",
    landingPoints: ["我的四柱 × 本命共鳴分數", "五行補足與十神角色", "單次5,000韓元分析卡"],
  },
  vi: {
    title: "Destiny Bias - bài đọc cộng hưởng fandom dựa trên Saju",
    h1: "Destiny Bias",
    description: "Năng lượng Saju của bạn và biểu tượng của người bạn thương mến được đặt cạnh nhau, để điểm cộng hưởng, phần Ngũ hành bù đắp, vai trò Thập Thần và hành động hôm nay hiện lên.",
    seoText: "Destiny Bias đọc tình cảm fandom như một cộng hưởng Saju, nơi nhịp Ngũ hành của bạn gặp biểu tượng của người bạn trân quý.",
    landingPoints: ["Điểm cộng hưởng Saju x bias", "Bù đắp Ngũ hành và vai trò Thập Thần", "Thẻ đọc một lần 5.000 KRW"],
  },
  hi: {
    title: "Destiny Bias - Saju आधारित fandom resonance रीडिंग",
    h1: "Destiny Bias",
    description: "आपकी Saju ऊर्जा और आपके प्रिय bias की प्रतीक ऊर्जा साथ रखी जाती है, जहाँ resonance score, तत्वीय सहारा, दश देवों की भूमिका और आज का छोटा action उभरता है.",
    seoText: "Destiny Bias fandom स्नेह को Saju resonance की तरह पढ़ता है, जहाँ आपकी तत्वीय लय उस प्रिय उपस्थिति के प्रतीक से मिलती है.",
    landingPoints: ["मेरी Saju x bias resonance score", "तत्वीय सहारा और दश देव भूमिकाएँ", "5,000 KRW एक बार की reading card"],
  },
  es: {
    title: "Destiny Bias - lectura de resonancia fandom basada en Saju",
    h1: "Destiny Bias",
    description: "Tu energía Saju y la energía simbólica de tu bias se colocan lado a lado, revelando puntuación de resonancia, apoyo elemental, roles de Diez Dioses y una pequeña acción para hoy.",
    seoText: "Destiny Bias lee el afecto fandom como resonancia Saju, mostrando cómo tu ritmo elemental se encuentra con la presencia simbólica de quien aprecias.",
    landingPoints: ["Puntuación de resonancia Saju x bias", "Apoyo elemental y roles de Diez Dioses", "Tarjeta de lectura única de 5.000 KRW"],
  },
  fr: {
    title: "Destiny Bias - lecture de résonance fandom selon Saju",
    h1: "Destiny Bias",
    description: "Votre énergie Saju et l'énergie symbolique de votre bias se placent côte à côte, révélant score de résonance, soutien des éléments, rôles des Dix Dieux et petit geste du jour.",
    seoText: "Destiny Bias lit l'affection fandom comme une résonance Saju, là où votre rythme élémentaire rencontre la présence symbolique de la personne chérie.",
    landingPoints: ["Score de résonance Saju x bias", "Soutien des éléments et rôles des Dix Dieux", "Carte de lecture unique à 5 000 KRW"],
  },
  de: {
    title: "Destiny Bias - Saju-basierte Fandom-Resonanzlesung",
    h1: "Destiny Bias",
    description: "Deine Saju-Energie und die symbolische Energie deines Bias werden nebeneinandergelegt; Resonanzscore, elementare Unterstützung, Rollen der Zehn Götter und eine kleine heutige Handlung treten hervor.",
    seoText: "Destiny Bias liest Fandom-Zuneigung als Saju-Resonanz und zeigt, wie dein Elementrhythmus der symbolischen Präsenz deines Lieblings begegnet.",
    landingPoints: ["Saju x Bias Resonanzscore", "Elementare Unterstützung und Rollen der Zehn Götter", "Einmalige Lesekarte für 5.000 KRW"],
  },
  nl: {
    title: "Destiny Bias - Saju-gebaseerde fandomresonantielezing",
    h1: "Destiny Bias",
    description: "Jouw Saju-energie en de symbolische energie van je bias worden naast elkaar gelegd, waardoor resonantiescore, elementaire steun, rollen van Ten Gods en een kleine actie voor vandaag zichtbaar worden.",
    seoText: "Destiny Bias leest fandomliefde als Saju-resonantie en toont hoe jouw elementaire ritme de symbolische aanwezigheid van je geliefde artiest ontmoet.",
    landingPoints: ["Saju x bias resonantiescore", "Elementaire steun en rollen van Ten Gods", "Eenmalige lezingkaart van KRW 5.000"],
  },
  ms: {
    title: "Destiny Bias - bacaan resonans fandom berasaskan Saju",
    h1: "Destiny Bias",
    description: "Tenaga Saju anda dan tenaga simbolik bias anda diletakkan bersebelahan, membuka skor resonans, sokongan unsur, peranan Ten Gods dan tindakan kecil untuk hari ini.",
    seoText: "Destiny Bias membaca kasih fandom sebagai resonans Saju, tempat rentak unsur anda bertemu kehadiran simbolik orang yang anda hargai.",
    landingPoints: ["Skor resonans Saju x bias", "Sokongan unsur dan peranan Ten Gods", "Kad bacaan sekali 5,000 KRW"],
  },
};

const SAJU_GUARDIAN_LOCALIZED = {
  en: {
    title: "Saju Guardian Art - guardian animal test from your Four Pillars",
    h1: "Saju Guardian Art",
    description: "Your day stem, month branch, elemental balance, and Ten Gods flow call forth a guardian animal card with its protection tone, warning message, and relationship harmony.",
    seoText: "Saju Guardian Art reads the protective style hidden in your Four Pillars and shapes it into a shareable guardian animal card.",
    landingPoints: ["Day stem, month branch, and element-based match", "Fixed 2D guardian animal card", "Saju basis plus today’s message", "Save a share card"],
  },
  ja: {
    title: "四柱推命ガーディアンアート - 命式から読む守護動物テスト",
    h1: "四柱推命ガーディアンアート",
    description: "日干、月支、五行バランス、十神の流れから、守護動物カード、守護の質、警告メッセージ、相性の響きが呼び出されます。",
    seoText: "四柱推命ガーディアンアートは、命式に隠れた守護スタイルを読み、共有できる守護動物カードとして映し出します。",
    landingPoints: ["日干・月支・五行による照合", "固定2D守護動物カード", "四柱推命の根拠 + 今日のメッセージ", "共有カード保存"],
  },
  "zh-CN": {
    title: "四柱守护艺术 - 从命式唤醒守护动物测试",
    h1: "四柱守护艺术",
    description: "日干、月支、五行平衡与十神流动会唤出你的守护动物卡，也照见守护力、提醒讯息与关系合拍度。",
    seoText: "四柱守护艺术读取四柱中隐藏的保护方式，并把它化成可以保存分享的守护动物卡。",
    landingPoints: ["日干、月支与五行匹配", "固定2D守护动物卡", "四柱依据 + 今日讯息", "保存分享卡"],
  },
  "zh-TW": {
    title: "四柱守護藝術 - 從命式喚醒守護動物測試",
    h1: "四柱守護藝術",
    description: "日干、月支、五行平衡與十神流動會喚出你的守護動物卡，也照見守護力、提醒訊息與關係合拍度。",
    seoText: "四柱守護藝術讀取四柱中隱藏的保護方式，並把它化成可以保存分享的守護動物卡。",
    landingPoints: ["日干、月支與五行匹配", "固定2D守護動物卡", "四柱依據 + 今日訊息", "保存分享卡"],
  },
  vi: {
    title: "Saju Guardian Art - bài test linh thú hộ mệnh từ Tứ trụ",
    h1: "Saju Guardian Art",
    description: "Thiên can ngày, địa chi tháng, cân bằng Ngũ hành và dòng Thập Thần gọi lên lá bài linh thú hộ mệnh, sắc thái bảo hộ, lời nhắc cảnh tỉnh và độ hòa hợp.",
    seoText: "Saju Guardian Art đọc phong cách bảo hộ ẩn trong Tứ trụ rồi hóa nó thành một lá bài linh thú có thể lưu và chia sẻ.",
    landingPoints: ["Ghép theo can ngày, chi tháng và Ngũ hành", "Thẻ linh thú 2D cố định", "Căn cứ Saju + thông điệp hôm nay", "Lưu thẻ chia sẻ"],
  },
  hi: {
    title: "Saju Guardian Art - Four Pillars से रक्षक पशु टेस्ट",
    h1: "Saju Guardian Art",
    description: "दिन-तना, माह-शाखा, तत्व संतुलन और दश देवों की धारा आपका guardian animal card, सुरक्षा स्वर, चेतावनी संदेश और संबंध harmony बुलाते हैं.",
    seoText: "Saju Guardian Art आपकी Four Pillars में छिपी सुरक्षा शैली पढ़कर उसे share करने योग्य guardian animal card में बदलता है.",
    landingPoints: ["दिन-तना, माह-शाखा और तत्व आधारित मिलान", "स्थिर 2D guardian animal card", "Saju आधार + आज का संदेश", "Share card सहेजें"],
  },
  es: {
    title: "Arte Guardián Saju - test de animal protector desde tus Cuatro Pilares",
    h1: "Arte Guardián Saju",
    description: "El tallo del día, la rama del mes, el equilibrio elemental y el flujo de Diez Dioses llaman a tu animal guardián, su tono protector, advertencia y armonía relacional.",
    seoText: "Arte Guardián Saju lee el estilo protector escondido en tus Cuatro Pilares y lo convierte en una carta de animal guardián para guardar y compartir.",
    landingPoints: ["Asignación por tallo, rama y elementos", "Carta 2D fija de animal guardián", "Base Saju + mensaje de hoy", "Guardar carta para compartir"],
  },
  fr: {
    title: "Art Gardien Saju - test d'animal protecteur depuis les Quatre Piliers",
    h1: "Art Gardien Saju",
    description: "Le tronc du jour, la branche du mois, l'équilibre des éléments et le flux des Dix Dieux appellent votre animal gardien, sa tonalité de protection, son avertissement et son harmonie relationnelle.",
    seoText: "Art Gardien Saju lit le style protecteur caché dans vos Quatre Piliers et le transforme en carte d'animal gardien à sauvegarder et partager.",
    landingPoints: ["Correspondance tronc, branche et éléments", "Carte 2D fixe d'animal gardien", "Base Saju + message du jour", "Sauvegarde de carte partageable"],
  },
  de: {
    title: "Saju Guardian Art - Schutztier-Test aus deinen Vier Säulen",
    h1: "Saju Guardian Art",
    description: "Tagesstamm, Monatszweig, Elementbalance und der Fluss der Zehn Götter rufen dein Schutztier, seine Schutzfarbe, Warnbotschaft und Beziehungsharmonie hervor.",
    seoText: "Saju Guardian Art liest den Schutzstil in deinen Vier Säulen und formt ihn zu einer teilbaren Schutztierkarte.",
    landingPoints: ["Zuordnung nach Tagesstamm, Monatszweig und Elementen", "Feste 2D-Schutztierkarte", "Saju-Basis + heutige Botschaft", "Teilbare Karte speichern"],
  },
  nl: {
    title: "Saju Guardian Art - beschermdiertest vanuit je Vier Pilaren",
    h1: "Saju Guardian Art",
    description: "Dagstam, maandtak, elementbalans en de stroom van Ten Gods roepen je beschermdierkaart, beschermingstoon, waarschuwing en relatieharmonie op.",
    seoText: "Saju Guardian Art leest de beschermstijl in je Vier Pilaren en vormt die tot een deelbare beschermdierkaart.",
    landingPoints: ["Match op dagstam, maandtak en elementen", "Vaste 2D beschermdierkaart", "Saju-basis + boodschap van vandaag", "Deelkaart opslaan"],
  },
  ms: {
    title: "Saju Guardian Art - ujian haiwan penjaga daripada Empat Tiang",
    h1: "Saju Guardian Art",
    description: "Day stem, month branch, keseimbangan unsur dan aliran Ten Gods memanggil kad haiwan penjaga, nada perlindungan, mesej amaran dan keharmonian hubungan anda.",
    seoText: "Saju Guardian Art membaca gaya perlindungan yang tersembunyi dalam Empat Tiang anda lalu membentuknya menjadi kad haiwan penjaga yang boleh dikongsi.",
    landingPoints: ["Padanan day stem, month branch dan unsur", "Kad haiwan penjaga 2D tetap", "Asas Saju + mesej hari ini", "Simpan kad kongsi"],
  },
};

const DESTINY_MEETING_PLACE_LOCALIZED = {
  en: {
    title: "Destined Meeting Places by Saju - independent coordinates of connection",
    h1: "Destined Meeting Places by Saju",
    description: "Your Saju energy points toward the places, cities, timing, and small objects where a meaningful connection is most likely to open.",
    seoText: "This reading unfolds the spaces, city moods, seasons, and movement style where your Four Pillars energy can meet the right connection.",
    landingPoints: ["Standalone input flow", "Top 5 meeting-place types", "Country and city recommendations", "KRW 10,000 per reading"],
  },
  ja: {
    title: "四柱推命で見る縁の場所 - ご縁が開く独立運命座標リポート",
    h1: "四柱推命で見る縁の場所",
    description: "あなたの四柱推命の気が、縁の開きやすい場所、国や都市、動くとよい時期、そっと持ちたい運命の小物を指し示します。",
    seoText: "四柱推命の気の流れから、ご縁が届きやすい空間、街のムード、季節、行動スタイルが一つのリポートとして開きます。",
    landingPoints: ["独立入力フォーム", "縁の場所TOP5", "国・都市のおすすめ", "1回10,000ウォン"],
  },
  "zh-CN": {
    title: "四柱看缘分地点 - 独立命运坐标报告",
    h1: "四柱看缘分地点",
    description: "你的四柱能量会指向缘分容易开启的地点、国家与城市、适合行动的时机，以及带来呼应的命运小物。",
    seoText: "沿着四柱气势，可以展开适合相遇的空间类型、城市气质、时节与行动方式，形成一份独立的缘分地点报告。",
    landingPoints: ["独立输入流程", "缘分地点TOP5", "国家/城市推荐", "单次10,000韩元"],
  },
  "zh-TW": {
    title: "四柱看緣分地點 - 獨立命運座標報告",
    h1: "四柱看緣分地點",
    description: "你的四柱能量會指向緣分容易開啟的地點、國家與城市、適合行動的時機，以及帶來呼應的命運小物。",
    seoText: "沿著四柱氣勢，可以展開適合相遇的空間類型、城市氣質、時節與行動方式，形成一份獨立的緣分地點報告。",
    landingPoints: ["獨立輸入流程", "緣分地點TOP5", "國家/城市推薦", "單次10,000韓元"],
  },
  vi: {
    title: "Nơi gặp duyên qua Saju - tọa độ định mệnh độc lập",
    h1: "Nơi gặp duyên qua Saju",
    description: "Năng lượng Saju của bạn chỉ về nơi chốn, quốc gia, thành phố, thời điểm và vật nhỏ dễ mở ra một mối duyên có ý nghĩa.",
    seoText: "Dòng khí Tứ trụ mở ra kiểu không gian, sắc thái thành phố, mùa chuyển động và phong cách hành động nơi duyên lành dễ chạm tới bạn.",
    landingPoints: ["Luồng nhập độc lập", "Top 5 kiểu nơi gặp duyên", "Gợi ý quốc gia/thành phố", "10.000 KRW/lần"],
  },
  hi: {
    title: "Saju से नियत मिलन-स्थान - संबंध के स्वतंत्र भाग्य coordinates",
    h1: "Saju से नियत मिलन-स्थान",
    description: "आपकी Saju ऊर्जा उन जगहों, शहरों, समय और छोटे भाग्य-चिह्नों की ओर संकेत करती है जहाँ meaningful connection खुलने की संभावना अधिक है.",
    seoText: "Four Pillars की ऊर्जा से ऐसे स्थान, शहर का mood, मौसम और चलने का तरीका खुलता है जहाँ सही संबंध आप तक आसानी से पहुँच सकता है.",
    landingPoints: ["स्वतंत्र input flow", "मिलन स्थान TOP 5", "देश और शहर सुझाव", "प्रति reading 10,000 KRW"],
  },
  es: {
    title: "Lugar destinado por Saju - coordenadas independientes del encuentro",
    h1: "Lugar destinado por Saju",
    description: "Tu energía Saju señala lugares, países, ciudades, momentos y pequeños objetos donde una conexión significativa puede abrirse con más facilidad.",
    seoText: "Esta lectura despliega espacios, atmósferas de ciudad, estaciones y estilo de movimiento donde tu energía de Cuatro Pilares puede encontrar una conexión correcta.",
    landingPoints: ["Flujo de entrada independiente", "Top 5 tipos de lugares de encuentro", "Recomendación de país y ciudad", "10.000 KRW por lectura"],
  },
  fr: {
    title: "Lieu de rencontre destiné par Saju - coordonnées indépendantes du lien",
    h1: "Lieu de rencontre destiné par Saju",
    description: "Votre énergie Saju indique les lieux, pays, villes, moments et petits objets où une rencontre significative peut s'ouvrir plus naturellement.",
    seoText: "Cette lecture déploie les espaces, ambiances de ville, saisons et gestes où l'énergie des Quatre Piliers peut rejoindre le bon lien.",
    landingPoints: ["Saisie indépendante", "Top 5 des lieux de rencontre", "Pays et villes recommandés", "10 000 KRW par lecture"],
  },
  de: {
    title: "Schicksalhafter Treffpunkt nach Saju - unabhängige Koordinaten der Verbindung",
    h1: "Schicksalhafter Treffpunkt nach Saju",
    description: "Deine Saju-Energie weist auf Orte, Länder, Städte, Zeitfenster und kleine Schicksalsobjekte hin, an denen eine bedeutsame Verbindung leichter aufgehen kann.",
    seoText: "Diese Lesung entfaltet Räume, Stadtstimmungen, Jahreszeiten und Bewegungsarten, in denen deine Vier-Säulen-Energie der passenden Verbindung begegnen kann.",
    landingPoints: ["Eigenständiger Eingabefluss", "Top 5 Treffpunktarten", "Länder- und Stadtempfehlungen", "10.000 KRW pro Lesung"],
  },
  nl: {
    title: "Bestemde ontmoetingsplek via Saju - onafhankelijke coördinaten van verbinding",
    h1: "Bestemde ontmoetingsplek via Saju",
    description: "Je Saju-energie wijst naar plaatsen, landen, steden, timing en kleine voorwerpen waar een betekenisvolle verbinding gemakkelijker kan openen.",
    seoText: "Deze lezing ontvouwt ruimtes, stadsstemmingen, seizoenen en bewegingsstijl waarin je Vierpijlerenergie de juiste verbinding kan ontmoeten.",
    landingPoints: ["Zelfstandige invoerstroom", "Top 5 ontmoetingsplaatsen", "Land- en stadadvies", "KRW 10.000 per lezing"],
  },
  ms: {
    title: "Tempat Pertemuan Takdir melalui Saju - koordinat hubungan yang berdiri sendiri",
    h1: "Tempat Pertemuan Takdir melalui Saju",
    description: "Tenaga Saju anda menunjuk kepada tempat, negara, bandar, masa dan objek kecil yang lebih mudah membuka hubungan bermakna.",
    seoText: "Bacaan ini membuka jenis ruang, suasana bandar, musim dan gaya bergerak tempat tenaga Empat Tiang anda boleh bertemu hubungan yang tepat.",
    landingPoints: ["Aliran input berdiri sendiri", "Top 5 jenis tempat pertemuan", "Cadangan negara dan bandar", "KRW 10,000 setiap bacaan"],
  },
};

const ASTROLOGY_COSMIC_LOCALIZED = {
  en: {
    title: "Cosmic Astrology Chart - Sun, Moon, and Ascendant reading",
    h1: "Cosmic Astrology Chart",
    description: "Through the Sun, Moon, and Ascendant, your temperament, emotional rhythm, relationship patterns, and outer expression rise in the language of the stars.",
    seoText: "The Cosmic Astrology Chart reads the Sun, Moon, Ascendant, and house emphasis to illuminate inner nature, emotional habits, and the way you meet the world.",
    landingPoints: ["Sun, Moon, and Ascendant reading", "Cosmic-style chart", "Relationship pattern insight"],
  },
  ja: {
    title: "コズミック占星術チャート - 太陽・月・アセンダント分析",
    h1: "コズミック占星術チャート",
    description: "太陽、月、アセンダントを中心に、性質、感情のリズム、関係パターン、外へ見せる表情が星の言葉で浮かび上がります。",
    seoText: "コズミック占星術チャートは、太陽・月・アセンダント・ハウスの強調点を読み、内面の質、感情の癖、世界との向き合い方を照らします。",
    landingPoints: ["太陽・月・アセンダント解釈", "コズミックスタイルチャート", "関係パターン把握"],
  },
  "zh-CN": {
    title: "宇宙占星星盘 - 太阳、月亮与上升分析",
    h1: "宇宙占星星盘",
    description: "太阳、月亮与上升星座会以星辰语言显现你的气质、情绪节奏、关系模式与对外表达。",
    seoText: "宇宙占星星盘读取太阳、月亮、上升与宫位重点，照亮内在性格、情绪习惯，以及你与世界相遇的方式。",
    landingPoints: ["太阳/月亮/上升解读", "宇宙风格星盘", "关系模式洞察"],
  },
  "zh-TW": {
    title: "宇宙占星星盤 - 太陽、月亮與上升分析",
    h1: "宇宙占星星盤",
    description: "太陽、月亮與上升星座會以星辰語言顯現你的氣質、情緒節奏、關係模式與對外表達。",
    seoText: "宇宙占星星盤讀取太陽、月亮、上升與宮位重點，照亮內在性格、情緒習慣，以及你與世界相遇的方式。",
    landingPoints: ["太陽/月亮/上升解讀", "宇宙風格星盤", "關係模式洞察"],
  },
  vi: {
    title: "Bản đồ Chiêm tinh Cosmic - Mặt Trời, Mặt Trăng và Cung mọc",
    h1: "Bản đồ Chiêm tinh Cosmic",
    description: "Qua Mặt Trời, Mặt Trăng và Cung mọc, khí chất, nhịp cảm xúc, mô thức quan hệ và cách bạn bước ra thế giới hiện lên bằng ngôn ngữ các vì sao.",
    seoText: "Bản đồ Chiêm tinh Cosmic đọc Mặt Trời, Mặt Trăng, Cung mọc và trọng tâm nhà để soi sáng bản chất bên trong, thói quen cảm xúc và cách bạn gặp thế giới.",
    landingPoints: ["Đọc Mặt Trời, Mặt Trăng, Cung mọc", "Bản đồ phong cách cosmic", "Nhìn rõ mô thức quan hệ"],
  },
  hi: {
    title: "Cosmic Astrology Chart - सूर्य, चंद्र और Ascendant reading",
    h1: "Cosmic Astrology Chart",
    description: "सूर्य, चंद्र और Ascendant के माध्यम से आपका स्वभाव, भावनात्मक लय, संबंध pattern और बाहरी अभिव्यक्ति सितारों की भाषा में खुलती है.",
    seoText: "Cosmic Astrology Chart सूर्य, चंद्र, Ascendant और house emphasis को पढ़कर inner nature, emotional habits और दुनिया से मिलने का तरीका दिखाता है.",
    landingPoints: ["सूर्य, चंद्र और Ascendant reading", "Cosmic-style chart", "Relationship pattern insight"],
  },
  es: {
    title: "Carta de Astrología Cósmica - Sol, Luna y Ascendente",
    h1: "Carta de Astrología Cósmica",
    description: "A través del Sol, la Luna y el Ascendente, tu temperamento, ritmo emocional, patrones de relación y expresión externa aparecen en el lenguaje de las estrellas.",
    seoText: "La Carta de Astrología Cósmica lee Sol, Luna, Ascendente y énfasis de casas para iluminar naturaleza interior, hábitos emocionales y la forma en que encuentras el mundo.",
    landingPoints: ["Lectura de Sol, Luna y Ascendente", "Carta de estilo cósmico", "Patrones de relación"],
  },
  fr: {
    title: "Carte d'Astrologie cosmique - Soleil, Lune et Ascendant",
    h1: "Carte d'Astrologie cosmique",
    description: "À travers le Soleil, la Lune et l'Ascendant, votre tempérament, votre rythme émotionnel, vos schémas relationnels et votre expression extérieure apparaissent dans la langue des étoiles.",
    seoText: "La Carte d'Astrologie cosmique lit Soleil, Lune, Ascendant et maisons dominantes pour éclairer nature intérieure, habitudes émotionnelles et manière de rencontrer le monde.",
    landingPoints: ["Lecture Soleil, Lune et Ascendant", "Carte au style cosmique", "Schémas relationnels"],
  },
  de: {
    title: "Kosmische Astrologie-Chart - Sonne, Mond und Aszendent",
    h1: "Kosmische Astrologie-Chart",
    description: "Über Sonne, Mond und Aszendent treten Temperament, emotionaler Rhythmus, Beziehungsmuster und äußere Ausstrahlung in der Sprache der Sterne hervor.",
    seoText: "Die kosmische Astrologie-Chart liest Sonne, Mond, Aszendent und Häuserbetonung, um innere Natur, emotionale Gewohnheiten und Begegnung mit der Welt zu beleuchten.",
    landingPoints: ["Sonne, Mond und Aszendent lesen", "Kosmischer Chart-Stil", "Beziehungsmuster erkennen"],
  },
  nl: {
    title: "Kosmische astrologiekaart - Zon, Maan en Ascendant",
    h1: "Kosmische astrologiekaart",
    description: "Via Zon, Maan en Ascendant verschijnen je temperament, emotionele ritme, relatiepatronen en uiterlijke expressie in de taal van de sterren.",
    seoText: "De kosmische astrologiekaart leest Zon, Maan, Ascendant en huisaccenten om innerlijke natuur, emotionele gewoonten en je manier van de wereld ontmoeten te verlichten.",
    landingPoints: ["Zon, Maan en Ascendant lezen", "Kosmische kaartstijl", "Relatiepatronen zien"],
  },
  ms: {
    title: "Carta Astrologi Kosmik - bacaan Matahari, Bulan dan Ascendant",
    h1: "Carta Astrologi Kosmik",
    description: "Melalui Matahari, Bulan dan Ascendant, perangai, rentak emosi, pola hubungan dan ekspresi luar anda muncul dalam bahasa bintang.",
    seoText: "Carta Astrologi Kosmik membaca Matahari, Bulan, Ascendant dan penekanan rumah untuk menerangi sifat dalaman, tabiat emosi dan cara anda menemui dunia.",
    landingPoints: ["Bacaan Matahari, Bulan dan Ascendant", "Carta gaya kosmik", "Pola hubungan"],
  },
};

const ZIWEI_CHART_LOCALIZED = {
  en: {
    title: "Zi Wei Dou Shu 12-Palace Chart - destiny map of the life palace",
    h1: "Zi Wei Dou Shu 12-Palace Chart",
    description: "The Life Palace, major stars, and 12 palaces of Zi Wei Dou Shu open a layered map of temperament, relationships, career, and long-term flow.",
    seoText: "Zi Wei Dou Shu reads the Life Palace, body palace, star combinations, and 12-palace structure to reveal the deeper architecture of destiny.",
    landingPoints: ["12-palace chart structure", "Major star combinations", "Temperament, relationship, and career flow"],
  },
  ja: {
    title: "紫微斗数 十二宮命盤分析 - 命宮から開く運命地図",
    h1: "紫微斗数 十二宮命盤分析",
    description: "紫微斗数の命宮、主要星、十二宮の配置から、性質、関係、仕事、人生の長い流れが立体的に開きます。",
    seoText: "紫微斗数は命宮・身宮・星曜の組み合わせ・十二宮構造を読み、運命の深い設計図を静かに照らします。",
    landingPoints: ["十二宮命盤の構造", "主要星の組み合わせ解釈", "性質・関係・仕事の流れ"],
  },
  "zh-CN": {
    title: "紫微斗数十二宫命盘分析 - 从命宫展开的命运地图",
    h1: "紫微斗数十二宫命盘分析",
    description: "紫微斗数的命宫、主星与十二宫布局，会立体展开性格、关系、事业与人生长线流动。",
    seoText: "紫微斗数读取命宫、身宫、星曜组合与十二宫结构，安静照见命运更深层的架构。",
    landingPoints: ["十二宫命盘结构", "主要星曜组合解读", "性格、关系与事业流动"],
  },
  "zh-TW": {
    title: "紫微斗數十二宮命盤分析 - 從命宮展開的命運地圖",
    h1: "紫微斗數十二宮命盤分析",
    description: "紫微斗數的命宮、主星與十二宮布局，會立體展開性格、關係、事業與人生長線流動。",
    seoText: "紫微斗數讀取命宮、身宮、星曜組合與十二宮結構，安靜照見命運更深層的架構。",
    landingPoints: ["十二宮命盤結構", "主要星曜組合解讀", "性格、關係與事業流動"],
  },
  vi: {
    title: "Lá số Tử Vi Đẩu Số 12 cung - bản đồ vận mệnh từ cung Mệnh",
    h1: "Lá số Tử Vi Đẩu Số 12 cung",
    description: "Cung Mệnh, các chính tinh và bố cục 12 cung của Tử Vi Đẩu Số mở ra bản đồ nhiều lớp về khí chất, quan hệ, nghề nghiệp và dòng đời dài hạn.",
    seoText: "Tử Vi Đẩu Số đọc cung Mệnh, cung Thân, tổ hợp sao và cấu trúc 12 cung để soi sáng kiến trúc sâu hơn của vận mệnh.",
    landingPoints: ["Cấu trúc lá số 12 cung", "Giải tổ hợp chính tinh", "Dòng khí chất, quan hệ và nghề nghiệp"],
  },
  hi: {
    title: "Zi Wei Dou Shu 12-Palace Chart - life palace से खुलता destiny map",
    h1: "Zi Wei Dou Shu 12-Palace Chart",
    description: "Zi Wei Dou Shu का Life Palace, प्रमुख तारे और 12 palaces स्वभाव, संबंध, करियर और दीर्घकालिक जीवन प्रवाह का layered map खोलते हैं.",
    seoText: "Zi Wei Dou Shu Life Palace, body palace, star combinations और 12-palace structure पढ़कर destiny की गहरी architecture दिखाता है.",
    landingPoints: ["12-palace chart structure", "Major star combinations", "Temperament, relationship और career flow"],
  },
  es: {
    title: "Carta Zi Wei Dou Shu de 12 palacios - mapa del destino desde el palacio de vida",
    h1: "Carta Zi Wei Dou Shu de 12 palacios",
    description: "El palacio de vida, las estrellas principales y los 12 palacios de Zi Wei Dou Shu abren un mapa por capas de temperamento, relaciones, carrera y flujo vital.",
    seoText: "Zi Wei Dou Shu lee palacio de vida, palacio del cuerpo, combinaciones estelares y estructura de 12 palacios para revelar la arquitectura profunda del destino.",
    landingPoints: ["Estructura de 12 palacios", "Combinaciones de estrellas principales", "Flujo de temperamento, relaciones y carrera"],
  },
  fr: {
    title: "Thème Zi Wei Dou Shu des 12 palais - carte du destin depuis le palais de vie",
    h1: "Thème Zi Wei Dou Shu des 12 palais",
    description: "Le palais de vie, les étoiles majeures et les 12 palais de Zi Wei Dou Shu ouvrent une carte stratifiée du tempérament, des relations, du métier et du long courant de vie.",
    seoText: "Zi Wei Dou Shu lit le palais de vie, le palais du corps, les combinaisons d'étoiles et la structure des 12 palais pour révéler l'architecture profonde du destin.",
    landingPoints: ["Structure des 12 palais", "Combinaisons d'étoiles majeures", "Flux tempérament, relations et carrière"],
  },
  de: {
    title: "Zi-Wei-Dou-Shu-Chart der 12 Paläste - Schicksalskarte des Lebenspalasts",
    h1: "Zi-Wei-Dou-Shu-Chart der 12 Paläste",
    description: "Lebenspalast, Hauptsterne und die 12 Paläste des Zi Wei Dou Shu öffnen eine vielschichtige Karte von Temperament, Beziehungen, Beruf und langfristigem Lebensfluss.",
    seoText: "Zi Wei Dou Shu liest Lebenspalast, Körperpalast, Sternkombinationen und 12-Palast-Struktur, um die tiefere Architektur des Schicksals zu zeigen.",
    landingPoints: ["12-Palast-Chartstruktur", "Kombinationen der Hauptsterne", "Fluss von Temperament, Beziehung und Beruf"],
  },
  nl: {
    title: "Zi Wei Dou Shu 12-paleizenkaart - bestemmingskaart van het levenspaleis",
    h1: "Zi Wei Dou Shu 12-paleizenkaart",
    description: "Het levenspaleis, de hoofdsterren en de 12 paleizen van Zi Wei Dou Shu openen een gelaagde kaart van temperament, relaties, loopbaan en langetermijnstroom.",
    seoText: "Zi Wei Dou Shu leest levenspaleis, lichaamspaleis, sterrencombinaties en de 12-paleizenstructuur om de diepere architectuur van bestemming zichtbaar te maken.",
    landingPoints: ["Structuur van de 12 paleizen", "Combinaties van hoofdsterren", "Temperament-, relatie- en loopbaanstroom"],
  },
  ms: {
    title: "Carta Zi Wei Dou Shu 12 Istana - peta takdir daripada istana kehidupan",
    h1: "Carta Zi Wei Dou Shu 12 Istana",
    description: "Istana kehidupan, bintang utama dan 12 istana Zi Wei Dou Shu membuka peta berlapis tentang perangai, hubungan, kerjaya dan aliran hidup jangka panjang.",
    seoText: "Zi Wei Dou Shu membaca istana kehidupan, istana tubuh, gabungan bintang dan struktur 12 istana untuk menerangi seni bina takdir yang lebih dalam.",
    landingPoints: ["Struktur carta 12 istana", "Gabungan bintang utama", "Aliran perangai, hubungan dan kerjaya"],
  },
};

export const SERVICE_MAP = {
  "tarot/healing": {
    component: FeatureLandingPage,
    title: "따뜻한 태양 회복 타로 - 마음의 온도를 되찾는 4카드 리딩",
    h1: "따뜻한 태양 회복 타로",
    description:
      "햇살 같은 네 장의 카드로 상처의 이름, 감정의 온도, 다시 따뜻해지는 단서와 오늘의 회복 루틴을 읽습니다.",
    seoText:
      "따뜻한 태양 회복 타로는 지친 마음 위에 새벽빛을 올려놓듯, 감정의 자리와 작은 회복 행동을 정리하는 4카드 리딩입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/healing.webp",
    landingPoints: ["상처의 이름 확인", "감정의 온도 읽기", "오늘 10분 회복 루틴"],
    localized: {
      en: {
        title: "Warm Sun Healing Tarot - a 4-card reading to recover your inner warmth",
        h1: "Warm Sun Healing Tarot",
        description: "Four sunlit cards gently reveal the name of the wound, the temperature of your heart, the first clue of warmth returning, and a small recovery ritual for today.",
        seoText: "Warm Sun Healing Tarot gathers the place of your emotion and one tender action for recovery, like placing dawn light over a tired heart.",
        landingPoints: ["Name the wound", "Read the heart's temperature", "Today’s 10-minute recovery ritual"],
      },
      ja: {
        title: "あたたかな太陽ヒーリングタロット - 心の温度を取り戻す4カードリーディング",
        h1: "あたたかな太陽ヒーリングタロット",
        description: "陽だまりのような4枚のカードが、傷の名前、心の温度、もう一度あたたかくなる手がかり、そして今日できる小さな回復の儀式をやさしく照らします。",
        seoText: "あたたかな太陽ヒーリングタロットは、疲れた心に夜明けの光を置くように、感情の居場所と今日の回復行動を整える4カードリーディングです。",
        landingPoints: ["傷の名前を見つける", "心の温度を読む", "今日10分の回復リチュアル"],
      },
      "zh-CN": {
        title: "暖阳疗愈塔罗 - 找回内心温度的4张牌解读",
        h1: "暖阳疗愈塔罗",
        description: "四张像阳光一样的牌，温柔照见伤口的名字、情绪的温度、重新变暖的线索，以及今天可以完成的小小疗愈仪式。",
        seoText: "暖阳疗愈塔罗像把清晨的光放在疲惫的心上，为你整理情绪的位置与今天可以开始的恢复行动。",
        landingPoints: ["确认伤口的名字", "读取情绪温度", "今天10分钟疗愈仪式"],
      },
      "zh-TW": {
        title: "暖陽療癒塔羅 - 找回內心溫度的4張牌解讀",
        h1: "暖陽療癒塔羅",
        description: "四張像陽光一樣的牌，溫柔照見傷口的名字、情緒的溫度、重新變暖的線索，以及今天可以完成的小小療癒儀式。",
        seoText: "暖陽療癒塔羅像把清晨的光放在疲憊的心上，為你整理情緒的位置與今天可以開始的恢復行動。",
        landingPoints: ["確認傷口的名字", "讀取情緒溫度", "今天10分鐘療癒儀式"],
      },
      vi: {
        title: "Tarot Mặt Trời Hồi Phục - 4 lá để tìm lại hơi ấm trong tim",
        h1: "Tarot Mặt Trời Hồi Phục",
        description: "Bốn lá bài như nắng ấm khẽ gọi tên vết thương, đọc nhiệt độ cảm xúc, hé lộ dấu hiệu ấm lại và trao một nghi thức hồi phục nhỏ cho hôm nay.",
        seoText: "Tarot Mặt Trời Hồi Phục đặt một vệt sáng bình minh lên trái tim mỏi mệt, rồi gom lại nơi cảm xúc đang nằm và một hành động dịu dàng để hồi phục.",
        landingPoints: ["Gọi tên vết thương", "Đọc nhiệt độ cảm xúc", "Nghi thức hồi phục 10 phút hôm nay"],
      },
      hi: {
        title: "गर्म सूर्य उपचार टैरो - मन की ऊष्मा लौटाने वाली 4 कार्ड रीडिंग",
        h1: "गर्म सूर्य उपचार टैरो",
        description: "धूप जैसी चार कार्डें घाव का नाम, मन का तापमान, फिर से गरमाहट लौटने का संकेत और आज का छोटा उपचार अनुष्ठान धीरे से खोलती हैं.",
        seoText: "गर्म सूर्य उपचार टैरो थके हुए मन पर भोर की रोशनी रखने जैसा है, जहाँ भावना की जगह और आज का कोमल उपचार कर्म साफ दिखाई देता है.",
        landingPoints: ["घाव का नाम पहचानें", "मन का तापमान पढ़ें", "आज का 10 मिनट उपचार अनुष्ठान"],
      },
      es: {
        title: "Tarot Sanador del Sol Cálido - lectura de 4 cartas para recuperar tu temperatura interior",
        h1: "Tarot Sanador del Sol Cálido",
        description: "Cuatro cartas como rayos de sol nombran la herida, leen la temperatura emocional, revelan la primera señal de calor que vuelve y ofrecen un pequeño ritual de recuperación para hoy.",
        seoText: "El Tarot Sanador del Sol Cálido ordena el lugar de la emoción y una acción amable para recuperarte, como poner luz de amanecer sobre un corazón cansado.",
        landingPoints: ["Nombrar la herida", "Leer la temperatura emocional", "Ritual de recuperación de 10 minutos"],
      },
      fr: {
        title: "Tarot du Soleil réparateur - 4 cartes pour retrouver la chaleur du coeur",
        h1: "Tarot du Soleil réparateur",
        description: "Quatre cartes baignées de soleil nomment la blessure, lisent la température du coeur, révèlent le premier signe de chaleur qui revient et offrent un petit rituel de réparation pour aujourd'hui.",
        seoText: "Le Tarot du Soleil réparateur dépose une lumière d'aube sur le coeur fatigué et rassemble l'émotion avec un geste doux pour reprendre souffle.",
        landingPoints: ["Nommer la blessure", "Lire la température du coeur", "Rituel de 10 minutes pour aujourd'hui"],
      },
      de: {
        title: "Warmes Sonnen-Heiltarot - eine 4-Karten-Lesung für neue innere Wärme",
        h1: "Warmes Sonnen-Heiltarot",
        description: "Vier sonnenhelle Karten zeigen behutsam den Namen der Wunde, die Temperatur deines Herzens, den ersten Hinweis auf zurückkehrende Wärme und ein kleines Heilritual für heute.",
        seoText: "Das warme Sonnen-Heiltarot legt Morgenlicht auf ein müdes Herz und ordnet den Ort deiner Gefühle mit einer sanften Handlung für heute.",
        landingPoints: ["Die Wunde benennen", "Die Herztemperatur lesen", "10-Minuten-Heilritual für heute"],
      },
      nl: {
        title: "Warme zon healingtarot - 4 kaarten om je innerlijke warmte terug te vinden",
        h1: "Warme zon healingtarot",
        description: "Vier zonovergoten kaarten noemen zacht de wond, lezen de temperatuur van je hart, tonen het eerste teken van terugkerende warmte en geven een klein herstelritueel voor vandaag.",
        seoText: "Warme zon healingtarot legt ochtendlicht op een moe hart en brengt de plek van je emotie samen met één zachte herstelhandeling.",
        landingPoints: ["De wond benoemen", "De temperatuur van je hart lezen", "Herstelritueel van 10 minuten"],
      },
      ms: {
        title: "Tarot Penyembuhan Matahari Hangat - bacaan 4 kad untuk mengembalikan kehangatan hati",
        h1: "Tarot Penyembuhan Matahari Hangat",
        description: "Empat kad seperti cahaya matahari menamakan luka, membaca suhu emosi, membuka tanda awal kehangatan kembali, dan memberi satu ritual pemulihan kecil untuk hari ini.",
        seoText: "Tarot Penyembuhan Matahari Hangat meletakkan cahaya subuh di atas hati yang letih, lalu menyusun tempat emosi dan satu tindakan lembut untuk pulih.",
        landingPoints: ["Namakan luka", "Baca suhu emosi", "Ritual pemulihan 10 minit hari ini"],
      },
    },
    keywords: [
      "힐링 타로",
      "4카드 타로",
      "Sun and Light",
      "회복 타로",
      "무료 타로",
      "타로 리딩",
      "healing tarot spread",
    ],
  },
  "tarot/mingri": {
    component: FeatureLandingPage,
    title: "명리학 타로 - 카드와 십성이 비추는 선택 리딩",
    h1: "명리학 타로 - 카드와 십성이 비추는 선택 리딩",
    description:
      "연애, 재회, 사업, 건강 등 고민 카테고리에 맞춰 한 장 리딩 또는 세 장 흐름으로 오늘의 선택 방향을 읽습니다.",
    seoText:
      "명리학 타로는 카드 상징과 십성의 기운을 연결해 질문의 결, 선택의 속도, 조율할 방향을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20tarrot.webp",
    landingPoints: ["카테고리별 고민 리딩", "한 장 리딩과 세 장 흐름", "십성 조율 문장"],
    localized: {
      en: {
        title: "Myeongri Tarot - choice reading illuminated by cards and Ten Gods",
        h1: "Myeongri Tarot",
        description: "For love, reunion, work, business, and health questions, one-card or three-card flows reveal the direction your choice is leaning toward today.",
        seoText: "Myeongri Tarot connects tarot symbols with the energy of the Ten Gods to clarify the texture of your question, the speed of your choice, and the direction that asks for balance.",
        landingPoints: ["Category-based readings", "One-card and three-card flows", "Ten Gods alignment sentences"],
      },
      ja: {
        title: "命理タロット - カードと十神が照らす選択リーディング",
        h1: "命理タロット",
        description: "恋愛、復縁、仕事、事業、健康などの悩みに合わせて、1枚引きまたは3枚の流れで今日の選択の向きを読みます。",
        seoText: "命理タロットはカードの象徴と十神の気を重ね、問いの質感、選択の速度、整えるべき方向をやさしく浮かび上がらせます。",
        landingPoints: ["悩みカテゴリ別リーディング", "1枚引きと3枚の流れ", "十神で整えるメッセージ"],
      },
      "zh-CN": {
        title: "命理塔罗 - 由牌与十神照亮的选择解读",
        h1: "命理塔罗",
        description: "恋爱、复合、事业、工作、健康等问题，会依照主题以一张牌或三张牌的流动，读出今天选择的方向。",
        seoText: "命理塔罗把塔罗象征与十神之气相连，整理问题的质地、选择的速度，以及需要调和的方向。",
        landingPoints: ["按烦恼类别解读", "一张牌与三张牌流动", "十神调和语句"],
      },
      "zh-TW": {
        title: "命理塔羅 - 由牌與十神照亮的選擇解讀",
        h1: "命理塔羅",
        description: "戀愛、復合、事業、工作、健康等問題，會依照主題以一張牌或三張牌的流動，讀出今天選擇的方向。",
        seoText: "命理塔羅把塔羅象徵與十神之氣相連，整理問題的質地、選擇的速度，以及需要調和的方向。",
        landingPoints: ["按煩惱類別解讀", "一張牌與三張牌流動", "十神調和語句"],
      },
      vi: {
        title: "Myeongri Tarot - bài đọc lựa chọn qua lá bài và Thập Thần",
        h1: "Myeongri Tarot",
        description: "Với tình yêu, tái hợp, công việc, kinh doanh hay sức khỏe, dòng chảy một lá hoặc ba lá sẽ chỉ ra hướng lựa chọn đang nghiêng về hôm nay.",
        seoText: "Myeongri Tarot nối biểu tượng tarot với khí của Thập Thần để làm rõ chất của câu hỏi, nhịp của lựa chọn và hướng cần được cân bằng.",
        landingPoints: ["Đọc theo từng nhóm băn khoăn", "Dòng một lá và ba lá", "Câu điều hòa theo Thập Thần"],
      },
      hi: {
        title: "Myeongri टैरो - कार्ड और दश देवों से प्रकाशित चयन रीडिंग",
        h1: "Myeongri टैरो",
        description: "प्रेम, पुनर्मिलन, काम, व्यवसाय या स्वास्थ्य जैसे प्रश्नों में एक कार्ड या तीन कार्ड की धारा आज की पसंद की दिशा खोलती है.",
        seoText: "Myeongri टैरो कार्ड प्रतीकों को दश देवों की ऊर्जा से जोड़कर प्रश्न की बनावट, चयन की गति और संतुलन की दिशा साफ करता है.",
        landingPoints: ["विषय के अनुसार रीडिंग", "एक कार्ड और तीन कार्ड की धारा", "दश देवों से संतुलन वाक्य"],
      },
      es: {
        title: "Tarot Myeongri - lectura de elección iluminada por cartas y Diez Dioses",
        h1: "Tarot Myeongri",
        description: "Para amor, reencuentro, trabajo, negocio o salud, una carta o un flujo de tres cartas revela hacia dónde se inclina la elección de hoy.",
        seoText: "Tarot Myeongri conecta los símbolos de las cartas con la energía de los Diez Dioses para ordenar la textura de la pregunta, el ritmo de la elección y la dirección que pide equilibrio.",
        landingPoints: ["Lectura por categoría", "Flujo de una y tres cartas", "Frases de ajuste con Diez Dioses"],
      },
      fr: {
        title: "Tarot Myeongri - lecture de choix éclairée par les cartes et les Dix Dieux",
        h1: "Tarot Myeongri",
        description: "Pour l'amour, le retour, le travail, les affaires ou la santé, une carte ou un flux de trois cartes révèle l'orientation du choix d'aujourd'hui.",
        seoText: "Le Tarot Myeongri relie les symboles des cartes à l'énergie des Dix Dieux pour clarifier la texture de la question, le rythme du choix et la direction à harmoniser.",
        landingPoints: ["Lecture par catégorie", "Flux d'une carte ou de trois cartes", "Phrase d'accord avec les Dix Dieux"],
      },
      de: {
        title: "Myeongri-Tarot - Wahllegung im Licht von Karten und Zehn Göttern",
        h1: "Myeongri-Tarot",
        description: "Für Liebe, Wiederkehr, Arbeit, Geschäft oder Gesundheit zeigt eine Ein-Karten- oder Drei-Karten-Strömung, wohin deine heutige Wahl tendiert.",
        seoText: "Myeongri-Tarot verbindet Kartensymbole mit der Energie der Zehn Götter und ordnet die Textur der Frage, das Tempo der Wahl und die Richtung des Ausgleichs.",
        landingPoints: ["Lesung nach Anliegen", "Ein-Karten- und Drei-Karten-Fluss", "Ausgleichssätze der Zehn Götter"],
      },
      nl: {
        title: "Myeongri Tarot - keuzelezing verlicht door kaarten en Ten Gods",
        h1: "Myeongri Tarot",
        description: "Voor liefde, hereniging, werk, zaken of gezondheid laat een éénkaart- of driekaartenstroom zien waar je keuze vandaag naartoe neigt.",
        seoText: "Myeongri Tarot verbindt kaartsymboliek met de energie van Ten Gods en ordent de textuur van de vraag, het tempo van de keuze en de richting die om balans vraagt.",
        landingPoints: ["Lezing per vraagcategorie", "Eénkaart- en driekaartenstroom", "Afstemmingszinnen met Ten Gods"],
      },
      ms: {
        title: "Myeongri Tarot - bacaan pilihan yang diterangi kad dan Ten Gods",
        h1: "Myeongri Tarot",
        description: "Untuk cinta, pertemuan semula, kerja, perniagaan atau kesihatan, aliran satu kad atau tiga kad membuka arah pilihan hari ini.",
        seoText: "Myeongri Tarot menghubungkan simbol kad dengan tenaga Ten Gods untuk menjelaskan rasa soalan, rentak pilihan dan arah yang meminta keseimbangan.",
        landingPoints: ["Bacaan ikut kategori persoalan", "Aliran satu kad dan tiga kad", "Ayat penyelarasan Ten Gods"],
      },
    },
    keywords: [
      "명리학 타로",
      "78장 타로",
      "유니버설 덱",
      "한 장 타로",
      "세 장 타로",
      "십성 타로",
      "mingri tarot",
    ],
  },
  "tarot/love": {
    component: FeatureLandingPage,
    title: "우리는 무슨 사이? - 둘 사이의 이름과 속도",
    h1: "우리는 무슨 사이?",
    description:
      "그 사람의 말과 행동 사이에 남은 온도, 망설임, 관계의 이름과 지금 건네도 좋은 말을 6장의 카드로 읽습니다.",
    seoText:
      "우리는 무슨 사이 타로는 서로의 시선, 감정 온도, 현실 변수, 다음 대화의 선을 분리해 읽는 관계 특화 6카드 리딩입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tarolove.webp",
    landingPoints: ["서로 다른 시선 분리", "상대의 감정 온도", "건네도 좋은 말"],
    localized: {
      en: {
        title: "What Are We? - the name and pace between two hearts",
        h1: "What Are We?",
        description: "Six cards read the warmth left between words and actions, the hesitation, the name of the relationship, and the sentence you may safely offer now.",
        seoText: "What Are We? separates each point of view, the emotional temperature, real-world variables, and the next line of conversation in a relationship-focused 6-card reading.",
        landingPoints: ["Separate both viewpoints", "Read their emotional temperature", "Find words you can offer"],
      },
      ja: {
        title: "私たちはどんな関係？ - ふたりの名前と速度",
        h1: "私たちはどんな関係？",
        description: "その人の言葉と行動のあいだに残る温度、ためらい、関係の名前、そして今そっと差し出してもよい言葉を6枚のカードで読みます。",
        seoText: "私たちはどんな関係？タロットは、ふたりの視線、感情の温度、現実の波、次に交わす言葉の線を分けて読む恋愛特化の6カードリーディングです。",
        landingPoints: ["ふたりの視線を分ける", "相手の感情温度を読む", "今届けてもよい言葉"],
      },
      "zh-CN": {
        title: "我们是什么关系？- 两个人之间的名字与速度",
        h1: "我们是什么关系？",
        description: "六张牌读出对方言行之间残留的温度、犹豫、关系的名字，以及现在可以温柔递出的那句话。",
        seoText: "我们是什么关系塔罗，会分开阅读彼此视角、情绪温度、现实变量与下一次对话的界线，是偏向关系的6张牌解读。",
        landingPoints: ["分开彼此视角", "读取对方情绪温度", "找到可以递出的那句话"],
      },
      "zh-TW": {
        title: "我們是什麼關係？- 兩個人之間的名字與速度",
        h1: "我們是什麼關係？",
        description: "六張牌讀出對方言行之間殘留的溫度、猶豫、關係的名字，以及現在可以溫柔遞出的那句話。",
        seoText: "我們是什麼關係塔羅，會分開閱讀彼此視角、情緒溫度、現實變數與下一次對話的界線，是偏向關係的6張牌解讀。",
        landingPoints: ["分開彼此視角", "讀取對方情緒溫度", "找到可以遞出的那句話"],
      },
      vi: {
        title: "Chúng ta là gì của nhau? - tên gọi và nhịp độ giữa hai trái tim",
        h1: "Chúng ta là gì của nhau?",
        description: "Sáu lá bài đọc hơi ấm còn lại giữa lời nói và hành động, sự ngập ngừng, tên gọi của mối quan hệ và câu nói bạn có thể trao đi lúc này.",
        seoText: "Chúng ta là gì của nhau? tách riêng góc nhìn hai người, nhiệt độ cảm xúc, biến số thực tế và đường ranh của cuộc trò chuyện tiếp theo trong một trải bài 6 lá về quan hệ.",
        landingPoints: ["Tách hai góc nhìn", "Đọc nhiệt độ cảm xúc của người ấy", "Tìm câu nói có thể trao đi"],
      },
      hi: {
        title: "हमारा रिश्ता क्या है? - दो दिलों के बीच नाम और गति",
        h1: "हमारा रिश्ता क्या है?",
        description: "छह कार्ड शब्दों और व्यवहार के बीच बची ऊष्मा, झिझक, रिश्ते का नाम और अभी सुरक्षित रूप से कही जा सकने वाली पंक्ति पढ़ते हैं.",
        seoText: "हमारा रिश्ता क्या है? दोनों दृष्टियों, भावनात्मक तापमान, वास्तविक बाधाओं और अगली बातचीत की रेखा को अलग-अलग पढ़ने वाली 6 कार्ड प्रेम रीडिंग है.",
        landingPoints: ["दोनों दृष्टियों को अलग करें", "उसके मन का तापमान पढ़ें", "कहने योग्य शब्द खोजें"],
      },
      es: {
        title: "¿Qué somos? - el nombre y el ritmo entre dos corazones",
        h1: "¿Qué somos?",
        description: "Seis cartas leen la temperatura que queda entre palabras y actos, la duda, el nombre de la relación y la frase que puedes ofrecer ahora sin romper el equilibrio.",
        seoText: "¿Qué somos? separa las dos miradas, la temperatura emocional, las variables reales y la próxima línea de conversación en una lectura de relación de 6 cartas.",
        landingPoints: ["Separar ambas miradas", "Leer su temperatura emocional", "Encontrar palabras seguras"],
      },
      fr: {
        title: "Que sommes-nous ? - le nom et le rythme entre deux coeurs",
        h1: "Que sommes-nous ?",
        description: "Six cartes lisent la chaleur restée entre les mots et les gestes, l'hésitation, le nom du lien et la phrase que vous pouvez offrir maintenant avec douceur.",
        seoText: "Que sommes-nous ? sépare les deux regards, la température émotionnelle, les variables réelles et la prochaine ligne de dialogue dans une lecture relationnelle en 6 cartes.",
        landingPoints: ["Séparer les deux regards", "Lire sa température émotionnelle", "Trouver les mots à offrir"],
      },
      de: {
        title: "Was sind wir? - Name und Tempo zwischen zwei Herzen",
        h1: "Was sind wir?",
        description: "Sechs Karten lesen die Wärme zwischen Worten und Taten, das Zögern, den Namen der Beziehung und den Satz, den du jetzt sicher anbieten kannst.",
        seoText: "Was sind wir? trennt beide Blickwinkel, die emotionale Temperatur, reale Variablen und die nächste Gesprächslinie in einer 6-Karten-Beziehungslegung.",
        landingPoints: ["Beide Blickwinkel trennen", "Die emotionale Temperatur lesen", "Worte finden, die du geben kannst"],
      },
      nl: {
        title: "Wat zijn wij? - de naam en het tempo tussen twee harten",
        h1: "Wat zijn wij?",
        description: "Zes kaarten lezen de warmte tussen woorden en daden, de aarzeling, de naam van de relatie en de zin die je nu veilig kunt aanbieden.",
        seoText: "Wat zijn wij? scheidt beide perspectieven, de emotionele temperatuur, echte variabelen en de volgende gesprekslijn in een relatiegerichte 6-kaartenlezing.",
        landingPoints: ["Beide perspectieven scheiden", "Hun emotionele temperatuur lezen", "Woorden vinden die je kunt geven"],
      },
      ms: {
        title: "Apakah hubungan kita? - nama dan rentak antara dua hati",
        h1: "Apakah hubungan kita?",
        description: "Enam kad membaca kehangatan yang tinggal antara kata dan tindakan, keraguan, nama hubungan, dan ayat yang boleh anda hulurkan dengan selamat sekarang.",
        seoText: "Apakah hubungan kita? memisahkan dua sudut pandang, suhu emosi, pemboleh ubah nyata dan baris perbualan seterusnya dalam bacaan hubungan 6 kad.",
        landingPoints: ["Pisahkan dua sudut pandang", "Baca suhu emosi dirinya", "Cari kata yang boleh dihulurkan"],
      },
    },
    keywords: [
      "우리는 무슨 사이",
      "6카드 타로",
      "연애 타로",
      "관계 타로",
      "relationship six card",
      "연애 궁합",
    ],
  },
  "saju/basic": {
    component: FeatureLandingPage,
    title: "사주 만세력 기본 해석 - 오행·십성·명식 분석",
    h1: "사주 만세력 기본 해석",
    description:
      "생년월일시로 열린 사주 명식 속에서 오행의 균형과 십성의 흐름이 차분히 드러납니다.",
    seoText:
      "사주 만세력은 사주팔자, 오행, 십성, 시간의 흐름을 따라 성향과 관계, 일의 결, 전환점을 읽습니다.",
    ogImage: "/fuctionassets/saju.webp",
    landingPoints: ["사주팔자 명식 생성", "오행 균형 분석", "십성 흐름 해석"],
    localized: SAJU_BASIC_LOCALIZED,
  },
  "saju/destiny-bias": {
    component: FeatureLandingPage,
    title: "최애운명 - 사주 기반 팬덤 공명 분석",
    h1: "최애운명",
    description:
      "나의 사주 기운과 최애의 상징 에너지가 나란히 놓이며, 공명 점수와 오행 보완, 십성 역할, 오늘의 작은 액션이 카드처럼 떠오릅니다.",
    seoText:
      "최애운명은 팬덤의 애정을 사주 공명으로 읽어, 나의 오행 리듬이 소중한 존재의 상징과 어떻게 울리는지 비춥니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EC%B5%9C%EC%95%A0%EC%9A%B4%EB%AA%85.webp",
    landingPoints: ["내 사주 × 최애 사주 공명 점수", "오행 보완/십성 역할 제안", "1회 5,000원 분석 카드"],
    localized: DESTINY_BIAS_LOCALIZED,
    keywords: [
      "최애운명",
      "팬덤 사주",
      "사주 공명",
      "덕질 운세",
      "bias destiny",
      "k-fandom saju",
    ],
  },
  "saju/animal-destiny": {
    component: FeatureLandingPage,
    title: "사주 가디언 아트 - 내 사주 수호동물 테스트",
    h1: "사주 가디언 아트",
    description:
      "일간, 월지, 오행 균형, 십성 흐름이 나만의 수호동물 카드와 수호력, 경고 메시지, 관계의 조화를 불러냅니다.",
    seoText:
      "사주 가디언 아트는 명식 안에 숨어 있는 보호 스타일을 읽어, 저장하고 나눌 수 있는 수호동물 카드로 비춥니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EB%8F%99%EB%AC%BC%EC%A0%90%ED%85%8C%EC%8A%A4%ED%8A%B8.webp",
    landingPoints: ["일간·월지·오행 기반 배정", "고정 2D 수호동물 카드", "사주 근거 + 오늘의 메시지", "공유 카드 저장"],
    localized: SAJU_GUARDIAN_LOCALIZED,
    keywords: [
      "사주 가디언",
      "수호동물",
      "사주 수호동물 테스트",
      "animal destiny",
      "guardian animal",
    ],
  },
  "saju/animal-test": {
    component: FeatureLandingPage,
    title: "사주 가디언 아트 - 내 사주 수호동물 테스트",
    h1: "사주 가디언 아트",
    description:
      "일간, 월지, 오행 균형, 십성 흐름이 나만의 수호동물 카드와 수호력, 경고 메시지, 관계의 조화를 불러냅니다.",
    seoText:
      "사주 가디언 아트는 명식 안에 숨어 있는 보호 스타일을 읽어, 저장하고 나눌 수 있는 수호동물 카드로 비춥니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EB%8F%99%EB%AC%BC%EC%A0%90%ED%85%8C%EC%8A%A4%ED%8A%B8.webp",
    landingPoints: ["일간·월지·오행 기반 배정", "고정 2D 수호동물 카드", "사주 근거 + 오늘의 메시지", "공유 카드 저장"],
    localized: SAJU_GUARDIAN_LOCALIZED,
    keywords: [
      "사주 가디언",
      "수호동물",
      "사주 수호동물 테스트",
      "animal destiny",
      "guardian animal",
    ],
  },
  "saju/destiny-meeting-place": {
    component: FeatureLandingPage,
    title: "사주로 보는 인연의 장소 - 독립 운명 좌표 리포트",
    h1: "사주로 보는 인연의 장소",
    description:
      "생년월일 기반 사주 에너지가 인연이 열리기 쉬운 장소, 국가와 도시, 움직이기 좋은 때, 운명의 작은 물건을 가리킵니다.",
    seoText:
      "사주 에너지 위로 인연이 닿기 쉬운 장소, 도시의 무드, 움직이기 좋은 때가 독립된 리포트로 펼쳐집니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EC%82%AC%EC%A3%BC%EB%A1%9C%EB%B3%B4%EB%8A%94%20%EC%9D%B8%EC%97%B0%EC%9D%98%20%EC%9E%A5%EC%86%8C.webp",
    landingPoints: ["독립 실행 입력 폼", "인연 장소 TOP 5", "국가/도시 추천", "1회 10,000원"],
    localized: DESTINY_MEETING_PLACE_LOCALIZED,
    keywords: [
      "사주로 보는 인연의 장소",
      "인연 장소 추천",
      "사주 장소 운세",
      "meeting place saju",
      "destiny meeting place",
    ],
  },
  "astrology/cosmic": {
    component: FeatureLandingPage,
    title: "점성술 코즈믹 차트 - 태양·달·상승궁 분석",
    h1: "점성술 코즈믹 차트",
    description:
      "태양궁, 달궁, 상승궁을 중심으로 당신의 성향과 관계 패턴이 별자리의 언어로 드러납니다.",
    seoText:
      "점성술 코즈믹 차트는 태양, 달, 상승궁과 하우스의 강조점을 따라 내면의 결, 감정 습관, 세상과 만나는 방식을 비춥니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jumsung.webp",
    landingPoints: ["태양궁·달궁·상승궁 해석", "코즈믹 스타일 차트", "관계 패턴 파악"],
    localized: ASTROLOGY_COSMIC_LOCALIZED,
    keywords: [
      "점성술",
      "코즈믹 차트",
      "태양궁",
      "달궁",
      "상승궁",
      "서양 점성술",
      "natal chart",
      "astrology chart",
    ],
  },
  "ziwei/chart": {
    component: FeatureLandingPage,
    title: "자미두수 12궁 명반 분석 - Ziwei Doushu",
    h1: "자미두수 12궁 명반 분석",
    description:
      "자미두수(紫微斗數)의 명궁과 주요 성군, 12궁 배치 위로 삶의 결이 입체적으로 열립니다.",
    seoText:
      "자미두수는 명궁, 신궁, 성요 조합과 12궁 구조를 따라 운명의 깊은 설계도를 조용히 비춥니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jami.webp",
    landingPoints: ["12궁 명반 구조 도식", "주요 성군 조합 해석", "성향·관계·진로 흐름 파악"],
    localized: ZIWEI_CHART_LOCALIZED,
    keywords: [
      "자미두수",
      "紫微斗數",
      "12궁",
      "명반",
      "Zi Wei Dou Shu",
      "ziwei chart",
    ],
  },
  "animal/physio": {
    component: FeatureLandingPage,
    title: "전문가 동물 관상 - 셀카 얼굴 분석",
    h1: "전문가 동물 관상",
    description: "셀카에 담긴 얼굴형과 인상의 결에서 성향과 분위기의 흐름을 읽습니다.",
    seoText: "전문가 동물 관상에서는 얼굴 이미지 위로 동물상 비유와 해석의 포인트가 자연스럽게 떠오릅니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20animal.webp",
    landingPoints: ["셀카 기반 얼굴형 분석", "동물상 비유 해석", "가볍게 즐기는 성향 리포트"],
    localized: {
      en: {
        title: "AI Animal Face Reading - selfie-based face analysis",
        h1: "AI Animal Face Reading",
        description: "The shape and impression held in your selfie are read as a gentle flow of temperament and aura.",
        seoText: "AI Animal Face Reading brings animal archetype metaphors and key interpretation points to the surface of your face image.",
        landingPoints: ["Selfie-based face analysis", "Animal archetype interpretation", "Light temperament report"],
      },
    },
    keywords: [
      "전문가 동물 관상",
      "관상",
      "얼굴형 분석",
      "셀카 관상",
      "동물상",
      "physiognomy",
    ],
  },
  "animal/mbti": {
    component: FeatureLandingPage,
    title: "MBTI 동물 궁합 - 16가지 토템 케미",
    h1: "MBTI 동물 궁합",
    description: "MBTI 성향 조합을 동물 토템의 상징으로 비추어 관계의 케미와 소통 결을 읽습니다.",
    seoText: "MBTI 동물 궁합에서는 16유형 조합 속 관계 포인트와 소통의 결이 동물 토템처럼 선명하게 드러납니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20face.webp",
    landingPoints: ["16유형 조합 분석", "연애/친구 케미 포인트", "관계 소통 팁"],
    localized: {
      en: {
        title: "MBTI Animal Compatibility - sixteen totem chemistry types",
        h1: "MBTI Animal Compatibility",
        description: "MBTI combinations are reflected through animal totem symbols, revealing relationship chemistry and communication texture.",
        seoText: "MBTI Animal Compatibility shows relationship points and communication rhythms inside the sixteen type combinations with animal totem clarity.",
        landingPoints: ["Sixteen-type combination analysis", "Love and friendship chemistry points", "Relationship communication tips"],
      },
    },
    keywords: [
      "MBTI 궁합",
      "MBTI 동물",
      "16가지 유형",
      "연애 궁합",
      "MBTI compatibility",
    ],
  },
  "animal/totem": {
    component: FeatureLandingPage,
    title: "애니멀 토템 카드 리딩",
    h1: "애니멀 토템 리딩",
    description: "지금 곁에 머무는 수호 동물의 메시지가 카드 리딩처럼 경고와 행운의 방향을 비춥니다.",
    seoText: "애니멀 토템은 지금의 감정 상태와 방향성을 상징 메시지로 풀어줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/animaltotem.webp",
    landingPoints: ["수호 동물 메시지", "카드 기반 직관 리딩", "현재 상태 점검"],
    localized: {
      en: {
        title: "Animal Totem Card Reading",
        h1: "Animal Totem Reading",
        description: "The message of the guardian animal beside you now shines like a card reading, pointing toward warning and luck.",
        seoText: "Animal Totem translates your current emotional state and direction into symbolic guidance.",
        landingPoints: ["Guardian animal message", "Card-based intuitive reading", "Current-state check"],
      },
    },
    keywords: [
      "애니멀 토템",
      "토템 카드",
      "수호 동물",
      "animal totem",
      "토템 리딩",
    ],
  },
  "tarot/self-esteem": {
    component: FeatureLandingPage,
    title: "자존감 레벨업 타로 - 나를 다시 세우는 5카드",
    h1: "자존감 레벨업 타로",
    description: "눈치를 보게 되는 마음의 패턴, 아직 남아 있는 강점, 오늘 회복할 수 있는 작은 미션을 5장의 카드로 읽습니다.",
    seoText: "자존감 레벨업 타로는 낮아진 자기 확신을 부드럽게 회복하도록 내면의 강점과 오늘의 실천 문장을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jajongam.webp",
    landingPoints: ["눈치 보는 패턴", "내면의 강점 확인", "오늘의 회복 미션"],
    localized: {
      en: {
        title: "Self-Esteem Level-Up Tarot - five cards to rebuild yourself",
        h1: "Self-Esteem Level-Up Tarot",
        description: "Five cards read the pattern that makes you shrink, the strengths still alive within you, and a small mission you can recover today.",
        seoText: "Self-Esteem Level-Up Tarot gathers your inner strengths and today’s practice sentence so softened confidence can rise again.",
        landingPoints: ["People-pleasing pattern", "Inner strength check", "Today’s recovery mission"],
      },
    },
    keywords: [
      "자존감 타로",
      "5카드 타로",
      "자존감 회복 타로",
      "self esteem tarot",
      "성장 타로",
    ],
  },
  "tarot/reunion": {
    component: FeatureLandingPage,
    title: "재회운 등대 타로 - 다시 닿아도 안전한 거리",
    h1: "재회운 등대 타로",
    description: "그리움과 현실 사이에서 다시 닿아도 무너지지 않을 거리, 타이밍, 첫 문장을 5장의 카드로 읽습니다.",
    seoText: "재회운 등대 타로는 남은 마음의 온도와 연락을 막는 현실 파도를 분리해, 다시 닿기 전의 안전 기준을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/reunion.webp",
    landingPoints: ["남은 마음의 온도", "연락을 막는 파도", "부담 없는 첫 문장"],
    localized: {
      en: {
        title: "Reunion Lighthouse Tarot - a safe distance before reaching out again",
        h1: "Reunion Lighthouse Tarot",
        description: "Five cards read the safe distance, timing, and first sentence between longing and reality before you reach out again.",
        seoText: "Reunion Lighthouse Tarot separates the warmth that remains from the real waves blocking contact, then clarifies a safe standard before reconnecting.",
        landingPoints: ["Temperature of remaining feelings", "Waves blocking contact", "A gentle first sentence"],
      },
    },
    keywords: [
      "재회운 타로",
      "재회 타로",
      "5카드 스프레드",
      "연애 재회",
      "reunion tarot",
    ],
  },
  "tarot/year": {
    component: FeatureLandingPage,
    title: "십이지신 천운 타로 - 1년의 방향과 전환점",
    h1: "십이지신 천운 타로",
    description: "열두 수호 기운과 12장의 카드를 엮어 올해의 핵심 카드, 월별 흐름, 분야별 운세와 전환점을 읽습니다.",
    seoText: "십이지신 천운 타로는 타로 카드와 동양적 수호 상징을 연결해 한 해의 선택 기준과 현실적인 행운 행동을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/12animals.webp",
    landingPoints: ["올해의 핵심 카드와 1년 총운", "1월부터 12월까지 월별 리딩", "금전·일·관계·건강·성장운", "전환점과 행운 행동"],
    localized: {
      en: {
        title: "Twelve Zodiac Heavenly Luck Tarot - your yearly direction",
        h1: "Twelve Zodiac Heavenly Luck Tarot",
        description: "Twelve guardian energies and cards reveal the year's core theme, monthly flow, category guidance, and turning points.",
        seoText: "Twelve Zodiac Heavenly Luck Tarot connects eastern guardian symbols with tarot to turn the year's choices into a practical direction guide.",
        landingPoints: ["Core card and yearly overview", "Twelve monthly readings", "Money, work, love, health, and growth", "Turning points and lucky actions"],
      },
    },
    keywords: [
      "십이지신",
      "천운 타로",
      "12개월 운세",
      "연간 운세",
      "zodiac year tarot",
    ],
  },
  "oracle/hwatu": {
    component: FeatureLandingPage,
    title: "타짜들의 화투점 - 12달 화투패 운세",
    h1: "타짜들의 화투점",
    description: "화투 상징 위로 월별 운세의 기세와 조심해야 할 흐름이 또렷하게 떠오릅니다.",
    seoText: "화투점은 한국 전통 상징을 현대적으로 해석한 운세 콘텐츠입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tazza.webp",
    landingPoints: ["전통 화투 상징 해석", "12달 흐름 점검", "간편 운세 콘텐츠"],
    localized: {
      en: {
        title: "Hwatu Oracle of Gamblers - twelve-month card fortune",
        h1: "Hwatu Oracle",
        description: "Korean hwatu symbols reveal the force of each month and the currents you may want to watch with care.",
        seoText: "Hwatu Oracle is a modern fortune reading experience based on traditional Korean card symbols.",
        landingPoints: ["Traditional hwatu symbol reading", "Twelve-month flow check", "Simple fortune content"],
      },
    },
    keywords: [
      "화투점",
      "타짜 화투",
      "12달 운세",
      "한국 전통 운세",
      "hwatu fortune",
    ],
  },
  "oracle/kemet": {
    component: FeatureLandingPage,
    title: "고대 이집트 신탁 - 케멧 오라클",
    h1: "고대 이집트 신탁",
    description: "케멧 오라클의 상징이 질문 속에 숨어 있던 메시지와 지금 필요한 응답을 비춥니다.",
    seoText: "이집트 신탁에서는 케멧의 상징이 질문에 응답하며, 지금 붙잡아야 할 메시지를 조용히 비춥니다.",
    ogImage: "https://code-destiny.com/fuctionassets/egypt.webp",
    landingPoints: ["오라클 상징 리딩", "질문 중심 해석", "직관 메시지"],
    localized: {
      en: {
        title: "Ancient Egyptian Oracle - Kemet Oracle",
        h1: "Ancient Egyptian Oracle",
        description: "The symbols of the Kemet Oracle illuminate the message hidden inside your question and the answer you need now.",
        seoText: "In the Egyptian Oracle, Kemet symbols respond to your question and quietly reveal the message to hold onto now.",
        landingPoints: ["Oracle symbol reading", "Question-centered interpretation", "Intuitive message"],
      },
    },
    keywords: [
      "이집트 신탁",
      "케멧 오라클",
      "Kemet Oracle",
      "고대 이집트",
      "oracle reading",
    ],
  },
  "oracle/juyuk": {
    component: FeatureLandingPage,
    title: "주역 거북점 - 64괘 해석",
    h1: "주역 거북점",
    description: "주역 64괘의 상징 체계가 지금의 흐름과 선택 앞에 놓인 기미를 차분히 가리킵니다.",
    seoText: "주역 거북점에서는 고전 괘상의 흐름을 따라 선택 앞에 놓인 의사결정의 힌트가 드러납니다.",
    ogImage: "https://code-destiny.com/fuctionassets/juyuk.webp",
    landingPoints: ["64괘 상징 해석", "상황 판단 힌트", "고전 기반 리딩"],
    localized: {
      en: {
        title: "I Ching Turtle Oracle - sixty-four hexagram reading",
        h1: "I Ching Turtle Oracle",
        description: "The symbolic system of the sixty-four I Ching hexagrams calmly points to the signs surrounding your present flow and choice.",
        seoText: "I Ching Turtle Oracle follows the classical hexagram flow to reveal decision-making hints before a choice.",
        landingPoints: ["Sixty-four hexagram symbolism", "Situation judgment hint", "Classical oracle reading"],
      },
    },
    keywords: [
      "주역",
      "64괘",
      "거북점",
      "I Ching",
      "역점",
    ],
  },
  "oracle/sukuyo": {
    component: FeatureLandingPage,
    title: "숙요 인연 레이더 | Code Destiny",
    h1: "숙요 인연 레이더",
    description: "상대의 생년월일로 나와의 숙요 관계를 분석하고, 끌림·안정감·소모도·장기 인연 가능성부터 오래된 인연처럼 남는 여운까지 확인해보세요.",
    seoText: "숙요 인연 레이더는 두 사람의 본명숙과 27숙 관계를 바탕으로 끌림, 안정감, 소모도, 장기 인연 가능성을 비춥니다. 여기에 내 숙과 상대 숙의 기질을 겹쳐 처음부터 낯설지 않았던 이유, 반복되는 감정 패턴, 미완의 숙제까지 함께 읽습니다.",
    ogImage: "https://code-destiny.com/fuctionassets/sukyo.webp",
    landingPoints: ["27숙 관계 타입", "인연 레이더 9지수", "내 숙 × 상대 숙 개인 해설", "관계 목적별 조언과 30일 실행 플랜"],
    localized: {
      en: {
        title: "Sukuyo Bond Radar | Code Destiny",
        h1: "Sukuyo Bond Radar",
        description: "Enter the other person’s birth date to read your Sukuyo relationship, attraction, stability, energy drain, and long-term bond potential.",
        seoText: "Sukuyo Bond Radar uses each person’s birth mansion and the twenty-seven mansion relationship to reveal attraction, stability, drain, and long-term bond potential.",
        landingPoints: ["Twenty-seven mansion relationship type", "Bond radar index", "Advice by relationship purpose"],
      },
    },
    keywords: [
      "숙요점",
      "숙요 궁합",
      "27숙",
      "안괴",
      "영친",
      "업태",
      "우쇠",
      "성위",
      "인연 분석",
      "연애 궁합",
    ],
  },
  "oracle/rune": {
    componentKey: "stonehengeRune",
    title: "스톤헨지 룬 오라클 - Stonehenge Rune",
    h1: "스톤헨지 룬 오라클",
    description: "고대 룬 상징으로 현재 흐름과 연간 운세를 읽는 스톤헨지 룬 신탁 서비스입니다.",
    seoText: "스톤헨지 룬 오라클에서는 1/3/5/12 룬 스프레드 위로 상황별 통찰과 실행 힌트가 떠오릅니다.",
    ogImage: "https://code-destiny.com/fuctionassets/rune.webp",
    landingPoints: ["1/3/5/12 룬 스프레드", "정·역방향 룬 해석", "연간 흐름 리딩"],
    localized: {
      en: {
        title: "Stonehenge Rune Oracle",
        h1: "Stonehenge Rune Oracle",
        description: "Ancient rune symbols read your present flow and yearly fortune through the Stonehenge Rune oracle.",
        seoText: "Stonehenge Rune Oracle brings situational insight and action hints through 1, 3, 5, and 12-rune spreads.",
        landingPoints: ["1, 3, 5, and 12-rune spreads", "Upright and reversed rune meanings", "Yearly flow reading"],
      },
    },
    keywords: [
      "룬 점",
      "스톤헨지 룬",
      "Rune Oracle",
      "북유럽 룬",
      "rune reading",
    ],
  },
  "vedic/jyotish": {
    component: FeatureLandingPage,
    title: "베다 점성술 - Jyotish 차트",
    h1: "베다 점성술 (Jyotish)",
    description: "낙샤트라와 다샤의 흐름 위로 인생의 긴 주기와 전환의 실마리가 드러납니다.",
    seoText: "베다 점성술은 인도 점성술 전통의 별자리·주기 체계를 해석에 활용합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/veda.webp",
    landingPoints: ["낙샤트라/다샤 해석", "베다 전통 차트", "장기 흐름 점검"],
    localized: {
      en: {
        title: "Vedic Astrology - Jyotish Chart",
        h1: "Vedic Astrology (Jyotish)",
        description: "Nakshatra and dasha currents reveal long life cycles and the threads of coming transitions.",
        seoText: "Vedic Astrology uses the constellation and cycle systems of Indian astrological tradition for interpretation.",
        landingPoints: ["Nakshatra and dasha reading", "Traditional Vedic chart", "Long-term flow check"],
      },
    },
    keywords: [
      "베다 점성술",
      "Jyotish",
      "자이오티시",
      "낙샤트라",
      "다샤",
      "vedic astrology",
    ],
  },
  "flower": {
    component: FeatureLandingPage,
    title: "운명의 꽃 - 통합 아틀리에",
    h1: "운명의 꽃 아틀리에",
    description: "사주의 오행과 십성, 점성술의 행성 배치, 자미두수의 명궁, 숙요점의 27수 — 네 학문이 각각 짚어낸 기운을 소스 탭으로 넘겨 보며, 나만의 운명 꽃 한 송이로 모읍니다.",
    seoText: "운명의 꽃 아틀리에는 사주·점성술·자미두수·숙요점, 네 가지 오래된 셈법이 읽어낸 기운을 하나의 꽃과 팔레트로 엮어 보여줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower.webp",
    landingPoints: ["4개 운세 소스 탭 전환", "소스별 꽃·키워드·해석 패널", "프롬프트/저장/공유 도구"],
    localized: {
      en: {
        title: "Flower of Destiny - Integrated Atelier",
        h1: "Flower of Destiny Atelier",
        description: "Open Saju, astrology, Zi Wei Dou Shu, and Sukuyo in source tabs, then watch your flower of destiny and palette bloom.",
        seoText: "Flower of Destiny Atelier blossoms four fortune energies into flowers, palettes, and interpretation panels.",
        landingPoints: ["Switch four fortune-source tabs", "Flowers, keywords, and panels by source", "Prompt, save, and share tools"],
      },
    },
    keywords: [
      "운명의 꽃",
      "사주 꽃",
      "점성술 꽃",
      "자미두수 꽃",
      "숙요 꽃",
      "destiny flower",
    ],
  },
  "dream/tarot": {
    component: FeatureLandingPage,
    title: "드림 타로 - 꿈의 잔향을 전문가 상담 문장으로 봉인",
    h1: "드림 타로",
    description: "꿈속 장면과 깨어난 뒤의 감정이 세 장의 상징 카드에 머물며, AI에게 건넬 상담 문장으로 고요히 봉인됩니다.",
    seoText: "드림 타로는 꿈속 장면, 감정의 잔향, 반복 상징을 카드의 언어로 모아 AI에게 건넬 질문으로 봉인합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/heamong.webp",
    landingPoints: ["꿈 장면 정리", "깨어난 뒤 감정의 잔향", "AI에게 건넬 질문"],
    localized: {
      en: {
        title: "Dream Tarot - seal dream echoes into AI consultation language",
        h1: "Dream Tarot",
        description: "Dream scenes and waking emotions rest on three symbol cards, then become a quiet consultation prompt for AI.",
        seoText: "Dream Tarot gathers dream scenes, emotional echoes, and repeating symbols into the language of cards, then seals them as a question for AI.",
        landingPoints: ["Organize dream scenes", "Read waking emotional echoes", "Create a question for AI"],
      },
    },
    keywords: [
      "드림 타로",
      "드림 프롬프트",
      "꿈 타로",
      "꿈 프롬프트",
      "꿈 해석",
      "dream prompt",
      "dream interpretation",
    ],
  },
  "dream/psycho": {
    component: FeatureLandingPage,
    title: "정신분석 해몽 - Freud Study",
    h1: "정신분석 해몽",
    description: "프로이트의 시선으로 꿈 장면과 무의식 상징을 따라가며 마음의 숨은 맥락을 읽습니다.",
    seoText: "정신분석 해몽은 무의식 상징을 중심으로 심리적 맥락을 읽어줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/phydream.webp",
    landingPoints: ["프로이트 관점 해석", "무의식 상징 분석", "심리 맥락 리포트"],
    localized: {
      en: {
        title: "Psychoanalytic Dream Reading - Freud Study",
        h1: "Psychoanalytic Dream Reading",
        description: "Follow dream scenes and unconscious symbols through a Freudian lens to read the hidden context of the mind.",
        seoText: "Psychoanalytic Dream Reading centers unconscious symbols to reveal psychological context.",
        landingPoints: ["Freudian interpretation", "Unconscious symbol analysis", "Psychological context report"],
      },
    },
    keywords: [
      "정신분석 해몽",
      "프로이트",
      "꿈 분석",
      "psychoanalysis dream",
      "Freud dream",
    ],
  },
  /* ── 신규 서비스 엔트리 ── */
  "oracle/hwatu-life": {
    component: FeatureLandingPage,
    title: "화투 인생 패 테스트 - 7문항 심리테스트",
    h1: "화투 인생 패 테스트",
    description: "돈·사랑·위기 상황에서의 선택 패턴을 통해 나를 상징하는 화투 인생 패 아키타입을 찾아주는 심리테스트.",
    seoText: "화투 인생 패 테스트는 7문항 심리테스트로 삼광·고도리·청단·똑광 아키타입을 찾아드립니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tazza.webp",
    landingPoints: ["7문항 심리테스트", "화투 인생 패 아키타입 파악", "조건별 선택 패턴 분석"],
    localized: {
      en: {
        title: "Hwatu Life Card Test - seven-question personality test",
        h1: "Hwatu Life Card Test",
        description: "A personality test that finds your hwatu life-card archetype through your choices around money, love, and crisis.",
        seoText: "Hwatu Life Card Test uses seven questions to reveal archetypes such as Samgwang, Godori, Cheongdan, and Ttokgwang.",
        landingPoints: ["Seven-question personality test", "Find your hwatu life-card archetype", "Analyze choice patterns by condition"],
      },
    },
    keywords: [
      "화투",
      "화투 인생 패",
      "심리테스트",
      "아키타입 테스트",
      "hwatu life test",
    ],
  },
  "oracle/sikojen-povailu": {
    component: FeatureLandingPage,
    title: "핀란드 주석점 Sikojen Povailu",
    h1: "핀란드 주석점",
    description:
      "핀란드 전통 주석점(낙점) 의식을 무료로 체험하세요. 낙이 물에서 굳는 형태로 미래를 읽는 5단게 인터랙티브 오라클.",
    seoText:
      "핀란드 주석점에서는 5단계 의식 속에 굳어지는 주석의 형상이 지금의 그림자와 선택의 실마리를 비춥니다.",
    ogImage: "https://code-destiny.com/icons/꿀꿀 운세 로고.webp",
    landingPoints: ["5단계 인터랙티브 의식", "낙 형태 상징 해석", "Shadow Reading"],
    localized: {
      en: {
        title: "Finnish Tin Casting Sikojen Povailu",
        h1: "Finnish Tin Casting",
        description: "Experience a free Finnish tin-casting ritual: a five-step interactive oracle that reads the future through the shape of tin hardening in water.",
        seoText: "In Finnish Tin Casting, the shape that hardens during a five-step ritual reflects today’s shadow and the clue of choice.",
        landingPoints: ["Five-step interactive ritual", "Symbol reading from cast shape", "Shadow Reading"],
      },
    },
    keywords: [
      "핀란드 주석점",
      "Sikojen Povailu",
      "낙점",
      "핀란드 신탁",
      "tin casting oracle",
    ],
  },
  "oracle/ifa": {
    component: FeatureLandingPage,
    title: "IFA 오라클 - 요루바 256 오두 신탁",
    h1: "IFA 오라클",
    description:
      "요루바 전통 256 오두의 흐름 위로 질문의 뿌리와 지금 필요한 응답이 조용히 떠오릅니다.",
    seoText:
      "IFA 오라클에서는 상징 조합과 질문의 맥락이 맞물리며 연애, 재물, 건강의 흐름이 신탁처럼 드러납니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ifafortune.webp",
    landingPoints: ["256 오두 전통 해석", "질문 맥락형 오라클", "회차당 3,000원 리딩"],
    localized: {
      en: {
        title: "IFA Oracle - Yoruba 256 Odu divination",
        h1: "IFA Oracle",
        description: "Over the flow of the Yoruba 256 Odu tradition, the root of your question and the answer needed now quietly rise.",
        seoText: "In the IFA Oracle, symbolic combinations meet the context of your question and reveal love, wealth, and health currents like divination.",
        landingPoints: ["Traditional 256 Odu interpretation", "Question-context oracle", "KRW 3,000 per reading"],
      },
    },
    keywords: [
      "IFA 오라클",
      "이파 점술",
      "요루바 신탁",
      "256 오두",
      "ifa oracle",
    ],
  },
  "oracle/royal-tea": {
    component: FeatureLandingPage,
    title: "타세오그래피 찻잎 점 - 런던 로열 컵 문양 리딩",
    h1: "타세오그래피 찻잎 점",
    description:
      "런던 로열 컵에 남은 찻잎 문양을 따라 상징의 흐름과 다가오는 기미를 읽습니다.",
    seoText:
      "타세오그래피에서는 찻잔 안에 남은 잎의 패턴이 미래의 작은 징후와 마음의 방향을 비춥니다.",
    ogImage: "/fuctionassets/london.webp",
    landingPoints: ["런던 로열 컵 문양 리딩", "영국 홍차 전통 점술", "상징 해석 오라클"],
    localized: {
      en: {
        title: "Tasseography Tea Leaf Oracle - London Royal Cup pattern reading",
        h1: "Tasseography Tea Leaf Oracle",
        description: "Follow the tea leaf patterns left in the London Royal Cup to read symbolic flow and approaching signs.",
        seoText: "In tasseography, the pattern of leaves remaining in the teacup illuminates small signs of the future and the direction of the heart.",
        landingPoints: ["London Royal Cup pattern reading", "British tea divination tradition", "Symbol interpretation oracle"],
      },
    },
    keywords: [
      "타세오그래피",
      "찻잎 점",
      "로열 컵",
      "tasseography",
      "tea leaf reading",
    ],
  },
  "saju/love-simulation": {
    componentKey: "loveSimulation",
    title: "LOVE CODE - 사주 연애 시뮬레이션",
    h1: "LOVE CODE 사주 연애 시뮬레이션",
    description:
      "상대방의 생년월일로 사주를 분석해 페르소나 캐릭터를 만들고, 데이트 코스·선택지를 통해 상대방의 취향과 성격을 미리 경험해보는 사주 연애 시뮬레이션.",
    seoText:
      "LOVE CODE에서는 상대의 오행, 일간, MBTI가 연애 반응의 결로 이어지며 데이트 시나리오의 흐름을 엽니다.",
    ogImage: "https://code-destiny.com/fuctionassets/love%20code.webp",
    landingPoints: [
      "상대방 생년월일 사주 분석",
      "오행·일간 기반 페르소나 생성",
      "데이트 코스 선택지 시뮬레이션",
    ],
    localized: {
      en: {
        title: "LOVE CODE - Saju Love Simulation",
        h1: "LOVE CODE Saju Love Simulation",
        description: "Analyze the other person’s birth date with Saju, create a persona character, and preview their tastes and temperament through date-course choices.",
        seoText: "In LOVE CODE, the other person’s five elements, day stem, and MBTI become the texture of romantic response and open a dating scenario flow.",
        landingPoints: [
          "Saju analysis from the other person’s birth date",
          "Persona generation from elements and day stem",
          "Date-course choice simulation",
        ],
      },
    },
    keywords: [
      "연애 시뮬레이션",
      "사주 연애",
      "상대방 사주 분석",
      "데이트 시뮬레이션",
      "love simulation",
      "사주 궁합 게임",
    ],
  },
};

export function getService(slug) {
  return SERVICE_MAP[slug] ?? null;
}
