export const SERVICE_SECTIONS = [
  {
    id: "saju",
    title: "사주 & 명리",
    items: [
      { href: "/saju/basic", title: "🌸 사주 만세력 기본 해석", desc: "오행·십성 기반 명식 분석 · 무료" },
      { href: "/saju/sibyl", title: "⚡ 시빌라 시스템", desc: "사주 기반 진로 적성 × 운명 위험 계수 · 기본 무료" },
      { href: "/saju/lifebook", title: "📜 인생의 책", desc: "프리미엄 사주 심층 분석 · 490코인" },
      { href: "/saju/love-secret", title: "💕 연애 비책", desc: "사주 기반 연애 전략 · 1인 300코인 / 2인 500코인" },
      { href: "/saju/love-simulation", title: "💕 LOVE CODE", desc: "사주 연애 시뮬레이션 · 무료" },
      { href: "/saju/destiny-bias", title: "✨ 최애운명", desc: "사주 기반 팬덤 공명 분석 · 1회 50코인" },
    ],
  },
  {
    id: "core",
    title: "동서양 명리",
    items: [
      { href: "/ziwei/chart", title: "자미두수 명반", desc: "기본 서비스 무료 · 궁합 50코인" },
      { href: "/astrology/cosmic", title: "점성술 코즈믹", desc: "기본 서비스 무료 · 궁합 50코인" },
      { href: "/vedic/jyotish", title: "베다 점성술", desc: "기본 서비스 무료 · 궁합 50코인" },
    ],
  },
  {
    id: "tarot",
    title: "타로 리딩",
    items: [
      { href: "/tarot/mingri", title: "🔮 명리학 타로", desc: "78장 유니버설 덱 리딩 · 무료" },
      { href: "/tarot/love", title: "💕 우리는 무슨 사이?", desc: "6카드 연애 관계 리딩 · 50코인" },
      { href: "/tarot/healing", title: "☀ 따뜻한 태양 회복 타로", desc: "4카드 회복 스프레드 · 무료" },
      { href: "/tarot/self-esteem", title: "✨ 자존감 레벨업", desc: "5카드 RPG 퀘스트 · 무료" },
      { href: "/tarot/reunion", title: "🌊 재회운 타로", desc: "5카드 등대 스프레드 · 50코인" },
      { href: "/tarot/year", title: "십이지신 천운(天運)", desc: "12개월 연간 운세 · 30코인" },
      { href: "/tarot/crystal-soul/", title: "💎 원석 소울 타로", desc: "크리스탈 에너지 리딩 · 50코인" },
      { href: "/tarot/mindscan/", title: "🔮 속마음 알아보기", desc: "10카드 십자 스프레드 · 50코인" },
      { href: "/celestial-harmony.html", title: "✨ 천체의 선율", desc: "행성 11카드 코즈믹 리딩 · 100코인" },
      { href: "/tarot-ijik.html", title: "💼 이직 운명의 카드", desc: "7카드 커리어 스프레드 · 50코인" },
    ],
  },
  {
    id: "oracle",
    title: "신탁 & 해몽",
    items: [
      { href: "/oracle/hwatu", title: "타짜들의 화투점", desc: "12달 화투패 운세" },
      { href: "/oracle/hwatu-life", title: "화투 인생 패 테스트", desc: "타짜 컨셉 7문항 심리테스트" },
      { href: "/oracle/ifa", title: "IFA 오라클", desc: "요루바 256 오두 신탁 · 30코인" },
      { href: "/oracle/kemet", title: "고대 이집트 신탁", desc: "케멧 오라클 리딩" },
      { href: "/oracle/juyuk", title: "주역 거북점", desc: "64괘 상징 해석" },
      { href: "/oracle/sukuyo", title: "숙요점", desc: "기본 서비스 무료 · 궁합 50코인" },
      { href: "/oracle/rune", title: "스톤헨지 룬 오라클", desc: "고대 룬 상징 리딩" },
      { href: "/geomancy-oracle-v4.html", title: "지오맨시 흙점", desc: "대지의 징후 16행 신탁" },
      { href: "/royal-tea-oracle.html", title: "타세오그래피 찻잎 점", desc: "런던 로열 컵 문양 리딩" },
      { href: "/destiny-poker.html", title: "데스티니 포커", desc: "신들과 벌이는 운명의 카드 대결" },
      { href: "/dream/tarot", title: "드림 타로", desc: "AI 꿈 해석 리포트" },
      { href: "/dream/psycho", title: "정신분석 해몽", desc: "프로이트 관점 해석" },
    ],
  },
  {
    id: "special",
    title: "특별 콘텐츠",
    items: [
      { href: "/secret-house_real.html", title: "나는 솔로 시크릿 하우스", desc: "자동 일간 캐치 연애 시뮬" },
      { href: "/animal/physio", title: "AI 동물 관상", desc: "셀카 얼굴형 분석" },
      { href: "/animal/mbti", title: "MBTI 동물 궁합", desc: "16유형 케미 분석" },
      { href: "/animal/totem", title: "애니멀 토템", desc: "수호 동물 메시지" },
      { href: "/flower/destiny", title: "운명의 꽃", desc: "통합 아틀리에" },
      { href: "/flower/astrology", title: "점성술 꽃", desc: "성운 테마 시각화" },
      { href: "/flower/jamidusu", title: "자미두수 꽃", desc: "명궁 테마 리포트" },
      { href: "/flower/sukuyo", title: "숙요 꽃", desc: "달 위상 기반 꽃" },
    ],
  },
];

