import SolarOracleTarot from "../components/SolarOracleTarot";
import MingriTarot from "../components/MingriTarot";
import LoveRelationshipTarot from "../components/LoveRelationshipTarot";
import SajuBasicPage from "../components/SajuBasicPage";
import ZiweiChartPage from "../components/ZiweiChartPage";
import AstrologyCosmicPage from "../components/AstrologyCosmicPage";
import FeatureLandingPage from "../components/FeatureLandingPage";
import SunHealingTarot from "../components/SunHealingTarot";

export const SERVICE_MAP = {
  "tarot/healing": {
    component: SunHealingTarot,
    title: "따뜻한 태양 회복 타로 - 4카드 힐링 스프레드",
    h1: "따뜻한 태양 회복 타로 - Sun and Light 4카드 힐링 스프레드",
    description:
      "햇살처럼 포근한 빛으로 마음을 어루만지고, 다시 일어설 힘을 찾아가는 4카드 타로 리딩. 무료 힐링 타로로 오늘의 회복 에너지를 확인하세요.",
    seoText:
      "따뜻한 태양 회복 타로는 Sun and Light 에너지를 활용한 4카드 힐링 스프레드입니다. 과거의 상처, 현재의 에너지, 회복의 방향, 오늘의 선물을 카드로 읽습니다.",
    ogImage: "https://code-destiny.com/fuctionassets/healing.webp",
    keywords: [
      "힐링 타로",
      "4카드 타로",
      "Sun and Light",
      "회복 타로",
      "무료 타로",
      "타로 리딩",
      "healing tarot spread",
    ],
  },
  "tarot/solar": {
    component: SolarOracleTarot,
    title: "태양의 화답 - Solar Oracle 카드 리딩",
    h1: "태양의 화답 - Solar Oracle 카드 리딩",
    description:
      "태양의 상징을 담은 오라클 카드로 현재의 감정, 방향, 회복 메시지를 읽는 코즈믹 리딩 서비스.",
    seoText:
      "Solar Oracle 리딩은 태양의 상징과 메시지를 바탕으로 지금 필요한 통찰과 행동 힌트를 제공합니다.",
    ogImage: "https://code-destiny.com/icons/honeypig.webp",
    keywords: [
      "Solar Oracle",
      "태양 오라클",
      "카드 리딩",
      "코즈믹 타로",
      "solar oracle reading",
    ],
  },
  "tarot/mingri": {
    component: MingriTarot,
    title: "명리학 AI 타로 - 78장 유니버설 덱 리딩",
    h1: "명리학 AI 타로 - 78장 유니버설 덱 리딩",
    description:
      "연애, 재회, 사업, 건강 등 고민 카테고리에 맞춰 원카드 또는 3카드 명리학 타로 해석을 제공합니다.",
    seoText:
      "명리학 AI 타로는 타로 카드를 카테고리별 맥락으로 해석하는 서비스입니다. 원카드와 3카드 스프레드를 지원하며, 카드 공개 후 맞춤 리딩 결과를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20tarrot.webp",
    keywords: [
      "명리학 타로",
      "78장 타로",
      "유니버설 덱",
      "원카드 타로",
      "3카드 타로",
      "AI 타로",
      "mingri tarot",
    ],
  },
  "tarot/love": {
    component: LoveRelationshipTarot,
    title: "우리는 무슨 사이? - 6카드 연애 관계 타로",
    h1: "우리는 무슨 사이? - 6카드 연애 관계 타로",
    description:
      "내가 보는 상대, 상대의 시선, 관계를 막는 요인과 예상 결과까지 6카드 스프레드로 확인하는 연애 타로 리딩.",
    seoText:
      "우리는 무슨 사이 타로는 relationship_six_card 스프레드를 사용해 관계의 현재 상태와 흐름을 다각도로 읽어주는 연애 특화 카드 리딩입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tarolove.webp",
    keywords: [
      "우리는 무슨 사이",
      "6카드 타로",
      "연애 타로",
      "관계 타로",
      "relationship six card",
      "연애 궁합",
    ],
  },
  "saju/basic": {
    component: SajuBasicPage,
    title: "사주 만세력 기본 해석 - 오행·십성·명식 분석",
    h1: "사주 만세력 기본 해석",
    description:
      "생년월일시 기반 사주 명식으로 오행 균형과 십성 흐름을 분석하는 Code Destiny의 사주 서비스 안내 페이지.",
    seoText:
      "사주 서비스는 년월일시와 출생지 정보를 바탕으로 오행 균형, 십성 관계, 해석 포인트를 제공하는 개인 맞춤 운세 분석 기능입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/saju.webp",
  },
  "astrology/cosmic": {
    component: AstrologyCosmicPage,
    title: "점성술 코즈믹 차트 - 태양·달·상승궁 분석",
    h1: "점성술 코즈믹 차트",
    description:
      "서양 점성술의 태양궁, 달궁, 상승궁을 중심으로 성향과 관계 패턴을 읽는 코즈믹 차트 서비스 안내 페이지.",
    seoText:
      "점성술 코즈믹 차트는 출생 정보를 기반으로 태양, 달, 상승궁을 해석해 성향과 감정 패턴, 표현 방식을 이해하도록 돕습니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jumsung.webp",
    keywords: [
      "점성술",
      "코즈믹 차트",
      "태양궁",
      "달궁",
      "상승궁",
      "서양 점성술",
      "natal chart",
      "astrology chart",
    ],
  },
  "ziwei/chart": {
    component: ZiweiChartPage,
    title: "자미두수 12궁 명반 분석 - Ziwei Doushu",
    h1: "자미두수 12궁 명반 분석",
    description:
      "자미두수(紫微斗數) 기반으로 명궁과 주요 성군, 12궁 배치를 해석하는 운명 지도 서비스 안내 페이지.",
    seoText:
      "자미두수 서비스는 생년월일시를 기반으로 12궁 명반 구조를 해석하고 성향, 관계, 진로 등 핵심 흐름을 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jami.webp",
    keywords: [
      "자미두수",
      "紫微斗數",
      "12궁",
      "명반",
      "Zi Wei Dou Shu",
      "ziwei chart",
    ],
  },
  "animal/physio": {
    component: FeatureLandingPage,
    title: "AI 동물 관상 - 셀카 얼굴 분석",
    h1: "AI 동물 관상",
    description: "셀카 기반 얼굴형 관상 분석으로 성향과 분위기를 읽는 서비스 안내 페이지.",
    seoText: "AI 동물 관상은 얼굴 이미지를 바탕으로 동물상 비유 분석과 해석 포인트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20animal.webp",
    landingPoints: ["셀카 기반 얼굴형 분석", "동물상 비유 해석", "가볍게 즐기는 성향 리포트"],
    keywords: [
      "AI 동물 관상",
      "관상",
      "얼굴형 분석",
      "셀카 관상",
      "동물상",
      "physiognomy",
    ],
  },
  "animal/mbti": {
    component: FeatureLandingPage,
    title: "MBTI 동물 궁합 - 16가지 토템 케미",
    h1: "MBTI 동물 궁합",
    description: "MBTI 성향 조합을 동물 토템 관점으로 해석하는 궁합 서비스 안내 페이지.",
    seoText: "MBTI 동물 궁합은 16유형 조합의 관계 포인트를 쉽고 직관적으로 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20face.webp",
    landingPoints: ["16유형 조합 분석", "연애/친구 케미 포인트", "관계 소통 팁 제공"],
    keywords: [
      "MBTI 궁합",
      "MBTI 동물",
      "16가지 유형",
      "연애 궁합",
      "MBTI compatibility",
    ],
  },
  "animal/totem": {
    component: FeatureLandingPage,
    title: "애니멀 토템 카드 리딩",
    h1: "애니멀 토템 리딩",
    description: "수호 동물 메시지를 카드 리딩 형태로 제공하는 토템 서비스 안내 페이지.",
    seoText: "애니멀 토템은 지금의 감정 상태와 방향성을 상징 메시지로 풀어줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/animaltotem.webp",
    landingPoints: ["수호 동물 메시지", "카드 기반 직관 리딩", "현재 상태 점검"],
    keywords: [
      "애니멀 토템",
      "토템 카드",
      "수호 동물",
      "animal totem",
      "토템 리딩",
    ],
  },
  "tarot/self-esteem": {
    component: FeatureLandingPage,
    title: "자존감 레벨업 타로 - 5카드 퀘스트",
    h1: "자존감 레벨업 타로",
    description: "자존감 회복 흐름을 RPG 스타일 5카드로 해석하는 타로 서비스 안내 페이지.",
    seoText: "자존감 레벨업 타로는 감정 상태를 단계적으로 읽어 행동 힌트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jajongam.webp",
    landingPoints: ["5카드 성장 퀘스트", "감정 회복 흐름", "실천형 행동 힌트"],
    keywords: [
      "자존감 타로",
      "5카드 타로",
      "RPG 타로",
      "self esteem tarot",
      "성장 타로",
    ],
  },
  "tarot/reunion": {
    component: FeatureLandingPage,
    title: "재회운 타로 - 5카드 등대 스프레드",
    h1: "재회운 타로",
    description: "관계 재접점 가능성과 감정 흐름을 읽는 5카드 재회운 타로 안내 페이지.",
    seoText: "재회운 타로는 관계 신호와 타이밍 포인트를 카드 흐름으로 해석합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/reunion.webp",
    landingPoints: ["재회 가능성 흐름", "관계 타이밍 포인트", "감정 정리 가이드"],
    keywords: [
      "재회운 타로",
      "재회 타로",
      "5카드 스프레드",
      "연애 재회",
      "reunion tarot",
    ],
  },
  "tarot/year": {
    component: FeatureLandingPage,
    title: "십이지신 천운 타로 - 12개월 운세",
    h1: "십이지신 천운 타로",
    description: "12개월 월별 흐름을 확인하는 연간 운세 타로 안내 페이지.",
    seoText: "십이지신 천운 타로는 월별 재물, 연애, 관계 흐름을 점검하는 서비스입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/12animals.webp",
    landingPoints: ["12개월 월별 운세", "재물/연애/관계 흐름", "연간 계획 참고"],
    keywords: [
      "십이지신",
      "천운 타로",
      "12개월 운세",
      "연간 운세",
      "zodiac year tarot",
    ],
  },
  "oracle/hwatu": {
    component: FeatureLandingPage,
    title: "타짜들의 화투점 - 12달 화투패 운세",
    h1: "타짜들의 화투점",
    description: "화투 상징을 바탕으로 월별 운세 흐름을 해석하는 서비스 안내 페이지.",
    seoText: "화투점은 한국 전통 상징을 현대적으로 해석한 운세 콘텐츠입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tazza.webp",
    landingPoints: ["전통 화투 상징 해석", "12달 흐름 점검", "간편 운세 콘텐츠"],
    keywords: [
      "화투점",
      "타짜 화투",
      "12달 운세",
      "한국 전통 운세",
      "hwatu fortune",
    ],
  },
  "oracle/kemet": {
    component: FeatureLandingPage,
    title: "고대 이집트 신탁 - 케멧 오라클",
    h1: "고대 이집트 신탁",
    description: "케멧 오라클 상징 기반으로 메시지를 읽는 신탁 서비스 안내 페이지.",
    seoText: "이집트 신탁은 상징 중심 질문-응답 방식의 오라클 리딩을 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/egypt.webp",
    landingPoints: ["오라클 상징 리딩", "질문 중심 해석", "직관 메시지 제공"],
    keywords: [
      "이집트 신탁",
      "케멧 오라클",
      "Kemet Oracle",
      "고대 이집트",
      "oracle reading",
    ],
  },
  "oracle/juyuk": {
    component: FeatureLandingPage,
    title: "주역 거북점 - 64괘 해석",
    h1: "주역 거북점",
    description: "주역 64괘의 상징 체계로 현재 흐름을 해석하는 서비스 안내 페이지.",
    seoText: "주역 거북점은 고전 괘상 해석을 바탕으로 의사결정 힌트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/juyuk.webp",
    landingPoints: ["64괘 상징 해석", "상황 판단 힌트", "고전 기반 리딩"],
    keywords: [
      "주역",
      "64괘",
      "거북점",
      "I Ching",
      "역점",
    ],
  },
  "oracle/sukuyo": {
    component: FeatureLandingPage,
    title: "숙요점 - 27수 별자리 운명",
    h1: "숙요점",
    description: "27수 별자리 체계로 성향과 관계 흐름을 읽는 숙요 서비스 안내 페이지.",
    seoText: "숙요점은 동아시아 달력 전통의 27수 체계를 활용한 운세 분석입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/sukyo.webp",
    landingPoints: ["27수 별자리 해석", "성향·관계 흐름", "전통 달력 기반 분석"],
    keywords: [
      "숙요점",
      "宿曜",
      "27수",
      "숙요도",
      "Sukuyo",
    ],
  },
  "vedic/jyotish": {
    component: FeatureLandingPage,
    title: "베다 점성술 - Jyotish 차트",
    h1: "베다 점성술 (Jyotish)",
    description: "낙샤트라와 다샤 체계를 중심으로 읽는 베다 점성술 서비스 안내 페이지.",
    seoText: "베다 점성술은 인도 점성술 전통의 별자리·주기 체계를 해석에 활용합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/veda.webp",
    landingPoints: ["낙샤트라/다샤 해석", "베다 전통 차트", "장기 흐름 점검"],
    keywords: [
      "베다 점성술",
      "Jyotish",
      "자이오티시",
      "낙샤트라",
      "다샤",
      "vedic astrology",
    ],
  },
  "flower/destiny": {
    component: FeatureLandingPage,
    title: "운명의 꽃 - 통합 아틀리에",
    h1: "운명의 꽃 아틀리에",
    description: "사주·점성술·자미두수 흐름을 꽃 이미지로 시각화하는 서비스 안내 페이지.",
    seoText: "운명의 꽃은 명리/점성 데이터에 기반한 감성형 결과 시각화 콘텐츠입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower.webp",
    landingPoints: ["통합 꽃 리포트", "개인화 시각 결과", "공유/저장 기능"],
    keywords: [
      "운명의 꽃",
      "사주 꽃",
      "점성술 꽃",
      "자미두수 꽃",
      "destiny flower",
    ],
  },
  "flower/astrology": {
    component: FeatureLandingPage,
    title: "점성술 운명의 꽃",
    h1: "점성술 운명의 꽃",
    description: "점성술 차트 기반의 운명의 꽃 시각화 서비스 안내 페이지.",
    seoText: "점성술 운명의 꽃은 태양·달·상승궁 패턴을 꽃 테마로 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower2.webp",
    landingPoints: ["점성술 기반 꽃 시각화", "개인 패턴 표현", "감성형 결과 공유"],
    keywords: [
      "점성술 운명의 꽃",
      "네온 성운",
      "natal flower",
      "astrology flower",
    ],
  },
  "flower/jamidusu": {
    component: FeatureLandingPage,
    title: "자미두수 운명의 꽃",
    h1: "자미두수 운명의 꽃",
    description: "자미두수 명궁/성군 특징을 꽃 리포트로 표현하는 안내 페이지.",
    seoText: "자미두수 운명의 꽃은 명반 특징을 시각적 상징으로 풀어낸 콘텐츠입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower3.webp",
    landingPoints: ["명반 기반 꽃 리포트", "성군 특징 시각화", "운명 테마 요약"],
    keywords: [
      "자미두수 꽃",
      "紫微 꽃",
      "명궁 꽃",
      "ziwei flower",
    ],
  },
  "flower/sukuyo": {
    component: FeatureLandingPage,
    title: "숙요 운명의 꽃",
    h1: "숙요 운명의 꽃",
    description: "숙요 27수 흐름을 바탕으로 제작되는 꽃 리포트 안내 페이지.",
    seoText: "숙요 운명의 꽃은 달의 위상과 숙성 패턴을 감성 결과물로 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower4.webp",
    landingPoints: ["27수 기반 꽃 시각화", "달 위상 테마", "요약형 운세 리포트"],
    keywords: [
      "숙요 꽃",
      "27숙",
      "달 꽃",
      "sukuyo flower",
    ],
  },
  "dream/tarot": {
    component: FeatureLandingPage,
    title: "드림 타로 - AI 꿈 해석 리포트",
    h1: "드림 타로",
    description: "꿈 내용을 입력해 상징과 정서를 분석하는 AI 해몽 서비스 안내 페이지.",
    seoText: "드림 타로는 꿈속 사건과 감정을 바탕으로 해석 리포트를 생성합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/heamong.webp",
    landingPoints: ["꿈 문장 기반 해석", "정서 톤별 조언", "라이브러리 연동"],
    keywords: [
      "드림 타로",
      "AI 해몽",
      "꿈 해석",
      "dream tarot",
      "dream interpretation",
    ],
  },
  "dream/psycho": {
    component: FeatureLandingPage,
    title: "정신분석 해몽 - Freud Study",
    h1: "정신분석 해몽",
    description: "프로이트 관점으로 꿈 내용을 구조화해 해석하는 서비스 안내 페이지.",
    seoText: "정신분석 해몽은 무의식 상징을 중심으로 심리적 맥락을 읽어줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/phydream.webp",
    landingPoints: ["프로이트 관점 해석", "무의식 상징 분석", "심리 맥락 리포트"],
    keywords: [
      "정신분석 해몽",
      "프로이트",
      "꿈 분석",
      "psychoanalysis dream",
      "Freud dream",
    ],
  },
};

export function getService(slug) {
  return SERVICE_MAP[slug] ?? null;
}
