import FeatureLandingPage from "../components/FeatureLandingPage";

export const SECTION_LABELS = {
  tarot: "타로",
  saju: "사주",
  astrology: "점성술",
  ziwei: "자미두수",
  oracle: "신탁",
};

export const SERVICE_MAP = {
  "tarot/healing": {
    component: FeatureLandingPage,
    title: "따뜻한 태양 회복 타로 - 마음의 온도를 되찾는 4카드 리딩",
    h1: "따뜻한 태양 회복 타로",
    description:
      "햇살 같은 네 장의 카드로 상처의 이름, 감정의 온도, 다시 따뜻해지는 단서와 오늘의 회복 루틴을 읽습니다.",
    seoText:
      "따뜻한 태양 회복 타로는 지친 마음 위에 새벽빛을 올려놓듯, 감정의 자리와 작은 회복 행동을 정리하는 4카드 리딩입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/healing.webp",
    landingPoints: ["상처의 이름 확인", "감정의 온도 읽기", "오늘 10분 회복 루틴"],
    keywords: [
      "힐링 타로",
      "4카드 타로",
      "Sun and Light",
      "회복 타로",
      "무료 타로",
      "타로 리딩",
      "healing tarot spread",
    ],
  },
  "tarot/mingri": {
    component: FeatureLandingPage,
    title: "명리학 타로 - 카드와 십성이 비추는 선택 리딩",
    h1: "명리학 타로 - 카드와 십성이 비추는 선택 리딩",
    description:
      "연애, 재회, 사업, 건강 등 고민 카테고리에 맞춰 한 장 리딩 또는 세 장 흐름으로 오늘의 선택 방향을 읽습니다.",
    seoText:
      "명리학 타로는 카드 상징과 십성의 기운을 연결해 질문의 결, 선택의 속도, 조율할 방향을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20tarrot.webp",
    landingPoints: ["카테고리별 고민 리딩", "한 장 리딩과 세 장 흐름", "십성 조율 문장"],
    keywords: [
      "명리학 타로",
      "78장 타로",
      "유니버설 덱",
      "한 장 타로",
      "세 장 타로",
      "십성 타로",
      "mingri tarot",
    ],
  },
  "tarot/love": {
    component: FeatureLandingPage,
    title: "우리는 무슨 사이? - 둘 사이의 이름과 속도",
    h1: "우리는 무슨 사이?",
    description:
      "그 사람의 말과 행동 사이에 남은 온도, 망설임, 관계의 이름과 지금 건네도 좋은 말을 6장의 카드로 읽습니다.",
    seoText:
      "우리는 무슨 사이 타로는 서로의 시선, 감정 온도, 현실 변수, 다음 대화의 선을 분리해 읽는 관계 특화 6카드 리딩입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tarolove.webp",
    landingPoints: ["서로 다른 시선 분리", "상대의 감정 온도", "건네도 좋은 말"],
    keywords: [
      "우리는 무슨 사이",
      "6카드 타로",
      "연애 타로",
      "관계 타로",
      "relationship six card",
      "연애 궁합",
    ],
  },
  "saju/basic": {
    component: FeatureLandingPage,
    title: "사주 만세력 기본 해석 - 오행·십성·명식 분석",
    h1: "사주 만세력 기본 해석",
    description:
      "생년월일시 기반 사주 명식으로 오행 균형과 십성 흐름을 분석하는 Code Destiny의 사주 서비스 안내 페이지.",
    seoText:
      "사주 서비스는 년월일시와 출생지 정보를 바탕으로 오행 균형, 십성 관계, 해석 포인트를 제공하는 개인 맞완 운세 분석 기능입니다.",
    ogImage: "/fuctionassets/saju.webp",
    landingPoints: ["사주팔자 명식 생성", "오행 균형 분석", "십성 흐름 해석"],
  },
  "saju/destiny-bias": {
    component: FeatureLandingPage,
    title: "최애운명 - 사주 기반 팬덤 공명 분석",
    h1: "최애운명",
    description:
      "내 사주와 최애 사주를 내부 명식 엔진으로 계산해 공명 점수, 오행 보완, 오늘의 액션을 카드로 보여주는 팬덤 특화 사주 분석.",
    seoText:
      "최애운명은 AI가 계산하지 않고 내부 사주 엔진의 canonical JSON을 기반으로 해석만 생성합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EC%B5%9C%EC%95%A0%EC%9A%B4%EB%AA%85.webp",
    landingPoints: ["내 사주 × 최애 사주 공명 점수", "오행 보완/십성 역할 제안", "1회 50코인 분석 카드"],
    keywords: [
      "최애운명",
      "팬덤 사주",
      "사주 공명",
      "덕질 운세",
      "bias destiny",
      "k-fandom saju",
    ],
  },
  "saju/animal-destiny": {
    component: FeatureLandingPage,
    title: "사주 가디언 아트 - 내 사주 수호동물 테스트",
    h1: "사주 가디언 아트",
    description:
      "일간, 월지, 오행 균형, 십성 흐름을 기반으로 수호동물 카드, 사주 근거, 수호력, 경고 메시지, 궁합을 제공하는 사주 캐릭터 테스트.",
    seoText:
      "사주 가디언 아트는 사주 계산값으로 내 운명 보호 스타일과 수호동물을 배정하고 공유용 가디언 카드로 보여줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EB%8F%99%EB%AC%BC%EC%A0%90%ED%85%8C%EC%8A%A4%ED%8A%B8.webp",
    landingPoints: ["일간·월지·오행 기반 배정", "고정 2D 수호동물 카드", "사주 근거 + 오늘의 메시지", "공유 카드 저장"],
    keywords: [
      "사주 가디언",
      "수호동물",
      "사주 수호동물 테스트",
      "animal destiny",
      "guardian animal",
    ],
  },
  "saju/animal-test": {
    component: FeatureLandingPage,
    title: "사주 가디언 아트 - 내 사주 수호동물 테스트",
    h1: "사주 가디언 아트",
    description:
      "일간, 월지, 오행 균형, 십성 흐름을 기반으로 수호동물 카드, 사주 근거, 수호력, 경고 메시지, 궁합을 제공하는 사주 캐릭터 테스트.",
    seoText:
      "사주 가디언 아트는 사주 계산값으로 내 운명 보호 스타일과 수호동물을 배정하고 공유용 가디언 카드로 보여줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EB%8F%99%EB%AC%BC%EC%A0%90%ED%85%8C%EC%8A%A4%ED%8A%B8.webp",
    landingPoints: ["일간·월지·오행 기반 배정", "고정 2D 수호동물 카드", "사주 근거 + 오늘의 메시지", "공유 카드 저장"],
    keywords: [
      "사주 가디언",
      "수호동물",
      "사주 수호동물 테스트",
      "animal destiny",
      "guardian animal",
    ],
  },
  "saju/destiny-meeting-place": {
    component: FeatureLandingPage,
    title: "사주로 보는 인연의 장소 - 독립 운명 좌표 리포트",
    h1: "사주로 보는 인연의 장소",
    description:
      "생년월일 기반 사주 에너지로 인연이 열리는 장소, 국가/도시, 타이밍, 운명의 아이템을 추천하는 독립 리포트 페이지.",
    seoText:
      "인연의 장소 기능은 동물점 결과 화면 종속이 아닌 독립 분석 페이지로 실행되며, 입력 즉시 사주 계산 후 장소 리포트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/%EC%82%AC%EC%A3%BC%EB%A1%9C%EB%B3%B4%EB%8A%94%20%EC%9D%B8%EC%97%B0%EC%9D%98%20%EC%9E%A5%EC%86%8C.webp",
    landingPoints: ["독립 실행 입력 폼", "인연 장소 TOP 5", "국가/도시 추천", "1회 100코인"],
    keywords: [
      "사주로 보는 인연의 장소",
      "인연 장소 추천",
      "사주 장소 운세",
      "meeting place saju",
      "destiny meeting place",
    ],
  },
  "astrology/cosmic": {
    component: FeatureLandingPage,
    title: "점성술 코즈믹 차트 - 태양·달·상승궁 분석",
    h1: "점성술 코즈믹 차트",
    description:
      "서양 점성술의 태양궁, 달궁, 상승궁을 중심으로 성향과 관계 패턴을 읽는 코즈믹 차트 서비스 안내 페이지.",
    seoText:
      "점성술 코즈믹 차트는 출생 정보를 기반으로 태양, 달, 상승궁을 해석해 성향과 감정 패턴, 표현 방식을 이해하도록 돕습니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jumsung.webp",
    landingPoints: ["태양궁·달궁·상승궁 해석", "코즈믹 스타일 차트", "관계 패턴 파악"],
    keywords: [
      "점성술",
      "코즈믹 차트",
      "태양궁",
      "달궁",
      "상승궁",
      "서양 점성술",
      "natal chart",
      "astrology chart",
    ],
  },
  "ziwei/chart": {
    component: FeatureLandingPage,
    title: "자미두수 12궁 명반 분석 - Ziwei Doushu",
    h1: "자미두수 12궁 명반 분석",
    description:
      "자미두수(紫微斗數) 기반으로 명궁과 주요 성군, 12궁 배치를 해석하는 운명 지도 서비스 안내 페이지.",
    seoText:
      "자미두수 서비스는 생년월일시를 기반으로 12궁 명반 구조를 해석하고 성향, 관계, 진로 등 핵심 흐름을 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jami.webp",
    landingPoints: ["12궁 명반 구조 도식", "주요 성군 조합 해석", "성향·관계·진로 흐름 파악"],
    keywords: [
      "자미두수",
      "紫微斗數",
      "12궁",
      "명반",
      "Zi Wei Dou Shu",
      "ziwei chart",
    ],
  },
  "animal/physio": {
    component: FeatureLandingPage,
    title: "AI 동물 관상 - 셀카 얼굴 분석",
    h1: "AI 동물 관상",
    description: "셀카 기반 얼굴형 관상 분석으로 성향과 분위기를 읽는 서비스 안내 페이지.",
    seoText: "AI 동물 관상은 얼굴 이미지를 바탕으로 동물상 비유 분석과 해석 포인트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20animal.webp",
    landingPoints: ["셀카 기반 얼굴형 분석", "동물상 비유 해석", "가볍게 즐기는 성향 리포트"],
    keywords: [
      "AI 동물 관상",
      "관상",
      "얼굴형 분석",
      "셀카 관상",
      "동물상",
      "physiognomy",
    ],
  },
  "animal/mbti": {
    component: FeatureLandingPage,
    title: "MBTI 동물 궁합 - 16가지 토템 케미",
    h1: "MBTI 동물 궁합",
    description: "MBTI 성향 조합을 동물 토템 관점으로 해석하는 궁합 서비스 안내 페이지.",
    seoText: "MBTI 동물 궁합은 16유형 조합의 관계 포인트를 쉽고 직관적으로 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ai%20face.webp",
    landingPoints: ["16유형 조합 분석", "연애/친구 케미 포인트", "관계 소통 팁 제공"],
    keywords: [
      "MBTI 궁합",
      "MBTI 동물",
      "16가지 유형",
      "연애 궁합",
      "MBTI compatibility",
    ],
  },
  "animal/totem": {
    component: FeatureLandingPage,
    title: "애니멀 토템 카드 리딩",
    h1: "애니멀 토템 리딩",
    description: "수호 동물 메시지를 카드 리딩 형태로 제공하는 토템 서비스 안내 페이지.",
    seoText: "애니멀 토템은 지금의 감정 상태와 방향성을 상징 메시지로 풀어줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/animaltotem.webp",
    landingPoints: ["수호 동물 메시지", "카드 기반 직관 리딩", "현재 상태 점검"],
    keywords: [
      "애니멀 토템",
      "토템 카드",
      "수호 동물",
      "animal totem",
      "토템 리딩",
    ],
  },
  "tarot/self-esteem": {
    component: FeatureLandingPage,
    title: "자존감 레벨업 타로 - 나를 다시 세우는 5카드",
    h1: "자존감 레벨업 타로",
    description: "눈치를 보게 되는 마음의 패턴, 아직 남아 있는 강점, 오늘 회복할 수 있는 작은 미션을 5장의 카드로 읽습니다.",
    seoText: "자존감 레벨업 타로는 낮아진 자기 확신을 부드럽게 회복하도록 내면의 강점과 오늘의 실천 문장을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/jajongam.webp",
    landingPoints: ["눈치 보는 패턴", "내면의 강점 확인", "오늘의 회복 미션"],
    keywords: [
      "자존감 타로",
      "5카드 타로",
      "자존감 회복 타로",
      "self esteem tarot",
      "성장 타로",
    ],
  },
  "tarot/reunion": {
    component: FeatureLandingPage,
    title: "재회운 등대 타로 - 다시 닿아도 안전한 거리",
    h1: "재회운 등대 타로",
    description: "그리움과 현실 사이에서 다시 닿아도 무너지지 않을 거리, 타이밍, 첫 문장을 5장의 카드로 읽습니다.",
    seoText: "재회운 등대 타로는 남은 마음의 온도와 연락을 막는 현실 파도를 분리해, 다시 닿기 전의 안전 기준을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/reunion.webp",
    landingPoints: ["남은 마음의 온도", "연락을 막는 파도", "부담 없는 첫 문장"],
    keywords: [
      "재회운 타로",
      "재회 타로",
      "5카드 스프레드",
      "연애 재회",
      "reunion tarot",
    ],
  },
  "tarot/year": {
    component: FeatureLandingPage,
    title: "십이지신 천운 타로 - 열두 달의 수호 리듬",
    h1: "십이지신 천운 타로",
    description: "열두 수호 기운과 12장의 카드를 엮어 한 해의 상승 구간, 속도 조절이 필요한 달, 월별 선택을 읽습니다.",
    seoText: "십이지신 천운 타로는 월별 수호 리듬과 카드 상징을 연결해 한 해의 흐름과 조율 포인트를 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/12animals.webp",
    landingPoints: ["열두 달의 수호 리듬", "상승과 속도 조절의 달", "월별 선택의 작은 의식"],
    keywords: [
      "십이지신",
      "천운 타로",
      "12개월 운세",
      "연간 운세",
      "zodiac year tarot",
    ],
  },
  "oracle/hwatu": {
    component: FeatureLandingPage,
    title: "타짜들의 화투점 - 12달 화투패 운세",
    h1: "타짜들의 화투점",
    description: "화투 상징을 바탕으로 월별 운세 흐름을 해석하는 서비스 안내 페이지.",
    seoText: "화투점은 한국 전통 상징을 현대적으로 해석한 운세 콘텐츠입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tazza.webp",
    landingPoints: ["전통 화투 상징 해석", "12달 흐름 점검", "간편 운세 콘텐츠"],
    keywords: [
      "화투점",
      "타짜 화투",
      "12달 운세",
      "한국 전통 운세",
      "hwatu fortune",
    ],
  },
  "oracle/kemet": {
    component: FeatureLandingPage,
    title: "고대 이집트 신탁 - 케멧 오라클",
    h1: "고대 이집트 신탁",
    description: "케멧 오라클 상징 기반으로 메시지를 읽는 신탁 서비스 안내 페이지.",
    seoText: "이집트 신탁은 상징 중심 질문-응답 방식의 오라클 리딩을 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/egypt.webp",
    landingPoints: ["오라클 상징 리딩", "질문 중심 해석", "직관 메시지 제공"],
    keywords: [
      "이집트 신탁",
      "케멧 오라클",
      "Kemet Oracle",
      "고대 이집트",
      "oracle reading",
    ],
  },
  "oracle/juyuk": {
    component: FeatureLandingPage,
    title: "주역 거북점 - 64괘 해석",
    h1: "주역 거북점",
    description: "주역 64괘의 상징 체계로 현재 흐름을 해석하는 서비스 안내 페이지.",
    seoText: "주역 거북점은 고전 괘상 해석을 바탕으로 의사결정 힌트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/juyuk.webp",
    landingPoints: ["64괘 상징 해석", "상황 판단 힌트", "고전 기반 리딩"],
    keywords: [
      "주역",
      "64괘",
      "거북점",
      "I Ching",
      "역점",
    ],
  },
  "oracle/sukuyo": {
    component: FeatureLandingPage,
    title: "숙요점 - 27수 별자리 운명",
    h1: "숙요점",
    description: "27수 별자리 체계로 성향과 관계 흐름을 읽는 숙요 서비스 안내 페이지.",
    seoText: "숙요점은 동아시아 달력 전통의 27수 체계를 활용한 운세 분석입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/sukyo.webp",
    landingPoints: ["27수 별자리 해석", "성향·관계 흐름", "전통 달력 기반 분석"],
    keywords: [
      "숙요점",
      "宿曜",
      "27수",
      "숙요도",
      "Sukuyo",
    ],
  },
  "oracle/rune": {
    componentKey: "stonehengeRune",
    title: "스톤헨지 룬 오라클 - Stonehenge Rune",
    h1: "스톤헨지 룬 오라클",
    description: "고대 룬 상징으로 현재 흐름과 연간 운세를 읽는 스톤헨지 룬 신탁 서비스입니다.",
    seoText: "스톤헨지 룬 오라클은 1/3/5/12 룬 스프레드를 통해 상황별 통찰과 실행 힌트를 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/rune.webp",
    landingPoints: ["1/3/5/12 룬 스프레드", "정·역방향 룬 해석", "연간 흐름 리딩"],
    keywords: [
      "룬 점",
      "스톤헨지 룬",
      "Rune Oracle",
      "북유럽 룬",
      "rune reading",
    ],
  },
  "vedic/jyotish": {
    component: FeatureLandingPage,
    title: "베다 점성술 - Jyotish 차트",
    h1: "베다 점성술 (Jyotish)",
    description: "낙샤트라와 다샤 체계를 중심으로 읽는 베다 점성술 서비스 안내 페이지.",
    seoText: "베다 점성술은 인도 점성술 전통의 별자리·주기 체계를 해석에 활용합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/veda.webp",
    landingPoints: ["낙샤트라/다샤 해석", "베다 전통 차트", "장기 흐름 점검"],
    keywords: [
      "베다 점성술",
      "Jyotish",
      "자이오티시",
      "낙샤트라",
      "다샤",
      "vedic astrology",
    ],
  },
  "flower/destiny": {
    component: FeatureLandingPage,
    title: "운명의 꽃 - 통합 아틀리에",
    h1: "운명의 꽃 아틀리에",
    description: "사주·점성술·자미두수·숙요 데이터를 소스별 탭으로 전환해 운명의 꽃을 시각화하는 안내 페이지.",
    seoText: "운명의 꽃 아틀리에는 사주/점성술/자미두수/숙요 엔진 결과를 기반으로 꽃, 팔레트, 해석 패널을 생성합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower.webp",
    landingPoints: ["4개 운세 소스 탭 전환", "소스별 꽃·키워드·해석 패널", "프롬프트/저장/공유 도구"],
    keywords: [
      "운명의 꽃",
      "사주 꽃",
      "점성술 꽃",
      "자미두수 꽃",
      "숙요 꽃",
      "destiny flower",
    ],
  },
  "flower/astrology": {
    component: FeatureLandingPage,
    title: "점성술 운명의 꽃",
    h1: "점성술 운명의 꽃",
    description: "태양궁 중심 매핑에 상승궁·달궁 보조 신호를 더해 꽃 결과를 생성하는 점성술 꽃 안내 페이지.",
    seoText: "점성술 운명의 꽃은 태양궁으로 꽃을 선택하고, 상승궁·달궁은 분위기/해석 패널을 보강하는 구조입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower2.webp",
    landingPoints: ["태양궁 중심 꽃 매핑", "상승궁·달궁 보조 시그널", "성운 테마 시각화/공유"],
    keywords: [
      "점성술 운명의 꽃",
      "네온 성운",
      "natal flower",
      "astrology flower",
    ],
  },
  "flower/jamidusu": {
    component: FeatureLandingPage,
    title: "자미두수 운명의 꽃",
    h1: "자미두수 운명의 꽃",
    description: "명궁·주성(주요 별)·밝기 정보를 기반으로 꽃과 테마를 합성하는 자미두수 꽃 안내 페이지.",
    seoText: "자미두수 운명의 꽃은 명궁 힌트와 주성 규칙, 밝기 강도를 반영해 꽃 팔레트와 해석을 생성합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower3.webp",
    landingPoints: ["명궁/주성 기반 꽃 산출", "밝기 강도 반영 테마", "자미두수 해석 패널"],
    keywords: [
      "자미두수 꽃",
      "紫微 꽃",
      "명궁 꽃",
      "ziwei flower",
    ],
  },
  "flower/sukuyo": {
    component: FeatureLandingPage,
    title: "숙요 운명의 꽃",
    h1: "숙요 운명의 꽃",
    description: "숙요 27수(숙명)와 월상 정보를 바탕으로 달빛 테마 꽃을 생성하는 안내 페이지.",
    seoText: "숙요 운명의 꽃은 숙요 27수 인덱스/별칭 해석과 월상 보정으로 꽃·키워드·의식을 구성합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/flower4.webp",
    landingPoints: ["27수 기반 꽃 매칭", "달 위상 보정 시각화", "숙요 해석/가이드 패널"],
    keywords: [
      "숙요 꽃",
      "27숙",
      "달 꽃",
      "sukuyo flower",
    ],
  },
  "dream/tarot": {
    component: FeatureLandingPage,
    title: "드림 타로 - 꿈의 잔향을 여는 3카드 리딩",
    h1: "드림 타로",
    description: "꿈속 장면과 깨어난 뒤의 감정을 세 장의 카드에 겹쳐, 무의식이 남긴 상징과 오늘 봉인할 선택을 읽습니다.",
    seoText: "드림 타로는 꿈속 장면, 감정의 잔향, 반복 상징을 카드의 언어로 옮겨 오늘의 회복 방향을 정리합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/heamong.webp",
    landingPoints: ["꿈 장면의 상징 카드", "깨어난 뒤 감정의 잔향", "오늘 봉인할 작은 선택"],
    keywords: [
      "드림 타로",
      "꿈 카드 리딩",
      "꿈 해석",
      "dream tarot",
      "dream interpretation",
    ],
  },
  "dream/psycho": {
    component: FeatureLandingPage,
    title: "정신분석 해몽 - Freud Study",
    h1: "정신분석 해몽",
    description: "프로이트 관점으로 꿈 내용을 구조화해 해석하는 서비스 안내 페이지.",
    seoText: "정신분석 해몽은 무의식 상징을 중심으로 심리적 맥락을 읽어줍니다.",
    ogImage: "https://code-destiny.com/fuctionassets/phydream.webp",
    landingPoints: ["프로이트 관점 해석", "무의식 상징 분석", "심리 맥락 리포트"],
    keywords: [
      "정신분석 해몽",
      "프로이트",
      "꿈 분석",
      "psychoanalysis dream",
      "Freud dream",
    ],
  },
  /* ── 신규 서비스 엔트리 ── */
  "oracle/hwatu-life": {
    component: FeatureLandingPage,
    title: "화투 인생 패 테스트 - 7문항 심리테스트",
    h1: "화투 인생 패 테스트",
    description: "돈·사랑·위기 상황에서의 선택 패턴을 통해 나를 상징하는 화투 인생 패 아키타입을 찾아주는 심리테스트.",
    seoText: "화투 인생 패 테스트는 7문항 심리테스트로 삼광·고도리·청단·똑광 아키타입을 찾아드립니다.",
    ogImage: "https://code-destiny.com/fuctionassets/tazza.webp",
    landingPoints: ["7문항 심리테스트", "화투 인생 패 아키타입 파악", "조건별 선택 패턴 분석"],
    keywords: [
      "화투",
      "화투 인생 패",
      "심리테스트",
      "아키타입 테스트",
      "hwatu life test",
    ],
  },
  "oracle/sikojen-povailu": {
    component: FeatureLandingPage,
    title: "핀란드 주석점 Sikojen Povailu",
    h1: "핀란드 주석점",
    description:
      "핀란드 전통 주석점(낙점) 의식을 무료로 체험하세요. 낙이 물에서 굳는 형태로 미래를 읽는 5단게 인터랙티브 오라클.",
    seoText:
      "핀란드 주석점은 5단계 인터랙티브 의식으로 낙 형태 상징을 해석하고 Shadow Reading까지 제공합니다.",
    ogImage: "https://code-destiny.com/icons/꿀꿀 운세 로고.webp",
    landingPoints: ["5단계 인터랙티브 의식", "낙 형태 상징 해석", "Shadow Reading 제공"],
    keywords: [
      "핀란드 주석점",
      "Sikojen Povailu",
      "낙점",
      "핀란드 신탁",
      "tin casting oracle",
    ],
  },
  "oracle/ifa": {
    component: FeatureLandingPage,
    title: "IFA 오라클 - 요루바 256 오두 신탁",
    h1: "IFA 오라클",
    description:
      "요루바 전통 256 오두 체계를 기반으로 질문의 흐름을 읽는 IFA 오라클 안내 페이지입니다.",
    seoText:
      "IFA 오라클은 상징 조합과 질문 맥락을 연결해 연애·재물·건강 흐름을 해석하는 인터랙티브 신탁 서비스입니다.",
    ogImage: "https://code-destiny.com/fuctionassets/ifafortune.webp",
    landingPoints: ["256 오두 전통 해석", "질문 맥락형 오라클", "회차당 30코인 리딩"],
    keywords: [
      "IFA 오라클",
      "이파 점술",
      "요루바 신탁",
      "256 오두",
      "ifa oracle",
    ],
  },
  "oracle/royal-tea": {
    component: FeatureLandingPage,
    title: "타세오그래피 찻잎 점 - 랰던 로열 컵 문양 리딩",
    h1: "타세오그래피 찻잎 점",
    description:
      "랰던 로열 컵 문양을 기반으로 상징을 해석하는 영국 홀차 찻잎 점 오라클 리딩 서비스.",
    seoText:
      "타세오그래피는 타 컵 내에 남은 찻잎 패턴으로 미래를 읽는 유럽 전통 점술입니다.",
    ogImage: "/fuctionassets/london.webp",
    landingPoints: ["랰던 로열 컵 문양 리딩", "영국 홀차 전통 점술", "상징 해석 오라클"],
    keywords: [
      "타세오그래피",
      "찻잎 점",
      "로열 컵",
      "tasseography",
      "tea leaf reading",
    ],
  },
  "saju/love-simulation": {
    componentKey: "loveSimulation",
    title: "LOVE CODE - 사주 연애 시뮬레이션",
    h1: "LOVE CODE 사주 연애 시뮬레이션",
    description:
      "상대방의 생년월일로 사주를 분석해 페르소나 캐릭터를 만들고, 데이트 코스·선택지를 통해 상대방의 취향과 성격을 미리 경험해보는 사주 연애 시뮬레이션.",
    seoText:
      "LOVE CODE는 명리학 기반 사주 분석으로 상대방의 오행·일간·MBTI를 파악한 뒤 데이트 시나리오 시뮬레이션을 제공합니다.",
    ogImage: "https://code-destiny.com/fuctionassets/love%20code.webp",
    landingPoints: [
      "상대방 생년월일 사주 분석",
      "오행·일간 기반 페르소나 생성",
      "데이트 코스 선택지 시뮬레이션",
    ],
    keywords: [
      "연애 시뮬레이션",
      "사주 연애",
      "상대방 사주 분석",
      "데이트 시뮬레이션",
      "love simulation",
      "사주 궁합 게임",
    ],
  },
};

export function getService(slug) {
  return SERVICE_MAP[slug] ?? null;
}
