const SERVICE_SECTION_DEFINITIONS = [
  {
    id: "saju",
    fallbackTitle: "사주 & 명리",
    items: [
      { href: "/saju/basic", fallbackTitle: "사주 만세력 기본 해석", fallbackDesc: "오행·십성 기반 명식 분석 · 무료", isStaticCanonical: true },
      { href: "/saju/sibyl", fallbackTitle: "시빌라 시스템", fallbackDesc: "사주 기반 진로 적성 × 운명 위험 계수 · 기본 무료", isStaticCanonical: true },
      { href: "/life-book-ai", aliases: ["/saju/lifebook"], fallbackTitle: "인생의 책 전문가 상담", fallbackDesc: "삶의 흐름을 읽는 1:1 상담 · 30,000원 / 인생 총운 50,000원", isStaticCanonical: true },
      { href: "/love-secret-ai", fallbackTitle: "연애 비책 전문가 상담", fallbackDesc: "명리학 기반 1:1 연애 상담 · 30,000원" },
      { href: "/master-love-codex", fallbackTitle: "마스터 인연의 서", fallbackDesc: "사주×자미두수 융합 20장 연애 전략서 · 개인 1회 30,000원 / 상대와의 궁합 50,000원" },
      { href: "/naming-ai", fallbackTitle: "훈민정음 작명소", fallbackDesc: "사주 맞춤 프리미엄 전문가 작명 · 30,000원" },
      { href: "/saju/love-simulation", fallbackTitle: "LOVE CODE", fallbackDesc: "사주 연애 시뮬레이션 · 잠금 해제 10,000원", isStaticCanonical: true },
      { href: "/saju/destiny-bias", fallbackTitle: "최애운명", fallbackDesc: "사주 기반 팬덤 공명 분석 · 1회 5,000원" },
      { href: "/saju/animal-destiny", aliases: ["/saju/animal-test"], fallbackTitle: "십이운성 동물점", fallbackDesc: "사주 속 십이운성으로 깨어나는 나만의 수호 동물 · 해금 10,000원", isStaticCanonical: true },
      { href: "/saju/destiny-meeting-place", fallbackTitle: "사주로 보는 인연의 장소", fallbackDesc: "인연 장소·도시·타이밍 독립 분석 · 1회 10,000원", isStaticCanonical: true },
    ],
  },
  {
    id: "core",
    fallbackTitle: "동서양 명리",
    items: [
      { href: "/ziwei/chart", fallbackTitle: "자미두수 명반", fallbackDesc: "기본 서비스 무료 · 궁합 5,000원", isStaticCanonical: true },
      { href: "/astrology/cosmic", fallbackTitle: "점성술 코즈믹", fallbackDesc: "기본 서비스 무료 · 궁합 5,000원", isStaticCanonical: true },
      { href: "/vedic/jyotish", fallbackTitle: "베다 점성술", fallbackDesc: "기본 서비스 무료 · 궁합 5,000원", isStaticCanonical: true },
    ],
  },
  {
    id: "tarot",
    fallbackTitle: "타로 리딩",
    items: [
      { href: "/tarot/mingri", fallbackTitle: "명리학 타로", fallbackDesc: "카드와 십성을 잇는 리딩 · 무료", isStaticCanonical: true },
      { href: "/tarot/love", fallbackTitle: "우리는 무슨 사이?", fallbackDesc: "6카드 연애 관계 리딩 · 5,000원", isStaticCanonical: true },
      {
        href: "/tarot/prompt-maker",
        fallbackTitle: "타로 프롬프트 라이브러리",
        fallbackDesc: "질문 설계 + 카드 드로우 + 오라클 문장 정리 · 영구 해금 10,000원 · 63 스프레드",
        image: "/fuctionassets/연애 재회 타로 프롬프트 메이커.webp",
        fallbackAlt: "타로 프롬프트 라이브러리",
      },
      { href: "/tarot/healing", fallbackTitle: "따뜻한 태양 회복 타로", fallbackDesc: "감정 온도와 회복 루틴 · 무료" },
      { href: "/tarot/self-esteem", fallbackTitle: "자존감 레벨업", fallbackDesc: "나를 다시 세우는 5카드 · 무료", isStaticCanonical: true },
      { href: "/tarot/reunion", fallbackTitle: "재회운 등대 타로", fallbackDesc: "다시 닿아도 안전한 거리 · 5,000원", isStaticCanonical: true },
      { href: "/tarot/year", fallbackTitle: "십이지신 천운 타로", fallbackDesc: "1년 총운·12개월 월별 리딩 · 10,000원", isStaticCanonical: true },
      { href: "/tarot/crystal-soul/", fallbackTitle: "원석 소울 타로", fallbackDesc: "원석과 카드의 결 리딩 · 5,000원" },
      { href: "/tarot/mindscan/", fallbackTitle: "속마음 알아보기", fallbackDesc: "겉말과 속마음의 간격 리딩 · 5,000원" },
      { href: "/celestial-harmony.html", fallbackTitle: "천체의 선율", fallbackDesc: "행성 11카드 코즈믹 리딩 · 10,000원" },
      { href: "/tarot-ijik.html", fallbackTitle: "이직 운명의 카드", fallbackDesc: "7카드 커리어 스프레드 · 5,000원" },
    ],
  },
  {
    id: "oracle",
    fallbackTitle: "신탁 & 해몽",
    items: [
      { href: "/oracle/hwatu", fallbackTitle: "타짜들의 화투점", fallbackDesc: "12달 화투패 운세", isStaticCanonical: true },
      { href: "/oracle/hwatu-life", fallbackTitle: "화투 인생 패 테스트", fallbackDesc: "타짜 컨셉 7문항 심리테스트" },
      { href: "/ifa-oracle.html", aliases: ["/oracle/ifa"], fallbackTitle: "IFA 오라클", fallbackDesc: "요루바 256 오두 신탁 · 3,000원", isStaticCanonical: true },
      { href: "/oracle/kemet", fallbackTitle: "고대 이집트 신탁", fallbackDesc: "케멧 오라클 리딩" },
      { href: "/oracle/juyuk", fallbackTitle: "주역 거북점", fallbackDesc: "64괘 상징 해석", isStaticCanonical: true },
      { href: "/oracle/sukuyo", fallbackTitle: "숙요점", fallbackDesc: "기본 서비스 무료 · 궁합 5,000원", isStaticCanonical: true },
      { href: "/oracle/rune", fallbackTitle: "스톤헨지 룬 오라클", fallbackDesc: "고대 룬 상징 리딩" },
      { href: "/geomancy-oracle-v4.html", fallbackTitle: "지오맨시 흙점", fallbackDesc: "대지의 징후 16행 신탁" },
      { href: "/royal-tea-oracle.html", fallbackTitle: "타세오그래피 찻잎 점", fallbackDesc: "런던 로열 컵 문양 리딩" },
      { href: "/destiny-poker.html", fallbackTitle: "데스티니 포커", fallbackDesc: "신들과 벌이는 운명의 카드 대결" },
      { href: "/dream/tarot", fallbackTitle: "드림 타로", fallbackDesc: "꿈 문장 AI 프롬프트" },
      { href: "/dream/psycho", fallbackTitle: "정신분석 해몽", fallbackDesc: "프로이트 관점 해석" },
    ],
  },
  {
    id: "special",
    fallbackTitle: "특별 콘텐츠",
    items: [
      { href: "/secret-house_real.html", fallbackTitle: "나는 솔로 시크릿 하우스", fallbackDesc: "자동 일간 캐치 연애 시뮬" },
      { href: "/animal/physio", fallbackTitle: "전문가 동물 관상", fallbackDesc: "셀카 얼굴형 분석" },
      { href: "/animal/mbti", fallbackTitle: "MBTI 동물 궁합", fallbackDesc: "16유형 케미 분석" },
      { href: "/animal/totem", fallbackTitle: "애니멀 토템", fallbackDesc: "수호 동물 메시지" },
      { href: "/flower/destiny", fallbackTitle: "운명의 꽃", fallbackDesc: "통합 아틀리에" },
      { href: "/flower/astrology", fallbackTitle: "점성술 꽃", fallbackDesc: "성운 테마 시각화" },
      { href: "/flower/jamidusu", fallbackTitle: "자미두수 꽃", fallbackDesc: "명궁 테마 리포트" },
      { href: "/flower/sukuyo", fallbackTitle: "숙요 꽃", fallbackDesc: "달 위상 기반 꽃" },
    ],
  },
  {
    // 위 섹션들에 없던 상시 서비스 · AI 상담 라인업. /all-fortunes 허브에서 함께 노출한다.
    id: "signature",
    fallbackTitle: "대표 서비스 & AI 상담",
    items: [
      { href: "/today", fallbackTitle: "오늘의 운세", fallbackDesc: "매일 새로 갱신되는 하루 운세 · 무료" },
      { href: "/destiny-compass", fallbackTitle: "운명의 지도", fallbackDesc: "인생의 흐름을 한 장의 지도로" },
      { href: "/island-consult", fallbackTitle: "운명의 섬", fallbackDesc: "명반을 섬으로 읽는 상담" },
      { href: "/fortune-tea-house", fallbackTitle: "운명 찻집", fallbackDesc: "연이와 함께 보는 타로·사주 상담" },
      { href: "/neo-operation-room", fallbackTitle: "네오 전략실", fallbackDesc: "네오와 짜는 실행 전략 상담" },
      { href: "/palm-reading", fallbackTitle: "손금 리딩", fallbackDesc: "손바닥 선으로 읽는 기질과 흐름" },
      { href: "/saju-guardian", fallbackTitle: "사주 수호신", fallbackDesc: "십성으로 찾는 나의 수호신" },
      { href: "/ziwei-ai", fallbackTitle: "자미두수 전문가 상담", fallbackDesc: "명반 기반 1:1 심층 상담" },
      { href: "/astrology-ai", fallbackTitle: "점성술 전문가 상담", fallbackDesc: "출생 차트 기반 1:1 상담" },
      { href: "/vedic-ai", fallbackTitle: "베다 점성술 전문가 상담", fallbackDesc: "다샤·나크샤트라 심층 상담" },
      { href: "/sukuyo-compatibility-ai", fallbackTitle: "숙요 궁합 전문가 상담", fallbackDesc: "27수 기반 관계 상담" },
    ],
  },
];

const SERVICE_SECTION_TRANSLATIONS = {
  en: [
    {
      title: "Saju & Myeongri",
      items: [
        ["Basic Saju Manse Calendar Reading", "Five elements and Ten Gods birth chart analysis · Free"],
        ["Sibyl System", "Saju career aptitude and destiny risk coefficient · Basic free"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Love Secret Strategy", "Saju-based love strategy · Solo KRW 30,000 / compatibility +KRW 10,000 (total KRW 40,000)"],
        ["LOVE CODE", "Saju love simulation · Unlock KRW 10,000"],
        ["Destiny Bias", "Saju-based fandom resonance analysis · KRW 5,000 per reading"],
        ["Twelve Growth Animal Oracle", "Your guardian animal awakened through Twelve Growth Stars in Saju · Unlock KRW 10,000"],
        ["Destined Meeting Place by Saju", "Independent reading for relationship places, cities, and timing · KRW 10,000 per reading"],
      ],
    },
    {
      title: "Eastern & Western Fate Systems",
      items: [
        ["Zi Wei Dou Shu Chart", "Basic service free · Compatibility KRW 5,000"],
        ["Cosmic Astrology", "Basic service free · Compatibility KRW 5,000"],
        ["Vedic Astrology", "Basic service free · Compatibility KRW 5,000"],
      ],
    },
    {
      title: "Tarot Readings",
      items: [
        ["Myeongri Tarot", "A reading that connects cards and Ten Gods · Free"],
        ["What Are We?", "6-card love relationship reading · KRW 5,000"],
        ["Tarot Prompt Library", "Question design, card draw, and oracle sentence summary · KRW 5,000 per use · 63 spreads", "Tarot Prompt Library"],
        ["Warm Sun Healing Tarot", "Emotional temperature and recovery routines · Free"],
        ["Self-Esteem Level Up", "A 5-card reading that helps you stand again · Free"],
        ["Reunion Lighthouse Tarot", "The safe distance for reconnecting · KRW 5,000"],
        ["Twelve Zodiac Heavenly Luck Tarot", "Yearly overview and twelve monthly readings · KRW 10,000"],
        ["Crystal Soul Tarot", "Stone and card texture reading · KRW 5,000"],
        ["Mind Scan Tarot", "Reading the gap between spoken words and inner feelings · KRW 5,000"],
        ["Celestial Harmony", "11-card planetary cosmic reading · KRW 10,000"],
        ["Career Change Destiny Cards", "7-card career spread · KRW 5,000"],
      ],
    },
    {
      title: "Oracles & Dreams",
      items: [
        ["Hwatu Oracle of Card Masters", "12-month Hwatu card fortune"],
        ["Hwatu Life Card Test", "7-question psychology test with a card-master concept"],
        ["IFA Oracle", "Yoruba 256 Odu oracle · KRW 3,000"],
        ["Ancient Egyptian Oracle", "Kemet oracle reading"],
        ["I Ching Turtle Oracle", "64 hexagram symbolic reading"],
        ["Sukuyo Astrology", "Basic service free · Compatibility KRW 5,000"],
        ["Stonehenge Rune Oracle", "Ancient rune symbol reading"],
        ["Geomancy Earth Oracle", "16-line earth sign oracle"],
        ["Tasseography Tea Leaf Oracle", "London royal cup pattern reading"],
        ["Destiny Poker", "A destiny card duel with the gods"],
        ["Dream Tarot", "AI prompt from dream sentences"],
        ["Psychoanalytic Dream Reading", "Freudian interpretation"],
      ],
    },
    {
      title: "Special Content",
      items: [
        ["I Am Solo Secret House", "Automatic daily love-catch simulation"],
        ["AI Animal Face Reading", "Selfie face-shape analysis"],
        ["MBTI Animal Compatibility", "16-type chemistry analysis"],
        ["Animal Totem", "Guardian animal message"],
        ["Destiny Flower", "Integrated atelier"],
        ["Astrology Flower", "Nebula-themed visualization"],
        ["Zi Wei Flower", "Life palace themed report"],
        ["Sukuyo Flower", "Moon-phase based flower"],
      ],
    },
  ],
  ja: [
    {
      title: "四柱推命・命理",
      items: [
        ["四柱推命 万歳暦 基本解釈", "五行・十神にもとづく命式分析 · 無料"],
        ["シビュラシステム", "四柱推命ベースの適職適性 × 運命リスク係数 · 基本無料"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["恋愛秘策", "四柱推命ベースの恋愛戦略 · 1名 30,000ウォン / 相性 +10,000ウォン（合計 40,000ウォン）"],
        ["LOVE CODE", "四柱推命恋愛シミュレーション · 解錠 10,000ウォン"],
        ["推し運命", "四柱推命ベースのファンダム共鳴分析 · 1回 5,000ウォン"],
        ["十二運星どうぶつ占い", "四柱推命の十二運星から目覚める私だけの守護動物 · 解錠 10,000ウォン"],
        ["四柱推命で見る縁の場所", "縁の場所・都市・タイミング独立分析 · 1回 10,000ウォン"],
      ],
    },
    {
      title: "東西の命理",
      items: [
        ["紫微斗数命盤", "基本サービス無料 · 相性 5,000ウォン"],
        ["コズミック占星術", "基本サービス無料 · 相性 5,000ウォン"],
        ["ヴェーダ占星術", "基本サービス無料 · 相性 5,000ウォン"],
      ],
    },
    {
      title: "タロットリーディング",
      items: [
        ["命理タロット", "カードと十神をつなぐリーディング · 無料"],
        ["私たちはどんな関係？", "6枚カード恋愛関係リーディング · 5,000ウォン"],
        ["タロットプロンプトライブラリ", "質問設計 + カードドロー + オラクル文整理 · 1回 5,000ウォン · 63スプレッド", "タロットプロンプトライブラリ"],
        ["あたたかな太陽回復タロット", "感情の温度と回復ルーティン · 無料"],
        ["自己肯定感レベルアップ", "自分をもう一度立て直す5枚カード · 無料"],
        ["復縁運 灯台タロット", "もう一度届いても安全な距離 · 5,000ウォン"],
        ["十二支天運タロット", "1年の総運と12か月の月別リーディング · 10,000ウォン"],
        ["クリスタルソウルタロット", "天然石とカードの質感リーディング · 5,000ウォン"],
        ["本音を読むタロット", "表の言葉と本音の距離を読む · 5,000ウォン"],
        ["天体の旋律", "惑星11カード コズミックリーディング · 10,000ウォン"],
        ["転職運命のカード", "7枚カード キャリアスプレッド · 5,000ウォン"],
      ],
    },
    {
      title: "神託・夢占い",
      items: [
        ["花札師たちの花札占い", "12か月花札運勢"],
        ["花札人生カードテスト", "勝負師コンセプトの7問心理テスト"],
        ["IFAオラクル", "ヨルバ256オドゥ神託 · 3,000ウォン"],
        ["古代エジプト神託", "ケメトオラクルリーディング"],
        ["易経亀占い", "64卦象徴解釈"],
        ["宿曜占星術", "基本サービス無料 · 相性 5,000ウォン"],
        ["ストーンヘンジ ルーンオラクル", "古代ルーン象徴リーディング"],
        ["ジオマンシー土占い", "大地の兆し16行神託"],
        ["タッセオグラフィー茶葉占い", "ロンドンロイヤルカップ文様リーディング"],
        ["デスティニーポーカー", "神々と挑む運命のカード対決"],
        ["ドリームプロンプト", "夢の文章AIプロンプト"],
        ["精神分析夢占い", "フロイト視点の解釈"],
      ],
    },
    {
      title: "特別コンテンツ",
      items: [
        ["私はソロ Secret House", "自動日干キャッチ恋愛シミュレーション"],
        ["AIどうぶつ人相", "セルフィー顔型分析"],
        ["MBTIどうぶつ相性", "16タイプのケミ分析"],
        ["アニマルトーテム", "守護動物メッセージ"],
        ["運命の花", "統合アトリエ"],
        ["占星術の花", "星雲テーマ視覚化"],
        ["紫微斗数の花", "命宮テーマレポート"],
        ["宿曜の花", "月相ベースの花"],
      ],
    },
  ],
  "zh-CN": [
    {
      title: "八字与命理",
      items: [
        ["八字万年历基础解读", "五行·十神命式分析 · 免费"],
        ["西比拉系统", "基于八字的职业适性 × 命运风险系数 · 基础免费"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["恋爱秘籍", "八字恋爱策略 · 单人30,000韩元 / 合盘 +10,000韩元（共40,000韩元）"],
        ["LOVE CODE", "八字恋爱模拟 · 解锁10,000韩元"],
        ["本命偏爱", "基于八字的粉丝共鸣分析 · 每次5,000韩元"],
        ["十二运星动物占", "从八字十二运星唤醒你的守护动物 · 解锁10,000韩元"],
        ["八字中的缘分地点", "缘分地点、城市与时机独立分析 · 每次10,000韩元"],
      ],
    },
    {
      title: "东西方命理",
      items: [
        ["紫微斗数命盘", "基础服务免费 · 合盘5,000韩元"],
        ["宇宙占星术", "基础服务免费 · 合盘5,000韩元"],
        ["吠陀占星术", "基础服务免费 · 合盘5,000韩元"],
      ],
    },
    {
      title: "塔罗解读",
      items: [
        ["命理塔罗", "连接卡牌与十神的解读 · 免费"],
        ["我们是什么关系？", "6张牌恋爱关系解读 · 5,000韩元"],
        ["塔罗提示词库", "问题设计 + 抽牌 + 神谕句整理 · 每次5,000韩元 · 63个牌阵", "塔罗提示词库"],
        ["暖阳疗愈塔罗", "情绪温度与恢复日常 · 免费"],
        ["自尊感升级", "重新支撑自己的5张牌 · 免费"],
        ["复合灯塔塔罗", "再次靠近也安全的距离 · 5,000韩元"],
        ["十二生肖天运塔罗", "年度总运与十二个月月度解读 · 10,000韩元"],
        ["水晶灵魂塔罗", "原石与卡牌质感解读 · 5,000韩元"],
        ["内心扫描塔罗", "读取表面话语与真实心意的距离 · 5,000韩元"],
        ["天体的旋律", "行星11张牌宇宙解读 · 10,000韩元"],
        ["转职命运卡牌", "7张牌职业牌阵 · 5,000韩元"],
      ],
    },
    {
      title: "神谕与解梦",
      items: [
        ["牌手花札占", "12个月花札牌运势"],
        ["花札人生牌测试", "牌手概念7题心理测试"],
        ["IFA神谕", "约鲁巴256奥杜神谕 · 3,000韩元"],
        ["古埃及神谕", "凯美特神谕解读"],
        ["周易龟占", "64卦象征解读"],
        ["宿曜占星", "基础服务免费 · 合盘5,000韩元"],
        ["巨石阵卢恩神谕", "古代卢恩象征解读"],
        ["地占土之神谕", "大地征兆16行神谕"],
        ["茶叶占卜", "伦敦皇家杯纹样解读"],
        ["命运扑克", "与诸神展开的命运卡牌对决"],
        ["梦境塔罗", "梦句AI提示词"],
        ["精神分析解梦", "弗洛伊德视角解读"],
      ],
    },
    {
      title: "特别内容",
      items: [
        ["我是Solo秘密之家", "自动日干捕捉恋爱模拟"],
        ["AI动物面相", "自拍脸型分析"],
        ["MBTI动物合盘", "16型化学反应分析"],
        ["动物图腾", "守护动物讯息"],
        ["命运之花", "综合工作室"],
        ["占星花", "星云主题视觉化"],
        ["紫微斗数花", "命宫主题报告"],
        ["宿曜花", "月相基础花朵"],
      ],
    },
  ],
  "zh-TW": [
    {
      title: "八字與命理",
      items: [
        ["八字萬年曆基礎解讀", "五行·十神命式分析 · 免費"],
        ["西比拉系統", "基於八字的職業適性 × 命運風險係數 · 基礎免費"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["戀愛祕策", "八字戀愛策略 · 單人30,000韓元 / 合盤 +10,000韓元（共40,000韓元）"],
        ["LOVE CODE", "八字戀愛模擬 · 解鎖10,000韓元"],
        ["本命偏愛", "基於八字的粉絲共鳴分析 · 每次5,000韓元"],
        ["十二運星動物占", "從八字十二運星喚醒你的守護動物 · 解鎖10,000韓元"],
        ["八字中的緣分地點", "緣分地點、城市與時機獨立分析 · 每次10,000韓元"],
      ],
    },
    {
      title: "東西方命理",
      items: [
        ["紫微斗數命盤", "基礎服務免費 · 合盤5,000韓元"],
        ["宇宙占星術", "基礎服務免費 · 合盤5,000韓元"],
        ["吠陀占星術", "基礎服務免費 · 合盤5,000韓元"],
      ],
    },
    {
      title: "塔羅解讀",
      items: [
        ["命理塔羅", "連接卡牌與十神的解讀 · 免費"],
        ["我們是什麼關係？", "6張牌戀愛關係解讀 · 5,000韓元"],
        ["塔羅提示詞庫", "問題設計 + 抽牌 + 神諭句整理 · 每次5,000韓元 · 63個牌陣", "塔羅提示詞庫"],
        ["暖陽療癒塔羅", "情緒溫度與恢復日常 · 免費"],
        ["自尊感升級", "重新支撐自己的5張牌 · 免費"],
        ["復合燈塔塔羅", "再次靠近也安全的距離 · 5,000韓元"],
        ["十二生肖天運塔羅", "年度總運與十二個月月度解讀 · 10,000韓元"],
        ["水晶靈魂塔羅", "原石與卡牌質感解讀 · 5,000韓元"],
        ["內心掃描塔羅", "讀取表面話語與真實心意的距離 · 5,000韓元"],
        ["天體的旋律", "行星11張牌宇宙解讀 · 10,000韓元"],
        ["轉職命運卡牌", "7張牌職業牌陣 · 5,000韓元"],
      ],
    },
    {
      title: "神諭與解夢",
      items: [
        ["牌手花札占", "12個月花札牌運勢"],
        ["花札人生牌測試", "牌手概念7題心理測試"],
        ["IFA神諭", "約魯巴256奧杜神諭 · 3,000韓元"],
        ["古埃及神諭", "凱美特神諭解讀"],
        ["周易龜占", "64卦象徵解讀"],
        ["宿曜占星", "基礎服務免費 · 合盤5,000韓元"],
        ["巨石陣盧恩神諭", "古代盧恩象徵解讀"],
        ["地占土之神諭", "大地徵兆16行神諭"],
        ["茶葉占卜", "倫敦皇家杯紋樣解讀"],
        ["命運撲克", "與諸神展開的命運卡牌對決"],
        ["夢境塔羅", "夢句AI提示詞"],
        ["精神分析解夢", "佛洛伊德視角解讀"],
      ],
    },
    {
      title: "特別內容",
      items: [
        ["我是Solo秘密之家", "自動日干捕捉戀愛模擬"],
        ["AI動物面相", "自拍臉型分析"],
        ["MBTI動物合盤", "16型化學反應分析"],
        ["動物圖騰", "守護動物訊息"],
        ["命運之花", "綜合工作室"],
        ["占星花", "星雲主題視覺化"],
        ["紫微斗數花", "命宮主題報告"],
        ["宿曜花", "月相基礎花朵"],
      ],
    },
  ],
  vi: [
    {
      title: "Saju & Mệnh lý",
      items: [
        ["Luận Saju Manse cơ bản", "Phân tích mệnh cục theo ngũ hành và Thập Thần · Miễn phí"],
        ["Hệ thống Sibyl", "Năng khiếu nghề nghiệp và hệ số rủi ro vận mệnh dựa trên Saju · Cơ bản miễn phí"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Bí quyết tình yêu", "Chiến lược tình yêu dựa trên Saju · 1 người 30.000 KRW / tương hợp +10.000 KRW (tổng 40.000 KRW)"],
        ["LOVE CODE", "Mô phỏng tình yêu Saju · Mở khóa 10.000 KRW"],
        ["Destiny Bias", "Phân tích cộng hưởng fandom dựa trên Saju · 5.000 KRW/lần"],
        ["Bói động vật Thập Nhị Vận Tinh", "Linh thú hộ mệnh thức tỉnh từ Thập Nhị Vận Tinh trong Saju · Mở khóa 10.000 KRW"],
        ["Nơi gặp duyên qua Saju", "Phân tích độc lập về địa điểm, thành phố và thời điểm duyên phận · 10.000 KRW/lần"],
      ],
    },
    {
      title: "Mệnh lý Đông Tây",
      items: [
        ["Lá số Tử Vi Đẩu Số", "Dịch vụ cơ bản miễn phí · Tương hợp 5.000 KRW"],
        ["Chiêm tinh Cosmic", "Dịch vụ cơ bản miễn phí · Tương hợp 5.000 KRW"],
        ["Chiêm tinh Vệ Đà", "Dịch vụ cơ bản miễn phí · Tương hợp 5.000 KRW"],
      ],
    },
    {
      title: "Bài đọc Tarot",
      items: [
        ["Myeongri Tarot", "Bài đọc nối lá bài với Thập Thần · Miễn phí"],
        ["Chúng ta là gì của nhau?", "Bài đọc quan hệ tình yêu 6 lá · 5.000 KRW"],
        ["Thư viện prompt Tarot", "Thiết kế câu hỏi + rút bài + tổng hợp câu oracle · 5.000 KRW/lần · 63 trải bài", "Thư viện prompt Tarot"],
        ["Tarot Mặt Trời Hồi Phục", "Nhiệt độ cảm xúc và routine hồi phục · Miễn phí"],
        ["Nâng cấp lòng tự trọng", "5 lá giúp bạn đứng vững lại · Miễn phí"],
        ["Tarot Ngọn Hải Đăng Tái Hợp", "Khoảng cách an toàn để chạm lại · 5.000 KRW"],
        ["Thiên vận 12 con giáp", "Nhịp bảo hộ của mười hai tháng · 3.000 KRW"],
        ["Tarot Linh Hồn Pha Lê", "Bài đọc theo kết cấu đá và lá bài · 5.000 KRW"],
        ["Đọc thầm tâm trí", "Đọc khoảng cách giữa lời nói ngoài mặt và cảm xúc bên trong · 5.000 KRW"],
        ["Giai điệu thiên thể", "Bài đọc cosmic 11 lá hành tinh · 10.000 KRW"],
        ["Lá bài vận mệnh đổi việc", "Trải bài sự nghiệp 7 lá · 5.000 KRW"],
      ],
    },
    {
      title: "Oracle & Giải mộng",
      items: [
        ["Bói Hwatu của cao thủ bài", "Vận may 12 tháng bằng bộ bài Hwatu"],
        ["Bài test cuộc đời Hwatu", "Bài test tâm lý 7 câu theo concept cao thủ bài"],
        ["Ifa Oracle", "Oracle Yoruba 256 Odu · 3.000 KRW"],
        ["Oracle Ai Cập cổ đại", "Bài đọc Kemet oracle"],
        ["Bói rùa Kinh Dịch", "Giải nghĩa biểu tượng 64 quẻ"],
        ["Sukuyo Astrology", "Dịch vụ cơ bản miễn phí · Tương hợp 5.000 KRW"],
        ["Stonehenge Rune Oracle", "Bài đọc biểu tượng rune cổ"],
        ["Geomancy Earth Oracle", "Oracle 16 hàng dấu hiệu của đất"],
        ["Bói lá trà Tasseography", "Bài đọc hoa văn tách trà hoàng gia London"],
        ["Destiny Poker", "Trận đấu bài vận mệnh với các vị thần"],
        ["Gợi ý giấc mơ", "Prompt AI từ câu chữ trong mơ"],
        ["Giải mộng phân tâm học", "Diễn giải theo góc nhìn Freud"],
      ],
    },
    {
      title: "Nội dung đặc biệt",
      items: [
        ["I Am Solo Secret House", "Mô phỏng tình yêu bắt daily stem tự động"],
        ["AI xem tướng động vật", "Phân tích dáng mặt từ selfie"],
        ["Tương hợp động vật MBTI", "Phân tích chemistry 16 kiểu"],
        ["Vật tổ linh thú", "Thông điệp linh thú hộ mệnh"],
        ["Hoa định mệnh", "Atelier tích hợp"],
        ["Hoa chiêm tinh", "Trực quan hóa chủ đề tinh vân"],
        ["Zi Wei Flower", "Báo cáo chủ đề cung Mệnh"],
        ["Hoa Sukuyo", "Hoa dựa trên pha Mặt Trăng"],
      ],
    },
  ],
  es: [
    {
      title: "Saju y Myeongri",
      items: [
        ["Lectura básica de Saju Manse", "Análisis de carta por cinco elementos y Diez Dioses · Gratis"],
        ["Sistema Sibyl", "Aptitud profesional y coeficiente de riesgo del destino basado en Saju · Básico gratis"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Estrategia secreta del amor", "Estrategia amorosa basada en Saju · 1 persona 30.000 KRW / compatibilidad +10.000 KRW (total 40.000 KRW)"],
        ["LOVE CODE", "Simulación amorosa de Saju · Desbloqueo 10.000 KRW"],
        ["Destiny Bias", "Análisis de resonancia fandom basado en Saju · 5.000 KRW por lectura"],
        ["Oráculo animal de Doce Fases", "Tu animal guardián despierta desde las Doce Fases de Saju · Desbloqueo 10.000 KRW"],
        ["Lugar del encuentro destinado por Saju", "Análisis de lugares, ciudades y tiempos de encuentro · 10.000 KRW por lectura"],
      ],
    },
    {
      title: "Sistemas orientales y occidentales",
      items: [
        ["Carta Zi Wei Dou Shu", "Servicio básico gratis · Compatibilidad 5.000 KRW"],
        ["Astrología Cósmica", "Servicio básico gratis · Compatibilidad 5.000 KRW"],
        ["Astrología Védica", "Servicio básico gratis · Compatibilidad 5.000 KRW"],
      ],
    },
    {
      title: "Lecturas de tarot",
      items: [
        ["Tarot Myeongri", "Lectura que une cartas y Diez Dioses · Gratis"],
        ["¿Qué somos?", "Lectura de relación amorosa de 6 cartas · 5.000 KRW"],
        ["Biblioteca de prompts de tarot", "Diseño de pregunta + robo de cartas + frase oracular · 5.000 KRW por uso · 63 tiradas", "Biblioteca de prompts de tarot"],
        ["Tarot Sanador del Sol Cálido", "Temperatura emocional y rutina de recuperación · Gratis"],
        ["Sube tu autoestima", "5 cartas para volver a sostenerte · Gratis"],
        ["Tarot Faro de Reencuentro", "La distancia segura para volver a acercarse · 5.000 KRW"],
        ["Suerte celestial de los doce signos", "Ritmo guardián de doce meses · 3.000 KRW"],
        ["Tarot del Alma de Cristal", "Lectura por textura de piedra y cartas · 5.000 KRW"],
        ["Lectura de la mente", "Lee la distancia entre palabras y sentimientos internos · 5.000 KRW"],
        ["Armonía celestial", "Lectura cósmica planetaria de 11 cartas · 10.000 KRW"],
        ["Cartas del destino laboral", "Tirada profesional de 7 cartas · 5.000 KRW"],
      ],
    },
    {
      title: "Oráculos y sueños",
      items: [
        ["Oráculo Hwatu de los maestros", "Fortuna de 12 meses con cartas Hwatu"],
        ["Test de vida Hwatu", "Test psicológico de 7 preguntas con concepto de maestro de cartas"],
        ["Oráculo IFA", "Oráculo Yoruba de 256 Odu · 3.000 KRW"],
        ["Oráculo del Antiguo Egipto", "Lectura oracular Kemet"],
        ["Oráculo tortuga del I Ching", "Interpretación simbólica de 64 hexagramas"],
        ["Astrología Sukuyo", "Servicio básico gratis · Compatibilidad 5.000 KRW"],
        ["Oráculo de runas Stonehenge", "Lectura de símbolos rúnicos antiguos"],
        ["Geomancia de tierra", "Oráculo de 16 líneas de signos de la tierra"],
        ["Taseografía de hojas de té", "Lectura de patrones en taza real de Londres"],
        ["Destiny Poker", "Duelo de cartas del destino contra los dioses"],
        ["Prompt de sueños", "Prompt de IA desde frases de sueños"],
        ["Lectura psicoanalítica de sueños", "Interpretación desde Freud"],
      ],
    },
    {
      title: "Contenido especial",
      items: [
        ["I Am Solo Secret House", "Simulación amorosa automática por tallo diario"],
        ["Lectura animal con IA", "Análisis de forma facial desde selfie"],
        ["Compatibilidad animal MBTI", "Análisis de química de 16 tipos"],
        ["Tótem animal", "Mensaje del animal guardián"],
        ["Flor del destino", "Atelier integrado"],
        ["Flor astrológica", "Visualización con tema de nebulosa"],
        ["Zi Wei Flower", "Reporte temático del palacio de vida"],
        ["Flor Sukuyo", "Flor basada en fase lunar"],
      ],
    },
  ],
  fr: [
    {
      title: "Saju et Myeongri",
      items: [
        ["Lecture Saju Manse de base", "Analyse de thème par cinq éléments et Dix Dieux · Gratuit"],
        ["Système Sibyl", "Aptitudes professionnelles et coefficient de risque du destin selon Saju · Base gratuite"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Stratégie secrète d'amour", "Stratégie amoureuse selon Saju · Solo 30 000 KRW / compatibilité +10 000 KRW (total 40 000 KRW)"],
        ["LOVE CODE", "Simulation amoureuse Saju · Déblocage 10 000 KRW"],
        ["Destiny Bias", "Analyse de résonance fandom selon Saju · 5 000 KRW par lecture"],
        ["Oracle animal des douze phases", "Votre animal gardien éveillé par les douze phases de Saju · Déblocage 10 000 KRW"],
        ["Lieu de rencontre destiné par Saju", "Analyse des lieux, villes et timing de rencontre · 10 000 KRW par lecture"],
      ],
    },
    {
      title: "Systèmes orientaux et occidentaux",
      items: [
        ["Carte Zi Wei Dou Shu", "Service de base gratuit · Compatibilité 5 000 KRW"],
        ["Astrologie cosmique", "Service de base gratuit · Compatibilité 5 000 KRW"],
        ["Astrologie védique", "Service de base gratuit · Compatibilité 5 000 KRW"],
      ],
    },
    {
      title: "Lectures de tarot",
      items: [
        ["Tarot Myeongri", "Lecture reliant cartes et Dix Dieux · Gratuit"],
        ["Que sommes-nous ?", "Lecture relation amoureuse en 6 cartes · 5 000 KRW"],
        ["Bibliothèque de prompts tarot", "Conception de question + tirage + phrase oracle · 5 000 KRW par usage · 63 tirages", "Bibliothèque de prompts tarot"],
        ["Tarot du Soleil réparateur", "Température émotionnelle et routine de récupération · Gratuit"],
        ["Estime de soi niveau supérieur", "5 cartes pour vous remettre debout · Gratuit"],
        ["Tarot Phare de Réunion", "La distance sûre pour se rejoindre · 5 000 KRW"],
        ["Chance céleste des douze signes", "Rythme gardien de douze mois · 3 000 KRW"],
        ["Tarot de l'Âme Cristal", "Lecture de texture pierre et cartes · 5 000 KRW"],
        ["Lecture du coeur caché", "Lire l'écart entre paroles et sentiments intérieurs · 5 000 KRW"],
        ["Harmonie céleste", "Lecture cosmique planétaire en 11 cartes · 10 000 KRW"],
        ["Cartes du destin professionnel", "Tirage carrière en 7 cartes · 5 000 KRW"],
      ],
    },
    {
      title: "Oracles et rêves",
      items: [
        ["Oracle Hwatu des maîtres", "Fortune 12 mois par cartes Hwatu"],
        ["Test de vie Hwatu", "Test psychologique 7 questions au concept de maître de cartes"],
        ["Oracle IFA", "Oracle yoruba 256 Odu · 3 000 KRW"],
        ["Oracle de l'Égypte ancienne", "Lecture oracle Kemet"],
        ["Oracle tortue du Yi Jing", "Interprétation symbolique des 64 hexagrammes"],
        ["Astrologie Sukuyo", "Service de base gratuit · Compatibilité 5 000 KRW"],
        ["Oracle runique Stonehenge", "Lecture de symboles runiques anciens"],
        ["Oracle de géomancie", "Oracle des 16 lignes de signes terrestres"],
        ["Tasséographie des feuilles de thé", "Lecture des motifs de tasse royale londonienne"],
        ["Destiny Poker", "Duel de cartes du destin contre les dieux"],
        ["Prompt de rêve", "Prompt IA depuis les phrases du rêve"],
        ["Lecture de rêve psychanalytique", "Interprétation selon Freud"],
      ],
    },
    {
      title: "Contenus spéciaux",
      items: [
        ["I Am Solo Secret House", "Simulation amoureuse automatique par pilier du jour"],
        ["Lecture animale IA", "Analyse de forme du visage par selfie"],
        ["Compatibilité animale MBTI", "Analyse de chimie des 16 types"],
        ["Totem animal", "Message de l'animal gardien"],
        ["Fleur du destin", "Atelier intégré"],
        ["Fleur astrologique", "Visualisation thème nébuleuse"],
        ["Zi Wei Flower", "Rapport thème palais de vie"],
        ["Fleur Sukuyo", "Fleur selon phase lunaire"],
      ],
    },
  ],
  de: [
    {
      title: "Saju & Myeongri-Schicksalslehre",
      items: [
        ["Basisdeutung Saju Manse", "Geburtschartanalyse mit fünf Elementen und Zehn Göttern · Kostenlos"],
        ["Sibyl-System", "Saju-basierte Berufseignung und Schicksalsrisiko · Basis kostenlos"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Liebesgeheimnis", "Saju-basierte Liebesstrategie · Solo 30.000 KRW / Kompatibilität +10.000 KRW (gesamt 40.000 KRW)"],
        ["LOVE CODE", "Saju-Liebessimulation · Freischaltung 10.000 KRW"],
        ["Destiny Bias", "Saju-basierte Fandom-Resonanzanalyse · 5.000 KRW pro Lesung"],
        ["Zwölf-Phasen-Tierorakel", "Dein Schutztier aus den zwölf Saju-Phasen · Freischaltung 10.000 KRW"],
        ["Schicksalhafter Treffpunkt nach Saju", "Analyse von Orten, Städten und Timing · 10.000 KRW pro Lesung"],
      ],
    },
    {
      title: "Östliche und westliche Schicksalssysteme",
      items: [
        ["Zi-Wei-Dou-Shu-Chart", "Basisdienst kostenlos · Kompatibilität 5.000 KRW"],
        ["Kosmische Astrologie", "Basisdienst kostenlos · Kompatibilität 5.000 KRW"],
        ["Vedische Astrologie", "Basisdienst kostenlos · Kompatibilität 5.000 KRW"],
      ],
    },
    {
      title: "Tarot-Lesungen",
      items: [
        ["Myeongri Tarot", "Lesung, die Karten und Zehn Götter verbindet · Kostenlos"],
        ["Was sind wir?", "6-Karten-Liebesbeziehungslesung · 5.000 KRW"],
        ["Tarot-Prompt-Bibliothek", "Fragedesign + Kartenziehung + Orakelsatz · 5.000 KRW pro Nutzung · 63 Legungen", "Tarot-Prompt-Bibliothek"],
        ["Warmes Sonnen-Heiltarot", "Emotionale Temperatur und Erholungsroutine · Kostenlos"],
        ["Selbstwert-Level-up", "5 Karten, die dich wieder aufrichten · Kostenlos"],
        ["Wiedervereinigungs-Leuchtturm-Tarot", "Sichere Distanz zum erneuten Kontakt · 5.000 KRW"],
        ["Himmelsglück der zwölf Zeichen", "Schutzrhythmus von zwölf Monaten · 3.000 KRW"],
        ["Kristallseelen-Tarot", "Lesung der Textur von Stein und Karten · 5.000 KRW"],
        ["Gedankenscan-Tarot", "Liest den Abstand zwischen Worten und inneren Gefühlen · 5.000 KRW"],
        ["Himmlische Harmonie", "11-Karten-planetare kosmische Lesung · 10.000 KRW"],
        ["Karrierewechsel-Schicksalskarten", "7-Karten-Karrierelegung · 5.000 KRW"],
      ],
    },
    {
      title: "Orakel & Träume",
      items: [
        ["Hwatu-Orakel der Kartenmeister", "12-Monats-Glück mit Hwatu-Karten"],
        ["Hwatu-Lebenskartentest", "7-Fragen-Psychotest im Kartenmeister-Konzept"],
        ["IFA-Orakel", "Yoruba 256 Odu Orakel · 3.000 KRW"],
        ["Altägyptisches Orakel", "Kemet-Orakellesung"],
        ["I-Ging-Schildkrötenorakel", "Symboldeutung der 64 Hexagramme"],
        ["Sukuyo-Astrologie", "Basisdienst kostenlos · Kompatibilität 5.000 KRW"],
        ["Stonehenge-Runenorakel", "Lesung alter Runensymbole"],
        ["Geomantie-Erdorakel", "16-Zeilen-Orakel der Erdzeichen"],
        ["Tasseografie-Teeblattorakel", "Lesung königlicher Londoner Tassenmuster"],
        ["Schicksalspoker", "Schicksalskartenduell mit den Göttern"],
        ["Traum-Prompt", "KI-Prompt aus Traumsätzen"],
        ["Psychoanalytische Traumdeutung", "Deutung aus Freuds Perspektive"],
      ],
    },
    {
      title: "Spezielle Inhalte",
      items: [
        ["I Am Solo Secret House", "Automatische Tagesstamm-Liebessimulation"],
        ["KI-Tiergesichtslesen", "Selfie-Gesichtsformanalyse"],
        ["MBTI-Tierkompatibilität", "Chemieanalyse der 16 Typen"],
        ["Tier-Totem", "Botschaft des Schutztieres"],
        ["Schicksalsblume", "Integriertes Atelier"],
        ["Astrologieblume", "Nebelthemen-Visualisierung"],
        ["Zi-Wei-Blume", "Bericht zum Lebenspalast-Thema"],
        ["Sukuyo-Blume", "Blume auf Mondphasenbasis"],
      ],
    },
  ],
  hi: [
    {
      title: "Saju और भाग्य विद्या",
      items: [
        ["Saju Manse मूल रीडिंग", "पाँच तत्व और दश देवों पर आधारित जन्मपत्र विश्लेषण · मुफ्त"],
        ["Sibyl प्रणाली", "Saju आधारित करियर क्षमता और भाग्य जोखिम गुणांक · मूल सेवा मुफ्त"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["प्रेम रहस्य रणनीति", "Saju आधारित प्रेम रणनीति · एकल 30,000 KRW / संगति +10,000 KRW (कुल 40,000 KRW)"],
        ["LOVE CODE", "Saju प्रेम सिमुलेशन · 10,000 KRW में अनलॉक"],
        ["Destiny Bias", "Saju आधारित फैनडम अनुनाद विश्लेषण · प्रति रीडिंग 5,000 KRW"],
        ["बारह वृद्धि पशु ओरेकल", "Saju के बारह वृद्धि सितारों से जागता आपका रक्षक पशु · 10,000 KRW में अनलॉक"],
        ["Saju से नियत मिलन-स्थान", "मिलन के स्थान, शहर और समय की स्वतंत्र रीडिंग · प्रति रीडिंग 10,000 KRW"],
      ],
    },
    {
      title: "पूर्वी और पश्चिमी भाग्य प्रणालियाँ",
      items: [
        ["Zi Wei Dou Shu चार्ट", "मूल सेवा मुफ्त · संगति 5,000 KRW"],
        ["कॉस्मिक ज्योतिष", "मूल सेवा मुफ्त · संगति 5,000 KRW"],
        ["वैदिक ज्योतिष", "मूल सेवा मुफ्त · संगति 5,000 KRW"],
      ],
    },
    {
      title: "टैरो रीडिंग",
      items: [
        ["Myeongri टैरो", "कार्ड और दश देवों को जोड़ने वाली रीडिंग · मुफ्त"],
        ["हमारा रिश्ता क्या है?", "6 कार्ड प्रेम संबंध रीडिंग · 5,000 KRW"],
        ["टैरो प्रॉम्प्ट लाइब्रेरी", "प्रश्न रचना + कार्ड ड्रॉ + ओरेकल वाक्य सार · प्रति उपयोग 5,000 KRW · 63 स्प्रेड", "टैरो प्रॉम्प्ट लाइब्रेरी"],
        ["गर्म सूर्य उपचार टैरो", "भावनात्मक तापमान और पुनर्संतुलन रूटीन · मुफ्त"],
        ["आत्मसम्मान स्तर-उन्नयन", "आपको फिर से खड़ा करने वाली 5 कार्ड रीडिंग · मुफ्त"],
        ["पुनर्मिलन दीपस्तंभ टैरो", "फिर जुड़ने के लिए सुरक्षित दूरी · 5,000 KRW"],
        ["बारह राशियों का स्वर्गीय भाग्य", "बारह महीनों की रक्षक लय · 3,000 KRW"],
        ["क्रिस्टल सोल टैरो", "रत्न और कार्ड की बनावट से रीडिंग · 5,000 KRW"],
        ["मन स्कैन टैरो", "बोले गए शब्दों और अंदरूनी भावों के बीच की दूरी · 5,000 KRW"],
        ["आकाशीय सामंजस्य", "11 कार्ड ग्रह-आधारित कॉस्मिक रीडिंग · 10,000 KRW"],
        ["करियर परिवर्तन भाग्य कार्ड", "7 कार्ड करियर स्प्रेड · 5,000 KRW"],
      ],
    },
    {
      title: "ओरेकल और स्वप्न",
      items: [
        ["कार्ड उस्तादों का Hwatu ओरेकल", "12 महीनों का Hwatu कार्ड भाग्य"],
        ["Hwatu जीवन कार्ड टेस्ट", "कार्ड उस्ताद शैली का 7 प्रश्नों वाला मनोवैज्ञानिक टेस्ट"],
        ["IFA ओरेकल", "योरूबा 256 ओडु ओरेकल · 3,000 KRW"],
        ["प्राचीन मिस्री ओरेकल", "Kemet ओरेकल रीडिंग"],
        ["I Ching कछुआ ओरेकल", "64 हेक्साग्राम प्रतीक रीडिंग"],
        ["Sukuyo ज्योतिष", "मूल सेवा मुफ्त · संगति 5,000 KRW"],
        ["Stonehenge रून ओरेकल", "प्राचीन रून प्रतीकों की रीडिंग"],
        ["Geomancy पृथ्वी ओरेकल", "पृथ्वी संकेतों का 16 रेखाओं वाला ओरेकल"],
        ["Tasseography चाय-पत्ती ओरेकल", "लंदन रॉयल कप पैटर्न रीडिंग"],
        ["भाग्य पोकर", "देवताओं के साथ भाग्य कार्ड द्वंद्व"],
        ["स्वप्न प्रॉम्प्ट", "स्वप्न वाक्यों से AI प्रॉम्प्ट"],
        ["मनोविश्लेषणात्मक स्वप्न रीडिंग", "फ्रायडीय दृष्टि से व्याख्या"],
      ],
    },
    {
      title: "विशेष सामग्री",
      items: [
        ["I Am Solo Secret House", "स्वचालित दैनिक-स्तंभ प्रेम सिमुलेशन"],
        ["AI पशु मुख-पाठ", "सेल्फी चेहरे के आकार का विश्लेषण"],
        ["MBTI पशु संगति", "16 प्रकारों की केमिस्ट्री विश्लेषण"],
        ["पशु टोटेम", "रक्षक पशु का संदेश"],
        ["भाग्य पुष्प", "समेकित अटेलियर"],
        ["ज्योतिष पुष्प", "नेब्युला थीम दृश्यांकन"],
        ["Zi Wei पुष्प", "जीवन महल थीम रिपोर्ट"],
        ["Sukuyo पुष्प", "चंद्र चरण पर आधारित पुष्प"],
      ],
    },
  ],
  nl: [
    {
      title: "Saju en Myeongri",
      items: [
        ["Basis Saju Manse lezing", "Analyse van geboortechart met vijf elementen en Ten Gods · Gratis"],
        ["Sibyl-systeem", "Saju-gebaseerde beroepsaanleg en bestemmingsrisico · Basis gratis"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Liefdesgeheimstrategie", "Saju-gebaseerde liefdesstrategie · solo KRW 30.000 / compatibiliteit +KRW 10.000 (totaal KRW 40.000)"],
        ["LOVE CODE", "Saju liefdessimulatie · unlock KRW 10.000"],
        ["Bestemmingsbias", "Saju-gebaseerde fandomresonantieanalyse · KRW 5.000 per lezing"],
        ["Twaalf-fasen dierenorakel", "Je beschermdier gewekt door de twaalf groeifasen in Saju · unlock KRW 10.000"],
        ["Bestemde ontmoetingsplek via Saju", "Onafhankelijke lezing van plaatsen, steden en timing · KRW 10.000 per lezing"],
      ],
    },
    {
      title: "Oosterse en westerse systemen",
      items: [
        ["Zi Wei Dou Shu-kaart", "Basisservice gratis · compatibiliteit KRW 5.000"],
        ["Kosmische astrologie", "Basisservice gratis · compatibiliteit KRW 5.000"],
        ["Vedische astrologie", "Basisservice gratis · compatibiliteit KRW 5.000"],
      ],
    },
    {
      title: "Tarotlezingen",
      items: [
        ["Myeongri Tarot", "Lezing die kaarten en Ten Gods verbindt · Gratis"],
        ["Wat zijn wij?", "6-kaarten liefdesrelatielezing · KRW 5.000"],
        ["Tarotpromptbibliotheek", "Vraagontwerp + kaarttrekking + orakelzin · KRW 5.000 per gebruik · 63 spreads", "Tarotpromptbibliotheek"],
        ["Warme zon healingtarot", "Emotionele temperatuur en herstelroutine · Gratis"],
        ["Zelfwaardering omhoog", "5 kaarten die je weer laten staan · Gratis"],
        ["Herenigingsvuurtoren-tarot", "Veilige afstand om opnieuw te verbinden · KRW 5.000"],
        ["Hemels geluk van de twaalf dierenriemtekens", "Beschermend ritme van twaalf maanden · KRW 3.000"],
        ["Kristalziel-tarot", "Steen- en kaarttextuurlezing · KRW 5.000"],
        ["Gedachtenscan-tarot", "Leest de afstand tussen woorden en innerlijke gevoelens · KRW 5.000"],
        ["Hemelse harmonie", "11-kaarten planetaire kosmische lezing · KRW 10.000"],
        ["Bestemmingskaarten voor carrièreswitch", "7-kaarten carrière spread · KRW 5.000"],
      ],
    },
    {
      title: "Orakels & dromen",
      items: [
        ["Hwatu-orakel van kaartmeesters", "12-maanden Hwatu kaartfortuin"],
        ["Hwatu Life Card Test", "7-vragen psychologische test met kaartmeesterconcept"],
        ["IFA-orakel", "Yoruba 256 Odu-orakel · KRW 3.000"],
        ["Oud-Egyptisch orakel", "Kemet-orakellezing"],
        ["I Ching-schildpadorakel", "Symbolische lezing van 64 hexagrammen"],
        ["Sukuyo-astrologie", "Basisservice gratis · compatibiliteit KRW 5.000"],
        ["Stonehenge-runeorakel", "Oude rune-symbolenlezing"],
        ["Geomantie-aardeorakel", "16-regelige aarde-teken oracle"],
        ["Tasseografie-theebladorakel", "London royal cup patroonlezing"],
        ["Bestemmingspoker", "Bestemmingskaartduel met de goden"],
        ["Droomprompt", "AI-prompt uit droomzinnen"],
        ["Psychoanalytische droomlezing", "Interpretatie vanuit Freud"],
      ],
    },
    {
      title: "Speciale content",
      items: [
        ["I Am Solo Secret House", "Automatische daily stem liefdessimulatie"],
        ["AI dierengezichtslezing", "Selfie gezichtsvormanalyse"],
        ["MBTI dierencompatibiliteit", "16-type chemieanalyse"],
        ["Dierentotem", "Bericht van het beschermdier"],
        ["Bestemmingsbloem", "Geïntegreerd atelier"],
        ["Astrologiebloem", "Nebula-thema visualisatie"],
        ["Zi Wei-bloem", "Life-palace themarapport"],
        ["Sukuyo-bloem", "Bloem op basis van maanfase"],
      ],
    },
  ],
  ms: [
    {
      title: "Saju & Myeongri",
      items: [
        ["Bacaan asas Saju Manse", "Analisis carta dengan lima unsur dan Ten Gods · Percuma"],
        ["Sistem Sibyl", "Aptitud kerjaya dan pekali risiko takdir berasaskan Saju · Asas percuma"],
        ["Life Book AI Consultation", "One-on-one life-flow consultation - KRW 50,000"],
        ["Strategi Rahsia Cinta", "Strategi cinta berasaskan Saju · solo KRW 30,000 / keserasian +KRW 10,000 (jumlah KRW 40,000)"],
        ["LOVE CODE", "Simulasi cinta Saju · buka kunci KRW 10,000"],
        ["Destiny Bias", "Analisis resonans fandom berasaskan Saju · KRW 5,000 setiap bacaan"],
        ["Oracle Haiwan Dua Belas Pertumbuhan", "Haiwan penjaga anda terjaga melalui dua belas bintang pertumbuhan dalam Saju · buka kunci KRW 10,000"],
        ["Tempat Pertemuan Takdir melalui Saju", "Bacaan bebas tempat, bandar dan masa pertemuan · KRW 10,000 setiap bacaan"],
      ],
    },
    {
      title: "Sistem takdir Timur & Barat",
      items: [
        ["Carta Zi Wei Dou Shu", "Servis asas percuma · keserasian KRW 5,000"],
        ["Astrologi Kosmik", "Servis asas percuma · keserasian KRW 5,000"],
        ["Astrologi Veda", "Servis asas percuma · keserasian KRW 5,000"],
      ],
    },
    {
      title: "Bacaan tarot",
      items: [
        ["Myeongri Tarot", "Bacaan yang menghubungkan kad dan Ten Gods · Percuma"],
        ["Apakah hubungan kita?", "Bacaan hubungan cinta 6 kad · KRW 5,000"],
        ["Perpustakaan Prompt Tarot", "Reka soalan + cabut kad + susun ayat oracle · KRW 5,000 setiap guna · 63 spread", "Perpustakaan Prompt Tarot"],
        ["Tarot Penyembuhan Matahari Hangat", "Suhu emosi dan rutin pemulihan · Percuma"],
        ["Naik Taraf Harga Diri", "5 kad untuk menegakkan diri semula · Percuma"],
        ["Tarot Rumah Api Pertemuan Semula", "Jarak selamat untuk bersambung semula · KRW 5,000"],
        ["Tuah Langit Dua Belas Zodiak", "Ritma penjaga dua belas bulan · KRW 3,000"],
        ["Tarot Jiwa Kristal", "Bacaan tekstur batu dan kad · KRW 5,000"],
        ["Tarot Imbas Minda", "Membaca jarak antara kata luar dan perasaan dalaman · KRW 5,000"],
        ["Harmoni Langit", "Bacaan kosmik planet 11 kad · KRW 10,000"],
        ["Kad Takdir Tukar Kerjaya", "Spread kerjaya 7 kad · KRW 5,000"],
      ],
    },
    {
      title: "Oracle & mimpi",
      items: [
        ["Oracle Hwatu Para Master Kad", "Nasib 12 bulan dengan kad Hwatu"],
        ["Hwatu Life Card Test", "Ujian psikologi 7 soalan bertema card master"],
        ["Oracle IFA", "Oracle Yoruba 256 Odu · KRW 3,000"],
        ["Oracle Mesir Purba", "Bacaan oracle Kemet"],
        ["Oracle Kura-Kura I Ching", "Bacaan simbolik 64 hexagram"],
        ["Astrologi Sukuyo", "Servis asas percuma · keserasian KRW 5,000"],
        ["Oracle Rune Stonehenge", "Bacaan simbol rune purba"],
        ["Oracle Tanah Geomansi", "Oracle 16 baris tanda bumi"],
        ["Oracle Daun Teh Tasseography", "Bacaan corak cawan diraja London"],
        ["Poker Takdir", "Duel kad takdir bersama para dewa"],
        ["Prompt Mimpi", "Prompt AI daripada ayat mimpi"],
        ["Bacaan Mimpi Psikoanalitik", "Tafsiran dari sudut Freud"],
      ],
    },
    {
      title: "Kandungan khas",
      items: [
        ["I Am Solo Secret House", "Simulasi cinta daily stem automatik"],
        ["Bacaan Wajah Haiwan AI", "Analisis bentuk wajah selfie"],
        ["Keserasian Haiwan MBTI", "Analisis kimia 16 jenis"],
        ["Totem Haiwan", "Mesej haiwan penjaga"],
        ["Bunga Takdir", "Atelier bersepadu"],
        ["Bunga Astrologi", "Visualisasi tema nebula"],
        ["Bunga Zi Wei", "Laporan tema life palace"],
        ["Bunga Sukuyo", "Bunga berdasarkan fasa bulan"],
      ],
    },
  ],
};

function materializeServiceSection(section) {
  return {
    ...section,
    title: section.fallbackTitle,
    items: section.items.map(({ fallbackTitle, fallbackDesc, fallbackAlt, ...item }) => ({
      ...item,
      title: fallbackTitle,
      desc: fallbackDesc,
      ...(fallbackAlt ? { alt: fallbackAlt } : {}),
    })),
  };
}

export const SERVICE_SECTIONS = SERVICE_SECTION_DEFINITIONS.map(materializeServiceSection);

export function getLocalizedServiceSections(locale = "ko") {
  const normalizedLocale = locale === "zh" ? "zh-CN" : locale;
  const localized = SERVICE_SECTION_TRANSLATIONS[normalizedLocale] || (normalizedLocale === "ko" ? null : SERVICE_SECTION_TRANSLATIONS.en);
  if (!localized) return SERVICE_SECTIONS;

  return SERVICE_SECTIONS.map((section, sectionIndex) => {
    const translatedSection = localized[sectionIndex];
    if (!translatedSection) return section;

    return {
      ...section,
      title: translatedSection.title || section.title,
      items: section.items.map((item, itemIndex) => {
        const translatedItem = translatedSection.items?.[itemIndex];
        if (!translatedItem) return item;
        return {
          ...item,
          title: translatedItem[0] || item.title,
          desc: translatedItem[1] || item.desc,
          alt: translatedItem[2] || item.alt,
        };
      }),
    };
  });
}
